### ISSUE TITLE
Pgtasks parameters should be typed

### ISSUE THREAD

**Issue by moshloop** [CrunchyData/postgres-operator#1058]
The parameters used in Pgtasks are most maps and free text, they should be typed e.g.

e.g rather than:
```yaml
apiVersion: crunchydata.com/v1
kind: Pgtask
metadata:
  name: 
  namespace:
spec:
  name: 
  namespace: ""
  parameters:
    ccp-image-tag: centos7-11.4-2.3.3
    containername: database
    pg-cluster:
    pgdump: pgdump
    pgdump-all: "false"
    pgdump-db: 
    pgdump-host: harbor
    pgdump-opts: 
    pgdump-port: "5432"
    pgdump-user:
    pvc-name:
  tasktype: pgdump
```

Use 
```yaml
apiVersion: crunchydata.com/v1
kind: Pgtask
metadata:
     name: 
     namespace:
spec:
    ccp-image-tag: centos7-11.4-2.3.3
    containername: database
    cluster:
       name: cluster1
       host: host1
       db: db1
       port: 5432
       user:
    pgdump: 
       all: "false"
       opts: ""
       db: ""
       pvc-name: ""
```
