### ISSUE TITLE
nfs pvc pending

### ISSUE THREAD

**Issue by willzhang** [CrunchyData/postgres-operator#1094]
## install nfs and test it ok
```
[root@kmaster postgres-operator]# kubectl get pods
NAME                                      READY   STATUS    RESTARTS   AGE
nfs-client-provisioner-544b895d6f-55gxw   1/1     Running   0          72m

[root@kmaster postgres-operator]# kubectl get pv
NAME                                       CAPACITY   ACCESS MODES   RECLAIM POLICY   STATUS   CLAIM                STORAGECLASS          REASON   AGE
pvc-77b29e46-8a27-4e50-a5a6-a4f23b0ad956   1Mi        RWX            Delete           Bound    default/test-claim   managed-nfs-storage            9m52s

[root@kmaster postgres-operator]# kubectl get pvc
NAME         STATUS   VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS          AGE
test-claim   Bound    pvc-77b29e46-8a27-4e50-a5a6-a4f23b0ad956   1Mi        RWX            managed-nfs-storage   9m54s
```

## config postgres-operator for nfsstorage

```
cat conf/postgres-operator/pgo.yaml
PrimaryStorage: nfsstorage
BackupStorage: nfsstorage
ReplicaStorage: nfsstorage
BackrestStorage: nfsstorage
Storage:
  hostpathstorage:
    AccessMode:  ReadWriteMany
    Size:  1G
    StorageType:  create
  replicastorage:
    AccessMode:  ReadWriteMany
    Size:  700M
    StorageType:  create
  nfsstorage:
    AccessMode:  ReadWriteMany
    Size:  1G
    StorageType:  dynamic
    StorageClass: managed-nfs-storage
    SupplementalGroups:  65534
```

## create cluster
```
pgo create cluster pickles1 -n pgouser1
```

## check pod
```
[root@kmaster postgres-operator]# kubectl -n pgouser1 get pods
NAME                                             READY   STATUS    RESTARTS   AGE
pickles1-5f8fc59455-df9vb                        0/1     Pending   0          17m
pickles1-backrest-shared-repo-6fdcbbbcb6-rlqxp   0/1     Pending   0          17m
pickles2-69bb786fc4-lc2r7                        0/1     Pending   0          16m
pickles2-backrest-shared-repo-ccbbc7648-r5qsd    0/1     Pending   0          16m

[root@kmaster postgres-operator]# kubectl -n pgouser1 get pvc
NAME                 STATUS    VOLUME   CAPACITY   ACCESS MODES   STORAGECLASS   AGE
pickles1             Pending                                                     17m
pickles1-pgbr-repo   Pending                                                     17m
pickles2             Pending                                                     16m
pickles2-pgbr-repo   Pending                                                     16m
[root@kmaster postgres-operator]# 
[root@kmaster postgres-operator]# kubectl -n pgouser1 describe pvc pickles1 
Name:          pickles1
Namespace:     pgouser1
StorageClass:  
Status:        Pending
Volume:        
Labels:        pg-cluster=pickles1
               pgremove=true
               vendor=crunchydata
Annotations:   <none>
Finalizers:    [kubernetes.io/pvc-protection]
Capacity:      
Access Modes:  
VolumeMode:    Filesystem
Mounted By:    pickles1-5f8fc59455-df9vb
Events:
  Type    Reason         Age                   From                         Message
  ----    ------         ----                  ----                         -------
  Normal  FailedBinding  2m49s (x62 over 17m)  persistentvolume-controller  no persistent volumes available for this claim and no storage class is set

```
##  the question
how can i use nfs dynamic type storage,why the storage class is empty?
