### ISSUE TITLE
v4.2.0: With the pgo clone command the metrics flag doesn't get passed to the cloned instance

### ISSUE THREAD

**Issue by TFK1410** [CrunchyData/postgres-operator#1186]
**Describe the bug**
Using the new pgo clone command the new pgcluster instance doesn't get the metrics flag passed down. This makes the new cluster create without the metrics sidecar container.

**To Reproduce**
1. Create a new cluster with metrics enabled: `pgo create cluster test -n pgouser1 --metrics`
2. After that's done clone the cluster: `pgo clone test test-clone -n pgouser1`
3. Compare the userlabels of both pgcluster objects:
```
# oc get pgcluster test -o yaml
...
  userlabels:
    archive-timeout: "60"
    crunchy_collect: "true"
    pg-pod-anti-affinity: ""
    pgo-version: 4.2.0
    workflowid: 1a384122-e78d-451d-bc16-c557a50132ba
...
# oc get pgcluster test-clone -o yaml
...
  userlabels:
    backrest-storage-type: ""
    pgo-version: 4.2.0
...
```
The crunchy_collect label is missing.
4. Compare the deployments of both instances to see that there's no metrics sidecar container in the cloned instance.

**Expected behavior**
The cloned instance of pgcluster has the same configuration of the metrics sidecar as the original.

**Environment**

* Platform: OpenShift
* Platform Version: 3.11

**Additional context**
I assume the solution involves the comment in the [clone.go](https://github.com/CrunchyData/postgres-operator/blob/e85901b8017fc6f61a22ecd8b9c8dfd8f33c7c39/operator/cluster/clone.go#L785-L790) code.
