### ISSUE TITLE
Cannot create resource "secrets"

### ISSUE THREAD

**Issue by captainjapeng** [CrunchyData/postgres-operator#1489]
**Describe the bug**
`postgres-operator` service account is unable to create secrets
Running `pgo create cluster -n pgouser1 postgres` after following the installation guide (`kubectl apply -f operator.yml`)

**To Reproduce**
1. Follow the [Install the PostgreSQL Operator](https://access.crunchydata.com/documentation/postgres-operator/4.3.0/installation/postgres-operator/) guide
2. Run `pgo version -n pgouser1` (displays v4.3.0)
3. Run `pgo create cluster -n pgouser1 postgres`

**Expected behavior**
Cluster should be created

**Screenshots**
2. ![image](https://user-images.githubusercontent.com/26142675/81108511-64855400-8f4b-11ea-93bf-2a965225b5b5.png)
4. ![image](https://user-images.githubusercontent.com/26142675/81108569-78c95100-8f4b-11ea-9caa-5c6344044e5e.png)

**Please tell us about your environment:**

* Operating System: Debian do-kube-1.16.6-do.2
* Where is this running ( Local, Cloud Provider): Digital Ocean
* Storage being used (NFS, Hostpath, Gluster, etc): Digital Ocean Block Storage
* Container Image Tag: centos7-12.2-4.3.0
* PostgreSQL Version: N/A
* Platform (Docker, Kubernetes, OpenShift): Kubernetes
* Platform Version: 1.16.6

**Additional context**
Only changes made to the operator is change admin password and add/change the ff:
```yml
                  - name: BACKREST_STORAGE
                    value: "digitalocean"
                  - name: BACKUP_STORAGE
                    value: "digitalocean"
                  - name: PRIMARY_STORAGE
                    value: "digitalocean"
                  - name: REPLICA_STORAGE
                    value: "digitalocean"

                  - name: STORAGE5_NAME
                    value: "digitalocean"
                  - name: STORAGE5_ACCESS_MODE
                    value: "ReadWriteOnce"
                  - name: STORAGE5_SIZE
                    value: "1Gi"
                  - name: STORAGE5_TYPE
                    value: "dynamic"
                  - name: STORAGE5_CLASS
                    value: "do-block-storage"
```
