### ISSUE TITLE
too permisive ClusterRoleBinding

### ISSUE THREAD

**Issue by obeyler** [CrunchyData/postgres-operator#1492]
**What is the motivation or use case for the change? **
For security reason the ClusterRoleBinding set that allow serviceaccount:pgo:pgo-deployer-sa is not acceptable on shared cluster.

```
kind: ClusterRoleBinding
metadata:
    name: pgo-deployer-crb
    namespace: backend-staging
roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: ClusterRole
    name: cluster-admin
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: User
  name: system:serviceaccount:pgo:pgo-deployer-sa

```
**Describe the solution you'd like**
In best case transform ClusterRoleBinding to a RoleBinding and define the role
