### ISSUE TITLE
pgo client istio config?

### ISSUE THREAD

**Issue by tirelibirefe** [CrunchyData/postgres-operator#1616]
Hello;
I've installed postgres-operator on baremetal Kubespray Kubernetes 1.18 but I couldn't have connected to the operator via pgo through Istio ingress controller.

The following config gives 404 error, not working.

```
cat <<EOF | kubectl apply -f -
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: postgres-operator-gateway
  namespace: pgo
spec:
  selector:
    istio: ingressgateway
  servers:
  - port:
      number: 443
      name: https-postgres-operator
      protocol: https
    tls:
      mode: SIMPLE
      credentialName: pgo-client-cert
    hosts:
    - "postgres-operator.int.kik.io"
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: postgres-operator-vs
  namespace: pgo
spec:
  hosts:
  - "postgres-operator.int.kik.io"
  gateways:
  - postgres-operator-gateway
  tcp:
  - route:
    - destination:
        host: postgres-operator.pgo.svc.cluster.local
        port:
          number: 8443
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: postgres-operator
  namespace: pgo
spec:
  host: postgres-operator
  trafficPolicy:
    tls:
      mode: DISABLE
---
EOF

```
Is there anyone who can provide a sample recipe for pgo virtual service and gateway config?

Should I use client certificates created during installation or pgo.tls secret to connect operator?
