### ISSUE TITLE
Unable to find configMap <cluster-name>-config when attempting disable autofailover.

### ISSUE THREAD

**Issue by miteshsa-onnet** [CrunchyData/postgres-operator#1645]
**Describe the bug**
when i crate new cluster i face some error in operator container.

Unable to find configMap <'cluster-name'>-config when attempting disable autofailover.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Please tell us about your environment:**

* Operating System: Ubuntu 18.04
* Where is this running ( Local, Cloud Provider) Cloud
* Storage being used (NFS, Hostpath, Gluster, etc): csi.trident.netapp.io
* Container Image Tag:
* PostgreSQL Version:
* Platform (Docker, Kubernetes, OpenShift): Kubernetes (RKE)
* Platform Version: Rancher 2.0

**Additional context**

**Comment by jkatz** [comment]
Please fill out the bug template fully. Which version of the Operator are you using? How did you create the cluster? What commands did you run before you tried to disable autofailover?

**Comment by miteshsa-onnet** [comment]
Hello @jkatz 
Version is as bellow.
pgo client version 4.3.2
pgo-apiserver version 4.3.2

I use this operator file to configure operator.

```
apiVersion: v1
kind: ServiceAccount
metadata:
    name: pgo-deployer-sa
    namespace: pgo
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: pgo-deployer-cr
rules:
  - apiGroups:
      - ''
    resources:
      - namespaces
    verbs:
      - get
      - list
      - create
      - patch
      - delete
  - apiGroups:
      - ''
    resources:
      - pods
    verbs:
      - list
  - apiGroups:
      - ''
    resources:
      - secrets
    verbs:
      - get
      - create
      - delete
  - apiGroups:
      - ''
    resources:
      - configmaps
      - services
      - persistentvolumeclaims
    verbs:
      - get
      - create
      - delete
  - apiGroups:
      - ''
    resources:
      - serviceaccounts
    verbs:
      - get
      - create
      - delete
      - patch
  - apiGroups:
      - apps
      - extensions
    resources:
      - deployments
    verbs:
      - get
      - list
      - create
      - delete
  - apiGroups:
      - apiextensions.k8s.io
    resources:
      - customresourcedefinitions
    verbs:
      - get
      - create
      - delete
  - apiGroups:
      - rbac.authorization.k8s.io
    resources:
      - clusterroles
      - clusterrolebindings
      - roles
      - rolebindings
    verbs:
      - get
      - create
      - delete
      - bind
      - escalate
  - apiGroups:
      - rbac.authorization.k8s.io
    resources:
      - roles
    verbs:
      - create
      - delete
  - apiGroups:
      - batch
    resources:
      - jobs
    verbs:
      - delete
  - apiGroups:
      - crunchydata.com
    resources:
      - pgclusters
      - pgreplicas
      - pgpolicies
      - pgtasks
    verbs:
      - delete
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
    name: pgo-deployer-crb
roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: ClusterRole
    name: pgo-deployer-cr
subjects:
- kind: ServiceAccount
  name: pgo-deployer-sa
  namespace: pgo
---
apiVersion: batch/v1
kind: Job
metadata:
    name: pgo-deploy
    namespace: pgo
spec:
    backoffLimit: 0
    template:
        metadata:
            name: pgo-deploy
        spec:
            serviceAccountName: pgo-deployer-sa
            restartPolicy: Never
            containers:
            - name: pgo-deploy
              image: registry.developers.crunchydata.com/crunchydata/pgo-deployer:centos7-4.3.2
              imagePullPolicy: IfNotPresent
              env:
                  - name: ARCHIVE_MODE
                    value: "true"
                  - name: ARCHIVE_TIMEOUT
                    value: "60"
                  - name: BACKREST
                    value: "true"
                  - name: BADGER
                    value: "false"
                  - name: CRUNCHY_DEBUG
                    value: "false"
                  - name: CREATE_RBAC
                    value: "true"
                  - name: CCP_IMAGE_PREFIX
                    value: "registry.developers.crunchydata.com/crunchydata"
                  - name: CCP_IMAGE_TAG
                    value: "centos7-12.3-4.3.2"
                  - name: DB_PASSWORD_LENGTH
                    value: "24"
                  - name: DB_PORT
                    value: "5432"
                  - name: DB_REPLICAS
                    value: "0"
                  - name: DB_USER
                    value: "testuser"
                  - name: DEFAULT_INSTANCE_MEMORY
                    value: "128Mi"
                  - name: DEFAULT_PGBACKREST_MEMORY
                    value: ""
                  - name: DEFAULT_PGBOUNCER_MEMORY
                    value: ""
                  - name: DEPLOY_ACTION
                    value: "install"
                  - name: DISABLE_AUTO_FAILOVER
                    value: "false"
                  - name: DISABLE_FSGROUP
                    value: "false"
                  - name: DYNAMIC_RBAC
                    value: "false"
                  - name: EXPORTERPORT
                    value: "9187"
                  - name: METRICS
                    value: "false"
                  - name: NAMESPACE
                    value: "pgo"
                  - name: NAMESPACE_MODE
                    value: "dynamic"
                  - name: PGBADGERPORT
                    value: "10000"
                  - name: PGO_ADMIN_PASSWORD
                    value: "pgo_password"
                  - name: PGO_ADMIN_PERMS
                    value: "*"
                  - name: PGO_ADMIN_ROLE_NAME
                    value: "pgoadmin"
                  - name: PGO_ADMIN_USERNAME
                    value: "admin"
                  - name: PGO_CLIENT_VERSION
                    value: "v4.3.2"
                  - name: PGO_IMAGE_PREFIX
                    value: "registry.developers.crunchydata.com/crunchydata"
                  - name: PGO_IMAGE_TAG
                    value: "centos7-4.3.2"
                  - name: PGO_INSTALLATION_NAME
                    value: "devtest"
                  - name: PGO_OPERATOR_NAMESPACE
                    value: "pgo"
                  - name: SCHEDULER_TIMEOUT
                    value: "3600"
                  - name: BACKREST_STORAGE
                    value: "csipostgresstorage"
                  - name: BACKUP_STORAGE
                    value: "csipostgresstorage"
                  - name: PRIMARY_STORAGE
                    value: "csipostgresstorage"
                  - name: REPLICA_STORAGE
                    value: "csipostgresstorage"
                  - name: WAL_STORAGE
                    value: ""
                  - name: STORAGE1_NAME
                    value: "csipostgresstorage"
                  - name: STORAGE1_ACCESS_MODE
                    value: "ReadWriteMany"
                  - name: STORAGE1_SIZE
                    value: "5G"
                  - name: STORAGE1_TYPE
                    value: "dynamic"
                  - name: STORAGE1_CLASS
                    value: "basic-csi"

```

And I did not try to disable autofailover.

I just run bellow command after installing operator and pgo Client.

`pgo create cluster test-ha --pvc-size=500Mi --replica-count=1  -n pgo --pgo-client-key=/home/ocadmin/.pgo/pgo/client.key`

After this i cluster is not up so i check the operator container log and it shows as bellow.

time="2020-06-21T03:47:32Z" level=debug msg="Controller Manager: canCreateRBACInNamespace is 'true' for namespace pgo" func="controller/manager.(*ControllerManager).AddAndRunGroup()" file="controller/manager/controllermanager.go:161" version=4.3.2
time="2020-06-21T03:47:32Z" level=debug msg="Controller Manager: a controller for namespace pgo already exists" func="controller/manager.(*ControllerManager).addControllerGroup()" file="controller/manager/controllermanager.go:256" version=4.3.2
time="2020-06-21T03:47:32Z" level=debug msg="Controller Manager: controller group for namespace pgo is already running" func="controller/manager.(*ControllerManager).runControllerGroup()" file="controller/manager/controllermanager.go:491" version=4.3.2
time="2020-06-21T03:47:35Z" level=debug msg="task putting key in queue pgo/test-ha-createcluster" func="controller/pgtask.(*Controller).onAdd()" file="controller/pgtask/pgtaskcontroller.go:175" version=4.3.2
time="2020-06-21T03:47:35Z" level=debug msg="working on pgo/test-ha-createcluster" func="controller/pgtask.(*Controller).processNextItem()" file="controller/pgtask/pgtaskcontroller.go:74" version=4.3.2
time="2020-06-21T03:47:35Z" level=debug msg="queue got key ns=[pgo] resource=[test-ha-createcluster]" func="controller/pgtask.(*Controller).processNextItem()" file="controller/pgtask/pgtaskcontroller.go:79" version=4.3.2
time="2020-06-21T03:47:35Z" level=debug msg="{\"status\":{\"message\":\"Successfully processed Pgtask by controller\",\"state\":\"pgtask Processed\"}}" func="kubeapi.PatchpgtaskStatus()" file="kubeapi/pgtask.go:193" version=4.3.2
time="2020-06-21T03:47:35Z" level=debug msg="[pgcluster Controller] ns pgo onAdd /apis/crunchydata.com/v1/namespaces/pgo/pgclusters/test-ha" func="controller/pgcluster.(*Controller).onAdd()" file="controller/pgcluster/pgclustercontroller.go:52" version=4.3.2
time="2020-06-21T03:47:35Z" level=debug msg="cluster putting key in queue pgo/test-ha" func="controller/pgcluster.(*Controller).onAdd()" file="controller/pgcluster/pgclustercontroller.go:63" version=4.3.2
time="2020-06-21T03:47:35Z" level=debug msg="working on pgo/test-ha" func="controller/pgcluster.(*Controller).processNextItem()" file="controller/pgcluster/pgclustercontroller.go:97" version=4.3.2
time="2020-06-21T03:47:35Z" level=debug msg="cluster add queue got key ns=[pgo] resource=[test-ha]" func="controller/pgcluster.(*Controller).processNextItem()" file="controller/pgcluster/pgclustercontroller.go:102" version=4.3.2
time="2020-06-21T03:47:35Z" level=debug msg="deployment test-ha not found" func="kubeapi.GetDeployment()" file="kubeapi/deployment.go:64" version=4.3.2
time="2020-06-21T03:47:35Z" level=debug msg="{\"status\":{\"message\":\"Successfully processed Pgcluster by controller\",\"state\":\"pgcluster Processed\"}}" func="kubeapi.PatchpgclusterStatus()" file="kubeapi/pgcluster.go:177" version=4.3.2
time="2020-06-21T03:47:35Z" level=debug msg="workflow task added [test-ha-createcluster] ID [0c560401-3008-4328-b938-6a724aeb5b62]" func="controller/pgtask.(*Controller).processNextItem()" file="controller/pgtask/pgtaskcontroller.go:148" version=4.3.2
time="2020-06-21T03:47:35Z" level=debug msg="pgcluster added: test-ha" func="controller/pgcluster.(*Controller).processNextItem()" file="controller/pgcluster/pgclustercontroller.go:137" version=4.3.2
time="2020-06-21T03:47:35Z" level=debug msg="in createPVC" func="operator/pvc.Create()" file="operator/pvc/pvc.go:134" version=4.3.2
time="2020-06-21T03:47:35Z" level=debug msg="using dynamic PVC template" func="operator/pvc.Create()" file="operator/pvc/pvc.go:148" version=4.3.2
time="2020-06-21T03:47:35Z" level=debug msg="Cluster Operator: starting cluster test-ha" func="operator/cluster.StartupCluster()" file="operator/cluster/clusterlogic.go:533" version=4.3.2
time="2020-06-21T03:47:35Z" level=debug msg="setting autofailover to true for cluster with pgha scope " func="util.ToggleAutoFailover()" file="util/failover.go:244" version=4.3.2
time="2020-06-21T03:47:35Z" level=debug msg="configmaps \"-config\" not found" func="kubeapi.GetConfigMap()" file="kubeapi/configmap.go:45" version=4.3.2
time="2020-06-21T03:47:35Z" level=debug msg="-config configmap not found " func="kubeapi.GetConfigMap()" file="kubeapi/configmap.go:46" version=4.3.2
time="2020-06-21T03:47:35Z" level=error msg="Unable to find configMap -config when attempting disable autofailover" func="util.ToggleAutoFailover()" file="util/failover.go:249" version=4.3.2
time="2020-06-21T03:47:35Z" level=info msg="created service test-ha" func="kubeapi.CreateService()" file="kubeapi/service.go:78" version=4.3.2
time="2020-06-21T03:47:35Z" level=info msg="creating Pgcluster object  in namespace pgo" func="operator/cluster.addClusterCreateDeployments()" file="operator/cluster/clusterlogic.go:73" version=4.3.2
time="2020-06-21T03:47:35Z" level=info msg="created with Name=test-ha in namespace pgo" func="operator/cluster.addClusterCreateDeployments()" file="operator/cluster/clusterlogic.go:74" version=4.3.2
time="2020-06-21T03:47:35Z" level=info msg="created service test-ha-backrest-shared-repo" func="kubeapi.CreateService()" file="kubeapi/service.go:78" version=4.3.2
time="2020-06-21T03:47:35Z" level=debug msg="StorageType is create" func="operator/pvc.CreatePVC()" file="operator/pvc/pvc.go:119" version=4.3.2
time="2020-06-21T03:47:35Z" level=debug msg="pvcname=test-ha-pgbr-repo storagespec=&{  ReadWriteMany 5G dynamic  }" func="operator/pvc.CreatePVC()" file="operator/pvc/pvc.go:120" version=4.3.2
time="2020-06-21T03:47:35Z" level=debug msg="in createPVC" func="operator/pvc.Create()" file="operator/pvc/pvc.go:134" version=4.3.2
time="2020-06-21T03:47:35Z" level=debug msg="using dynamic PVC template" func="operator/pvc.Create()" file="operator/pvc/pvc.go:148" version=4.3.2
time="2020-06-21T03:47:35Z" level=info msg="created PVC =test-ha-pgbr-repo in namespace pgo" func="operator/pvc.CreatePVC()" file="operator/pvc/pvc.go:126" version=4.3.2
time="2020-06-21T03:47:35Z" level=debug msg="created backrest-shared-repo pvc [test-ha-pgbr-repo]" func="operator/backrest.CreateRepoDeployment()" file="operator/backrest/repo.go:102" version=4.3.2

"resources": {
  
  
  "requests": {
    
    
    "memory": "48Mi"
    
  }
  
},

time="2020-06-21T03:47:35Z" level=debug msg="[123 34 102 115 71 114 111 117 112 34 58 50 54 125]" func="operator.GetPodSecurityContext()" file="operator/common.go:174" version=4.3.2
time="2020-06-21T03:47:35Z" level=debug msg="GetPodAnitAffinity with clusterName=[test-ha]" func="operator.GetPodAntiAffinity()" file="operator/clusterutilities.go:572" version=4.3.2
time="2020-06-21T03:47:35Z" level=debug msg=test-ha-backrest-shared-repo func="operator/backrest.CreateRepoDeployment()" file="operator/backrest/repo.go:131" version=4.3.2
time="2020-06-21T03:47:35Z" level=info msg="created deployment test-ha-backrest-shared-repo" func="kubeapi.CreateDeployment()" file="kubeapi/deployment.go:55" version=4.3.2
time="2020-06-21T03:47:35Z" level=debug msg="[123 34 102 115 71 114 111 117 112 34 58 50 54 125]" func="operator.GetPodSecurityContext()" file="operator/common.go:174" version=4.3.2
time="2020-06-21T03:47:35Z" level=debug msg="GetAffinity with nodeLabelKey=[] nodeLabelKey=[] and operator=[In]\n" func="operator.GetAffinity()" file="operator/clusterutilities.go:543" version=4.3.2
time="2020-06-21T03:47:35Z" level=debug msg="GetPodAnitAffinity with clusterName=[test-ha]" func="operator.GetPodAntiAffinity()" file="operator/clusterutilities.go:572" version=4.3.2

"resources": {
  
  
  "requests": {
    
    
    "memory": "128Mi"
    
  }
  
},

```
time="2020-06-21T03:47:35Z" level=debug msg="configmaps \"pgo-custom-pg-config\" not found" func="kubeapi.GetConfigMap()" file="kubeapi/configmap.go:45" version=4.3.2
time="2020-06-21T03:47:35Z" level=debug msg="pgo-custom-pg-config configmap not found " func="kubeapi.GetConfigMap()" file="kubeapi/configmap.go:46" version=4.3.2
time="2020-06-21T03:47:35Z" level=debug msg="pgo-custom-pg-config was not found, skipping global configMap" func="operator.GetConfVolume()" file="operator/clusterutilities.go:323" version=4.3.2
time="2020-06-21T03:47:35Z" level=debug msg="ConfigMap Controller: handling a configmap sync for key pgo/test-ha-pgha-config" func="controller/configmap.(*Controller).handleConfigMapSync()" file="controller/configmap/synchandler.go:35" version=4.3.2
time="2020-06-21T03:47:35Z" level=debug msg="created ConfigMap test-ha-pgha-config" func="kubeapi.CreateConfigMap()" file="kubeapi/configmap.go:35" version=4.3.2
time="2020-06-21T03:47:35Z" level=debug msg="collectaddon value is []" func="operator/cluster.addClusterCreateDeployments()" file="operator/cluster/clusterlogic.go:177" version=4.3.2
time="2020-06-21T03:47:35Z" level=debug msg="deployment test-ha not found" func="kubeapi.GetDeployment()" file="kubeapi/deployment.go:64" version=4.3.2
time="2020-06-21T03:47:35Z" level=info msg="created deployment test-ha" func="kubeapi.CreateDeployment()" file="kubeapi/deployment.go:55" version=4.3.2
time="2020-06-21T03:47:35Z" level=debug msg="{\"metadata\":{\"labels\":{\"crunchy-pgha-scope\":\"test-ha\",\"crunchy_collect\":\"false\",\"deployment-name\":\"test-ha\",\"pg-cluster\":\"test-ha\",\"pg-pod-anti-affinity\":\"\",\"pgo-version\":\"4.3.2\",\"workflowid\":\"0c560401-3008-4328-b938-6a724aeb5b62\"}},\"spec\":{\"PrimaryStorage\":{\"name\":\"test-ha\"}}}" func="util.PatchClusterCRD()" file="util/util.go:160" version=4.3.2
time="2020-06-21T03:47:35Z" level=debug msg="Cluster Operator: starting cluster test-ha" func="operator/cluster.StartupCluster()" file="operator/cluster/clusterlogic.go:533" version=4.3.2
time="2020-06-21T03:47:35Z" level=debug msg="setting autofailover to true for cluster with pgha scope test-ha" func="util.ToggleAutoFailover()" file="util/failover.go:244" version=4.3.2
time="2020-06-21T03:47:35Z" level=debug msg="[{\"op\":\"replace\",\"path\":\"/spec/status\",\"value\":\"completed\"}]" func="util.Patch()" file="util/util.go:70" version=4.3.2
time="2020-06-21T03:47:35Z" level=debug msg="configmaps \"test-ha-config\" not found" func="kubeapi.GetConfigMap()" file="kubeapi/configmap.go:45" version=4.3.2
time="2020-06-21T03:47:35Z" level=debug msg="test-ha-config configmap not found " func="kubeapi.GetConfigMap()" file="kubeapi/configmap.go:46" version=4.3.2
time="2020-06-21T03:47:35Z" level=error msg="Unable to find configMap test-ha-config when attempting disable autofailover" func="util.ToggleAutoFailover()" file="util/failover.go:249" version=4.3.2
time="2020-06-21T03:47:35Z" level=debug msg="Cluster Operator: starting cluster test-ha" func="operator/cluster.StartupCluster()" file="operator/cluster/clusterlogic.go:533" version=4.3.2
time="2020-06-21T03:47:35Z" level=debug msg="setting autofailover to true for cluster with pgha scope test-ha" func="util.ToggleAutoFailover()" file="util/failover.go:244" version=4.3.2
time="2020-06-21T03:47:35Z" level=debug msg="configmaps \"test-ha-config\" not found" func="kubeapi.GetConfigMap()" file="kubeapi/configmap.go:45" version=4.3.2
time="2020-06-21T03:47:35Z" level=debug msg="test-ha-config configmap not found " func="kubeapi.GetConfigMap()" file="kubeapi/configmap.go:46" version=4.3.2
time="2020-06-21T03:47:35Z" level=error msg="Unable to find configMap test-ha-config when attempting disable autofailover" func="util.ToggleAutoFailover()" file="util/failover.go:249" version=4.3.2
time="2020-06-21T03:47:35Z" level=debug msg="[{\"op\":\"replace\",\"path\":\"/spec/PrimaryStorage/name\",\"value\":\"test-ha\"}]" func="util.Patch()" file="util/util.go:70" version=4.3.2
time="2020-06-21T03:47:35Z" level=debug msg="publishing events.EventCreateClusterFormat message Event Event CreateCluster - ns [pgo] - user [admin] topics [[clustertopic]] timestamp [2020-06-21 03:47:35.777955326 +0000 UTC m=+169270.217486482] - (create cluster) clustername test-ha workflow 0c560401-3008-4328-b938-6a724aeb5b62" func="events.Publish()" file="events/eventing.go:49" version=4.3.2
time="2020-06-21T03:47:35Z" level=debug msg="header Event CreateCluster - ns [pgo] - user [admin] topics [[clustertopic]] timestamp [2020-06-21 03:47:35.777955326 +0000 UTC m=+169270.217486482] " func="events.Publish()" file="events/eventing.go:50" version=4.3.2
time="2020-06-21T03:47:35Z" level=debug msg="{\n  \"eventheader\": {\n    \"EventType\": \"CreateCluster\",\n    \"namespace\": \"pgo\",\n    \"username\": \"admin\",\n    \"timestamp\": \"2020-06-21T03:47:35.777955326Z\",\n    \"topic\": [\n      \"clustertopic\"\n    ]\n  },\n  \"clustername\": \"test-ha\",\n  \"workflowid\": \"0c560401-3008-4328-b938-6a724aeb5b62\"\n}" func="events.Publish()" file="events/eventing.go:60" version=4.3.2
2020/06/21 03:47:35 INF   42 (localhost:4150) connecting to nsqd
time="2020-06-21T03:47:35Z" level=debug msg="onAdd putting key in queue pgo/test-ha-vzbz" func="controller/pgreplica.(*Controller).onAdd()" file="controller/pgreplica/pgreplicacontroller.go:153" version=4.3.2
time="2020-06-21T03:47:35Z" level=debug msg="working on pgo/test-ha-vzbz" func="controller/pgreplica.(*Controller).processNextItem()" file="controller/pgreplica/pgreplicacontroller.go:70" version=4.3.2
time="2020-06-21T03:47:35Z" level=debug msg="pgreplica queue got key ns=[pgo] resource=[test-ha-vzbz]" func="controller/pgreplica.(*Controller).processNextItem()" file="controller/pgreplica/pgreplicacontroller.go:75" version=4.3.2
time="2020-06-21T03:47:35Z" level=debug msg="scaling deployment test-ha-backrest-shared-repo to 1 for cluster test-ha" func="operator/cluster.ScaleClusterDeployments()" file="operator/cluster/clusterlogic.go:610" version=4.3.2
time="2020-06-21T03:47:35Z" level=debug msg="deployment test-ha-vzbz not found" func="kubeapi.GetDeployment()" file="kubeapi/deployment.go:64" version=4.3.2
time="2020-06-21T03:47:35Z" level=debug msg="working...no replica found, means we process" func="controller/pgreplica.(*Controller).processNextItem()" file="controller/pgreplica/pgreplicacontroller.go:95" version=4.3.2
time="2020-06-21T03:47:35Z" level=debug msg="Scaled pgBackRest repo deployment test-ha to 1 to proceed with initializing cluster test-ha" func="controller/pgcluster.(*Controller).processNextItem()" file="controller/pgcluster/pgclustercontroller.go:155" version=4.3.2
time="2020-06-21T03:47:35Z" level=debug msg="{\"status\":{\"message\":\"Pgreplica processing pending the creation of the initial backup\",\"state\":\"pgreplica Pending init\"}}" func="kubeapi.PatchpgreplicaStatus()" file="kubeapi/pgreplica.go:173" version=4.3.2
time="2020-06-21T03:47:35Z" level=debug msg="[pgreplica Controller] onUpdate ns=pgo /apis/crunchydata.com/v1/namespaces/pgo/pgreplicas/test-ha-vzbz" func="controller/pgreplica.(*Controller).onUpdate()" file="controller/pgreplica/pgreplicacontroller.go:164" version=4.3.2
time="2020-06-21T03:47:35Z" level=debug msg="Pod Controller: onAdd processing the addition of pod test-ha-backrest-shared-repo-77d8bcbf4-gqzvn in namespace pgo" func="controller/pod.(*Controller).onAdd()" file="controller/pod/podcontroller.go:50" version=4.3.2
time="2020-06-21T03:47:35Z" level=debug msg="Pod Controller: onUpdate processing update for pod test-ha-backrest-shared-repo-77d8bcbf4-gqzvn in namespace pgo" func="controller/pod.(*Controller).onUpdate()" file="controller/pod/podcontroller.go:74" version=4.3.2

```
