### ISSUE TITLE
[4.3.2] ccp_monitoring eating all memory

### ISSUE THREAD

**Issue by cubed-it** [CrunchyData/postgres-operator#1671]
Hey,
I have deployed a cluster with version 4.3.2 and monitoring support. I now observe that postgres crashes cyclically. The reason is that the ccp_monitoring connection occupies the whole memory bit by bit.
Do you have an idea what could be the reason for this?

```
2020-06-25 06:27:40.241 CEST [2506] LOG:  server process (PID 2617) was terminated by signal 9: Killed
2020-06-25 06:27:40.241 CEST [2506] DETAIL:  Failed process was running: WITH all_backups AS ( SELECT config_file , jsonb_array_elements(data) AS stanza_data FROM monitor.pgbackrest_info(10) ) , per_stanza AS ( SELECT config_file , stanza_data->>'name' AS stanza , jsonb_array_elements(stanza_data->'backup') AS backup_data FROM all_backups ) SELECT config_file , stanza , backup_data->>'type' AS backup_type , EXTRACT( epoch FROM (max(to_timestamp((backup_data->'timestamp'->>'stop')::bigint))) - max(to_timestamp((backup_data->'timestamp'->>'start')::bigint)) ) AS backup_runtime_seconds FROM per_stanza GROUP BY config_file, stanza, backup_data->>'type'
2020-06-25 06:27:40.241 CEST [2506] LOG:  terminating any other active server processes
```
<img width="460" alt="pgo_1_top" src="https://user-images.githubusercontent.com/11182260/85918666-19a9fd80-b865-11ea-91eb-dd7038675401.PNG">
<img width="1149" alt="pgo_1_user" src="https://user-images.githubusercontent.com/11182260/85918668-1a429400-b865-11ea-9617-3ef93d7741c6.PNG">

Blue is container_memory_working_set_bytes, yellow is container_memory_cache. The working set drop is when I terminate the ccp connection
<img width="1235" alt="pgo_1_graf" src="https://user-images.githubusercontent.com/11182260/85918673-24fd2900-b865-11ea-96fe-76255b542d99.PNG">

```
    postgresql:
      parameters:
        archive_command: source /opt/cpm/bin/pgbackrest/pgbackrest-set-env.sh && pgbackrest
          archive-push "%p"
        archive_mode: on
        archive_timeout: 60
        log_directory: pg_log
        log_min_duration_statement: 60000
        log_statement: none
        shared_preload_libraries: pgaudit.so,pg_stat_statements.so
        temp_buffers: 8MB
        unix_socket_directories: /tmp,/crunchyadm
        log_timezone: Europe/Berlin
        datestyle: iso, dmy
        timezone: Europe/Berlin
        default_text_search_config: pg_catalog.german
        log_filename: server_log.%a
        log_truncate_on_rotation: on
        log_rotation_age: 1440
        max_connections: 200
        superuser_reserved_connections: 3
        # Memory Settings
        shared_buffers: '512 MB'
        work_mem: '32 MB'
        maintenance_work_mem: '320 MB'
        huge_pages: off
        effective_cache_size: '1024 MB'
        effective_io_concurrency: 100
        # Monitoring
        track_io_timing: on
        track_functions: pl
        # Replication
        wal_level: replica
        max_wal_senders: 10
        synchronous_commit: on
        wal_keep_segments: 130
        # Checkpointing
        checkpoint_timeout : '15 min'
        checkpoint_completion_target: 0.9
        max_wal_size: '1024 MB'
        min_wal_size: '512 MB'
        # WAL writing
        wal_compression: on
        wal_buffers: -1
        wal_writer_delay: 200ms
        wal_writer_flush_after: 1MB
        # Background writer
        bgwriter_delay: 200ms
        bgwriter_lru_maxpages: 100
        bgwriter_lru_multiplier: 2.0
        bgwriter_flush_after: 0
        # Parallel queries
        max_worker_processes: 2
        max_parallel_workers_per_gather: 1
        max_parallel_maintenance_workers: 1
        max_parallel_workers: 2
        parallel_leader_participation: on
        # Advanced features
        enable_partitionwise_join: on
        enable_partitionwise_aggregate: on
      recovery_conf:
        restore_command: source /opt/cpm/bin/pgbackrest/pgbackrest-set-env.sh && pgbackrest
          archive-get %f "%p"
      use_pg_rewind: true
```
