### ISSUE TITLE
How should I configure pgo with custom storage class

### ISSUE THREAD

**Issue by fiibbb** [CrunchyData/postgres-operator#1685]
** Which example are you working with? **
Following the setup guide with slight customizations

**What is the current behavior?**
pgo fails to create clusters because it's not using the requested storageclass when creating pvc's, with custom storageclass in `postgres-operator.yml`'s `STORAGE1_*` fields.

**What is the expected behavior?**
pgo should respect the storage configuration and create PVCs using the specified storage class.

**Other information** (e.g. detailed explanation, related issues,  etc)

My k8s cluster runs in the cloud with PVs managed using custom storage class and the storage class looks like the following:
```
➜  ~ kubectl get sc
NAME       PROVISIONER                    RECLAIMPOLICY   VOLUMEBINDINGMODE      ALLOWVOLUMEEXPANSION   AGE
standard   kubernetes.io/no-provisioner   Delete          WaitForFirstConsumer   false                  17m
➜  ~ kubectl describe sc standard
Name:            standard
IsDefaultClass:  No
Annotations:     kubectl.kubernetes.io/last-applied-configuration={"apiVersion":"storage.k8s.io/v1","kind":"StorageClass","metadata":{"annotations":{},"name":"standard"},"provisioner":"kubernetes.io/no-provisioner","reclaimPolicy":"Delete","volumeBindingMode":"WaitForFirstConsumer"}

Provisioner:           kubernetes.io/no-provisioner
Parameters:            <none>
AllowVolumeExpansion:  <unset>
MountOptions:          <none>
ReclaimPolicy:         Delete
VolumeBindingMode:     WaitForFirstConsumer
Events:                <none>
➜  ~
```

I can successfully deploy `pgo` with the following storage config:
```
                  - name: BACKREST_STORAGE
                    value: "standard"
                  - name: BACKUP_STORAGE
                    value: "standard"
                  - name: PRIMARY_STORAGE
                    value: "standard"
                  - name: REPLICA_STORAGE
                    value: "standard"
                  - name: WAL_STORAGE
                    value: ""
                  - name: STORAGE1_NAME
                    value: "standard"
                  - name: STORAGE1_ACCESS_MODE
                    value: "ReadWriteOnce"
                  - name: STORAGE1_SIZE
                    value: "1G"
                  - name: STORAGE1_TYPE
                    value: "dynamic"
                  - name: STORAGE1_CLASS
                    value: "standard"
```

I was expecting that when I then run `pgo create cluster test --storage-config=standard`, it would try to create PVCs with `standard` storageclass. However, the pgo config seem to be ignoring my `STORAGE1_CLASS` setting, as shown below. Note that `StorageClass` is set to empty string while other `STORAGE1_*` fields are preserved.

```
➜  ~ pgo -n pgo show config
BackrestStorage: standard
BackupStorage: standard
BasicAuth: ""
Cluster:
  Backrest: true
  BackrestPort: 2022
  BackrestS3Bucket: ""
  BackrestS3Endpoint: ""
  BackrestS3Region: ""
  Badger: false
  CCPImagePrefix: registry.developers.crunchydata.com/crunchydata
  CCPImageTag: centos7-12.3-4.3.2
  Database: ""
  DefaultBackrestMemory: 48Mi
  DefaultInstanceMemory: 128Mi
  DefaultPgBouncerMemory: 24Mi
  DisableAutofail: false
  DisableFSGroup: false
  DisableReplicaStartFailReinit: false
  EnableCrunchyadm: false
  ExporterPort: "9187"
  Metrics: false
  PGBadgerPort: "10000"
  PasswordAgeDays: ""
  PasswordLength: "24"
  PgmonitorPassword: ""
  PodAntiAffinity: preferred
  PodAntiAffinityPgBackRest: ""
  PodAntiAffinityPgBouncer: ""
  Policies: ""
  Port: "5432"
  Replicas: "0"
  ServiceType: ClusterIP
  SyncReplication: false
  User: testuser
Pgo:
  Audit: false
  ConfigMapWorkerCount: null
  ControllerGroupRefreshInterval: null
  NamespaceRefreshInterval: null
  NamespaceWorkerCount: null
  PGClusterWorkerCount: null
  PGOImagePrefix: registry.developers.crunchydata.com/crunchydata
  PGOImageTag: centos7-4.3.2
  PGReplicaWorkerCount: null
  PGTaskWorkerCount: null
PrimaryStorage: standard
ReplicaStorage: standard
Storage:
  standard:
    AccessMode: ReadWriteOnce
    MatchLabels: ""
    Size: 1G
    StorageClass: ""
    StorageType: dynamic
    SupplementalGroups: ""
WALStorage: ""
```

This then further lead to PVCs created with empty storage class, hence unable to bind:

```
➜  ~ kubectl get pvc -n pgo
NAME             STATUS    VOLUME   CAPACITY   ACCESS MODES   STORAGECLASS   AGE
test             Pending                                                     12m
test-pgbr-repo   Pending                                                     12m
➜  ~ kubectl describe -n pgo pvc test
Name:          test
Namespace:     pgo
StorageClass:
Status:        Pending
Volume:
Labels:        pg-cluster=test
               pgremove=true
               vendor=crunchydata
Annotations:   <none>
Finalizers:    [kubernetes.io/pvc-protection]
Capacity:
Access Modes:
VolumeMode:    Filesystem
Mounted By:    <none>
Events:
  Type    Reason         Age                   From                         Message
  ----    ------         ----                  ----                         -------
  Normal  FailedBinding  2m25s (x42 over 12m)  persistentvolume-controller  no persistent volumes available for this claim and no storage class is set
```
Am I doing something wrong when configuring those `STORAGE1_*` fields? Are custom storage classes supported at all?
