### ISSUE TITLE
postgres-operator deployment didn't happen

### ISSUE THREAD

**Issue by shaikmuzakkir** [CrunchyData/postgres-operator#1731]
** Which example are you working with? **
kubernetes setup

**What is the current behavior?**
Instaling postgres on kubernetes with the instruction here - https://www.crunchydata.com/developers/download-postgres/containers/postgres-operator

Job completed but the postgres-operator deployment wasn't created
```
[root@master /]# k get all -n pgo
NAME                   READY   STATUS      RESTARTS   AGE
pod/pgo-deploy-2jwkk   0/1     Completed   0          60m

NAME                   COMPLETIONS   DURATION   AGE
job.batch/pgo-deploy   1/1           28s        60m
```

**Please tell us about your environment:**
[root@master /]# kubectl version
Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.11", GitCommit:"25074a190ef2a07d8b0ed38734f2cb373edfb868", GitTreeState:"clean", BuildDate:"2019-09-18T14:41:46Z", GoVersion:"go1.11.13", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.11", GitCommit:"25074a190ef2a07d8b0ed38734f2cb373edfb868", GitTreeState:"clean", BuildDate:"2019-09-18T14:34:46Z", GoVersion:"go1.11.13", Compiler:"gc", Platform:"linux/amd64"}

If possible please run the following on the kubernetes or OpenShift (oc) commands and provide the result:
 kubectl describe yourPodName

```
apiVersion: v1
kind: ServiceAccount
metadata:
    name: pgo-deployer-sa
    namespace: pgo
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: pgo-deployer-cr
rules:
  - apiGroups:
      - ''
    resources:
      - namespaces
    verbs:
      - get
      - list
      - create
      - patch
      - delete
  - apiGroups:
      - ''
    resources:
      - pods
    verbs:
      - list
  - apiGroups:
      - ''
    resources:
      - secrets
    verbs:
      - get
      - create
      - delete
  - apiGroups:
      - ''
    resources:
      - configmaps
      - services
      - persistentvolumeclaims
    verbs:
      - get
      - create
      - delete
  - apiGroups:
      - ''
    resources:
      - serviceaccounts
    verbs:
      - get
      - create
      - delete
      - patch
  - apiGroups:
      - apps
      - extensions
    resources:
      - deployments
    verbs:
      - get
      - list
      - create
      - delete
  - apiGroups:
      - apiextensions.k8s.io
    resources:
      - customresourcedefinitions
    verbs:
      - get
      - create
      - delete
  - apiGroups:
      - rbac.authorization.k8s.io
    resources:
      - clusterroles
      - clusterrolebindings
      - roles
      - rolebindings
    verbs:
      - get
      - create
      - delete
      - bind
      - escalate
  - apiGroups:
      - rbac.authorization.k8s.io
    resources:
      - roles
    verbs:
      - create
      - delete
  - apiGroups:
      - batch
    resources:
      - jobs
    verbs:
      - delete
  - apiGroups:
      - crunchydata.com
    resources:
      - pgclusters
      - pgreplicas
      - pgpolicies
      - pgtasks
    verbs:
      - delete
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
    name: pgo-deployer-crb
roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: ClusterRole
    name: pgo-deployer-cr
subjects:
- kind: ServiceAccount
  name: pgo-deployer-sa
  namespace: pgo
---
apiVersion: batch/v1
kind: Job
metadata:
    name: pgo-deploy
    namespace: pgo
spec:
    backoffLimit: 0
    template:
        metadata:
            name: pgo-deploy
        spec:
            serviceAccountName: pgo-deployer-sa
            restartPolicy: Never
            containers:
            - name: pgo-deploy
              image: hub.docker.com/crunchydata/pgo-deployer:centos7-4.3.2
              imagePullPolicy: IfNotPresent
              env:
                  - name: ARCHIVE_MODE
                    value: "true"
                  - name: ARCHIVE_TIMEOUT
                    value: "60"
                  - name: BACKREST
                    value: "true"
                  - name: BADGER
                    value: "false"
                  - name: CRUNCHY_DEBUG
                    value: "false"
                  - name: CREATE_RBAC
                    value: "true"
                  - name: CCP_IMAGE_PREFIX
                    value: "hub.docker.com/crunchydata"
                  - name: CCP_IMAGE_TAG
                    value: "centos7-12.3-4.3.2"
                  - name: DB_PASSWORD_LENGTH
                    value: "24"
                  - name: DB_PORT
                    value: "5432"
                  - name: DB_REPLICAS
                    value: "2"
                  - name: DB_USER
                    value: "testuser"
                  - name: DEFAULT_INSTANCE_MEMORY
                    value: "128Mi"
                  - name: DEFAULT_PGBACKREST_MEMORY
                    value: ""
                  - name: DEFAULT_PGBOUNCER_MEMORY
                    value: ""
                  - name: DEPLOY_ACTION
                    value: "upgrade"
                  - name: DISABLE_AUTO_FAILOVER
                    value: "false"
                  - name: DISABLE_FSGROUP
                    value: "false"
                  - name: DYNAMIC_RBAC
                    value: "false"
                  - name: EXPORTERPORT
                    value: "9187"
                  - name: METRICS
                    value: "true"
                  - name: NAMESPACE
                    value: "pgo1"
                  - name: NAMESPACE_MODE
                    value: "dynamic"
                  - name: PGBADGERPORT
                    value: "10000"
                  - name: PGO_ADMIN_PASSWORD
                    value: "password"
                  - name: PGO_ADMIN_PERMS
                    value: "*"
                  - name: PGO_ADMIN_ROLE_NAME
                    value: "pgoadmin"
                  - name: PGO_ADMIN_USERNAME
                    value: "admin"
                  - name: PGO_CLIENT_VERSION
                    value: "v4.3.2"
                  - name: PGO_IMAGE_PREFIX
                    value: "hub.docker.com/crunchydata"
                  - name: PGO_IMAGE_TAG
                    value: "centos7-4.3.2"
                  - name: PGO_INSTALLATION_NAME
                    value: "devtest"
                  - name: PGO_OPERATOR_NAMESPACE
                    value: "pgo1"
                  - name: SCHEDULER_TIMEOUT
                    value: "3600"
                  - name: BACKREST_STORAGE
                    value: "hostpathstorage"
                  - name: BACKUP_STORAGE
                    value: "hostpathstorage"
                  - name: PRIMARY_STORAGE
                    value: "hostpathstorage"
                  - name: REPLICA_STORAGE
                    value: "hostpathstorage"
                  - name: WAL_STORAGE
                    value: ""
                  - name: STORAGE1_NAME
                    value: "hostpathstorage"
                  - name: STORAGE1_ACCESS_MODE
                    value: "ReadWriteMany"
                  - name: STORAGE1_SIZE
                    value: "1G"
                  - name: STORAGE1_TYPE
                    value: "create"
                  - name: STORAGE2_NAME
                    value: "replicastorage"
                  - name: STORAGE2_ACCESS_MODE
                    value: "ReadWriteMany"
                  - name: STORAGE2_SIZE
                    value: "700M"
                  - name: STORAGE2_TYPE
                    value: "create"
                  - name: STORAGE3_NAME
                    value: "nfsstorage"
                  - name: STORAGE3_ACCESS_MODE
                    value: "ReadWriteMany"
                  - name: STORAGE3_SIZE
                    value: "1G"
                  - name: STORAGE3_TYPE
                    value: "create"
                  - name: STORAGE3_SUPPLEMENTAL_GROUPS
                    value: "65534"
                  - name: STORAGE4_NAME
                    value: "nfsstoragered"
                  - name: STORAGE4_ACCESS_MODE
                    value: "ReadWriteMany"
                  - name: STORAGE4_SIZE
                    value: "1G"
                  - name: STORAGE4_MATCH_LABEL
                    value: "crunchyzone=red"
                  - name: STORAGE4_TYPE
                    value: "create"
                  - name: STORAGE4_SUPPLEMENTAL_GROUPS
                    value: "65534"
                  - name: STORAGE5_NAME
                    value: "storageos"
                  - name: STORAGE5_ACCESS_MODE
                    value: "ReadWriteOnce"
                  - name: STORAGE5_SIZE
                    value: "5Gi"
                  - name: STORAGE5_TYPE
                    value: "dynamic"
                  - name: STORAGE5_CLASS
                    value: "fast"
                  - name: STORAGE6_NAME
                    value: "primarysite"
                  - name: STORAGE6_ACCESS_MODE
                    value: "ReadWriteOnce"
                  - name: STORAGE6_SIZE
                    value: "4G"
                  - name: STORAGE6_TYPE
                    value: "dynamic"
                  - name: STORAGE6_CLASS
                    value: "primarysite"
                  - name: STORAGE7_NAME
                    value: "alternatesite"
                  - name: STORAGE7_ACCESS_MODE
                    value: "ReadWriteOnce"
                  - name: STORAGE7_SIZE
                    value: "4G"
                  - name: STORAGE7_TYPE
                    value: "dynamic"
                  - name: STORAGE7_CLASS
                    value: "alternatesite"
                  - name: STORAGE8_NAME
                    value: "gce"
                  - name: STORAGE8_ACCESS_MODE
                    value: "ReadWriteOnce"
                  - name: STORAGE8_SIZE
                    value: "300M"
                  - name: STORAGE8_TYPE
                    value: "dynamic"
                  - name: STORAGE8_CLASS
                    value: "standard"
                  - name: STORAGE9_NAME
                    value: "rook"
                  - name: STORAGE9_ACCESS_MODE
                    value: "ReadWriteOnce"
                  - name: STORAGE9_SIZE
                    value: "1Gi"
                  - name: STORAGE9_TYPE
                    value: "dynamic"
                  - name: STORAGE9_CLASS
                    value: "rook-ceph-block"
```

 kubectl log yourPodName

```
[root@master postgres]# k logs -f pod/pgo-deploy-4dqgj -n pgo

PLAY [Deploy Crunchy PostgreSQL Operator] **************************************

TASK [Gathering Facts] *********************************************************
ok: [localhost]

TASK [pgo-preflight : fail] ****************************************************
skipping: [localhost]

TASK [pgo-preflight : assert] **************************************************
ok: [localhost] => {
    "changed": false,
    "msg": "All assertions passed"
}

TASK [pgo-preflight : assert] **************************************************
skipping: [localhost]

TASK [pgo-preflight : assert] **************************************************
skipping: [localhost]

TASK [pgo-preflight : assert] **************************************************
ok: [localhost] => {
    "changed": false,
    "msg": "All assertions passed"
}

TASK [pgo-preflight : include_tasks] *******************************************
skipping: [localhost]

TASK [pgo-preflight : include_tasks] *******************************************
included: /ansible/roles/pgo-preflight/tasks/check_kubernetes.yml for localhost

TASK [pgo-preflight : Check if the kubectl command is installed] ***************
changed: [localhost]

TASK [pgo-preflight : Ensure kubectl is installed] *****************************
ok: [localhost] => {
    "changed": false,
    "msg": "All assertions passed"
}

TASK [pgo-preflight : include_tasks] *******************************************
included: /ansible/roles/pgo-preflight/tasks/check_inventory.yml for localhost

TASK [pgo-preflight : Check if mandatory inventory file variables are defined] ***
skipping: [localhost] => (item=pgo_operator_namespace)
skipping: [localhost] => (item=pgo_installation_name)
skipping: [localhost] => (item=pgo_admin_username)
skipping: [localhost] => (item=pgo_admin_password)
skipping: [localhost] => (item=pgo_admin_role_name)
skipping: [localhost] => (item=pgo_admin_perms)
skipping: [localhost] => (item=ccp_image_prefix)
skipping: [localhost] => (item=ccp_image_tag)
skipping: [localhost] => (item=pgo_image_prefix)
skipping: [localhost] => (item=pgo_image_tag)
skipping: [localhost] => (item=disable_auto_failover)
skipping: [localhost] => (item=backrest)
skipping: [localhost] => (item=badger)
skipping: [localhost] => (item=metrics)
skipping: [localhost] => (item=archive_mode)
skipping: [localhost] => (item=archive_timeout)
skipping: [localhost] => (item=db_password_length)
skipping: [localhost] => (item=create_rbac)
skipping: [localhost] => (item=db_port)
skipping: [localhost] => (item=db_replicas)
skipping: [localhost] => (item=db_user)
skipping: [localhost] => (item=backrest_storage)
skipping: [localhost] => (item=backup_storage)
skipping: [localhost] => (item=primary_storage)
skipping: [localhost] => (item=replica_storage)
skipping: [localhost] => (item=pgo_client_version)
skipping: [localhost] => (item=pgbadgerport)
skipping: [localhost] => (item=exporterport)
skipping: [localhost] => (item=scheduler_timeout)
skipping: [localhost] => (item=namespace_mode)
skipping: [localhost] => (item=dynamic_rbac)

TASK [pgo-operator : Set output directory fact] ********************************
ok: [localhost]

TASK [pgo-operator : Ensure output directory exists] ***************************
changed: [localhost]

TASK [pgo-operator : include_tasks] ********************************************
skipping: [localhost] => (item=openshift_auth.yml)
skipping: [localhost] => (item=openshift.yml)

TASK [pgo-operator : include_tasks] ********************************************
included: /ansible/roles/pgo-operator/tasks/kubernetes_auth.yml for localhost
included: /ansible/roles/pgo-operator/tasks/kubernetes.yml for localhost

TASK [pgo-operator : Set the Kubernetes Context] *******************************
skipping: [localhost]

TASK [pgo-operator : Use kubectl or oc] ****************************************
ok: [localhost]

TASK [pgo-metrics : include_tasks] *********************************************
skipping: [localhost]

TASK [pgo-metrics : include_tasks] *********************************************
skipping: [localhost]

TASK [pgo-metrics : include_tasks] *********************************************
skipping: [localhost] => (item=openshift_auth.yml)
skipping: [localhost] => (item=openshift.yml)

TASK [pgo-metrics : include_tasks] *********************************************
included: /ansible/roles/pgo-metrics/tasks/kubernetes_auth.yml for localhost
included: /ansible/roles/pgo-metrics/tasks/kubernetes.yml for localhost

TASK [pgo-metrics : Set the Kubernetes Context] ********************************
skipping: [localhost]

TASK [pgo-metrics : Use kubectl or oc] *****************************************
ok: [localhost]

TASK [pgo-metrics : include_tasks] *********************************************
skipping: [localhost]

TASK [pgo-metrics : include_tasks] *********************************************
skipping: [localhost]

PLAY RECAP *********************************************************************
localhost                  : ok=15   changed=2    unreachable=0    failed=0    skipped=13   rescued=0    ignored=0

```

While I did the setup on a different cluster I saw a deployment was created by the name postgres-operator and a corresponding pod was also running. But not on this cluster. 

I have a helm deployment of postgres already running on this cluster. Could that be the issue?
[root@master postgres]# helm list postgres
NAME    	REVISION	UPDATED                 	STATUS  	CHART            	APP VERSION	NAMESPACE
postgres	1       	Fri Sep  7 06:04:22 2018	DEPLOYED	postgresql-0.15.0	9.6.2      	default
