### ISSUE TITLE
pgo restore cluster with custom configmap

### ISSUE THREAD

**Issue by aurelien43** [CrunchyData/postgres-operator#1732]
hello, 

I have a cluster with a custom config and when i try to restore this cluster, the new cluster cant start. 

To reproduce this error : 

1. create the new configmap 
`kc create configmap pgaas-pg-config-cpu8ram16g --from-file=postgres-ha.yaml -n pgo1`

postgres-ha.yaml 
```
bootstrap:
  dcs:
    postgresql:
      parameters:
        shared_buffers: 3276MB
        hot_standby: off
        effective_cache_size: 9830MB
        maintenance_work_mem: 3276MB
        temp_buffers: 50MB
        work_mem: 819MB
        wal_buffers: 16MB
        log_connections: on
        log_disconnections: on
        max_worker_processes: 16
        max_parallel_workers: 15
        max_parallel_maintenance_workers: 14
        max_parallel_workers_per_gather: 12
        max_stack_depth: 6144
        effective_io_concurrency: 100
postgresql:
  pg_hba:
    - local all pgaasadmin peer map=postgres_to_pgaasadmin
    - local all postgres peer
    - local all crunchyadm peer
    - host replication primaryuser 0.0.0.0/0 md5
    - host all primaryuser 0.0.0.0/0 reject
    - host all postgres 0.0.0.0/0 md5
    - host all pgaasadmin 0.0.0.0/0 md5
    - host all all 0.0.0.0/0 md5
  pg_ident:
    - postgres_to_pgaas postgres pgaasadmin
```

2.  create the cluster
`pgo create cluster test-save -n pgo1 --custom-config pgaas-pg-config-cpu8ram16g --cpu 4 --memory 16Gi --cpu-limit 8 --memory-limit 16Gi ` 

3.  Insert value and create backup 
`pgo backup test-save --backup-opts="--type=full --process-max=4 --no-compress" -n pgo1`

4.  performe the restore
` pgo restore -n pgo1 test-save --backup-opts=" --set=20200722-125130F --target-action=promote --type=immediate"`

5. The new pods are stuck in _**Readiness probe failed:**_ with this error in logs : 
                    `FATAL:  hot standby is not possible because max_worker_processes = 8 is a lower setting than on the master server (its value was 16)`

**Please tell us about your environment:**

* Operating System: centos7
* Where is this running ( Local, Cloud Provider): VM
* Storage being used (NFS, Hostpath, Gluster, etc): NFS
* Container Image Tag: centos7-12.3-4.3.2
* PostgreSQL Version: 12.3
* Platform (Docker, Kubernetes, OpenShift): Kubernetes
* Platform Version: 1.16
