### ISSUE TITLE
backrest-shared-repo pod fails to start due to incorrect volume storage class

### ISSUE THREAD

**Issue by carminalazu** [CrunchyData/postgres-operator#1739]
Creating a new cluster fails on v4.4.0 due to the backrespg volume failing to mount:

```
┌───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────── Describe(pgo/mycluster-backrest-shared-repo-6987db4dd7-dbz7j) ──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┐
│ Name:           mycluster-backrest-shared-repo-6987db4dd7-dbz7j                                                                                                                                                                                                                                                                                                          │
│ Namespace:      pgo                                                                                                                                                                                                                                                                                                                                                      │
│ Priority:       0                                                                                                                                                                                                                                                                                                                                                        │
│ Node:           lke3984-5182-5ea5671f3298/192.168.176.179                                                                                                                                                                                                                                                                                                                │
│ Start Time:     Tue, 28 Jul 2020 19:35:49 +0100                                                                                                                                                                                                                                                                                                                          │
│ Labels:         name=mycluster-backrest-shared-repo                                                                                                                                                                                                                                                                                                                      │
│                 pg-cluster=mycluster                                                                                                                                                                                                                                                                                                                                     │
│                 pg-pod-anti-affinity=preferred                                                                                                                                                                                                                                                                                                                           │
│                 pgo-backrest-repo=true                                                                                                                                                                                                                                                                                                                                   │
│                 pod-template-hash=6987db4dd7                                                                                                                                                                                                                                                                                                                             │
│                 service-name=mycluster-backrest-shared-repo                                                                                                                                                                                                                                                                                                              │
│                 vendor=crunchydata                                                                                                                                                                                                                                                                                                                                       │
│ Annotations:    <none>                                                                                                                                                                                                                                                                                                                                                   │
│ Status:         Pending                                                                                                                                                                                                                                                                                                                                                  │
│ IP:                                                                                                                                                                                                                                                                                                                                                                      │
│ IPs:            <none>                                                                                                                                                                                                                                                                                                                                                   │
│ Controlled By:  ReplicaSet/mycluster-backrest-shared-repo-6987db4dd7                                                                                                                                                                                                                                                                                                     │
│ Containers:                                                                                                                                                                                                                                                                                                                                                              │
│   database:                                                                                                                                                                                                                                                                                                                                                              │
│     Container ID:                                                                                                                                                                                                                                                                                                                                                        │
│     Image:          registry.developers.crunchydata.com/crunchydata/pgo-backrest-repo:centos7-4.4.0                                                                                                                                                                                                                                                                      │
│     Image ID:                                                                                                                                                                                                                                                                                                                                                            │
│     Port:           2022/TCP                                                                                                                                                                                                                                                                                                                                             │
│     Host Port:      0/TCP                                                                                                                                                                                                                                                                                                                                                │
│     State:          Waiting                                                                                                                                                                                                                                                                                                                                              │
│       Reason:       ContainerCreating                                                                                                                                                                                                                                                                                                                                    │
│     Ready:          False                                                                                                                                                                                                                                                                                                                                                │
│     Restart Count:  0                                                                                                                                                                                                                                                                                                                                                    │
│     Requests:                                                                                                                                                                                                                                                                                                                                                            │
│       memory:  48Mi                                                                                                                                                                                                                                                                                                                                                      │
│     Environment:                                                                                                                                                                                                                                                                                                                                                         │
│       PGBACKREST_STANZA:           db                                                                                                                                                                                                                                                                                                                                    │
│       SSHD_PORT:                   2022                                                                                                                                                                                                                                                                                                                                  │
│       PGBACKREST_DB_PATH:          /pgdata/mycluster                                                                                                                                                                                                                                                                                                                     │
│       PGBACKREST_REPO_PATH:        /backrestrepo/mycluster-backrest-shared-repo                                                                                                                                                                                                                                                                                          │
│       PGBACKREST_PG1_PORT:         5432                                                                                                                                                                                                                                                                                                                                  │
│       PGBACKREST_LOG_PATH:         /tmp                                                                                                                                                                                                                                                                                                                                  │
│       PGBACKREST_PG1_SOCKET_PATH:  /tmp                                                                                                                                                                                                                                                                                                                                  │
│       PGBACKREST_DB_HOST:          mycluster                                                                                                                                                                                                                                                                                                                             │
│     Mounts:                                                                                                                                                                                                                                                                                                                                                              │
│       /backrestrepo from backrestrepo (rw)                                                                                                                                                                                                                                                                                                                               │
│       /sshd from sshd (ro)                                                                                                                                                                                                                                                                                                                                               │
│ Conditions:                                                                                                                                                                                                                                                                                                                                                              │
│   Type              Status                                                                                                                                                                                                                                                                                                                                               │
│   Initialized       True                                                                                                                                                                                                                                                                                                                                                 │
│   Ready             False                                                                                                                                                                                                                                                                                                                                                │
│   ContainersReady   False                                                                                                                                                                                                                                                                                                                                                │
│   PodScheduled      True                                                                                                                                                                                                                                                                                                                                                 │
│ Volumes:                                                                                                                                                                                                                                                                                                                                                                 │
│   sshd:                                                                                                                                                                                                                                                                                                                                                                  │
│     Type:        Secret (a volume populated by a Secret)                                                                                                                                                                                                                                                                                                                 │
│     SecretName:  mycluster-backrest-repo-config                                                                                                                                                                                                                                                                                                                          │
│     Optional:    false                                                                                                                                                                                                                                                                                                                                                   │
│   backrestrepo:                                                                                                                                                                                                                                                                                                                                                          │
│     Type:        PersistentVolumeClaim (a reference to a PersistentVolumeClaim in the same namespace)                                                                                                                                                                                                                                                                    │
│     ClaimName:   mycluster-pgbr-repo                                                                                                                                                                                                                                                                                                                                     │
│     ReadOnly:    false                                                                                                                                                                                                                                                                                                                                                   │
│ QoS Class:       Burstable                                                                                                                                                                                                                                                                                                                                               │
│ Node-Selectors:  <none>                                                                                                                                                                                                                                                                                                                                                  │
│ Tolerations:     node.kubernetes.io/not-ready:NoExecute for 300s                                                                                                                                                                                                                                                                                                         │
│                  node.kubernetes.io/unreachable:NoExecute for 300s                                                                                                                                                                                                                                                                                                       │
│ Events:                                                                                                                                                                                                                                                                                                                                                                  │
│   Type     Reason              Age                    From                                Message                                                                                                                                                                                                                                                                        │
│   ----     ------              ----                   ----                                -------                                                                                                                                                                                                                                                                        │
│   Warning  FailedScheduling    <unknown>              default-scheduler                   error while running "VolumeBinding" filter plugin for pod "mycluster-backrest-shared-repo-6987db4dd7-dbz7j": pod has unbound immediate PersistentVolumeClaims                                                                                                                  │
│   Warning  FailedScheduling    <unknown>              default-scheduler                   error while running "VolumeBinding" filter plugin for pod "mycluster-backrest-shared-repo-6987db4dd7-dbz7j": pod has unbound immediate PersistentVolumeClaims                                                                                                                  │
│   Normal   Scheduled           <unknown>              default-scheduler                   Successfully assigned pgo/mycluster-backrest-shared-repo-6987db4dd7-dbz7j to lke3984-5182-5ea5671f3298                                                                                                                                                                         │
│   Warning  FailedMount         2m12s (x2 over 4m29s)  kubelet, lke3984-5182-5ea5671f3298  Unable to attach or mount volumes: unmounted volumes=[backrestrepo], unattached volumes=[sshd backrestrepo]: timed out waiting for the condition                                                                                                                               │
│   Warning  FailedAttachVolume  19s (x11 over 6m32s)   attachdetach-controller             AttachVolume.Attach failed for volume "pvc-6690449c16a94738" : rpc error: code = InvalidArgument desc = ControllerPublishVolume Volume capability is not compatible: volume_id:"81833-pvc6690449c16a94738" node_id:"20248874" volume_capability:<mount:<fs_type:"ext4" > acces │
│ s_mode:<mode:MULTI_NODE_MULTI_WRITER > > volume_context:<key:"storage.kubernetes.io/csiProvisionerIdentity" value:"1592280910967-694-" >                                                                                                                                                                                                                                 │
│
```

This seems to be related to #1451

## To reproduce

Given a 1.17 Linode Kubernetes Engine, run the following:

```
mkdir -p ~/github.com/thechangelog
cd ~/github.com/thechangelog
git clone https://github.com/thechangelog/changelog.com
cd changelog.com

make lke-postgres-operator
# ( kubectl get namespace pgo || kubectl create namespace pgo ) \
# && ytt --data-value namespace=pgo --data-value version=4.4.0 \
#   --file ~/github.com/thechangelog/changelog.com/k8s/postgres-operator > ~/github.com/thechangelog/changelog.com/k8s/postgres-operator.yml \
# && ( kubectl apply --filename ~/github.com/thechangelog/changelog.com/k8s/postgres-operator.yml \
#      || kubectl auth reconcile --filename ~/github.com/thechangelog/changelog.com/k8s/postgres-operator.yml ) \
# && echo "Waiting up to 60s for PostgreSQL Operator to install..." \
# && kubectl wait --namespace pgo --for=condition=complete job/pgo-deploy --timeout=60s \
# && echo "Running PostgreSQL Operator post-install cleanup..." \
# && kubectl delete --namespace pgo serviceaccounts/pgo-deployer-sa clusterrole/pgo-deployer-cr configmap/pgo-deployer-cm clusterrolebinding/pgo-deployer-crb job/pgo-deploy

make pgo
# kubectl exec --tty --stdin --namespace pgo deploy/pgo-client -- bash
pgo create cluster mycluster -n pgo
```


## Expected behavior
 
I would expect backrest-shared-repo to use the local-storage class, as captured in the `hostpathstorage` config, but it seems to pick the `linode-block-storage-retain` volumes which do not support `ReadWriteMany` mode.

```
pgo show config -n pgo
BackrestStorage: hostpathstorage
BackupStorage: hostpathstorage
BasicAuth: ""
Cluster:
  BackrestPort: 2022
  BackrestS3Bucket: ""
  BackrestS3Endpoint: ""
  BackrestS3Region: ""
  BackrestS3URIStyle: ""
  BackrestS3VerifyTLS: "true"
  Badger: false
  CCPImagePrefix: registry.developers.crunchydata.com/crunchydata
  CCPImageTag: centos7-12.3-4.4.0
  Database: ""
  DefaultBackrestMemory: 48Mi
  DefaultInstanceMemory: 128Mi
  DefaultPgBouncerMemory: 24Mi
  DisableAutofail: false
  DisableFSGroup: false
  DisableReplicaStartFailReinit: false
  EnableCrunchyadm: false
  ExporterPort: "9187"
  Metrics: true
  PGBadgerPort: "10000"
  PasswordAgeDays: "0"
  PasswordLength: "24"
  PgmonitorPassword: ""
  PodAntiAffinity: preferred
  PodAntiAffinityPgBackRest: ""
  PodAntiAffinityPgBouncer: ""
  Policies: ""
  Port: "5432"
  Replicas: "0"
  ServiceType: ClusterIP
  SyncReplication: false
  User: testuser
Pgo:
  Audit: false
  ConfigMapWorkerCount: null
  ControllerGroupRefreshInterval: null
  DisableReconcileRBAC: false
  NamespaceRefreshInterval: null
  NamespaceWorkerCount: null
  PGClusterWorkerCount: null
  PGOImagePrefix: registry.developers.crunchydata.com/crunchydata
  PGOImageTag: centos7-4.4.0
  PGReplicaWorkerCount: null
  PGTaskWorkerCount: null
PrimaryStorage: hostpathstorage
ReplicaStorage: hostpathstorage
Storage:
  alternatesite:
    AccessMode: ReadWriteOnce
    MatchLabels: ""
    Size: 4G
    StorageClass: alternatesite
    StorageType: dynamic
    SupplementalGroups: ""
  gce:
    AccessMode: ReadWriteOnce
    MatchLabels: ""
    Size: 300M
    StorageClass: standard
    StorageType: dynamic
    SupplementalGroups: ""
  hostpathstorage:
    AccessMode: ReadWriteMany
    MatchLabels: ""
    Size: 1G
    StorageClass: local-storage
    StorageType: create
    SupplementalGroups: ""
  linode:
    AccessMode: ReadWriteOnce
    MatchLabels: ""
    Size: 10Gi
    StorageClass: linode-block-storage-retain
    StorageType: dynamic
    SupplementalGroups: ""
  nfsstorage:
    AccessMode: ReadWriteMany
    MatchLabels: ""
    Size: 1G
    StorageClass: ""
    StorageType: create
    SupplementalGroups: "65534"
  nfsstoragered:
    AccessMode: ReadWriteMany
    MatchLabels: crunchyzone=red
    Size: 1G
    StorageClass: ""
    StorageType: create
    SupplementalGroups: "65534"
  primarysite:
    AccessMode: ReadWriteOnce
    MatchLabels: ""
    Size: 4G
    StorageClass: primarysite
    StorageType: dynamic
    SupplementalGroups: ""
  replicastorage:
    AccessMode: ReadWriteMany
    MatchLabels: ""
    Size: 1G
    StorageClass: ""
    StorageType: create
    SupplementalGroups: ""
  rook:
    AccessMode: ReadWriteOnce
    MatchLabels: ""
    Size: 1Gi
    StorageClass: rook-ceph-block
    StorageType: dynamic
    SupplementalGroups: ""
WALStorage: ""
```


## Environment

* Operating System: macOS Mojave, v10.14
* Where is this running ( Local, Cloud Provider): Linode Kubernetes Engine
* Storage being used (NFS, Hostpath, Gluster, etc): Hostpath & Linode Block Storage
* PostgreSQL Operator: v4.4.0
* Platform (Docker, Kubernetes, OpenShift): Kubernetes
* Platform Version: v1.17.9

**Comment by jkatz** [comment]
What is the output of `kubectl -n pgo describe pvc mycluster-pgbr-repo`?

**Comment by carminalazu** [comment]
```
Name:          mycluster-pgbr-repo
Namespace:     pgo
StorageClass:  linode-block-storage-retain
Status:        Bound
Volume:        pvc-b87bd422029743f9
Labels:        pg-cluster=mycluster
               pgremove=true
               vendor=crunchydata
Annotations:   pv.kubernetes.io/bind-completed: yes
               pv.kubernetes.io/bound-by-controller: yes
               volume.beta.kubernetes.io/storage-provisioner: linodebs.csi.linode.com
Finalizers:    [kubernetes.io/pvc-protection]
Capacity:      10Gi
Access Modes:  RWX
VolumeMode:    Filesystem
Mounted By:    mycluster-backrest-shared-repo-6987db4dd7-hvs2p
Events:
  Type    Reason                 Age                From                                                                                  Message
  ----    ------                 ----               ----                                                                                  -------
  Normal  Provisioning           74s                linodebs.csi.linode.com_csi-linode-controller-0_f9879c07-af87-11ea-9343-7e2c03ad2f73  External provisioner is provisioning volume for claim "pgo/mycluster-pgbr-repo"
  Normal  ExternalProvisioning   70s (x2 over 74s)  persistentvolume-controller                                                           waiting for a volume to be created, either by external provisioner "linodebs.csi.linode.com" or manually created by system administrator
  Normal  ProvisioningSucceeded  70s                linodebs.csi.linode.com_csi-linode-controller-0_f9879c07-af87-11ea-9343-7e2c03ad2f73  Successfully provisioned volume pvc-b87bd422029743f9
```

**Comment by jkatz** [comment]
I think I may see the issue.

`hostpathstorage` set to `create` mode has special meaning in the Operator. I don't believe it works with storage classes. That said, it appears to be delegating it to the local provisioner storage class (which is the linode one) and may be getting confused.

If you want to use that provisioner, I would suggest a new block, such as the `linode` one you set up and point `BackrestStorage` et al. to point to that.

**Comment by jkatz** [comment]
Additionally, if the provisioner is dynamic, you can set `StorageType` to `dynamic`.

There are details on the various [storage settings](https://access.crunchydata.com/documentation/postgres-operator/4.4.0/installation/configuration/#storage-settings) here:

[https://access.crunchydata.com/documentation/postgres-operator/4.4.0/installation/configuration/#storage-settings](https://access.crunchydata.com/documentation/postgres-operator/4.4.0/installation/configuration/#storage-settings)

**Comment by carminalazu** [comment]
The following config worked as expected, thank you for pointing me in the right direction 👍🏻

```yaml
BackrestStorage: persistent
BackupStorage: persistent
BasicAuth: ""
Cluster:
  BackrestPort: 2022
  BackrestS3Bucket: ""
  BackrestS3Endpoint: ""
  BackrestS3Region: ""
  BackrestS3URIStyle: ""
  BackrestS3VerifyTLS: "true"
  Badger: false
  CCPImagePrefix: registry.developers.crunchydata.com/crunchydata
  CCPImageTag: centos7-12.3-4.4.0
  Database: ""
  DefaultBackrestMemory: 48Mi
  DefaultInstanceMemory: 128Mi
  DefaultPgBouncerMemory: 24Mi
  DisableAutofail: false
  DisableFSGroup: false
  DisableReplicaStartFailReinit: false
  EnableCrunchyadm: false
  ExporterPort: "9187"
  Metrics: true
  PGBadgerPort: "10000"
  PasswordAgeDays: "0"
  PasswordLength: "24"
  PgmonitorPassword: ""
  PodAntiAffinity: preferred
  PodAntiAffinityPgBackRest: ""
  PodAntiAffinityPgBouncer: ""
  Policies: ""
  Port: "5432"
  Replicas: "0"
  ServiceType: ClusterIP
  SyncReplication: false
  User: testuser
Pgo:
  Audit: false
  ConfigMapWorkerCount: null
  ControllerGroupRefreshInterval: null
  DisableReconcileRBAC: false
  NamespaceRefreshInterval: null
  NamespaceWorkerCount: null
  PGClusterWorkerCount: null
  PGOImagePrefix: registry.developers.crunchydata.com/crunchydata
  PGOImageTag: centos7-4.4.0
  PGReplicaWorkerCount: null
  PGTaskWorkerCount: null
PrimaryStorage: persistentretain
ReplicaStorage: persistent
Storage:
  gce:
    AccessMode: ReadWriteOnce
    MatchLabels: ""
    Size: 300M
    StorageClass: standard
    StorageType: dynamic
    SupplementalGroups: ""
  hostpathstorage:
    AccessMode: ReadWriteMany
    MatchLabels: ""
    Size: 1G
    StorageClass: ""
    StorageType: create
    SupplementalGroups: ""
  local:
    AccessMode: ReadWriteOnce
    MatchLabels: ""
    Size: 10Gi
    StorageClass: local-storage
    StorageType: dynamic
    SupplementalGroups: ""
  nfsstorage:
    AccessMode: ReadWriteMany
    MatchLabels: ""
    Size: 1G
    StorageClass: ""
    StorageType: create
    SupplementalGroups: "65534"
  nfsstoragered:
    AccessMode: ReadWriteMany
    MatchLabels: crunchyzone=red
    Size: 1G
    StorageClass: ""
    StorageType: create
    SupplementalGroups: "65534"
  persistent:
    AccessMode: ReadWriteOnce
    MatchLabels: ""
    Size: 10Gi
    StorageClass: linode-block-storage
    StorageType: dynamic
    SupplementalGroups: ""
  persistentretain:
    AccessMode: ReadWriteOnce
    MatchLabels: ""
    Size: 10Gi
    StorageClass: linode-block-storage-retain
    StorageType: dynamic
    SupplementalGroups: ""
  replicastorage:
    AccessMode: ReadWriteMany
    MatchLabels: ""
    Size: 1G
    StorageClass: ""
    StorageType: create
    SupplementalGroups: ""
  rook:
    AccessMode: ReadWriteOnce
    MatchLabels: ""
    Size: 1Gi
    StorageClass: rook-ceph-block
    StorageType: dynamic
    SupplementalGroups: ""
WALStorage: persistent
```

Now that the issue is resolved, I have a related question: would you recommend a persistent volume for pgbackrest if the backups will be stored in an S3-compatible object store? Our current configuration results in 3 persistent volumes and while it makes sense for WAL to have its own volume, I am not convinced about giving pgbackrest a volume too - maybe local-storage would be more appropriate. What do you think?
