### ISSUE TITLE
Include option to deploy pgo-client container

### ISSUE THREAD

**Issue by strigona-worksight** [CrunchyData/postgres-operator#1748]
**What is the motivation or use case for the change?**
It gets a bit awkward to manage multiple kubernetes clusters / pgo configurations. To further simplify the deployment process & maintenance operations, it would nice handy to have the pre-configured pgo-client container ready to shell into.

**Describe the solution you'd like**
Add a configuration to the main operator config map indicating that the pgo-client should be deployed along side the operator. I based the following deployment on the job specified [here](https://github.com/CrunchyData/postgres-operator/blob/788f2d746e0048bc6c069600518c468e904b2db0/installers/olm/install.sh#L236-L262). Only needed to add the PGO_NAMESPACE env and add the image. It works great for my needs.

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pgo-client
spec:
  selector:
    matchLabels:
      app: pgo-client
  template:
    metadata:
      labels:
        app: pgo-client
    spec:
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      containers:
        - name: client
          image: crunchydata/pgo-client:centos7-4.4.0
          imagePullPolicy: IfNotPresent
          command:
            - tail
            - "-f"
            - "/dev/null"
          env:
            - name: PGO_NAMESPACE
              value: pgo
            - name: PGO_APISERVER_URL
              value: https://postgres-operator:8443
            - name: PGOUSERNAME
              valueFrom:
                secretKeyRef:
                  name: pgouser-admin
                  key: username
            - name: PGOUSERPASS
              valueFrom:
                secretKeyRef:
                  name: pgouser-admin
                  key: password
            - name: PGO_CA_CERT
              value: "/etc/pgo/certificates/tls.crt"
            - name: PGO_CLIENT_CERT
              value: "/etc/pgo/certificates/tls.crt"
            - name: PGO_CLIENT_KEY
              value: "/etc/pgo/certificates/tls.key"
          volumeMounts:
            - mountPath: "/etc/pgo/certificates"
              name: certificates
      volumes:
        - name: certificates
          secret:
            secretName: pgo.tls
```
