### ISSUE TITLE
getting error 72 from pgbackrest

### ISSUE THREAD

**Issue by IJOL** [CrunchyData/postgres-operator#1964]
Hi,

we have a cluster that is in state summarized in #1927 , so we try to exec into the backrest pod to do a backup, to try to have a replica working but to no avail we keep getting error 72 when doing backrest backup from inside backrest pod

```
bash-4.2$ pgbackrest info
stanza: db
    status: ok
    cipher: none

    db (current)
        wal archive min/max (12-1): 000000010000000000000001/00000041000000620000003D

        full backup: 20200923-123418F
            timestamp start/stop: 2020-09-23 12:34:18 / 2020-09-23 12:34:40
            wal start/stop: 000000010000000000000002 / 000000010000000000000002
            database size: 31MB, backup size: 31MB
            repository size: 3.7MB, repository backup size: 3.7MB

        incr backup: 20200923-123418F_20201006-085419I
            timestamp start/stop: 2020-10-06 08:54:19 / 2020-10-06 08:56:44
            wal start/stop: 0000003D000000480000004E / 0000003D0000004800000050
            database size: 2GB, backup size: 2GB
            repository size: 1GB, repository backup size: 1GB
            backup reference list: 20200923-123418F

        incr backup: 20200923-123418F_20201006-102726I
            timestamp start/stop: 2020-10-06 10:27:26 / 2020-10-06 10:27:29
            wal start/stop: 0000003D00000048000000AC / 0000003D00000048000000AC
            database size: 2GB, backup size: 2.6MB
            repository size: 1GB, repository backup size: 632.3KB
            backup reference list: 20200923-123418F, 20200923-123418F_20201006-085419I

bash-4.2$ pgbackrest backup
WARN: option 'repo1-retention-full' is not set for 'repo1-retention-full-type=count', the repository may run out of space
      HINT: to retain full backups indefinitely (without warning), set option 'repo1-retention-full' to the maximum.
ERROR: [072]: backup command must be run on the repository host

```

**Comment by jkatz** [comment]
The way the PostgreSQL Operator handles backups is through Kubernetes Jobs. These Jobs set a series of environmental variables, e.g.: [https://github.com/CrunchyData/postgres-operator/blob/master/installers/ansible/roles/pgo-operator/files/pgo-configs/backrest-job.json](https://github.com/CrunchyData/postgres-operator/blob/master/installers/ansible/roles/pgo-operator/files/pgo-configs/backrest-job.json). For a reference, I'm including the output of one of the generated Jobs below.

The documentation does not specify running `pgbackrest backup` directly on the pgBackRest Pod, but rather using the `pgo` client. There are several examples for how to do this in the documentation:

- [https://access.crunchydata.com/documentation/postgres-operator/latest/architecture/disaster-recovery/](https://access.crunchydata.com/documentation/postgres-operator/latest/architecture/disaster-recovery/)
- [https://access.crunchydata.com/documentation/postgres-operator/latest/tutorial/disaster-recovery/](https://access.crunchydata.com/documentation/postgres-operator/latest/tutorial/disaster-recovery/)

as well as the documentation around the client.

You can leverage the custom resources for creating the Jobs via pgtasks [https://access.crunchydata.com/documentation/postgres-operator/latest/custom-resources/](https://access.crunchydata.com/documentation/postgres-operator/latest/custom-resources/) though the documentation around that is admittedly lacking.

Anyway, the PostgreSQL Operator does not intend for `pgbackrest backup` to be run directly from the PostgreSQL Pod (which, when doing so, I reproduce the behavior you're seeing, but that is not the intended behavior). It does support `pgbackrest archive-push` but that is part of the `archive_command`. 

```yaml
apiVersion: batch/v1
kind: Job
metadata:
  labels:
    backrest-command: backup
    pg-cluster: hippo
    pgo-backrest: "true"
    pgo-backrest-job: "true"
    vendor: crunchydata
  name: backrest-backup-hippo
  namespace: pgo
spec:
  backoffLimit: 6
  completions: 1
  parallelism: 1
  template:
    metadata:
      creationTimestamp: null
      labels:
        backrest-command: backup
        job-name: backrest-backup-hippo
        pg-cluster: hippo
        pgo-backrest: "true"
        pgo-backrest-job: "true"
        vendor: crunchydata
      name: backrest-backup-hippo
    spec:
      containers:
      - env:
        - name: COMMAND
          value: backup
        - name: COMMAND_OPTS
          value: ' --db-host=10.44.0.5 --db-path=/pgdata/hippo'
        - name: PITR_TARGET
        - name: PODNAME
          value: hippo-backrest-shared-repo-7b8d7bb8f9-7bsk2
        - name: PGBACKREST_STANZA
        - name: PGBACKREST_DB_PATH
        - name: PGBACKREST_REPO_PATH
        - name: PGBACKREST_REPO_TYPE
          value: posix
        - name: PGHA_PGBACKREST_LOCAL_S3_STORAGE
          value: "false"
        - name: PGHA_PGBACKREST_S3_VERIFY_TLS
          value: "true"
        - name: PGBACKREST_LOG_PATH
          value: /tmp
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        image: registry.developers.crunchydata.com/crunchydata/pgo-backrest:centos7-4.5.0
        imagePullPolicy: IfNotPresent
        name: backrest
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Never
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: pgo-backrest
      serviceAccountName: pgo-backrest
      terminationGracePeriodSeconds: 30
```
