### ISSUE TITLE
Set VolumeMount to ReadOnly=true explicitly for DB replica pod for /pgdata

### ISSUE THREAD

**Issue by vladimirvivien** [CrunchyData/postgres-operator#20]
The documentation mentions that the replica pod for the database is read-only.  However, when inspecting the pod, it shows that the readOnly flag is set to `false`. 
```
Volumes:
  pgdata:
    Type:	PersistentVolumeClaim (a reference to a PersistentVolumeClaim in the same namespace)
    ClaimName:	pgcluster-pvc
    ReadOnly:	false
```
Would it make sense to also set the volume bind-mount to readOnly for the pod container or would that break the normal DB operation ?
