### ISSUE TITLE
metrics dashboard is not working

### ISSUE THREAD

**Issue by avanichy25** [CrunchyData/postgres-operator#2007]
Hello @jkatz 

I have deployed `4.3.2` pgo and  for monitoring i have deployed the `4.5.0`. After this I have created a cluster with metrics enabled using `pgo create cluster hippo --metrics`. After this cluster is having a sidecar called `collector` and after port-forwarding the collector sidecar i can see all the metrics `http://localhost:9187/metrics` but somehow prometheus is unable to scrape these metrics.

I also have promethes-operator running in the same cluster. I have added scrapping details there and i can see metrics are being scrapped and available.
*addtionalscrapeconfig*
```
- job_name: hippo
      kubernetes_sd_configs:
      - role: endpoints
      relabel_configs:
      - source_labels: [__meta_kubernetes_service_name]
        action: keep
        regex: hippo
```

but after importing the dashboarding it is not working because of the variables .
`label_valeus(pg_cluster)`.

Could you please help, how to fix this issue. ?

**Pgo:** : https://raw.githubusercontent.com/CrunchyData/postgres-operator/v4.3.2/installers/kubectl/postgres-operator.yml

**monitoring**: https://github.com/CrunchyData/postgres-operator/blob/master/installers/metrics/kubectl/postgres-operator-metrics.yml

Note: Currently, we cannot move to `4.5.0` due to our internal planning. Somehow want to make it work with `4.3.2`
