### ISSUE TITLE
Empty Grafana dashbord and Log error on Exporter pod

### ISSUE THREAD

**Issue by aurelien43** [CrunchyData/postgres-operator#2037]
hello, 
When i start a pods with --metrics flags, it's works but  Gafana Dashboard : "Pod Detail" is empty and Exporter pod logs error "queryNamespaceMappings returned 9 errors" evry15s. 

To reproduce the errors : 
1. Install pgo with ansible (tag=install)
2. Install metrics with ansible (tag=install-metrics)
3. Create clusterwith --metrics flags
4. When all pods are created, the dashboard "Pod Details is empty and the next kubernetes command 'kc logs -n <Namespace> <cluster-pods-name> exporter' return this errors : 

time="2020-11-09T19:12:01Z" level=info msg="Error running query on database \"127.0.0.1:5432\": ccp_nodemx_cpuacct pq: function monitor.cgroup_scalar_bigint(unknown) does not exist" source="postgres_exporter.go:1356"
time="2020-11-09T19:12:01Z" level=info msg="Error running query on database \"127.0.0.1:5432\": ccp_nodemx_process pq: function monitor.cgroup_process_count() does not exist" source="postgres_exporter.go:1356"
time="2020-11-09T19:12:01Z" level=info msg="Error running query on database \"127.0.0.1:5432\": ccp_nodemx_cpu pq: function monitor.kdapi_scalar_bigint(unknown) does not exist" source="postgres_exporter.go:1356"
time="2020-11-09T19:12:02Z" level=info msg="Error running query on database \"127.0.0.1:5432\": ccp_nodemx_mem pq: function monitor.kdapi_scalar_bigint(unknown) does not exist" source="postgres_exporter.go:1356"
time="2020-11-09T19:12:02Z" level=info msg="Error running query on database \"127.0.0.1:5432\": ccp_nodemx_network pq: function monitor.proc_network_stats() does not exist" source="postgres_exporter.go:1356"
time="2020-11-09T19:12:02Z" level=info msg="Error running query on database \"127.0.0.1:5432\": ccp_nodemx_cpustat pq: function monitor.cgroup_setof_kv(unknown) does not exist" source="postgres_exporter.go:1356"
time="2020-11-09T19:12:02Z" level=info msg="Error running query on database \"127.0.0.1:5432\": ccp_nodemx_cpucfs pq: function monitor.cgroup_scalar_bigint(unknown) does not exist" source="postgres_exporter.go:1356"
time="2020-11-09T19:12:02Z" level=info msg="Error running query on database \"127.0.0.1:5432\": ccp_nodemx_data_disk pq: function monitor.proc_mountinfo() does not exist" source="postgres_exporter.go:1356"
time="2020-11-09T19:12:02Z" level=info msg="Error running query on database \"127.0.0.1:5432\": ccp_nodemx_disk_activity pq: function monitor.proc_mountinfo() does not exist" source="postgres_exporter.go:1356"
time="2020-11-09T19:12:02Z" level=error msg="queryNamespaceMappings returned 9 errors" source="postgres_exporter.go:1474"

**screenshot**
![Capture](https://user-images.githubusercontent.com/25898200/98657068-c03cf980-2341-11eb-9106-31b68f90940a.PNG)

**Please tell us about your environment:**

* Operating System: centos7
* Where is this running ( Local, Cloud Provider): Local
* Storage being used (NFS, Hostpath, Gluster, etc): CSI (SAN)
* Container Image Tag: centos7-12.4-4.5.0
* PostgreSQL Version: 12.4
* Platform (Docker, Kubernetes, OpenShift): Kubernetes
* Platform Version: 1.17

**Comment by jkatz** [comment]
Ensure `pgnodemx` is installed and loaded. This is installed by default in the 4.5.0 containers when `--metrics` is enabled:

https://github.com/CrunchyData/crunchy-containers/blob/52b00df9d5715105a733b5fd76f82e43fa7593ab/conf/postgres-ha/postgres-ha-initdb.yaml#L15

https://github.com/CrunchyData/crunchy-containers/blob/c950e180a4fa453a2c23c9441f53b7e6f58c9602/bin/postgres-ha/modules/pgmonitor.sh#L60-L61

**Comment by aurelien43** [comment]
Thank you for your quick reply and it's correct all of this error.
But 3 news error appear in the exporter pod. 

When I logs exporter pod, i have this error : 

time="2020-11-10T17:13:44Z" level=info msg="Error running query on database \"127.0.0.1:5432\": ccp_nodemx_cpustat pq: could not open file \"/sys/fs/cgroup/cpuacct,cpu/cpu.stat\" for reading: No such file or directory" source="postgres_exporter.go:1356"
time="2020-11-10T17:13:45Z" level=info msg="Error running query on database \"127.0.0.1:5432\": ccp_nodemx_cpuacct pq: could not open file \"/sys/fs/cgroup/cpuacct,cpu/cpuacct.usage\" for reading: No such file or directory" source="postgres_exporter.go:1356"
time="2020-11-10T17:13:45Z" level=info msg="Error running query on database \"127.0.0.1:5432\": ccp_nodemx_cpucfs pq: could not open file \"/sys/fs/cgroup/cpuacct,cpu/cpu.cfs_period_us\" for reading: No such file or directory" source="postgres_exporter.go:1356"

When i look in this pods, i have no folder : "cpuacct,cpu" but i have this folder : "cpu,cpuacct" which contain all the files needed. 

what can i do to correct this errors  ?

**Comment by jkatz** [comment]
Ensure the Downward API is mounted. This was added in 4.5.0, covered in the [release notes](https://github.com/CrunchyData/postgres-operator/releases/tag/v4.5.0)

https://github.com/CrunchyData/postgres-operator/blob/b25c6b1a6e646380f4847de3c26f87cabb503188/installers/ansible/roles/pgo-operator/files/pgo-configs/cluster-deployment.json#L350-L401

**Comment by aurelien43** [comment]
Hello, 
The Doward API is mounted with the name: podinfo.

**Comment by cbandy** [comment]
> When I logs exporter pod, i have this error :
> 
> ```
> time="2020-11-10T17:13:44Z" level=info msg="Error running query on database "127.0.0.1:5432": ccp_nodemx_cpustat pq: could not open file "/sys/fs/cgroup/cpuacct,cpu/cpu.stat" for reading: No such file or directory" source="postgres_exporter.go:1356"
> time="2020-11-10T17:13:45Z" level=info msg="Error running query on database "127.0.0.1:5432": ccp_nodemx_cpuacct pq: could not open file "/sys/fs/cgroup/cpuacct,cpu/cpuacct.usage" for reading: No such file or directory" source="postgres_exporter.go:1356"
> time="2020-11-10T17:13:45Z" level=info msg="Error running query on database "127.0.0.1:5432": ccp_nodemx_cpucfs pq: could not open file "/sys/fs/cgroup/cpuacct,cpu/cpu.cfs_period_us" for reading: No such file or directory" source="postgres_exporter.go:1356"
> ```
> 
> When i look in this pods, i have no folder : "cpuacct,cpu" but i have this folder : "cpu,cpuacct" which contain all the files needed.

@aurelien43 This sounds like something unexpected is happening with your cgroupfs. What do see from the following commands?

- `cat /proc/self/cgroup`
- `ls -l /sys/fs/cgroup/`

**Comment by aurelien43** [comment]
I see this : 

**$ cat /proc/self/cgroup :**
11:cpuset:/kubepods.slice/kubepods-burstable.slice/kubepods-burstable-pod3c42b2d7_22ec_484d_9f2f_6868bb4afbe9.slice/docker-68195e7b0aa1f4dad0700cdb81aebd540ed674ba367ac2c39e6c420bb8abd56b.scope
10:memory:/kubepods.slice/kubepods-burstable.slice/kubepods-burstable-pod3c42b2d7_22ec_484d_9f2f_6868bb4afbe9.slice/docker-68195e7b0aa1f4dad0700cdb81aebd540ed674ba367ac2c39e6c420bb8abd56b.scope
9:pids:/kubepods.slice/kubepods-burstable.slice/kubepods-burstable-pod3c42b2d7_22ec_484d_9f2f_6868bb4afbe9.slice/docker-68195e7b0aa1f4dad0700cdb81aebd540ed674ba367ac2c39e6c420bb8abd56b.scope
8:devices:/kubepods.slice/kubepods-burstable.slice/kubepods-burstable-pod3c42b2d7_22ec_484d_9f2f_6868bb4afbe9.slice/docker-68195e7b0aa1f4dad0700cdb81aebd540ed674ba367ac2c39e6c420bb8abd56b.scope
7:hugetlb:/kubepods.slice/kubepods-burstable.slice/kubepods-burstable-pod3c42b2d7_22ec_484d_9f2f_6868bb4afbe9.slice/docker-68195e7b0aa1f4dad0700cdb81aebd540ed674ba367ac2c39e6c420bb8abd56b.scope
6:cpuacct,cpu:/kubepods.slice/kubepods-burstable.slice/kubepods-burstable-pod3c42b2d7_22ec_484d_9f2f_6868bb4afbe9.slice/docker-68195e7b0aa1f4dad0700cdb81aebd540ed674ba367ac2c39e6c420bb8abd56b.scope
5:freezer:/kubepods.slice/kubepods-burstable.slice/kubepods-burstable-pod3c42b2d7_22ec_484d_9f2f_6868bb4afbe9.slice/docker-68195e7b0aa1f4dad0700cdb81aebd540ed674ba367ac2c39e6c420bb8abd56b.scope
4:perf_event:/kubepods.slice/kubepods-burstable.slice/kubepods-burstable-pod3c42b2d7_22ec_484d_9f2f_6868bb4afbe9.slice/docker-68195e7b0aa1f4dad0700cdb81aebd540ed674ba367ac2c39e6c420bb8abd56b.scope
3:blkio:/kubepods.slice/kubepods-burstable.slice/kubepods-burstable-pod3c42b2d7_22ec_484d_9f2f_6868bb4afbe9.slice/docker-68195e7b0aa1f4dad0700cdb81aebd540ed674ba367ac2c39e6c420bb8abd56b.scope
2:net_prio,net_cls:/kubepods.slice/kubepods-burstable.slice/kubepods-burstable-pod3c42b2d7_22ec_484d_9f2f_6868bb4afbe9.slice/docker-68195e7b0aa1f4dad0700cdb81aebd540ed674ba367ac2c39e6c420bb8abd56b.scope
1:name=systemd:/kubepods.slice/kubepods-burstable.slice/kubepods-burstable-pod3c42b2d7_22ec_484d_9f2f_6868bb4afbe9.slice/docker-68195e7b0aa1f4dad0700cdb81aebd540ed674ba367ac2c39e6c420bb8abd56b.scope

**$ ls -l /sys/fs/cgroup/ :**
total 0
drwxr-xr-x 2 root root  0 Nov 23 09:23 blkio
lrwxrwxrwx 1 root root 11 Nov 23 09:23 cpu -> cpu,cpuacct
lrwxrwxrwx 1 root root 11 Nov 23 09:23 cpuacct -> cpu,cpuacct
drwxr-xr-x 2 root root  0 Nov 23 09:23 cpu,cpuacct
drwxr-xr-x 2 root root  0 Nov 23 09:23 cpuset
drwxr-xr-x 2 root root  0 Nov 23 09:23 devices
drwxr-xr-x 2 root root  0 Nov 23 09:23 freezer
drwxr-xr-x 2 root root  0 Nov 23 09:23 hugetlb
drwxr-xr-x 2 root root  0 Nov 23 09:23 memory
lrwxrwxrwx 1 root root 16 Nov 23 09:23 net_cls -> net_cls,net_prio
drwxr-xr-x 2 root root  0 Nov 23 09:23 net_cls,net_prio
lrwxrwxrwx 1 root root 16 Nov 23 09:23 net_prio -> net_cls,net_prio
drwxr-xr-x 2 root root  0 Nov 23 09:23 perf_event
drwxr-xr-x 2 root root  0 Nov 23 09:23 pids
drwxr-xr-x 2 root root  0 Nov 23 09:23 systemd

**Comment by jconway** [comment]
> When i look in this pods, i have no folder : "cpuacct,cpu" but i have this folder : "cpu,cpuacct"
> what can i do to correct this errors ?

In the command output I see:
8<------------------
$ cat /proc/self/cgroup:
...
6:cpuacct,cpu:/kubepods.slice/...
...
8<------------------

and

8<------------------
$ ls -l /sys/fs/cgroup/ :
lrwxrwxrwx 1 root root 11 Nov 23 09:23 cpu -> cpu,cpuacct
lrwxrwxrwx 1 root root 11 Nov 23 09:23 cpuacct -> cpu,cpuacct
drwxr-xr-x 2 root root 0 Nov 23 09:23 cpu,cpuacct
8<------------------

The order is reversed (cpuacct,cpu vs cpu,cpuacct).

That is weird (in that I have not seen it before), but I guess the ordering is probably not guaranteed and I assumed it was. So my bad, and my bug, I guess :-(

Will fix.

**Comment by jconway** [comment]
Just to be clear, this will be fixed in pgnodemx where the problem is, not in the postgres operator repo...

**Comment by jkatz** [comment]
pgnodemx 1.0.3 is confirmed for 4.6.0 and 4.5.2.

**Comment by pratikbalar** [comment]
@jkatz I'm testing PGO `5.0.4` (`registry.developers.crunchydata.com/crunchydata/postgres-operator:ubi8-5.0.4-0`) 

And followed this <https://access.crunchydata.com/documentation/postgres-operator/5.0.4/guides/extension-management/>. Getting same kind of logs as above. FYI, I'm testing this in my local k3s  `v1.20.14`

```logs
time="2021-12-24T10:33:42Z" level=info msg="Error running query on database \"localhost:5432\": ccp_nodemx_cpucfs pq: could not open file \"/sys/fs/cgroup//cpu.cfs_period_us\" for reading: No such file or directory" source="postgres_exporter.go:1356"
time="2021-12-24T10:33:42Z" level=info msg="Error running query on database \"localhost:5432\": ccp_nodemx_cpuacct pq: failed to find controller cpuacct" source="postgres_exporter.go:1356"
time="2021-12-24T10:33:42Z" level=info msg="Error running query on database \"localhost:5432\": ccp_nodemx_mem pq: could not open file \"/sys/fs/cgroup//memory.limit_in_bytes\" for reading: No such file or directory" source="postgres_exporter.go:1356"
```

<details>
  <summary>(click to expand) Cluster manifest with init-sql configmap</summary>
  

  ```yaml
    ---
    ---
    apiVersion: postgres-operator.crunchydata.com/v1beta1
    kind: PostgresCluster
    metadata:
      name: directus
      namespace: directus
    spec:
      image: registry.developers.crunchydata.com/crunchydata/crunchy-postgres:centos8-13.5-0
      users:
        - name: sensei
          databases:
            - "sensei"
          options: "SUPERUSER"
        - name: directus
          databases:
            - "directus"
          options: "NOSUPERUSER"
      databaseInitSQL:
        key: init.sql
        name: pgnodemx-ext-initsql
      postgresVersion: 13
      instances:
        - name: directus1
          replicas: 1
          resources:
            limits:
              cpu: 200m
              memory: "300M"
          metadata:
            annotations:
              prometheus.io/scrape: "true"
              prometheus.io/path: "/metrics"
              prometheus.io/port: "9187"
          dataVolumeClaimSpec:
            accessModes:
              - "ReadWriteOnce"
            resources:
              requests:
                storage: 2Gi
      backups:
        pgbackrest:
          manual:
            repoName: repo1
            options:
              - --type=full
          global:
            repo2-retention-full: "10"
            repo2-retention-full-type: count
            repo1-retention-full: "10"
          image: registry.developers.crunchydata.com/crunchydata/crunchy-pgbackrest:centos8-2.36-0
          repos:
            - name: repo1
              schedules:
                incremental: "*/5 * * * *"
                full: "*/15 * * * *"
              volume:
                volumeClaimSpec:
                  accessModes:
                    - "ReadWriteOnce"
                  resources:
                    requests:
                      storage: 1Gi
      patroni:
        dynamicConfiguration:
          postgresql:
            parameters:
              shared_preload_libraries: pgnodemx
              pgnodemx.kdapi_enabled: on
              pgnodemx.kdapi_path: /etc/database-containerinfo
      monitoring:
        pgmonitor:
          exporter:
            image: registry.developers.crunchydata.com/crunchydata/crunchy-postgres-exporter:ubi8-5.0.4-0
            resources:
              limits:
                cpu: 50m
                memory: 100M
      proxy:
        pgBouncer:
          image: registry.developers.crunchydata.com/crunchydata/crunchy-pgbouncer:centos8-1.16-0
          replicas: 1
          resources:
            limits:
              cpu: 100m
              memory: 200M
          config:
            global:
              pool_mode: transaction
              client_tls_sslmode: allow
    ---
    apiVersion: v1
    kind: ConfigMap
    metadata:
      name: pgnodemx-ext-initsql
      namespace: directus
    data:
      init.sql: |-
        \c hippo\\
        CREATE EXTENSION pgnodemx;
  ```
</details>
