### ISSUE TITLE
create cluster with NFS, loop Detected an earlier failed attempt to initialize

### ISSUE THREAD

**Issue by RazgrizHsu** [CrunchyData/postgres-operator#2099]
i'm trying use NFS to create cluster,
the pod keep looping on initialize
how can I solve this problem?

when show log from kubectl..
```
❯ kubectl logs -n pgo psql-54689bb9d9-pnl2w                                                                                               ─╯
Sun Dec  6 10:28:46 UTC 2020 WARN: Detected an earlier failed attempt to initialize
Sun Dec  6 10:28:46 UTC 2020 INFO: Correct the issue, remove '/pgdata/psql.initializing', and try again
Sun Dec  6 10:28:46 UTC 2020 INFO: Your data might be in: /pgdata/psql_2020-12-06-10-28-46
Sun Dec  6 10:28:56 UTC 2020 WARN: Detected an earlier failed attempt to initialize
Sun Dec  6 10:28:56 UTC 2020 INFO: Correct the issue, remove '/pgdata/psql.initializing', and try again
Sun Dec  6 10:28:57 UTC 2020 INFO: Your data might be in: /pgdata/psql_2020-12-06-10-28-46
Sun Dec  6 10:29:07 UTC 2020 WARN: Detected an earlier failed attempt to initialize
Sun Dec  6 10:29:07 UTC 2020 INFO: Correct the issue, remove '/pgdata/psql.initializing', and try again
Sun Dec  6 10:29:07 UTC 2020 INFO: Your data might be in: /pgdata/psql_2020-12-06-10-28-46
Sun Dec  6 10:29:17 UTC 2020 WARN: Detected an earlier failed attempt to initialize
Sun Dec  6 10:29:17 UTC 2020 INFO: Correct the issue, remove '/pgdata/psql.initializing', and try again
Sun Dec  6 10:29:17 UTC 2020 INFO: Your data might be in: /pgdata/psql_2020-12-06-10-28-46
```

the nfs.yml
```
apiVersion: v1
kind: ServiceAccount
metadata:
  name: nfs-provisioner
  namespace: pgo
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: nfs-provisioner-runner
rules:
  - apiGroups: [""]
    resources: ["persistentvolumes"]
    verbs: ["get", "list", "watch", "create", "delete"]
  - apiGroups: [""]
    resources: ["persistentvolumeclaims"]
    verbs: ["get", "list", "watch", "update"]
  - apiGroups: ["storage.k8s.io"]
    resources: ["storageclasses"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["list", "watch", "create", "update", "patch"]
  - apiGroups: [""]
    resources: ["endpoints"]
    verbs: ["get", "list", "watch", "create", "update", "patch"]

---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: run-nfs-provisioner
subjects:
  - kind: ServiceAccount
    name: nfs-provisioner
    namespace: pgo
roleRef:
  kind: ClusterRole
  name: nfs-provisioner-runner
  apiGroup: rbac.authorization.k8s.io

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: nfs-provisioner

---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: nfs-k8s-share
provisioner: pvr-nfs
parameters:
  archiveOnDelete: "false"
reclaimPolicy: Retain

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nfs-provisioner
  labels:
    app: nfs-provisioner
  namespace: pgo
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: nfs-provisioner
  template:
    metadata:
      labels:
        app: nfs-provisioner
    spec:
      serviceAccountName: nfs-provisioner
      containers:
        - name: nfs-provisioner
          image: quay.io/external_storage/nfs-client-provisioner:latest
          volumeMounts:
            - name: nfs-client-root
              mountPath: /persistentvolumes
          env:
            - name: PROVISIONER_NAME
              value: pvr-nfs
            - name: NFS_SERVER
              value: nas.raz.lan
            - name: NFS_PATH
              value: /mnt/m/svc/k8s/share
      volumes:
        - name: nfs-client-root
          nfs:
            server: nas.raz.lan
            path: /mnt/m/svc/k8s/share
```

use pgo.yml
```
apiVersion: v1
kind: ServiceAccount
metadata:
  name: pgo-deployer-sa
  namespace: pgo
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: pgo-deployer-cr
rules:
  - apiGroups: [ "" ]
    resources: [ "namespaces" ]
    verbs: [ "get", "list", "create", "patch", "delete" ]
  - apiGroups: [ "" ]
    resources: [ "pods" ]
    verbs: [ "list" ]
  - apiGroups: [ "" ]
    resources: [ "secrets" ]
    verbs: [ "list", "get", "create", "delete" ]
  - apiGroups: [ "" ]
    resources: [ "configmaps", "services", "persistentvolumeclaims" ]
    verbs: [ "list", "get", "create", "delete" ]
  - apiGroups: [ "" ]
    resources: [ "serviceaccounts" ]
    verbs: [ "list", "get", "create", "delete", "patch" ]
  - apiGroups: [ "apps", "extensions" ]
    resources: [ "deployments" ]
    verbs: [ "list", "get", "create", "delete", "watch" ]
  - apiGroups: [ "apiextensions.k8s.io" ]
    resources: [ "customresourcedefinitions" ]
    verbs: [ "get", "create", "delete" ]
  - apiGroups: [ "rbac.authorization.k8s.io" ]
    resources: [ "clusterroles", "clusterrolebindings", "roles", "rolebindings" ]
    verbs: [ "get", "create", "delete", "bind", "escalate" ]
  - apiGroups: [ "rbac.authorization.k8s.io" ]
    resources: [ "roles" ]
    verbs: [ "create", "delete" ]
  - apiGroups: [ "batch" ]
    resources: [ "jobs" ]
    verbs: [ "list", "delete" ]
  - apiGroups: [ "crunchydata.com" ]
    resources: [ "pgclusters", "pgreplicas", "pgpolicies", "pgtasks" ]
    verbs: [ "list", "delete" ]
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: pgo-deployer-cm
  namespace: pgo
data:
  values.yaml: |-
    # =====================
    # Configuration Options
    # More info for these options can be found in the docs
    # https://access.crunchydata.com/documentation/postgres-operator/latest/installation/configuration/
    # =====================
    archive_mode: "true"
    archive_timeout: "60"
    backrest_aws_s3_bucket: ""
    backrest_aws_s3_endpoint: ""
    backrest_aws_s3_key: ""
    backrest_aws_s3_region: ""
    backrest_aws_s3_secret: ""
    backrest_aws_s3_uri_style: ""
    backrest_aws_s3_verify_tls: "true"
    backrest_port: "2022"
    badger: "false"
    ccp_image_prefix: "registry.developers.crunchydata.com/crunchydata"
    ccp_image_pull_secret: ""
    ccp_image_pull_secret_manifest: ""
    ccp_image_tag: "centos7-12.5-4.5.1"
    create_rbac: "true"
    crunchy_debug: "true"
    db_name: "testdb"
    db_password_age_days: "0"
    db_password_length: "6"
    db_port: "5432"
    db_replicas: "2"
    db_user: "raz"
    default_instance_memory: "512Mi"
    default_pgbackrest_memory: "48Mi"
    default_pgbouncer_memory: "50Mi"
    default_exporter_memory: "50Mi"
    delete_operator_namespace: "false"
    delete_watched_namespaces: "false"
    disable_auto_failover: "false"
    disable_fsgroup: "false"
    reconcile_rbac: "true"
    exporterport: "9187"
    metrics: "false"
    namespace: "pgo"
    namespace_mode: "dynamic"
    pgbadgerport: "10000"
    pgo_add_os_ca_store: "false"
    pgo_admin_password: "test"
    pgo_admin_perms: "*"
    pgo_admin_role_name: "pgoadmin"
    pgo_admin_username: "admin"
    pgo_apiserver_port: "8443"
    pgo_apiserver_url: "https://postgres-operator"
    pgo_client_cert_secret: "pgo.tls"
    pgo_client_container_install: "false"
    pgo_client_install: "true"
    pgo_client_version: "4.5.1"
    pgo_cluster_admin: "false"
    pgo_disable_eventing: "false"
    pgo_disable_tls: "false"
    pgo_image_prefix: "registry.developers.crunchydata.com/crunchydata"
    pgo_image_pull_secret: ""
    pgo_image_pull_secret_manifest: ""
    pgo_image_tag: "centos7-4.5.1"
    pgo_installation_name: "devtest"
    pgo_noauth_routes: ""
    pgo_operator_namespace: "pgo"
    pgo_tls_ca_store: ""
    pgo_tls_no_verify: "true"
    pod_anti_affinity: "preferred"
    pod_anti_affinity_pgbackrest: ""
    pod_anti_affinity_pgbouncer: ""
    scheduler_timeout: "3600"
    service_type: "ClusterIP"
    sync_replication: "false"

    backrest_storage: "nfs"
    backup_storage: "nfs"
    primary_storage: "nfs"
    replica_storage: "nfs"
    wal_storage: ""

    storage1_name: "default"
    storage1_access_mode: "ReadWriteOnce"
    storage1_size: "5G"
    storage1_type: "dynamic"

    storage2_name: "hostpathstorage"
    storage2_access_mode: "ReadWriteMany"
    storage2_size: "5G"
    storage2_type: "create"

    storage3_name: "nfsstorage"
    storage3_access_mode: "ReadWriteMany"
    storage3_size: "1G"
    storage3_type: "create"
    storage3_supplemental_groups: "65534"

    storage4_name: "nfs"
    storage4_access_mode: "ReadWriteMany"
    storage4_size: "5G"
    storage4_type: "dynamic"
    storage4_supplemental_groups: "0"
    storage4_class: "nfs-k8s-share"

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: pgo-deployer-crb
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: pgo-deployer-cr
subjects:
  - kind: ServiceAccount
    name: pgo-deployer-sa
    namespace: pgo

---
apiVersion: batch/v1
kind: Job
metadata:
  name: pgo-deploy
  namespace: pgo
spec:
  backoffLimit: 0
  template:
    metadata:
      name: pgo-deploy
    spec:
      serviceAccountName: pgo-deployer-sa
      restartPolicy: Never
      containers:
        - name: pgo-deploy
          image: registry.developers.crunchydata.com/crunchydata/pgo-deployer:centos7-4.5.1
          imagePullPolicy: IfNotPresent
          env:
            - name: DEPLOY_ACTION
              value: install
          volumeMounts:
            - name: deployer-conf
              mountPath: "/conf"
      volumes:
        - name: deployer-conf
          configMap:
            name: pgo-deployer-cm

```

then create with
```
❯ pgo create cluster -n pgo psql --pvc-size=6G 
```

get pods,svc,pvc
```
Every 2.0s: kubectl get pods,svc,pvc -n pgo                                                                            nb.raz.lan: Sun Dec  6 18:34:25 2020

NAME                                             READY   STATUS      RESTARTS   AGE
pod/nfs-provisioner-5fdc8f99b7-wg4l6             1/1     Running     0          14m
pod/pgo-deploy-9ck8c                             0/1     Completed   0          7m32s
pod/postgres-operator-644bdf758f-qmjtt           4/4     Running     0          6m53s
pod/psql-54689bb9d9-pnl2w                        0/1     Running     1          5m45s
pod/psql-backrest-shared-repo-7d8f6bd7b8-9h97d   1/1     Running     0          5m47s

NAME                                TYPE        CLUSTER-IP       EXTERNAL-IP   PORT(S)                      AGE
service/postgres-operator           ClusterIP   10.103.11.132    <none>        8443/TCP,4171/TCP,4150/TCP   6m55s
service/psql                        ClusterIP   10.110.210.109   <none>        2022/TCP,5432/TCP            5m47s
service/psql-backrest-shared-repo   ClusterIP   10.98.242.132    <none>        2022/TCP                     5m47s

NAME                                   STATUS   VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS    AGE
persistentvolumeclaim/psql             Bound    pvc-58e6ee3f-5e79-4e31-9c6a-f0294415fabc   6G         RWX            nfs-k8s-share   5m47s
persistentvolumeclaim/psql-pgbr-repo   Bound    pvc-840674a1-d6b2-4b63-a834-50500c1c35b4   5G         RWX            nfs-k8s-share   5m47s

```

the Instances always DOWN status..
```
❯ pgo test -n pgo psql                                                                                                                    ─╯

cluster : psql
        Services
                primary (10.110.210.109:5432): UP
        Instances
                unknown (psql-54689bb9d9-pnl2w): DOWN
```

describe pod
```
❯ kubectl describe -n pgo pod psql-54689bb9d9-pnl2w                                                                                       ─╯
Name:         psql-54689bb9d9-pnl2w
Namespace:    pgo
Priority:     0
Node:         k8sc2/10.6.8.102
Start Time:   Sun, 06 Dec 2020 18:28:42 +0800
Labels:       crunchy-pgha-scope=psql
              crunchy-postgres-exporter=false
              deployment-name=psql
              name=psql
              pg-cluster=psql
              pg-cluster-id=c8cbc85e-2fb7-4b11-9147-2b6e423d24a2
              pg-pod-anti-affinity=
              pgo-pg-database=true
              pgo-version=4.5.1
              pgouser=admin
              pod-template-hash=54689bb9d9
              service-name=psql
              vendor=crunchydata
              workflowid=f1383abe-ebc4-42bf-944b-09fdc3caa5c9
Annotations:  cni.projectcalico.org/podIP: 192.8.43.66/32
              cni.projectcalico.org/podIPs: 192.8.43.66/32
              status:
                {"conn_url":"postgres://192.8.43.66:5432/postgres","api_url":"http://192.8.43.66:8009/patroni","state":"stopped","role":"uninitialized","v...
Status:       Running
IP:           192.8.43.66
IPs:
  IP:           192.8.43.66
Controlled By:  ReplicaSet/psql-54689bb9d9
Containers:
  database:
    Container ID:   docker://a80fe0afe35e579f60c01948a89740940c145d8946c1b5f7f883bc319be7c61e
    Image:          registry.developers.crunchydata.com/crunchydata/crunchy-postgres-ha:centos7-12.5-4.5.1
    Image ID:       docker-pullable://registry.developers.crunchydata.com/crunchydata/crunchy-postgres-ha@sha256:6da064236af36c7e8829be124aa6663fc6a7782a2be1139636bcb708476ba714
    Ports:          5432/TCP, 8009/TCP
    Host Ports:     0/TCP, 0/TCP
    State:          Running
      Started:      Sun, 06 Dec 2020 18:28:46 +0800
    Last State:     Terminated
      Reason:       Completed
      Exit Code:    0
      Started:      Sun, 06 Dec 2020 18:28:44 +0800
      Finished:     Sun, 06 Dec 2020 18:28:46 +0800
    Ready:          False
    Restart Count:  1
    Requests:
      memory:   512Mi
    Liveness:   exec [/opt/cpm/bin/health/pgha-liveness.sh] delay=30s timeout=10s period=15s #success=1 #failure=3
    Readiness:  exec [/opt/cpm/bin/health/pgha-readiness.sh] delay=15s timeout=1s period=10s #success=1 #failure=3
    Environment:
      PGHA_PG_PORT:                       5432
      PGHA_USER:                          postgres
      PGHA_INIT:                          <set to the key 'init' of config map 'psql-pgha-config'>  Optional: false
      PATRONI_POSTGRESQL_DATA_DIR:        /pgdata/psql
      PGBACKREST_STANZA:                  db
      PGBACKREST_REPO1_HOST:              psql-backrest-shared-repo
      BACKREST_SKIP_CREATE_STANZA:        true
      PGHA_PGBACKREST:                    true
      PGBACKREST_REPO1_PATH:              /backrestrepo/psql-backrest-shared-repo
      PGBACKREST_DB_PATH:                 /pgdata/psql
      ENABLE_SSHD:                        true
      PGBACKREST_LOG_PATH:                /tmp
      PGBACKREST_PG1_SOCKET_PATH:         /tmp
      PGBACKREST_PG1_PORT:                5432
      PGBACKREST_REPO1_TYPE:              posix
      PGHA_PGBACKREST_LOCAL_S3_STORAGE:   false
      PGHA_DATABASE:                      psql
      PGHA_CRUNCHYADM:                    true
      PGHA_REPLICA_REINIT_ON_START_FAIL:  true
      PGHA_SYNC_REPLICATION:              false
      PGHA_TLS_ENABLED:                   false
      PGHA_TLS_ONLY:                      false
      PGHA_STANDBY:                       false
      PATRONI_KUBERNETES_NAMESPACE:       pgo (v1:metadata.namespace)
      PATRONI_KUBERNETES_SCOPE_LABEL:     crunchy-pgha-scope
      PATRONI_SCOPE:                       (v1:metadata.labels['crunchy-pgha-scope'])
      PATRONI_KUBERNETES_LABELS:          {vendor: "crunchydata"}
      PATRONI_LOG_LEVEL:                  INFO
      PGHOST:                             /tmp
    Mounts:
      /crunchyadm from crunchyadm (rw)
      /dev/shm from dshm (rw)
      /etc/pgbackrest/conf.d from pgbackrest-config (rw)
      /etc/podinfo from podinfo (rw)
      /pgconf from pgconf-volume (rw)
      /pgconf/pgreplicator from primary-volume (rw)
      /pgconf/pgsuper from root-volume (rw)
      /pgconf/pguser from user-volume (rw)
      /pgdata from pgdata (rw)
      /recover from recover-volume (rw)
      /sshd from sshd (ro)
      /var/run/secrets/kubernetes.io/serviceaccount from pgo-pg-token-6zb6s (ro)
Conditions:
  Type              Status
  Initialized       True 
  Ready             False 
  ContainersReady   False 
  PodScheduled      True 
Volumes:
  pgdata:
    Type:       PersistentVolumeClaim (a reference to a PersistentVolumeClaim in the same namespace)
    ClaimName:  psql
    ReadOnly:   false
  user-volume:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  psql-raz-secret
    Optional:    false
  primary-volume:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  psql-primaryuser-secret
    Optional:    false
  sshd:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  psql-backrest-repo-config
    Optional:    false
  root-volume:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  psql-postgres-secret
    Optional:    false
  recover-volume:
    Type:       EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:     Memory
    SizeLimit:  <unset>
  report:
    Type:       EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:     Memory
    SizeLimit:  <unset>
  crunchyadm:
    Type:       EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:     
    SizeLimit:  <unset>
  dshm:
    Type:       EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:     Memory
    SizeLimit:  <unset>
  pgbackrest-config:
    Type:                Projected (a volume that contains injected data from multiple sources)
    ConfigMapName:       psql-config-backrest
    ConfigMapOptional:   0xc000ca8ecd
    SecretName:          psql-config-backrest
    SecretOptionalName:  0xc000ca8ece
  pgconf-volume:
    Type:               Projected (a volume that contains injected data from multiple sources)
    ConfigMapName:      psql-pgha-config
    ConfigMapOptional:  0xc000ca8ed8
  podinfo:
    Type:  DownwardAPI (a volume populated by information about the pod)
    Items:
      limits.cpu -> cpu_limit
      requests.cpu -> cpu_request
      limits.memory -> mem_limit
      requests.memory -> mem_request
      metadata.labels -> labels
      metadata.annotations -> annotations
  pgo-pg-token-6zb6s:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  pgo-pg-token-6zb6s
    Optional:    false
QoS Class:       Burstable
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/not-ready:NoExecute op=Exists for 300s
                 node.kubernetes.io/unreachable:NoExecute op=Exists for 300s
Events:
  Type     Reason     Age                From               Message
  ----     ------     ----               ----               -------
  Normal   Scheduled  15m                default-scheduler  Successfully assigned pgo/psql-54689bb9d9-pnl2w to k8sc2
  Normal   Pulled     15m (x2 over 15m)  kubelet            Container image "registry.developers.crunchydata.com/crunchydata/crunchy-postgres-ha:centos7-12.5-4.5.1" already present on machine
  Normal   Created    15m (x2 over 15m)  kubelet            Created container database
  Normal   Started    15m (x2 over 15m)  kubelet            Started container database
  Warning  Unhealthy  7s (x89 over 14m)  kubelet            Readiness probe failed:
```

describe pvc
```
❯ kubectl describe -n pgo pvc psql                                                                                                        ─╯
Name:          psql
Namespace:     pgo
StorageClass:  nfs-k8s-share
Status:        Bound
Volume:        pvc-58e6ee3f-5e79-4e31-9c6a-f0294415fabc
Labels:        pg-cluster=psql
               pgremove=true
               vendor=crunchydata
Annotations:   pv.kubernetes.io/bind-completed: yes
               pv.kubernetes.io/bound-by-controller: yes
               volume.beta.kubernetes.io/storage-provisioner: pvr-nfs
Finalizers:    [kubernetes.io/pvc-protection]
Capacity:      6G
Access Modes:  RWX
VolumeMode:    Filesystem
Mounted By:    psql-54689bb9d9-pnl2w
Events:
  Type    Reason                 Age   From                                                                           Message
  ----    ------                 ----  ----                                                                           -------
  Normal  ExternalProvisioning   16m   persistentvolume-controller                                                    waiting for a volume to be created, either by external provisioner "pvr-nfs" or manually created by system administrator
  Normal  Provisioning           16m   pvr-nfs_nfs-provisioner-5fdc8f99b7-wg4l6_8a191ca9-37ac-11eb-8334-fa412624e44b  External provisioner is provisioning volume for claim "pgo/psql"
  Normal  ProvisioningSucceeded  16m   pvr-nfs_nfs-provisioner-5fdc8f99b7-wg4l6_8a191ca9-37ac-11eb-8334-fa412624e44b  Successfully provisioned volume pvc-58e6ee3f-5e79-4e31-9c6a-f0294415fabc
```

* Operating System:
* Where is this running **local**
* Storage being used **NFS**
* Container Image Tag: **centos7-4.5.1**
* Platform (Docker, Kubernetes, OpenShift): **k8s**
* Platform Version: **v1.19.4**

update:
event manual into pod to initdb
1. `kubectl exec -it psql-xxxx -- bash`
2. `chown $(whoami) /pgdata`
3. `pg_ctl initdb -D /pgdata`

the logs still looping..
```
Sun Dec  6 12:05:17 UTC 2020 WARN: Detected an earlier failed attempt to initialize
Sun Dec  6 12:05:17 UTC 2020 INFO: Correct the issue, remove '/pgdata/psql.initializing', and try again
Sun Dec  6 12:05:17 UTC 2020 INFO: Your data might be in: /pgdata/psql_2020-12-06-12-04-55
Sun Dec  6 12:05:27 UTC 2020 WARN: Detected an earlier failed attempt to initialize
Sun Dec  6 12:05:27 UTC 2020 INFO: Correct the issue, remove '/pgdata/psql.initializing', and try again
Sun Dec  6 12:05:27 UTC 2020 INFO: Your data might be in: /pgdata/psql_2020-12-06-12-04-55

>> at moment, i'm manual initdb from pod, the logs changed, but still looping...

Sun Dec  6 12:05:37 UTC 2020 WARN: Detected an earlier failed attempt to initialize
Sun Dec  6 12:05:37 UTC 2020 INFO: Correct the issue, remove '/pgdata/psql.initializing', and try again
Sun Dec  6 12:05:37 UTC 2020 INFO: Your data might be in: /pgdata/psql_*
Sun Dec  6 12:05:47 UTC 2020 WARN: Detected an earlier failed attempt to initialize
Sun Dec  6 12:05:47 UTC 2020 INFO: Correct the issue, remove '/pgdata/psql.initializing', and try again
Sun Dec  6 12:05:47 UTC 2020 INFO: Your data might be in: /pgdata/psql_*
```
