### ISSUE TITLE
Issue regarding the deployment of postgres-operator in two namespaces

### ISSUE THREAD

**Issue by avanichy25** [CrunchyData/postgres-operator#2209]
**I'm submitting a ...**

**Do you want to request a *feature* or report a *bug*?**
It is a bug request

**What is the current behavior?**

I am trying to deploy postgres-operator in two different namespace as dev and test but getting an error in dev as mentioned below:

```
time="2021-01-14T03:25:55Z" level=info msg="Operator version version check starts" func="operator/operatorupgrade.OperatorCRPgoVersionCheck()" file="operator/operatorupgrade/version-check.go:33" version=4.3.2
time="2021-01-14T03:25:55Z" level=error msg="error getting list of clusters pgclusters.crunchydata.com is forbidden: User \"system:serviceaccount:dev:postgres-operator\" cannot list resource \"pgclusters\" in API group \"crunchydata.com\" in the namespace \"dev\"" func="kubeapi.Getpgclusters()" file="kubeapi/pgcluster.go:72" version=4.3.2
time="2021-01-14T03:25:55Z" level=error msg="pgclusters.crunchydata.com is forbidden: User \"system:serviceaccount:dev:postgres-operator\" cannot list resource \"pgclusters\" in API group \"crunchydata.com\" in the namespace \"dev\"" func="operator/operatorupgrade.checkVersion()" file="operator/operatorupgrade/version-check.go:55" version=4.3.2
time="2021-01-14T03:25:55Z" level=error msg="problem running operator version check" func="operator/operatorupgrade.OperatorCRPgoVersionCheck()" file="operator/operatorupgrade/version-check.go:37" version=4.3.2
time="2021-01-14T03:25:55Z" level=debug msg="pgtask Controller: added event handler to informer" func="controller/pgtask.(*Controller).AddPGTaskEventHandler()" file="controller/pgtask/pgtaskcontroller.go:200" version=4.3.2
time="2021-01-14T03:25:55Z" level=debug msg="pgcluster Controller: added event handler to informer" func="controller/pgcluster.(*Controller).AddPGClusterEventHandler()" file="controller/pgcluster/pgclustercontroller.go:268" version=4.3.2
time="2021-01-14T03:25:55Z" level=debug msg="pgreplica Controller: added event handler to informer" func="controller/pgreplica.(*Controller).AddPGReplicaEventHandler()" file="controller/pgreplica/pgreplicacontroller.go:221" version=4.3.2
time="2021-01-14T03:25:55Z" level=debug msg="pgpolicy Controller: added event handler to informer" func="controller/pgpolicy.(*Controller).AddPGPolicyEventHandler()" file="controller/pgpolicy/pgpolicycontroller.go:129" version=4.3.2
time="2021-01-14T03:25:55Z" level=debug msg="Pod Controller: added event handler to informer" func="controller/pod.(*Controller).AddPodEventHandler()" file="controller/pod/podcontroller.go:179" version=4.3.2
time="2021-01-14T03:25:55Z" level=debug msg="Job Controller: added event handler to informer" func="controller/job.(*Controller).AddJobEventHandler()" file="controller/job/jobcontroller.go:119" version=4.3.2
time="2021-01-14T03:25:55Z" level=debug msg="Controller Manager: added controller group for namespace dev" func="controller/manager.(*ControllerManager).addControllerGroup()" file="controller/manager/controllermanager.go:370" version=4.3.2
time="2021-01-14T03:25:55Z" level=debug msg="Controller Manager: canCreateRBACInNamespace is 'false' for namespace dev" func="controller/manager.(*ControllerManager).addControllerGroup()" file="controller/manager/controllermanager.go:382" version=4.3.2
time="2021-01-14T03:25:55Z" level=debug msg="Controller Manager: new controller manager created for namespaces [dev]" func="controller/manager.NewControllerManager()" file="controller/manager/controllermanager.go:103" version=4.3.2
time="2021-01-14T03:25:55Z" level=error msg="Controller Manager: Controller Group for namespace dev does not have the required list privileges for resource pgtasks in the crunchydata.com API" func="controller/manager.(*ControllerManager).hasListerPrivs()" file="controller/manager/controllermanager.go:449" version=4.3.2
time="2021-01-14T03:25:55Z" level=error msg="Controller Manager: Controller Group for namespace dev does not have the required list privileges for resource pgclusters in the crunchydata.com API" func="controller/manager.(*ControllerManager).hasListerPrivs()" file="controller/manager/controllermanager.go:449" version=4.3.2
time="2021-01-14T03:25:55Z" level=error msg="Controller Manager: Controller Group for namespace dev does not have the required list privileges for resource pgreplicas in the crunchydata.com API" func="controller/manager.(*ControllerManager).hasListerPrivs()" file="controller/manager/controllermanager.go:449" version=4.3.2
time="2021-01-14T03:25:55Z" level=error msg="Controller Manager: Controller Group for namespace dev does not have the required list privileges for resource pgpolicies in the crunchydata.com API" func="controller/manager.(*ControllerManager).hasListerPrivs()" file="controller/manager/controllermanager.go:449" version=4.3.2
time="2021-01-14T03:25:55Z" level=error msg="Controller Manager: Controller Group for namespace dev does not have the required list privileges for resource pods in the Core API" func="controller/manager.(*ControllerManager).hasListerPrivs()" file="controller/manager/controllermanager.go:462" version=4.3.2
time="2021-01-14T03:25:55Z" level=error msg="Controller Manager: Controller Group for namespace dev does not have the required list privileges for resource jobs in the Batch API" func="controller/manager.(*ControllerManager).hasListerPrivs()" file="controller/manager/controllermanager.go:474" version=4.3.2
time="2021-01-14T03:25:55Z" level=error msg="Controller Manager: cannot start controller group for namespace dev because it does not have the required privs, will attempt to start on the next ns refresh interval" func="main.main()" file="postgres-operator.go:97" version=4.3.2
```

1) manifest.yaml

```
---
# Source: postgres-operator/templates/rbac.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: pgo-deployer-sa-dev
  namespace: dev
  labels:
    helm.sh/chart: postgres-operator-4.3.2
    app.kubernetes.io/name: postgres-operator
    app.kubernetes.io/instance: pgo-dev
    app.kubernetes.io/version: "1.16.0"
    app.kubernetes.io/managed-by: Helm
    meta.helm.sh/release-name: pgo-dev
    meta.helm.sh/release-namespace: dev
---
# Source: postgres-operator/templates/values_configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: pgo-dev-postgres-operator-cm
  namespace: dev
  labels:
    helm.sh/chart: postgres-operator-4.3.2
    app.kubernetes.io/name: postgres-operator
    app.kubernetes.io/instance: pgo-dev
    app.kubernetes.io/version: "1.16.0"
    app.kubernetes.io/managed-by: Helm
    meta.helm.sh/release-name: pgo-dev
    meta.helm.sh/release-namespace: dev
data:

  ARCHIVE_MODE: "true"
  ARCHIVE_TIMEOUT: "60"
  BACKREST: "true"
  BACKREST_PORT: "2022"
  BACKREST_STORAGE: "default"
  BACKUP_STORAGE: "default"
  BADGER: "true"
  CCP_IMAGE_PREFIX: "registry.developers.crunchydata.com/crunchydata"
  CCP_IMAGE_PULL_SECRET: ""
  CCP_IMAGE_PULL_SECRET_MANIFEST: ""
  CCP_IMAGE_TAG: "centos7-12.3-4.3.2"
  CREATE_RBAC: "true"
  CRUNCHY_DEBUG: "false"
  DB_PASSWORD_LENGTH: "24"
  DB_PORT: "5432"
  DB_REPLICAS: "0"
  DB_USER: "kong"
  DEFAULT_INSTANCE_MEMORY: "512Mi"
  DEFAULT_PGBACKREST_MEMORY: "48Mi"
  DEFAULT_PGBOUNCER_MEMORY: "256Mi"
  DEPLOY_ACTION: "install,install-metrics"
  DISABLE_AUTO_FAILOVER: "false"
  DISABLE_FSGROUP: "false"
  DYNAMIC_RBAC: "false"
  EXPORTERPORT: "9187"
  METRICS: "true"
  NAMESPACE: "dev"
  NAMESPACE_MODE: "dynamic"
  PGBADGERPORT: "10000"
  PGO_ADMIN_PASSWORD: "xxxxx"
  PGO_ADMIN_PERMS: "*"
  PGO_ADMIN_ROLE_NAME: "pgoadmin"
  PGO_ADMIN_USERNAME: "admin"
  PGO_CLIENT_VERSION: "v4.3.2"
  PGO_IMAGE_PREFIX: "registry.developers.crunchydata.com/crunchydata"
  PGO_IMAGE_TAG: "centos7-4.3.2"
  PGO_INSTALLATION_NAME: "devtest"
  PGO_OPERATOR_NAMESPACE: "dev"
  PRIMARY_STORAGE: "default"
  REPLICA_STORAGE: "default"
  SCHEDULER_TIMEOUT: "3600"
  STORAGE5_ACCESS_MODE: "ReadWriteOnce"
  STORAGE5_CLASS: "default"
  STORAGE5_NAME: "default"
  STORAGE5_SIZE: "1G"
  STORAGE5_TYPE: "dynamic"
  VolumeMounts: "[map[mountPath:sqlcommand name:pgo-postgres-operator-sqlcomm-conf readOnly:true] map[mountPath:pgo.tls name:pgo-tls-volume]]"
  Volumes: "[map[name:pgo-tls-volume secret:map[defaultMode:420 items:[map[key:tls.crt path:client.crt] map[key:tls.key path:client.key]] secretName:pgo.tls]] map[configMap:map[defaultMode:420 name:pgo-postgres-operator-sqlcomm-conf] name:pgo-postgres-operator-sqlcomm-conf]]"
  WAL_STORAGE: ""
  commonLabels: "map[package:mwe]"
  fullnameOverride: ""
  global: "map[imagePullSecrets:[docker-mwe]]"
  image: "map[pullPolicy:IfNotPresent repository:docker.io/crunchydata/pgo-client tag:centos7-4.3.2]"
  name: "pgo-client"
  namespaceOverride: "dev"
  pgoadminsecret: "pgouser-admin"
  pgoclienttlssecret: "pgo.tls"
  pgoendpoint: "https://postgres-operator:8443"
  rbac: "map[create:true name:pgo-deployer-cr-dev useClusterAdmin:false]"
  replicaCount: "1"
  resources: "map[limits:map[cpu:200m memory:100Mi] requests:map[cpu:100m memory:50Mi]]"
  serviceAccount: "map[create:true name:pgo-deployer-sa-dev namespace:dev]"
---
# Source: postgres-operator/templates/pgo-client.yaml
kind: Deployment
apiVersion: apps/v1
metadata:
  name: pgo-client
  namespace: dev
  labels:
    app: postgres-operator
    chart: postgres-operator-4.3.2
    release: "pgo-dev"
    heritage: "Helm"
    package: mwe
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pgo-client
  template:
    metadata:
      labels:
        app: pgo-client
    spec:
      volumes:
        - name: pgo-tls-volume
          secret:
            defaultMode: 420
            items:
            - key: tls.crt
              path: client.crt
            - key: tls.key
              path: client.key
            secretName: pgo.tls
        - configMap:
            defaultMode: 420
            name: pgo-postgres-operator-sqlcomm-conf
          name: pgo-postgres-operator-sqlcomm-conf
      containers:
        - name: pgo
          image: "docker.io/crunchydata/pgo-client:centos7-4.3.2"
          env:
            - name: PGO_APISERVER_URL
              value: 'https://postgres-operator:8443'
            - name: PGO_NAMESPACE
              value: dev
            - name: PGOUSERNAME
              valueFrom:
                secretKeyRef:
                  name: pgouser-admin
                  key: username
            - name: PGOUSERPASS
              valueFrom:
                secretKeyRef:
                  name: pgouser-admin
                  key: password
            - name: PGO_CA_CERT
              value: pgo.tls/client.crt
            - name: PGO_CLIENT_CERT
              value: pgo.tls/client.crt
            - name: PGO_CLIENT_KEY
              value: pgo.tls/client.key
          resources:
            limits:
              cpu: 200m
              memory: 100Mi
            requests:
              cpu: 100m
              memory: 50Mi
          volumeMounts:
            - mountPath: sqlcommand
              name: pgo-postgres-operator-sqlcomm-conf
              readOnly: true
            - mountPath: pgo.tls
              name: pgo-tls-volume
---
# Source: postgres-operator/templates/rbac.yaml
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: pgo-dev-postgres-operator-cr
  labels:
    helm.sh/chart: postgres-operator-4.3.2
    app.kubernetes.io/name: postgres-operator
    app.kubernetes.io/instance: pgo-dev
    app.kubernetes.io/version: "1.16.0"
    app.kubernetes.io/managed-by: Helm
    meta.helm.sh/release-name: pgo-dev
    meta.helm.sh/release-namespace: dev
  annotations:
    helm.sh/hook: post-install,post-upgrade,pre-delete
    helm.sh/hook-delete-policy: before-hook-creation,hook-succeeded
    helm.sh/hook-weight: "-10"
rules:
  - apiGroups:
      - ''
    resources:
      - namespaces
    verbs:
      - get
      - list
      - create
      - patch
      - delete
  - apiGroups:
      - ''
    resources:
      - pods
    verbs:
      - list
  - apiGroups:
      - ''
    resources:
      - secrets
    verbs:
      - list
      - get
      - create
      - delete
  - apiGroups:
      - ''
    resources:
      - configmaps
      - services
      - persistentvolumeclaims
    verbs:
      - get
      - create
      - delete
      - list
  - apiGroups:
      - ''
    resources:
      - serviceaccounts
    verbs:
      - get
      - create
      - delete
      - patch
      - list
  - apiGroups:
      - apps
      - extensions
    resources:
      - deployments
    verbs:
      - get
      - list
      - watch
      - create
      - delete
  - apiGroups:
      - apiextensions.k8s.io
    resources:
      - customresourcedefinitions
    verbs:
      - get
      - create
      - delete
  - apiGroups:
      - rbac.authorization.k8s.io
    resources:
      - clusterroles
      - clusterrolebindings
      - roles
      - rolebindings
    verbs:
      - get
      - create
      - delete
      - bind
      - escalate
  - apiGroups:
      - rbac.authorization.k8s.io
    resources:
      - roles
    verbs:
      - create
      - delete
  - apiGroups:
      - batch
    resources:
      - jobs
    verbs:
      - delete
      - list
  - apiGroups:
      - crunchydata.com
    resources:
      - pgclusters
      - pgreplicas
      - pgpolicies
      - pgtasks
    verbs:
      - delete
      - list
---
# Source: postgres-operator/templates/rbac.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: pgo-dev-postgres-operator-crb
  labels:
    helm.sh/chart: postgres-operator-4.3.2
    app.kubernetes.io/name: postgres-operator
    app.kubernetes.io/instance: pgo-dev
    app.kubernetes.io/version: "1.16.0"
    app.kubernetes.io/managed-by: Helm
    meta.helm.sh/release-name: pgo-dev
    meta.helm.sh/release-namespace: dev
  annotations:
    helm.sh/hook: post-install,post-upgrade,pre-delete
    helm.sh/hook-delete-policy: before-hook-creation,hook-succeeded
    helm.sh/hook-weight: "-10"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: pgo-dev-postgres-operator-cr
subjects:
- kind: ServiceAccount
  name: pgo-deployer-sa-dev
  namespace: dev
---
# Source: postgres-operator/templates/postgres-operator-install.yaml
apiVersion: batch/v1
kind: Job
metadata:
  name: pgo-deploy
  namespace: dev
  labels:
    helm.sh/chart: postgres-operator-4.3.2
    app.kubernetes.io/name: postgres-operator
    app.kubernetes.io/instance: pgo-dev
    app.kubernetes.io/version: "1.16.0"
    app.kubernetes.io/managed-by: Helm
    meta.helm.sh/release-name: pgo-dev
    meta.helm.sh/release-namespace: dev
  annotations:
    helm.sh/hook: post-install
    helm.sh/hook-delete-policy: hook-succeeded,before-hook-creation

spec:
  backoffLimit: 0
  template:
    metadata:
      name: pgo-deploy
      labels:
        helm.sh/chart: postgres-operator-4.3.2
        app.kubernetes.io/name: postgres-operator
        app.kubernetes.io/instance: pgo-dev
        app.kubernetes.io/version: "1.16.0"
        app.kubernetes.io/managed-by: Helm
        meta.helm.sh/release-name: pgo-dev
        meta.helm.sh/release-namespace: dev
    spec:
      serviceAccountName: pgo-deployer-sa-dev
      restartPolicy: Never
      containers:
      - name: pgo-deploy
        image: registry.developers.crunchydata.com/crunchydata/pgo-deployer:centos7-4.3.2
        imagePullPolicy: IfNotPresent
        env:
          - name: DEPLOY_ACTION
            value: "install"
        envFrom:
        - configMapRef:
            name: pgo-dev-postgres-operator-cm
```
