### ISSUE TITLE
CR deployment does not seem to respect the storageclass section

### ISSUE THREAD

**Issue by metabsd** [CrunchyData/postgres-operator#2240]
Hi, I'm trying to use Custom Resources method to deploy a PostgreSQL cluster via the 4.5.1 operator.

In my CR I explicitly specify that I want to use the rwx-nfs-storage storageclass but the claim is made on the default storageclass

That the claim be made on the correct storaclass

**Please tell us about your environment:**

* Operating System: Openshift 4.6
* Where is this running ( Local , Cloud Provider): Local
* Storage being used (NFS, Hostpath, Gluster, etc): NFS
* Container Image Tag:
* PostgreSQL Version: default value
* Platform (Docker, Kubernetes, OpenShift): Openshift 
* Platform Version: 4.6

If possible please run the following on the kubernetes or OpenShift (oc) commands and provide the result:
I can't because I can't actually deploy to this storageclass.

However, here is how I create the deployment : 
```
export pgo_cluster_name=postgresql-awx
export cluster_namespace=tower-awx

cat <<-EOF > "${pgo_cluster_name}-pgcluster.yaml"
apiVersion: crunchydata.com/v1
kind: Pgcluster
metadata:
  annotations:
    current-primary: ${pgo_cluster_name}
  labels:
    autofail: "true"
    crunchy-pgbadger: "false"
    crunchy-pgha-scope: ${pgo_cluster_name}
    crunchy-postgres-exporter: "false"
    deployment-name: ${pgo_cluster_name}
    name: ${pgo_cluster_name}
    pg-cluster: ${pgo_cluster_name}
    pg-pod-anti-affinity: ""
    pgo-backrest: "true"
    pgo-version: 4.5.1
    pgouser: admin
  name: ${pgo_cluster_name}
  namespace: ${cluster_namespace}
spec:
  BackrestStorage:
    accessmode: ReadWriteMany
    matchLabels: ""
    name: ""
    size: 1G
    storageclass: "rwx-nfs-storage"
    storagetype: create
    supplementalgroups: ""
  PrimaryStorage:
    accessmode: ReadWriteMany
    matchLabels: ""
    name: ${pgo_cluster_name}
    size: 1G
    storageclass: "rwx-nfs-storage"
    storagetype: create
    supplementalgroups: ""
  ReplicaStorage:
    accessmode: ReadWriteMany
    matchLabels: ""
    name: ""
    size: 1G
    storageclass: "rwx-nfs-storage"
    storagetype: create
    supplementalgroups: ""
  annotations:
  backrestLimits: {}
  backrestRepoPath: ""
  backrestResources:
    memory: 48Mi
  backrestS3Bucket: ""
  backrestS3Endpoint: ""
  backrestS3Region: ""
  backrestS3URIStyle: ""
  backrestS3VerifyTLS: ""
  ccpimage: crunchy-postgres-ha
  ccpimageprefix: registry.developers.crunchydata.com/crunchydata
  ccpimagetag: centos7-12.5-4.5.1
  clustername: ${pgo_cluster_name}
  customconfig: ""
  database: ${pgo_cluster_name}
  exporterport: "9187"
  limits: {}
  name: ${pgo_cluster_name}
  namespace: ${cluster_namespace}
  pgBouncer:
    limits: {}
    replicas: 0
  pgDataSource:
    restoreFrom: ""
    restoreOpts: ""
  pgbadgerport: "10000"
  pgoimageprefix: registry.developers.crunchydata.com/crunchydata
  podAntiAffinity:
    default: preferred
    pgBackRest: preferred
    pgBouncer: preferred
  policies: ""
  port: "5432"
  primarysecretname: ${pgo_cluster_name}-primaryuser-secret
  replicas: "0"
  rootsecretname: ${pgo_cluster_name}-postgres-secret
  shutdown: false
  standby: false
  tablespaceMounts: {}
  tls:
    caSecret: ""
    replicationTLSSecret: ""
    tlsSecret: ""
  tlsOnly: false
  user: postgresql-awx
  userlabels:
    crunchy-postgres-exporter: "false"
    pg-pod-anti-affinity: ""
    pgo-version: 4.5.1
  usersecretname: ${pgo_cluster_name}-postgresql-awx-secret
EOF

kubectl apply -f "${pgo_cluster_name}-pgcluster.yaml"
```
