### ISSUE TITLE
CRD schema doesn't have metadata defined

### ISSUE THREAD

**Issue by kesavkolla** [CrunchyData/postgres-operator#2245]
The CRDs for PgCluster and others schema doesn't define metadata. It only defines spec. 

```yaml
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: pgclusters.crunchydata.com
spec:
  group: crunchydata.com
  names:
    kind: Pgcluster
    listKind: PgclusterList
    plural: pgclusters
    singular: pgcluster
  scope: Namespaced
  version: v1
  validation:
    openAPIV3Schema:
      properties:
        spec:
          properties:
            clustername: { type: string }
            ccpimage: { type: string }
            ccpimagetag: { type: string }
            database: { type: string }
            exporterport: { type: string }
            name: { type: string }
            pgbadgerport: { type: string }
            PrimaryStorage: { type: object }
            port: { type: string }
            userlabels: { type: object }
        status:
          properties:
            state: { type: string }
            message: { type: string }
```

It would be good to include **metadata** as part of the CRD definition. I'm trying to use cdk8s to import the CRD to create a type definitions for the CRD. When imported the CRD they miss the metadata.  All the examples in documentation also includes metadata but the definition is missing metadata.
