### ISSUE TITLE
4.6.1 Stanza creation fails in kubernetes because clustername-backrest-shared-repo directory is not created

### ISSUE THREAD

**Issue by cristichiru** [CrunchyData/postgres-operator#2318]
**Describe the bug**
4.6.1 Stanza creation fails in kubernetes because clustername-backrest-shared-repo is not created

**To Reproduce**
1. Deployed 4.6.1 using ansible roles in a Kubernetes cluster. Namespace: `pgo-new`
2. Before creating a pg cluster, the following volumes were created:
    - 1 NFS volume for backrest
    - 2 local volumes for data
2. Create a new cluster: `pgo --namespace pgo-new create cluster pgo-new-x-postgres --metrics --pgbackrest-pvc-size 1Gi --pgbackrest-storage-config=x-backrest-nfs --storage-config=x-local-provisioner --replica-storage-config=x-local-provisioner --label release=x --node-label kubernetes.io/hostname=myhost1 --replica-count 1`
3. The following k8s objects are there:
```
kubectl -n pgo-new get all

NAME                                                           READY   STATUS    RESTARTS   AGE
pod/pgo-client-56d747b5d-n5bsc                                 1/1     Running   0          3h18m
pod/pgo-new-x-postgres-56d69bb679-lw428                        2/2     Running   0          20m
pod/pgo-new-x-postgres-backrest-shared-repo-5bbc75966c-ntcbv   1/1     Running   0          20m
pod/pgo-new-x-postgres-stanza-create-298qq                     0/1     Error     0          19m
pod/pgo-new-x-postgres-stanza-create-dkvpx                     0/1     Error     0          18m
pod/pgo-new-x-postgres-stanza-create-gz8g4                     0/1     Error     0          19m
pod/pgo-new-x-postgres-stanza-create-s54b2                     0/1     Error     0          17m
pod/pgo-new-x-postgres-stanza-create-xxfhd                     0/1     Error     0          19m
pod/postgres-operator-7f7d4746f9-qzl7s                         4/4     Running   0          20m

NAME                                              TYPE        CLUSTER-IP      EXTERNAL-IP   PORT(S)                      AGE
service/pgo-new-x-postgres                        ClusterIP   10.233.14.47    <none>        9187/TCP,2022/TCP,5432/TCP   20m
service/pgo-new-x-postgres-backrest-shared-repo   ClusterIP   10.233.15.198   <none>        2022/TCP                     20m
service/postgres-operator                         ClusterIP   10.233.47.244   <none>        8443/TCP,4171/TCP,4150/TCP   3h19m

NAME                                                      READY   UP-TO-DATE   AVAILABLE   AGE
deployment.apps/pgo-client                                1/1     1            1           3h18m
deployment.apps/pgo-new-x-postgres                        1/1     1            1           20m
deployment.apps/pgo-new-x-postgres-backrest-shared-repo   1/1     1            1           31m
deployment.apps/postgres-operator                         1/1     1            1           3h19m

NAME                                                                 DESIRED   CURRENT   READY   AGE
replicaset.apps/pgo-client-56d747b5d                                 1         1         1       3h18m
replicaset.apps/pgo-new-x-postgres-56d69bb679                        1         1         1       20m
replicaset.apps/pgo-new-x-postgres-backrest-shared-repo-5bbc75966c   1         1         1       31m
replicaset.apps/postgres-operator-79b5548578                         0         0         0       82m
replicaset.apps/postgres-operator-7b978498bf                         0         0         0       3h19m
replicaset.apps/postgres-operator-7f7d4746f9                         1         1         1       78m

NAME                                         COMPLETIONS   DURATION   AGE
job.batch/pgo-new-x-postgres-stanza-create   0/1           19m        19m

```
4. Stanza is not created, so no standby can be created, no backups.

**Expected behavior**
`clustername-backrest-shared-repo` directory created in the backrest volume, just as in 4.5.x, and stanza and replica successfully created.

**Please tell us about your environment:**

* Operating System: Ubuntu 20.04
* Where is this running: Local
* Storage being used (NFS, Hostpath, Gluster, etc): nfs, local
* Container Image Tag:
   - operator: centos8-4.6.1
   - ccp_image_tag: centos8-12.6-4.6.1
* PostgreSQL Version: 12.6
* Platform (Docker, Kubernetes, OpenShift): Kubernetes
* Platform Version: 1.18.5

**Additional context**
This issue does not occur in 4.5.x

**Comment by jkatz** [comment]
@cristichiru Can you please provide logs from the failing Pods?

**Comment by cristichiru** [comment]
This is a consequence of that dir not being created. If I do create it by hand, everything will work.

```
time="2021-03-04T21:46:12Z" level=info msg="pgo-backrest starts"
time="2021-03-04T21:46:12Z" level=info msg="debug flag set to false"
time="2021-03-04T21:46:12Z" level=info msg="backrest stanza-create command requested"
time="2021-03-04T21:46:12Z" level=info msg="command to execute is [pgbackrest stanza-create --db-host=10.233.65.90 --db-path=/pgdata/pgo-new-x-postgres]"
time="2021-03-04T21:46:12Z" level=info msg="command is pgbackrest stanza-create --db-host=10.233.65.90 --db-path=/pgdata/pgo-new-x-postgres "
time="2021-03-04T21:46:13Z" level=error msg="command terminated with exit code 56"
time="2021-03-04T21:46:13Z" level=info msg="output=[]"
time="2021-03-04T21:46:13Z" level=info msg="stderr=[WARN: unable to check pg-1: [ProtocolError] expected value '2.29' for greeting key 'version' but got '2.31'\nERROR: [056]: unable to find primary cluster - cannot proceed\n]"
time="2021-03-04T21:46:13Z" level=error msg="command terminated with exit code 56"
```

**Comment by jkatz** [comment]
This appears to be a mismatch in your containers. The Job issuing `stanza-create` is using a 4.5 container whereas the PostgreSQL Pod has a 4.6 container. Ensure you have properly loaded all of the 4.6.1 containers.

See [compatibility](https://access.crunchydata.com/documentation/postgres-operator/latest/configuration/compatibility/).

**Comment by cristichiru** [comment]
Indeed, the jobs have the image 4.5.2

So, I do have a 4.5.2 deployed as well in another namespace `pgo`  because we needed to use the cluster and I did not know a fix and how long will take for https://github.com/CrunchyData/postgres-operator/issues/2251

I did not specify anywhere that version. Is it picking it up from the other operator?
So, once I upgrade the **main** operator, it should work by itself since container tags will be aligned.

Also, as another topic: I have noticed that deploying 4.6.1 alongside 4.5.2, `pgo-cluster-role` is not updated with the `postgres-operator` ServiceAccount for the 4.6.1 namespace, `pgo-new`. Had to do it manually.

For 4.6.1 deployment, `namespace` parameter is set only to the operator namespace. 4.5.2 does **not** manage `pgo-new` namespace. I have deployed 4.6.1 to help with https://github.com/CrunchyData/postgres-operator/issues/2251. Probably will do the same with new versions to test them before rolling them out to existing instances.

My config (is default with minor changes):

```yaml
# =====================
# Configuration Options
# More info for these options can be found in the docs
# https://access.crunchydata.com/documentation/postgres-operator/latest/installation/configuration/
# =====================

## Set to true enable archive logging on all newly created clusters.
archive_mode: "true"

## Set to a value in seconds to configure the timeout threshold for archiving.
archive_timeout: "60"
backrest_aws_s3_bucket: ""
backrest_aws_s3_endpoint: ""
backrest_aws_s3_key: ""
backrest_aws_s3_region: ""
backrest_aws_s3_secret: ""
backrest_aws_s3_uri_style: ""
backrest_aws_s3_verify_tls: "true"
backrest_port: "2022"

## Set to true enable pgBadger capabilities on all newly created clusters. This can be disabled by the client.
badger: "false"

## Configures the image prefix used when creating containers from Crunchy Container Suite.
ccp_image_prefix: "registry.developers.crunchydata.com/crunchydata"

## Name of a Secret containing credentials for container image registries.
ccp_image_pull_secret: ""

## Provide a path to the Secret manifest to be installed in each namespace. (optional)
ccp_image_pull_secret_manifest: ""

## Configures the image tag (version) used when creating containers from Crunchy Container Suite.
ccp_image_tag: "centos8-12.6-4.6.1"

## Set to true if the installer should create the RBAC resources required to run the PostgreSQL Operator.
create_rbac: "true"

## Set to configure Operator to use debugging mode. Note: this can cause sensitive data such as passwords to appear in Operator logs.
crunchy_debug: "false"

## Set to a value to configure the default database name on all newly created clusters.
db_name: "postgres"

## Set to a value in days to configure the expiration age on PostgreSQL role passwords on all newly created clusters.
db_password_age_days: "0"

## Set to configure the size of passwords generated by the operator on all newly created roles.
db_password_length: "16"

## Set to configure the default port used on all newly created clusters.
db_port: "5432"

## Set to configure the amount of replicas provisioned on all newly created clusters.
db_replicas: "1"

## Set to configure the username of the dedicated user account on all newly created clusters.
db_user: "postgres"

## Represents the memory request for a PostgreSQL instance.
default_instance_memory: "128Mi"

## Represents the memory request for a pgBackRest repository.
default_pgbackrest_memory: "48Mi"

## Represents the memory request for a pgBouncer instance.
default_pgbouncer_memory: "24Mi"

default_exporter_memory: "24Mi"

## Set to configure whether or not the PGO operator namespace (defined using variable pgo_operator_namespace) is deleted when uninstalling the PGO.
delete_operator_namespace: "false"

## Set to configure whether or not the PGO watched namespaces (defined using variable namespace) are deleted when uninstalling the PGO.
delete_watched_namespaces: "false"

## Set to true disable auto failover capabilities on all newly created cluster requests. This cannot be overriden by the client on a cluster create, but on a cluster update. Setting this is not generally recommend, as it
disable_auto_failover: "false"

## Set to true for deployments where you do not want to have the default PostgreSQL fsGroup (26) set. The typical usage is in OpenShift environments that have a restricted Security Context Constraints.
disable_fsgroup: "false"

## Determines whether or not the PostgreSQL Operator will granted the permissions needed to reconcile RBAC within targeted namespaces.
reconcile_rbac: "true"

## Set to configure the default port used to connect to postgres exporter.
exporterport: "9187"

## Set to true enable performance metrics on all newly created clusters. This can be disabled by the client.
metrics: "true"

## Namespace in which the metrics deployments with be run.
metrics_namespace: "pgo-new"

## Set to a comma delimited string of all the namespaces Operator will manage.
namespace: "pgo-new"

## Determines which namespace permissions are assigned to the PostgreSQL Operator using a ClusterRole. Options: dynamic, readonly, and disabled
namespace_mode: "dynamic"

## Set to configure the default port used to connect to pgbadger.
pgbadgerport: "10000"

## When true, includes system default certificate authorities.
pgo_add_os_ca_store: "false"

## Configures the pgo administrator password.
pgo_admin_password: "somerandompass"

pgo_admin_perms: "*"

pgo_admin_role_name: "pgoadmin"

## Configures the pgo administrator username.
pgo_admin_username: "admin"

## Set to configure the port used by the Crunchy PostgreSQL Operator apiserver.
pgo_apiserver_port: "8443"

## Sets the pgo_apiserver_url for the pgo-client deployment.
pgo_apiserver_url: "https://postgres-operator"

## Sets the secret that the pgo-client will use when connecting to the PostgreSQL Operator.
pgo_client_cert_secret: "pgo.tls"

## Run the pgo-client deployment with the PostgreSQL Operator.
pgo_client_container_install: "true"

## Enable to download the pgo client binary as part of the Ansible install
pgo_client_install: "true"

## pgo-client version
pgo_client_version: "4.6.1"

## Determines whether or not the cluster-admin role is assigned to the PGO service account. Must be true to enable PGO namespace & role creation when installing in OpenShift.
pgo_cluster_admin: "false"

## Set to configure whether or not eventing should be enabled for the Crunchy PostgreSQL Operator installation.
pgo_disable_eventing: "false"

## Set to configure whether or not TLS should be enabled for the Crunchy PostgreSQL Operator apiserver.
pgo_disable_tls: "false"

## Configures the image prefix used when creating containers for the Crunchy PostgreSQL Operator (apiserver, operator, scheduler..etc).
pgo_image_prefix: "registry.developers.crunchydata.com/crunchydata"

## Name of a Secret containing credentials for container image registries.
#pgo_image_pull_secret: ""

## Provide a path to the Secret manifest to be installed in each namespace. (optional)
#pgo_image_pull_secret_manifest: ""

## Configures the image tag used when creating containers for the Crunchy PostgreSQL Operator (apiserver, operator, scheduler..etc)
pgo_image_tag: "centos8-4.6.1"

## The name of the PGO installation.
pgo_installation_name: "x"

## Configures URL routes with mTLS and HTTP BasicAuth disabled.
#pgo_noauth_routes: ""

## Set to configure the namespace where Operator will be deployed.
pgo_operator_namespace: "pgo-new"

## Set to add additional Certificate Authorities for Operator to trust (PEM-encoded file).
#pgo_tls_ca_store: ""

## Set to configure Operator to verify TLS certificates.
pgo_tls_no_verify: "false"

## This will set the default pod anti-affinity for the deployed PostgreSQL clusters.
pod_anti_affinity: "preferred"

## This will set the default pod anti-affinity for the pgBackRest pods.
#pod_anti_affinity_pgbackrest: ""

## This will set the default pod anti-affinity for the pgBouncer pods.
#pod_anti_affinity_pgbouncer: ""

## Set to a value in seconds to configure the pgo-scheduler timeout threshold when waiting for schedules to complete.
scheduler_timeout: "3600"

## Set to configure the type of Kubernetes service provisioned on all newly created clusters.
service_type: "ClusterIP"

## If set to true will automatically enable synchronous replication in new PostgreSQL clusters.
sync_replication: "false"

backrest_storage: "x-backrest-nfs"
primary_storage: "x-local-provisioner"
replica_storage: "x-local-provisioner"
backup_storage: "x-local-provisioner"
wal_storage: ""

## Default storage
storage1_name: "x-backrest-nfs"
storage1_access_mode: "ReadWriteOnce"
storage1_size: "500Mi"
storage1_type: "dynamic"
storage1_class: "pgo-x-backrest-nfs"

storage2_name: "x-local-provisioner"
storage2_access_mode: "ReadWriteOnce"
storage2_size: "500Mi"
storage2_type: "dynamic"
storage2_class: "pgo-x-local-provisioner"
```
