### ISSUE TITLE
S3 backup supporting http

### ISSUE THREAD

**Issue by teplydat** [CrunchyData/postgres-operator#2327]
**What is the motivation or use case for the change?**
A S3 backup over http could be very helpful for local s3-like storage (like minio) in the same kubernetes cluster. 

**Describe the solution you'd like**
https://access.crunchydata.com/documentation/postgres-operator/latest/architecture/disaster-recovery/#using-s3
```
kind: Pgcluster
spec:
  backrest:
    backrestS3Bucket: "bucketname"
    backrestS3Endpoint: "http://minio.default:9000"
    backrestS3Region: ":default-placement"
(aws-s3-key+aws-s3-key-secret in a secret)
```
current error message: 'http://minio.default:9000 is not valid for option "repo1-s3-endpoint"'' 

**Please tell us about your environment:**

* Where is this running ( Local, Cloud Provider): Local
* Platform (Docker, Kubernetes, OpenShift): Kubernetes/OpenShift

**Additional context**
