### ISSUE TITLE
Restore from S3 - unable to verify certificate presented by ...

### ISSUE THREAD

**Issue by teplydat** [CrunchyData/postgres-operator#2329]
**Which example are you working with?**
setting up s3 backup in pgcluster (including backrestS3VerifyTLS=false):
```
kind: Pgcluster
spec:
  backrest:
    backrestS3Bucket: "bucketname"
    backrestS3Endpoint: "storage.example.com"
    backrestS3Region: ":default-placement"
    backrestS3URIStyle: 'path'
    backrestS3VerifyTLS: 'false'
(aws-s3-key+aws-s3-key-secret in a secret)
```
a s3 backup:
```
pgo backup postgres-db --backup-opts="--type=full" --apiserver-url=https://localhost:8443 --pgo-ca-cert=pgotls.txt --pgo-client-cert=pgotls.txt --pgo-client-key=pgotls.key --namespace default
```
try to restore:
```
pgo restore --pgbackrest-storage-type="s3" postgres-db --pitr-target="20210310-152522F" --backup-opts="--type=time --log-level-console=info" --apiserver-url=https://localhost:8443 --pgo-ca-cert=pgotls.txt --pgo-client-cert=pgotls.txt --pgo-client-key=pgotls.key --namespace default
```

**What is the current behavior?**
error message:
```
kubectl get pods -n default | grep postgr
postgres-db-bootstrap-kk87m                         0/1     Error              0          3m49s

kubectl logs postgres-db-bootstrap-kk87m -n default
CryptoError: raised from remote-0 protocol on 'postgres-db-backrest-shared-repo': unable to verify certificate presented by 'storage.example.com:443': [20] unable to get local issuer certificate
```

**What is the expected behavior?**
Either it skips tls verification automatically (like in pgcluster described) or a flag exists in order to skip it or it is possible to add a custom CA file.

**Other information** (e.g. detailed explanation, related issues,  etc)
I could not find a command line flag to skip tsl verification: `pgo restore --help` 
Does is exist?
Or where could I add the CA cert for s3/minio server?

Thank you so much!

**Please tell us about your environment:**

* Where is this running (Local , Cloud Provider): Local
* Platform (Docker, Kubernetes, OpenShift): Kubernetes/OpenShift
