### ISSUE TITLE
Operator does not find role 'pgo-target-role'

### ISSUE THREAD

**Issue by timbrd** [CrunchyData/postgres-operator#2334]
**Describe the bug**
After successfully installing pgo 4.6.1 using the operator lifecycle manager as described [here](https://access.crunchydata.com/documentation/postgres-operator/4.6.1/installation/other/operator-hub/), I have found the following error messages in the operator logs:

```
[...]
time="2021-03-14T20:05:55Z" level=error msg="operator is unable to reconcile RBAC resource: roles.rbac.authorization.k8s.io \"pgo-target-role\" not found" func="internal/controller/manager.(*ControllerManager).reconcileRoleBindings()" file="internal/controller/manager/rbac.go:112" version=4.6.1
time="2021-03-14T20:06:55Z" level=error msg="operator is unable to reconcile RBAC resource: roles.rbac.authorization.k8s.io \"pgo-target-role\" is forbidden: user \"system:serviceaccount:pgo:postgres-operator\" (groups=[\"system:serviceaccounts\" \"system:serviceaccounts:pgo\" \"system:authenticated\"]) is attempting to grant RBAC permissions not currently held:\n{APIGroups:[\"apps\"], Resources:[\"replicasets\"], Verbs:[\"get\" \"list\" \"watch\" \"create\" \"patch\" \"update\" \"delete\" \"deletecollection\"]}" func="internal/controller/manager.(*ControllerManager).reconcileRoles()" file="internal/controller/manager/rbac.go:95" version=4.6.1
[...]
```

The deployment is running:
```
[root@b59e326509a5 postgres-operator]# kubectl get deployment -n pgo
NAME                READY   UP-TO-DATE   AVAILABLE   AGE
postgres-operator   1/1     1            1           106m
```

Do I have to create the role manually?

**To Reproduce**
1. Create operator group and olm subscription as described in the docs
2. Check the operator logs: `kubectl logs postgres-operator-6df4f5746c-jq8ss operator -n pgo`

**Comment by jkatz** [comment]
- Have you or someone on your system previously installed the Postgres Operator with a different method?
- Which namespace mode did you select?

**Comment by timbrd** [comment]
> * Have you or someone on your system previously installed the Postgres Operator with a different method?
I have not used a different installation method to install the operator before, but I had to delete the olm install plan and crds since I have installed them into the wrong namespace.

> * Which namespace mode did you select?

I didn't select any namespace mode. I did only install the operator using the manifests as described in the mentioned documentation:

```
kubectl -n "$PGO_OPERATOR_NAMESPACE" create -f- <<YAML
---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: postgresql
spec:
  targetNamespaces: ["$PGO_OPERATOR_NAMESPACE"]

---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: postgresql
spec:
  name: postgresql
  channel: stable
  source: operatorhubio-catalog
  sourceNamespace: olm
  startingCSV: postgresoperator.v4.6.1
YAML
```

> I would also suggest reviewing the [Namespaces](https://access.crunchydata.com/documentation/postgres-operator/latest/architecture/namespace/) section of the documentation that detail the various namespaces and required privileges.

Thanks, I will check that. But isn't the operator supposed to prepare the namespace and create the basic roles?
