### ISSUE TITLE
Improve documentation on provide a secret for Pgbackrest S3 CA

### ISSUE THREAD

**Issue by mgalesloot** [CrunchyData/postgres-operator#2361]
We try to create a cluster with the CRD Pgcluster, as per the documentation at https://access.crunchydata.com/documentation/postgres-operator/latest/custom-resources/

Our requirement is to make backups with pgBackRest to a privately hosted S3 with a LetsEncrypt certificate. Therefore, we need to make sure pgBackRest will trust the CA of LetsEncrypt. 

The documentation for the CRD is not specific how to make a trust to the CA of LetsEncrypt. We would like to make a secret with the CA  and provide the secret to pgBackRest. This works quite fine in the REST API of the Operator. 

However, it seems the CRD resource Pgcluster does not support a field such as `backrestS3CASecretName`. 

Would it be possible to add support for the field `backrestS3CASecretName` in the Pgcluster resource?

**Comment by jkatz** [comment]
This is [described in the docs](https://access.crunchydata.com/documentation/postgres-operator/latest/pgo-client/reference/pgo_create_cluster/) though I would agree that it could use a more prominent callout:

```
--pgbackrest-s3-ca-secret string        If used, specifies a Kubernetes secret that uses a different CA certificate for S3 or a S3-like storage interface. Must contain a key with the value "aws-s3-ca.crt"
```

So your Secret must have a key of `aws-s3-ca.crt` that includes your CA.

**Comment by mgalesloot** [comment]
The issue we have is that the **CRD** pgCluster does not seem to support the field backrestS3CASecretName. I am aware of the docs for the pgo binary, they are sufficient from my perspective. 

To make it very specific the example pgCluster (some fields omitted for brevity) which we apply with kubectl.
Look for the line "Crunchy does not seem .." 
(I have looked in the golang code of the operator but could not understand all the details how the CRD is processed) 
```
      apiVersion: crunchydata.com/v1
      kind: Pgcluster
      metadata:
        annotations:
          current-primary: "{{ database }}"
        labels:
          crunchy-pgha-scope: "{{ database }}"
          deployment-name: "{{ database }}"
          name: "{{ database }}"
          pg-cluster: "{{ database }}"
          pgo-version: "{{ deployments.postgres_operator.version }}"
          pgouser: admin
        name: "{{ database }}"
        namespace: "{{ database_namespace }}"
      spec:
        annotations: {}
        backrestStorageTypes:
          - s3
          - posix
        backrestS3Bucket: "{{ database_namespace }}"
        backrestS3Endpoint: "{{ config.backup_vault.fqdn }}"
        backrestS3Region: minio
        backrestS3URIStyle: path
        backrestS3VerifyTLS: "true"  
       # Crunchy does not seem to read next param 
        backrestS3CASecretName: letsencrypt-issuer
```

**Comment by mgalesloot** [comment]
The issue can be fixed by directly creating the secret `<database>-backrest-repo-config` for pgBackRest before making the PgCluster manifest. With this workaround, the secret for the field `backrestS3CASecretName` can be skipped. 
```
      apiVersion: v1
      kind: Secret
      type: Opaque
      metadata:
        name: "{{ database }}-backrest-repo-config"
      data:
        aws-s3-ca.crt: "<CA certificate>"
        aws-s3-key: "<redacted>"
        aws-s3-key-secret: "<redacted>"
```
