### ISSUE TITLE
[4.6.2] Creating a Pgcluster custom resource object doesn't trigger cluster creation

### ISSUE THREAD

**Issue by aakarshg** [CrunchyData/postgres-operator#2435]
I am using the following custom resource definition and after applying it I don't see any objects being created to support postgres cluster creation..:

```
---
apiVersion: crunchydata.com/v1
kind: Pgcluster
metadata:
  annotations:
    current-primary: postgres-dev
    primary-deployment: postgres-dev
  labels:
    crunchy-pgha-scope: postgres-dev
    deployment-name: postgres-dev
    name: postgres-dev
    crunchy-postgres-exporter: "true"
    pg-cluster: postgres-dev
    pgo-version: 4.6.2
    pgouser: admin
  name: postgres-dev
  namespace: postgres-dev
spec:
  BackrestStorage:
    accessmode: ReadWriteOnce
    matchLabels: ""
    name: ""
    size: 1G
    storageclass: fast
    storagetype: dynamic
    supplementalgroups: ""
  PrimaryStorage:
    accessmode: ReadWriteOnce
    matchLabels: ""
    name: postgres-dev
    size: 500Gi
    storageclass: fast
    storagetype: dynamic
    supplementalgroups: ""
  ReplicaStorage:
    accessmode: ReadWriteOnce
    matchLabels: ""
    name: ""
    size: 500Gi
    storageclass: fast
    storagetype: dynamic
    supplementalgroups: ""
  WALStorage:
    accessmode: ""
    matchLabels: ""
    name: ""
    size: ""
    storageclass: fast
    storagetype: ""
    supplementalgroups: ""
  annotations:
    backrest: {}
    global: {}
    pgBouncer: {}
    postgres: {}
  backrestConfig: null
  backrestLimits: {}
  backrestRepoPath: ""
  backrestResources:
    memory: 48Mi
  backrestS3Bucket: ""
  backrestS3Endpoint: ""
  backrestS3Region: ""
  backrestS3URIStyle: ""
  backrestS3VerifyTLS: "true"
  backrestStorageTypes: []
  ccpimage: crunchy-postgres-ha
  ccpimageprefix: registry.developers.crunchydata.com/crunchydata
  ccpimagetag: centos8-13.2-4.6.2
  clustername: postgres-dev
  customconfig: ""
  database: vaticdb
  disableAutofail: false
  exporter: true
  exporterLimits: {}
  exporterResources:
    memory: 24Mi
  exporterport: "9187"
  limits:
    cpu: "3"
    memory: 4192Mi
  name: postgres-dev
  namespace: postgres-dev
  nodeAffinity:
    default:
      preferredDuringSchedulingIgnoredDuringExecution:
      - preference:
          matchExpressions:
          - key: environment
            operator: In
            values:
            - dev
        weight: 10
  pgBadger: false
  pgBouncer:
    limits: {}
    replicas: 1
    resources:
      memory: 24Mi
    serviceType: ""
    tlsSecret: ""
  pgDataSource:
    restoreFrom: ""
    restoreOpts: ""
  pgbadgerport: "10000"
  pgoimageprefix: registry.developers.crunchydata.com/crunchydata
  podAntiAffinity:
    default: preferred
    pgBackRest: preferred
    pgBouncer: preferred
  policies: ""
  port: "5432"
  replicas: "1"
  resources:
    memory: 128Mi
  serviceType: ""
  shutdown: false
  standby: false
  status: completed
  syncReplication: true
  tablespaceMounts: {}
  tls:
    caSecret: ""
    replicationTLSSecret: ""
    tlsSecret: ""
  tlsOnly: false
  tolerations:
  - effect: NoExecute
    key: purpose
    operator: Equal
    value: postgres
  - effect: NoExecute
    key: environment
    operator: Equal
    value: dev
  user: testuser
  userlabels:
    pgo-version: 4.6.2
    
```

The above is actually the same object that is created minus the missing workflow-ids.. when using the pgo client to create it and the addition of the storageclass `fast` which is the special storage class that I'd like to use which is not supported if using the client. 

Here's the relevant operator logs after the CR is created:

```
time="2021-05-10T16:00:47Z" level=error msg="ConfigMap Controller: cannot find pgcluster for configMap postgres-dev-pgha-config (namespace postgres-dev),ignoring" func="internal/controller/configmap.(*Controller).handleConfigMapSync()" file="internal/controller/configmap/synchandler.go:55" version=4.6.2
time="2021-05-10T16:00:51Z" level=error msg="pgclusters.crunchydata.com \"postgres-dev\" not found" func="internal/controller/pod.(*Controller).onUpdate()" file="internal/controller/pod/podcontroller.go:95" version=4.6.2
time="2021-05-10T16:00:53Z" level=error msg="pgclusters.crunchydata.com \"postgres-dev\" not found" func="internal/controller/pod.(*Controller).onUpdate()" file="internal/controller/pod/podcontroller.go:95" version=4.6.2
time="2021-05-10T16:00:53Z" level=error msg="pgclusters.crunchydata.com \"postgres-dev\" not found" func="internal/controller/pod.(*Controller).onUpdate()" file="internal/controller/pod/podcontroller.go:95" version=4.6.2
time="2021-05-10T16:00:58Z" level=error msg="pgclusters.crunchydata.com \"postgres-dev\" not found" func="internal/controller/pod.(*Controller).onUpdate()" file="internal/controller/pod/podcontroller.go:95" version=4.6.2
time="2021-05-10T16:01:01Z" level=error msg="pgclusters.crunchydata.com \"postgres-dev\" not found" func="internal/controller/pod.(*Controller).onUpdate()" file="internal/controller/pod/podcontroller.go:95" version=4.6.2
2021/05/10 16:01:02 INF  3803 (localhost:4150) connecting to nsqd
time="2021-05-10T16:01:02Z" level=error msg="pgclusters.crunchydata.com \"postgres-dev\" not found" func="internal/controller/pod.(*Controller).onUpdate()" file="internal/controller/pod/podcontroller.go:95" version=4.6.2
time="2021-05-10T16:01:02Z" level=error msg="pgclusters.crunchydata.com \"postgres-dev\" not found" func="internal/controller/pod.(*Controller).onUpdate()" file="internal/controller/pod/podcontroller.go:95" version=4.6.2
time="2021-05-10T16:01:02Z" level=error msg="pgclusters.crunchydata.com \"postgres-dev\" not found" func="internal/controller/pod.(*Controller).onUpdate()" file="internal/controller/pod/podcontroller.go:95" version=4.6.2
2021/05/10 16:01:07 INF  3804 (localhost:4150) connecting to nsqd
time="2021-05-10T16:01:07Z" level=error msg="jobs.batch \"postgres-dev-rmdata-vbgb\" not found" func="internal/controller/job.(*Controller).handleRMDataUpdate()" file="internal/controller/job/rmdatahandler.go:61" version=4.6.2
time="2021-05-10T16:01:10Z" level=error msg="pgclusters.crunchydata.com \"postgres-dev\" not found" func="internal/controller/pod.(*Controller).onUpdate()" file="internal/controller/pod/podcontroller.go:95" version=4.6.2

```
