### ISSUE TITLE
How to resolve initdb / permission denied issue in postgres cluster ?

### ISSUE THREAD

**Issue by sathishc58** [CrunchyData/postgres-operator#2436]
I have installed Crunchydata PG Operator on K8S Cluster by following the link mentioned below

[https://access.crunchydata.com/documentation/postgres-operator/4.6.2/installation/postgres-operator/](url)

I followed the link mentioned below to create PG Cluster

[https://access.crunchydata.com/documentation/postgres-operator/latest/custom-resources/](url)  > postgres-cluster.yml

Environment

`CentOS:  7

Kubernetes:  Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.0", ```
GitCommit:"cb303e613a121a29364f75cc67d3d580833a7479", GitTreeState:"clean", BuildDate:"2021-04-08T16:31:21Z", GoVersion:"go1.16.1", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.0", GitCommit:"cb303e613a121a29364f75cc67d3d580833a7479", GitTreeState:"clean", BuildDate:"2021-04-08T16:25:06Z", GoVersion:"go1.16.1", Compiler:"gc", Platform:"linux/amd64"}`

I executed `'kubectl -f postgres-cluster.yml'` which resulted in the following error

`[root@control1 ~]# kubectl logs deployment.apps/hippo -n pgo
/opt/crunchy/bin/postgres-ha/bootstrap-postgres-ha.sh: line 198: /pgdata/hippo.initializing: Permission denied
mkdir: cannot create directory ‘/pgdata/hippo’: Permission denied
chmod: cannot access '/pgdata/hippo': No such file or directory`

I am not sure where should I insert the following piece of code in **posgres-cluster.yaml** and disablefs_group is set to 'false'

`spec:
  securityContext:
      fsGroup:  26`

Though I see same / similar issues in SO, I am not sure what needs to be added where.  I spent almost a day to resolve this issue with no result

Kindly let me know what should be done to fix this issue

Thanks
Sathish Kumar

**Comment by sathishc58** [comment]
This was the error message which still persists and this is the very 1st line. 

```
[root@control1 ~]# kubectl logs deployment.apps/hippo -n pgo
 /opt/crunchy/bin/postgres-ha/bootstrap-postgres-ha.sh: line 198: /pgdata/hippo.initializing: Permission denied
```

As bootstrap failed I am not sure whether 'readinessProbe' will be taken into account at this stage

Following are my PV settings

```
apiVersion: v1
kind: PersistentVolume
metadata:
  name: hippo
  namespace: pgo
  labels:
    type: local
spec:
  storageClassName: default
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  claimRef:
    namespace: pgo
    name: hippo
  hostPath:
    path: "/mnt/data"

apiVersion: v1
kind: PersistentVolume
metadata:
  name: hippo-pgbr-repo
  namespace: pgo
  labels:
    type: local
spec:
  storageClassName: default
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  claimRef:
    namespace: pgo
    name: hippo-pgbr-repo
  hostPath:
    path: "/mnt/data1"
```
State of PV and PVC

```
[root@control01 ~]# kubectl get pv -n pgo
NAME              CAPACITY   ACCESS MODES   RECLAIM POLICY   STATUS   CLAIM                 STORAGECLASS   REASON   AGE
hippo             1Gi        RWX            Retain           Bound    pgo/hippo             default                 116m
hippo-pgbr-repo   1Gi        RWX            Retain           Bound    pgo/hippo-pgbr-repo   default                 116m

[root@control01 ~]# kubectl get pvc -n pgo
NAME              STATUS   VOLUME            CAPACITY   ACCESS MODES   STORAGECLASS   AGE
hippo             Bound    hippo             1Gi        RWX                           116m
hippo-pgbr-repo   Bound    hippo-pgbr-repo   1Gi        RWX                           116m
```
