### ISSUE TITLE
pgbackrest repo with S3 storage fails to initialize

### ISSUE THREAD

**Issue by tpatrascu** [CrunchyData/postgres-operator#2445]
## Overview

Hello, I am trying to deploy a synchronous replication cluster with 3 nodes and WAL streaming and backup to S3, but the pgbackrest repository fails to initialize. Initially I though it was a bug in minio, but tried it with AWS S3 and ceph RGW and can't get it to work and can't figure out what is wrong with it from the pgbackrest logs.

## Environment

Please provide the following details:

- Platform: Kubernetes
- Platform Version: v1.19.7
- PGO Image Tag: centos8-13.2-4.6.2
- Postgres Version: 13
- Storage: PVC RWO

### REPRO

I create my cluster with the following settings:

```
---
apiVersion: crunchydata.com/v1
kind: Pgcluster
metadata:
  annotations:
    current-primary: mycluster
  labels:
    crunchy-pgbadger: "true"
    crunchy-pgha-scope: mycluster
    deployment-name: mycluster
    name: mycluster
    pg-cluster: mycluster
    pgo-version: 4.6.2
    pgouser: admin
  name: mycluster
spec:
  name: mycluster
  clustername: mycluster
  namespace: myns

  user: myuser
  database: myuser

  replicas: "2"
  syncReplication: true
  disableAutofail: false

  # set as active or DR instance
  standby: false
  # set to true to shutdown the cluster
  shutdown: false

  BackrestStorage:
    accessmode: ReadWriteOnce
    size: 20Gi
    storageclass: "rbd"
    storagetype: dynamic
  PrimaryStorage:
    accessmode: ReadWriteOnce
    name: mycluster
    size: 20Gi
    storageclass: rbd
    storagetype: dynamic
  ReplicaStorage:
    accessmode: ReadWriteOnce
    name: ""
    size: 20Gi
    storageclass: "rbd"
    storagetype: dynamic
  resources:
    cpu: 500m
    memory: 512Mi
  limits:
    cpu: 1000m
    memory: 1024Mi

  backrestStorageTypes:
  - s3
  backrestS3Bucket: pgbak
  backrestS3Endpoint: mys3server.com
  backrestS3Region: us-east-1
  backrestS3URIStyle: "path"
  backrestS3VerifyTLS: "false"

  # Used to indicate if a PostgreSQL cluster should bootstrap its data from a pgBackRest repository.
  # restoreFrom 	create 	The name of a PostgreSQL cluster, active or former, that will be used for bootstrapping the data of a new PostgreSQL cluster.
  # restoreOpts 	create 	Additional pgBackRest restore options that can be used as part of the bootstrapping operation, for example, point-in-time-recovery options.
  # https://pgbackrest.org/command.html#command-restore
  pgDataSource:
    restoreFrom: ""
    restoreOpts: ""
  
  pgoimageprefix: registry.developers.crunchydata.com/crunchydata
  ccpimage: crunchy-postgres-ha
  ccpimageprefix: registry.developers.crunchydata.com/crunchydata
  ccpimagetag: centos8-13.2-4.6.2

  port: "5432"

  exporter: true
  exporterport: "9187"
  #exporterLimits: {}
  #exporterResources: {}
  
  pgBadger: true
  pgbadgerport: "10000"
  
  podAntiAffinity:
    default: required
    pgBackRest: preferred
    pgBouncer: preferred
  annotations: {}
  tolerations: []
  userlabels:
      pgo-version: 4.6.2

```

### EXPECTED

pgbackrest repo initialized, pushing WALs and backup and cluster working

### ACTUAL

The postgres cluster starts up and works fine if I don't enable pgbackrest, but if I do enable it, only one postgres node will start up and the rest will wait for pgbackrest.

## Logs

```
kubectl logs mycluster-stanza-create-5fft5
Wed May 12 05:27:43 UTC 2021 INFO: Image mode found: pgbackrest
Wed May 12 05:27:43 UTC 2021 INFO: Starting in 'pgbackrest' mode
time="2021-05-12T05:27:43Z" level=info msg="crunchy-pgbackrest starts"
time="2021-05-12T05:27:43Z" level=info msg="debug flag set to %tfalse"
time="2021-05-12T05:27:43Z" level=info msg="backrest stanza-create command requested"
time="2021-05-12T05:27:43Z" level=info msg="s3 flag enabled for backrest command"
time="2021-05-12T05:27:43Z" level=info msg="command to execute is [pgbackrest stanza-create  --db-host=10.233.81.106 --db-path=/pgdata/mycluster --repo1-type=s3 --no-repo1-s3-verify-tls]"
time="2021-05-12T05:27:44Z" level=info msg="output=[]"
time="2021-05-12T05:27:44Z" level=info msg="stderr=[ERROR: [039]: HTTP request failed with 400 (Bad Request):\n       *** URI/Query ***:\n       /pgbak/backrestrepo/mycluster-backrest-shared-repo/archive/db/archive.info\n       *** Request Headers ***:\n       authorization: <redacted>\n       content-length: 0\n       host: mys3server.com\n       x-amz-content-sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855\n       x-amz-date: <redacted>\n       *** Response Headers ***:\n       accept-ranges: bytes\n       connection: keep-alive\n       content-length: 176\n       content-type: application/xml\n       date: Wed, 12 May 2021 05:27:44 GMT\n       strict-transport-security: max-age=15724800; includeSubDomains\n       x-amz-request-id: tx000000000000000002abb-00609b6750-71f9-rgw\n]"
time="2021-05-12T05:27:44Z" level=fatal msg="command terminated with exit code 39"
```

I've rand pgbackrest in trace loglevel but doesn't really give much more detail.

On the S3 server side I get:

```
debug 2021-05-12T05:27:57.617+0000 7efe609a3700  1 beast: 0x7eff02c106b0: 10.233.89.167 - - [2021-05-12T05:27:57.617253+0000] "HEAD /pgbak/backrestrepo/mycluster-backrest-shared-repo/archive/db/archive.info HTTP/1.1" 400 0 - "pgBackRest/2.31" -
```

## Additional Information

In the backrest pod I see the /pgdata directory where --db-path points to is empty. Not sure if this is how it's supposed to be as I've never seen it working.

Thanks!
