### ISSUE TITLE
Is it possible to enable "archive-async" for "archive-push" ?

### ISSUE THREAD

**Issue by jose-joye** [CrunchyData/postgres-operator#2460]
Hello,
I'm running some stress test on a pg cluster  (8 CPU, 32 GB RAM and 1TB disk). It will create a lot of rows within a single table
``` 
CREATE TABLE Townsnew (
  id SERIAL UNIQUE NOT NULL,
  code VARCHAR(100) NOT NULL, -- not unique
  article TEXT,
  name TEXT NOT NULL, -- not unique
  department VARCHAR(100) NOT NULL,
  UNIQUE (code, department)
);

insert into townsnew (
    code, article, name, department
)
select
    left(md5(i::text), 1000),
    md5(random()::text),
    md5(random()::text),
    left(md5(random()::text), 1000)
from generate_series(1, 100000000) s(i);
``` 

This end up with a very large lag related to wal pushed (was up to 16000)

```
select pg_walfile_name(pg_current_wal_lsn()),last_archived_wal,last_failed_wal,
('x'||substring(pg_walfile_name(pg_current_wal_lsn()),9,8))::bit(32)::int*256 +
('x'||substring(pg_walfile_name(pg_current_wal_lsn()),17))::bit(32)::int -
('x'||substring(last_archived_wal,9,8))::bit(32)::int*256 -
('x'||substring(last_archived_wal,17))::bit(32)::int
as diff from pg_stat_archiver;
     pg_walfile_name      |    last_archived_wal     | last_failed_wal | diff
--------------------------+--------------------------+-----------------+------
 000000030000004800000036 | 000000010000002D00000053 |                 | 6883
```

I was wondering if we can somehow enable the `--archive-async` for the `pgbackrest archive-push` command so as to mitigate the issue.

**environment:**
Operating System: SUSE Linux Enterprise Server 15 SP1
Where is this running ( Local)
Storage being used (NFS)
Container Image Tag: crunchy-postgres-ha:centos7-11.10-4.5.1
PostgreSQL Version: 11.10
Platform (kubernetes 1.17.13 )

Thanks,
José

**Comment by jkatz** [comment]
You can overwrite the `archive_command` via custom configuration. You may also be able to set the [pgBackRest environmental variables](https://pgbackrest.org/command.html#introduction) to accomplish the configuration.

pgBackRest documents information around configuring `archive-async`. While you can certainly get a performance boost with using it, there are tradeoffs. Some documentation in that direction:

- [https://pgbackrest.org/configuration.html#section-archive/option-archive-async](https://pgbackrest.org/configuration.html#section-archive/option-archive-async)
- [https://pgbackrest.org/configuration.html#section-general/option-spool-path](https://pgbackrest.org/configuration.html#section-general/option-spool-path)

**Comment by iosifnicolae2** [comment]
@jkatz How can I overwrite `archive_command` in a V5 cluster?
I've tried adding the below configuration but the `archive_command` parameter seems to be overridden by Operator:
```yaml
patroni:
  dynamicConfiguration:
    postgresql:
      parameters:
        archive_command : pgbackrest --stanza=db archive-push --process-max=3 "%p"
```

Thank you!

**Comment by iosifnicolae2** [comment]
For V5, if you want to enable async archive-push you have to have the following `postgresCluster` configuration:
```yaml
postgresCluster:
  backups:
    pgbackrest:
      global:
        archive-async: y
        spool-path: /tmp/pgbackrest-spool
        process-max: 4
        compress-level: 5
        # ...
```
Also, for heavy write databases, I use:
```yaml
postgresCluster:
  patroni:
    dynamicConfiguration:
      postgresql:
        parameters:
          wal_buffers: 64MB
          wal_compression: on
          min_wal_size: 100MB
          max_wal_size: 1GB
          # ...
```
Also, you can use [pgtune](https://pgtune.leopard.in.ua/#/) to identify what parameters are appropriate for you load.
