### ISSUE TITLE
Unable to specify postgres version with CRD

### ISSUE THREAD

**Issue by odrodrig** [CrunchyData/postgres-operator#2501]
## Overview

I am trying to create a pgcluster instance using a custom resource definition and in the file I specify the property `ccpimagetag: ubi8-12.6-4.6.2`  however when I connect to the cluster with the psql cli tool and check the version, it is listed as 13.2. I double checked the operand and the 12.6 image tag is listed there however the cluster does not reflect that version.

## Environment

Please provide the following details:

- Platform: OpenShift
- Platform Version: 4.6
- PGO Image Tag: 
    - PGO version: 4.6.2
    - Image that I found in the operator pod is: registry.connect.redhat.com/crunchydata/postgres-operator@sha256:d35bef163c91e13fd180f25c97379245bb4965769b3f5c01a84d850ea8240103
- Postgres Version: 12.6
- Storage: block storage (ibmc-block-gold)

## Steps to Reproduce
 1. Create project called postgres
 2. Install crunchy PGO 4.6.2 from operator hub in postgres project. Specify manual upgrade strategy.
 3. Apply the following CRD

```yaml
apiVersion: crunchydata.com/v1
kind: Pgcluster
metadata:
  namespace: postgres
  name: postgresql126
  labels:
    crunchy-pgha-scope: postgresql126
    deployment-name: postgresql126
    name: postgresql126
    namespace: postgres
    pg-cluster: postgresql126
    pgo-version: 4.6.2
  annotations:
    current-primary: postgresql126
spec:
  port: '5432'
  exporterport: '9187'
  clustername: postgresql126
  pgbadgerport: '10000'
  userlabels:
    pgo-version: 4.6.2
  name: postgresql126
  ccpimage: crunchy-postgres-ha
  ccpimagetag: ubi8-12.6-4.6.2
  PrimaryStorage:
    accessmode: ReadWriteOnce
    matchLabels: ''
    name: primary
    size: 30Gi
    storagetype: dynamic
    supplementalgroups: ''
  database: postgres
  namespace: postgres
  pgBouncer:
    limits:
      memory: 2048Mi
    replicas: 2
  BackrestStorage:
    accessmode: ReadWriteOnce
    matchLabels: ''
    name: 'backrest'
    size: 30Gi
    storagetype: dynamic
    supplementalgroups: ''
  ReplicaStorage:
    accessmode: ReadWriteOnce
    matchLabels: ''
    name: 'repl'
    size: 30Gi
    storagetype: dynamic
    supplementalgroups: ''
  podAntiAffinity:
    default: preferred
  user: postgres
  replicas: "2"
  exporter: true
  limits: 
    memory: 10240Mi
    cpu: 2
```

### REPRO

Provide steps to get to the error condition:

1. After applying the file above, create a pod on the OpenShift cluster and exec into it.

```sh
oc run pg-isready -it --rm --image postgres /bin/bash
```

2. Once inside the pg-isready pod, run the following while replacing POSTGRES_SECRET with the postgres user password in the respective secret.

```sh
PGPASSWORD="POSTGRES_SECRET" psql -h postgresql126.postgres -p 5432 -U postgres postgres
```

3. You should be connected to the pgcluster now in the psql cli. Run the following command from the psql cli:

```sh
SELECT version();
```

### EXPECTED

1. After checking the version I expected to see version 12.6

### ACTUAL

1. I am seeing version 13.2 running in my cluster even though I specified the 12.6 image tag

## Logs

```sh
postgres=# SELECT version();
                                                version                                                 
--------------------------------------------------------------------------------------------------------
 PostgreSQL 13.2 on x86_64-pc-linux-gnu, compiled by gcc (GCC) 8.3.1 20191121 (Red Hat 8.3.1-5), 64-bit
(1 row)
```

I also verified by getting a terminal directly into a pod in the pgcluster via the OpenShift UI and also saw 13.2 as seen below.

![image](https://user-images.githubusercontent.com/12896721/122121592-6fb6de80-cdf1-11eb-958e-9135297b72a2.png)
