### ISSUE TITLE
Unable to set shared_preload_libraries when exporter turned on

### ISSUE THREAD

**Issue by james-callahan** [CrunchyData/postgres-operator#2526]
## Overview

When monitoring/the metric exporter is turned on, then `shared_preload_libraries` gets hard coded to `pg_stat_statements,pgnodemx`

```
  monitoring:
    pgmonitor:
      exporter:
        image: registry.developers.crunchydata.com/crunchydata/crunchy-postgres-exporter:ubi8-5.0.0-0
```

## Environment

Please provide the following details:

- Platform: EKS
- Platform Version: 5.0.0
- PGO Image Tag: ubi8-5.0.0-0
- Postgres Version 13

## Steps to Reproduce

Create a PostgresCluster with e.g.:
```yaml
apiVersion: postgres-operator.crunchydata.com/v1beta1
kind: PostgresCluster
metadata:
  name: horse
spec:
  image: registry.developers.crunchydata.com/crunchydata/crunchy-postgres-ha:centos8-13.3-4.7.0
  postgresVersion: 13
  patroni:
    dynamicConfiguration:
      postgresql:
        parameters:
          shared_preload_libraries: timescaledb
  instances:
    - name: demo
      replicas: 2
      dataVolumeClaimSpec:
        accessModes:
        - "ReadWriteOnce"
        resources:
          requests:
            storage: 1Gi
  backups:
    pgbackrest:
      image: registry.developers.crunchydata.com/crunchydata/crunchy-pgbackrest:centos8-2.33-0
```

Observe that timescaledb is preloaded:
```
$ PG_CLUSTER_PRIMARY_POD=$(kubectl -o name -l postgres-operator.crunchydata.com/cluster=horse,postgres-operator.crunchydata.com/role=master)
$ kubectl exec -it ${PG_CLUSTER_PRIMARY_POD} -c database  -- patronictl show-config | grep shared_preload_libraries
    shared_preload_libraries: timescaledb
```

Now, try with this instead (adds `monitoring` section):
```yaml
apiVersion: postgres-operator.crunchydata.com/v1beta1
kind: PostgresCluster
metadata:
  name: horse
spec:
  image: registry.developers.crunchydata.com/crunchydata/crunchy-postgres-ha:centos8-13.3-4.7.0
  postgresVersion: 13
  monitoring:
    pgmonitor:
      exporter:
        image: registry.developers.crunchydata.com/crunchydata/crunchy-postgres-exporter:ubi8-5.0.0-0
  patroni:
    dynamicConfiguration:
      postgresql:
        parameters:
          shared_preload_libraries: timescaledb
  instances:
    - name: demo
      replicas: 2
      dataVolumeClaimSpec:
        accessModes:
        - "ReadWriteOnce"
        resources:
          requests:
            storage: 1Gi
  backups:
    pgbackrest:
      image: registry.developers.crunchydata.com/crunchydata/crunchy-pgbackrest:centos8-2.33-0
```

Observe that timescaledb is not loaded:
```
$ PG_CLUSTER_PRIMARY_POD=$(kubectl -o name -l postgres-operator.crunchydata.com/cluster=horse,postgres-operator.crunchydata.com/role=master)
$ kubectl exec -it ${PG_CLUSTER_PRIMARY_POD} -c database  -- patronictl show-config | grep shared_preload_libraries
    shared_preload_libraries: pg_stat_statements,pgnodemx
```

## Additional Information

Where the new value is coming from: https://github.com/CrunchyData/postgres-operator/blob/21905f0c2962e22f72aec34a9cad733e31afcdf0/internal/pgmonitor/postgres.go#L57-L69
However the old value was not available in that code; my user-provided `dynamicConfiguration` is merged here: https://github.com/CrunchyData/postgres-operator/blob/21905f0c2962e22f72aec34a9cad733e31afcdf0/internal/patroni/config.go#L224
