### ISSUE TITLE
primary db container crashes after 220k commits

### ISSUE THREAD

**Issue by stackdump** [CrunchyData/postgres-operator#256]
I'm doing a loadtest on a newly provisioned db using attached storage backed by netapp.

After I push ~ 220k events (single row inserts) - the db crashes.

I've tried tailing the log when this happens - I don't see anything useful.

Is there something specific about using non-local storage that may be causing this?

NOTE: I've repeated the same test using a single DB mounting the same storage type w/ netapp, and have been able to complete 500k w/o issue.

Also note: I've tried latest cruncy 10.x and 9.6.x containers.

Perhaps there is some db setting I need to customize?

I'm applying the db w/ this manifest Using Postgres Operator
```
[root@pgo-client /]# pgo version
pgo client version 3.0
apiserver version 3.0
```

cluster manifest (only primary no secondary db + pgpool )
```
apiVersion: cr.client-go.k8s.io/v1
kind: Pgcluster
metadata:
  clusterName: "sledger-loadtest"
  generation: 0
  labels:
    archive: "false"
    archive-timeout: "60"
    crunchy-pgpool: "true"
    crunchy_collect: "false"
    name: sledger-loadtest
    pg-cluster: sledger-loadtest
    pgpool-secret: ""
    primary: "true"
    replica: "true"
  name: sledger-loadtest
  namespace: exodus-stage
spec:
  ContainerResources:
    limitscpu: ""
    limitsmemory: ""
    requestscpu: ""
    requestsmemory: ""
  PrimaryStorage:
    accessmode: ReadWriteMany
    fsgroup: ""
    name: sledger-loadtest
    size: 500M
    storageclass: "netapp"
    storagetype: "dynamic"
    supplementalgroups: ""
  ReplicaStorage:
    accessmode: ReadWriteMany
    fsgroup: ""
    name: sledger-loadtest-replica
    size: 500M
    storageclass: "netapp"
    storagetype: "dynamic"
  backuppath: ""
  backuppvcname: ""
  ccpimagetag: centos7-9.6.9-1.8.3
  clustername: sledger-loadtest
  customconfig: ""
  database: userdb
  name: sledger-loadtest
  nodename: ""
  password: ""
  policies: ""
  port: "5432"
  primaryhost: sledger-loadtest
  primarypassword: ""
  primarysecretname: sledger-loadtest-primaryuser-secret
  replicas: "0"
  rootpassword: ""
  rootsecretname: sledger-loadtest-postgres-secret
  secretfrom: ""
  strategy: "1"
  user: testuser
  userlabels:
    archive: "false"
    archive-timeout: "60"
    crunchy-pgpool: "true"
    crunchy_collect: "false"
    pgpool-secret: ""
  usersecretname: sledger-loadtest-testuser-secret
```

**Comment by jmccormick2001** [comment]
question, are you running your SQL via the pgpool connection or to the database directly?

**Comment by jmccormick2001** [comment]
also curious as to your volume size, run 'pgo df yourclustername' and it might show the volume usage.

**Comment by stackdump** [comment]
Thx for the comments.

Using SQL against pgpool - using the testuser that is seeded by default.

Here's a sample pod I used to verify config (not to run the loadtest)
```
kind: Pod
apiVersion: v1
metadata:
  name: psql-client
spec:
  containers:
    - name: psql-client
      image: postgres:10
      imagePullPolicy: IfNotPresent
      command: [ "/bin/bash", "-c", "--" ]
      args: [ "while true; do sleep 30; done;" ]
      env:
        - name: PGHOST
          value: sledger-cluster-pgpool
        - name: PGDATABASE
          value: userdb
        - name: PGUSER
          valueFrom:
            secretKeyRef:
              name: sledger-cluster-testuser-secret
              key: username
        - name: PGPASSWORD
          valueFrom:
            secretKeyRef:
              name: sledger-cluster-testuser-secret
              key: password
```

As to your second question : I'll repeat my test to get a confirmation on the volume size
