### ISSUE TITLE
No way to specify `--repo-s3-uri-style` anymore in v5

### ISSUE THREAD

**Issue by zerkms** [CrunchyData/postgres-operator#2561]
## Overview

I guess it was available in 4.x but I cannot see how to configure it in v5

https://github.com/CrunchyData/postgres-operator/blob/deecd9eca0e2340f53ddf92c5c2ed514cc9b78cb/internal/pgbackrest/config.go#L373-L378

## Environment

Please provide the following details:

- Platform: (`Kubernetes`, `OpenShift`, `Rancher`, `GKE`, `EKS`, `AKS` etc.) k8s baremetal
- Platform Version: (e.g. `1.20.3`, `4.7.0`) 1.20.6
- PGO Image Tag: (e.g. `ubi8-5.0.0-0`)  `ubi8-5.0.0-0`
- Postgres Version (e.g. `13`) 13.3
- Storage: (e.g. `hostpath`, `nfs`, or the name of your storage class) ceph

### REPRO

Provide steps to get to the error condition:

1. Run `...`
1. Do `...`
1. Try `...`

### EXPECTED

1. Provide the behavior that you expected.

### ACTUAL

1. Describe what actually happens

## Logs

Please provided appropriate log output or any configuration files that may help troubleshoot the issue. **DO NOT** include sensitive information, such as passwords.

## Additional Information

Please provide any additional information that may be helpful.

**Comment by andrewlecuyer** [comment]
Using the custom configuration fields available in the spec, it is possible to further customize any pgBackRest `repo` defined within the spec.  This includes the ability to customize the `repo1-s3-uri-style` setting as needed.

For instance, using the `global` field in the `pgBackRest` section of the spec, you can configure this setting (in addition to any other pgBackRest [configuration settings](https://pgbackrest.org/configuration.html)) as follows:

```yaml
spec:
  backups:
    pgbackrest:
      global:
        repo1-s3-uri-style: path
```

Alternatively, you could include this setting in any custom pgBackRest configuration created using a ConfigMap or Secret.  E.g. I could add this setting to a ConfigMap called `pgbackrest-custom-config`:

```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: pgbackrest-custom-config
data:
  custom.conf: |
    [db]
    repo1-s3-uri-style=path
```

...which can then be configured in the spec as follows:

```yaml
spec:
  pgbackrest:
    configuration:
    - configMap:
        name: pgbackrest-custom-config
```

And when defining the setting, please ensure the `repo` prefix matches the name of the repo being configured within the spec (e.g.`repo1`, `repo2`, etc.).
