### ISSUE TITLE
How to add PGO exporter custom config (queries.yml)?

### ISSUE THREAD

**Issue by sunofsparda** [CrunchyData/postgres-operator#2571]
Hello colleagues,

In our setup we want add several custom queries to exporter.
Documentation says:
_

> Custom queries to collect metrics can be specified by the user. By mounting a queries.yml file to /conf on the container, additional metrics can be specified for the API to collect. For an example of a queries.yml file, see here

_

I assume editing _deployment_ or _pod_ yaml makes no sense.
How exactly should I add my configmap with queries.yml to exporter container in PGO? Should I edit _pgclusters.crunchydata.com_ CRD of my running postgres cluster? 

Please advise.

**Comment by sunofsparda** [comment]
As a workaround I built custom exporter image..
`FROM registry.developers.crunchydata.com/crunchydata/crunchy-postgres-exporter:centos8-4.6.2
ADD queries.yml /conf/queries.yml`

**Comment by jkatz** [comment]
What queries are you trying to add?

**Comment by sunofsparda** [comment]
Hello @jkatz 
We want to add:
1) Top waits
2) Top waits events
```yml
###

#

# Begin File: pg_stat_activity.yml

#

###



# Gathers all metrics for per query monitoring. WARNING: This can greatly affect Prometheus storage and performance

ccp_pg_stat_activity:

  query: "SELECT

                a.state as state,

                a.wait_event as wait_event,

                a.wait_event_type as wait_event_type,

                count(*) wait_event_count

                FROM public.pg_stat_activity a

                group by 1,2,3"

  metrics:

    - state:

        usage: "LABEL"

        description: "Current overall state of this backend"

    - wait_event:

        usage: "LABEL"

        description: "Wait event name if backend is currently waiting, otherwise NULL"

    - wait_event_type:

        usage: "LABEL"

        description: "The type of event for which the backend is waiting, if any; otherwise NULL"

    - wait_event_count:

        usage: "GAUGE"

        description: "Count of wait_event with state"



ccp_pg_stat_activity_event_type:

  query: "SELECT

                a.wait_event_type as wait_event_type,

                count(*) wait_event_count

                FROM public.pg_stat_activity a

                group by 1"

  metrics:

    - state:

        usage: "LABEL"

        description: "Current overall state of this backend"

    - wait_event:

        usage: "LABEL"

        description: "Wait event name if backend is currently waiting, otherwise NULL"

    - wait_event_type:

        usage: "LABEL"

        description: "The type of event for which the backend is waiting, if any; otherwise NULL"

    - wait_event_count:

        usage: "GAUGE"

        description: "Count of wait_event"

    



###

#

# End File: pg_stat_activity.yml

#

###
```

3) Top SQL   
 from [queries_pg_stat_statements_full_pg13.yml](https://github.com/CrunchyData/pgmonitor/blob/master/exporter/postgres/queries_pg_stat_statements_full_pg13.yml) and 

```yml
###

#

# Begin File: queries_pg_stat_statements_full_pg13.yml

#

###



# Gathers all metrics for per query monitoring. WARNING: This can greatly affect Prometheus storage and performance

ccp_pg_stat_statements:

  query: "SELECT

                pg_get_userbyid(s.userid) as role,

                d.datname AS dbname,

                s.queryid,

                btrim(replace(left(s.query, 40), '\n', '')) AS query,

                s.plans,

                s.total_plan_time AS total_plan_time_ms,

                s.min_plan_time AS min_plan_time_ms,

                s.max_plan_time AS max_plan_time_ms,

                s.mean_plan_time AS mean_plan_time_ms,

                s.stddev_plan_time AS stddev_plan_time_ms,

                s.calls,

                s.total_exec_time AS total_exec_time_ms,

                s.min_exec_time AS min_exec_time_ms,

                s.max_exec_time AS max_exec_time_ms,

                s.mean_exec_time AS mean_exec_time_ms,

                s.stddev_exec_time AS stddev_exec_time_ms,

                s.rows,

                s.shared_blks_hit,

                s.shared_blks_read,

                s.shared_blks_dirtied,

                s.shared_blks_written,

                s.local_blks_hit,

                s.local_blks_read,

                s.local_blks_dirtied,

                s.local_blks_written,

                s.temp_blks_read,

                s.temp_blks_written,

                s.blk_read_time AS blk_read_time_ms,

                s.blk_write_time AS blk_write_time_ms,

                s.wal_records,

                s.wal_fpi,

                s.wal_bytes

            FROM public.pg_stat_statements s

            JOIN pg_catalog.pg_database d

            ON d.oid = s.dbid"

  metrics:

    - role:

        usage: "LABEL"

        description: "Role that executed the statement"

    - dbname:

        usage: "LABEL"

        description: "Database in which the statement was executed"

    - queryid:

        usage: "LABEL"

        description: "Internal hash code, computed from the statement's parse tree"

    - query:

        usage: "LABEL"

        description: "First 40 characters of query text"

    - plans:

        usage: "GAUGE"

        description: "Number of times the statement was planned (if pg_stat_statements.track_planning is enabled, otherwise zero)"

    - total_plan_time_ms:

        usage: "GAUGE"

        description: "Total time spent planning the statement, in milliseconds (if pg_stat_statements.track_planning is enabled, otherwise zero)"

    - min_plan_time_ms:

        usage: "GAUGE"

        description: "Minimum time spent planning the statement, in milliseconds (if pg_stat_statements.track_planning is enabled, otherwise zero)"

    - max_plan_time_ms:

        usage: "GAUGE"

        description: "Maximum time spent planning the statement, in milliseconds (if pg_stat_statements.track_planning is enabled, otherwise zero)"

    - mean_plan_time_ms:

        usage: "GAUGE"

        description: "Mean time spent planning the statement, in milliseconds (if pg_stat_statements.track_planning is enabled, otherwise zero)"

    - stddev_plan_time_ms:

        usage: "GAUGE"

        description: "Population standard deviation of time spent planning the statement, in milliseconds (if pg_stat_statements.track_planning is enabled, otherwise zero)"

    - calls:

        usage: "GAUGE"

        description: "Number of times executed"

    - total_exec_time_ms:

        usage: "GAUGE"

        description: "Total time spent in the statement, in milliseconds"

    - min_exec_time_ms:

        usage: "GAUGE"

        description: "Minimum time spent in the statement, in milliseconds"

    - max_exec_time_ms:

        usage: "GAUGE"

        description: "Maximum time spent in the statement, in milliseconds"

    - mean_exec_time_ms:

        usage: "GAUGE"

        description: "Mean time spent in the statement, in milliseconds"

    - stddev_exec_time_ms:

        usage: "GAUGE"

        description: "Population standard deviation of time spent in the statement, in milliseconds"

    - rows:

        usage: "GAUGE"

        description: "Total number of rows retrieved or affected by the statement"

    - shared_blks_hit:

        usage: "GAUGE"

        description: "Total number of shared block cache hits by the statement"

    - shared_blks_read:

        usage: "GAUGE"

        description: "Total number of shared blocks read by the statement"

    - shared_blks_dirtied:

        usage: "GAUGE"

        description: "Total number of shared blocks dirtied by the statement"

    - shared_blks_written:

        usage: "GAUGE"

        description: "Total number of shared blocks written by the statement"

    - local_blks_hit:

        usage: "GAUGE"

        description: "Total number of local block cache hits by the statement"

    - local_blks_read:

        usage: "GAUGE"

        description: "Total number of local blocks read by the statement"

    - local_blks_dirtied:

        usage: "GAUGE"

        description: "Total number of local blocks dirtied by the statement"

    - local_blks_written:

        usage: "GAUGE"

        description: "Total number of local blocks written by the statement"

    - temp_blks_read:

        usage: "GAUGE"

        description: "Total number of temp blocks read by the statement"

    - temp_blks_written:

        usage: "GAUGE"

        description: "Total number of temp blocks written by the statement"

    - blk_read_time_ms:

        usage: "GAUGE"

        description: "Total time the statement spent reading blocks, in milliseconds (if track_io_timing is enabled, otherwise zero)"

    - blk_write_time_ms:

        usage: "GAUGE"

        description: "Total time the statement spent writing blocks, in milliseconds (if track_io_timing is enabled, otherwise zero)"

    - wal_records:

        usage: "GAUGE"

        description: "Total number of WAL records generated by the statement"

    - wal_fpi:

        usage: "GAUGE"

        description: "Total number of WAL full page images generated by the statement"

    - wal_bytes:

        usage: "GAUGE"

        description: "Total amount of WAL bytes generated by the statement"

        

ccp_pg_stat_statements_top_temp_blks_written:

  query: "SELECT pg_get_userbyid(s.userid) as role,

              d.datname AS dbname,

              s.queryid,

              btrim(replace(left(s.query, 40), '\n', '')) AS query,

              temp_blks_written AS temp_blks_written

          FROM public.pg_stat_statements s

          JOIN pg_catalog.pg_database d

          ON d.oid = s.dbid

          GROUP BY 1,2,3,4

          ORDER BY 5 DESC

          LIMIT #PG_STAT_STATEMENTS_LIMIT#"

  metrics:

    - role:

        usage: "LABEL"

        description: "Role that executed the statement"

    - dbname:

        usage: "LABEL"

        description: "Database in which the statement was executed"

    - queryid:

        usage: "LABEL"

        description: "Internal hash code, computed from the statement's parse tree"

    - query:

        usage: "LABEL"

        description: "First 40 characters of query text"

    - temp_blks_written:

        usage: "GAUGE"

        description: "Total number of temp blocks written by the statement"



###

#

# End File: queries_pg_stat_statements_full_pg13.yml

#

###
```

**Comment by sunofsparda** [comment]
After baking exporter image with custom queries.yml faced an issue..
```
time="2021-07-29T14:17:10Z" level=error msg="queryNamespaceMappings returned 3 errors" source="postgres_exporter.go:1474" 

time="2021-07-29T14:18:10Z" level=info msg="Error running query on database \"127.0.0.1:5432\": ccp_pg_stat_statements_top_temp_blks_written pq: column \"s.temp_blks_written\" must appear in the GROUP BY clause or be used in an aggregate function" source="postgres_exporter.go:1356" 

time="2021-07-29T14:18:10Z" level=info msg="Error running query on database \"127.0.0.1:5432\": ccp_pg_stat_activity_event_type pq: relation \"public.pg_stat_activity\" does not exist" source="postgres_exporter.go:1356" 

time="2021-07-29T14:18:10Z" level=info msg="Error running query on database \"127.0.0.1:5432\": ccp_pg_stat_activity pq: relation \"public.pg_stat_activity\" does not exist" source="postgres_exporter.go:1356"
```

Don't understand why faced this `\"public.pg_stat_activity\" does not exist" source="postgres_exporter.go:1356"`.
Also I looked into exporter `start.sh` script and saw that it generates `/tmp/queries.yml` if there is no custom config. [queries_pg_stat_statements_pg13.yml](https://github.com/CrunchyData/pgmonitor/blob/master/exporter/postgres/queries_pg_stat_statements_pg13.yml) is one of source configs, and there is `public.pg_stat_activity`, so why it works..

I might did something wrong... not a Postgres expert, just a novice user..

**Comment by sunofsparda** [comment]
1) `\"public.pg_stat_activity\" does not exist` fixed by removing `public.` from `FROM public.pg_stat_activity`
```yaml
###
#
# Begin File: pg_stat_activity.yml
#
###

# Gathers all metrics for per query monitoring. WARNING: This can greatly affect Prometheus storage and performance
ccp_pg_stat_activity:
  query: "SELECT
                a.state as state,
                a.wait_event as wait_event,
                a.wait_event_type as wait_event_type,
                count(*) wait_event_count
                FROM pg_stat_activity a
                group by 1,2,3"
  metrics:
    - state:
        usage: "LABEL"
        description: "Current overall state of this backend"
    - wait_event:
        usage: "LABEL"
        description: "Wait event name if backend is currently waiting, otherwise NULL"
    - wait_event_type:
        usage: "LABEL"
        description: "The type of event for which the backend is waiting, if any; otherwise NULL"
    - wait_event_count:
        usage: "GAUGE"
        description: "Count of wait_event with state"

ccp_pg_stat_activity_event_type:
  query: "SELECT
                a.wait_event_type as wait_event_type,
                count(*) wait_event_count
                FROM pg_stat_activity a
                group by 1"
  metrics:
    - state:
        usage: "LABEL"
        description: "Current overall state of this backend"
    - wait_event:
        usage: "LABEL"
        description: "Wait event name if backend is currently waiting, otherwise NULL"
    - wait_event_type:
        usage: "LABEL"
        description: "The type of event for which the backend is waiting, if any; otherwise NULL"
    - wait_event_count:
        usage: "GAUGE"
        description: "Count of wait_event"


###
#
# End File: pg_stat_activity.yml
#
###
```
2) `\"s.temp_blks_written\" must appear in the GROUP BY clause or be used in an aggregate function` fixed by removing `GROUP BY 1,2,3,4`
