### ISSUE TITLE
How to configure PgBouncer credentials

### ISSUE THREAD

**Issue by sasadangelo** [CrunchyData/postgres-operator#2594]
Hi,

I followed the tutorial in [postgres-operator example](https://github.com/CrunchyData/postgres-operator-examples). I successfully create a cluster of three nodes for DB Hippo (your tutorial).

```
apiVersion: postgres-operator.crunchydata.com/v1beta1
kind: PostgresCluster
metadata:
  name: hippo
spec:
  image: registry.developers.crunchydata.com/crunchydata/crunchy-postgres-ha:centos8-13.3-0
  postgresVersion: 13
  instances:
    - name: instance1
      replicas: 3
      dataVolumeClaimSpec:
        accessModes:
        - "ReadWriteOnce"
        resources:
          requests:
            storage: 1Gi
        storageClassName: "local-storage"
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - topologyKey: kubernetes.io/hostname
            labelSelector:
              matchLabels:
                postgres-operator.crunchydata.com/cluster: hippo
                postgres-operator.crunchydata.com/instance-set: instance1
  backups:
    pgbackrest:
      image: registry.developers.crunchydata.com/crunchydata/crunchy-pgbackrest:centos8-2.33-0
      repoHost:
        dedicated: {}
      repos:
      - name: repo1
        volume:
          volumeClaimSpec:
            accessModes:
            - "ReadWriteOnce"
            resources:
              requests:
                storage: 2Gi
            storageClassName: "local-storage"
```

Then I decided to configure PgBouncer in front of my cluster using these options:

```
  proxy:
    pgBouncer:
      image: registry.developers.crunchydata.com/crunchydata/crunchy-pgbouncer:centos8-1.15-0
      replicas: 2
      config:
        global:
          pool_mode: session
          server_reset_query: DISCARD ALL
          server_check_delay: "60"
          auth_type: md5
          auth_file: /etc/pgbouncer/users.txt
          tcp_keepalive: "1"
          tcp_keepcnt: "10"
          tcp_keepidle: "12"
          tcp_keepintvl: "2"
          ignore_startup_parameters: extra_float_digits
          log_connections: "0"
          log_disconnections: "0"
          log_pooler_errors: "1"
          verbose: "1"
          server_connect_timeout: "10"
          listen_port: "5432"
          listen_addr: 0.0.0.0
          admin_users: "hippo"
          stats_users: "hippo"
          min_pool_size: "25"
          max_client_conn: "41"
        databases:
          'hippo': pool_size=100 reserve_pool=0 pool_mode=session port=5432 user=hippo host=hippo-primary.postgres-operator.svc.cluster.local
        files:
          - configMap:
              name: pgbouncer-users
              items:
                - key: users.txt
                  path: users.txt
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 1
            podAffinityTerm:
              topologyKey: kubernetes.io/hostname
              labelSelector:
                matchLabels:
                  postgres-operator.crunchydata.com/cluster: hippo-ha
                  postgres-operator.crunchydata.com/role: pgbouncer
```

As you can see the PgBouncer credentials are configured in the following ConfigMap:

```
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: postgres-operator
  name: pgbouncer-users
data:
  users.txt: |
    "hippo": "md5WVFuTD04P2xFfU9nKjxySWtJMGk/LHp7K2hpcHBv"
```

My problem is that the PostgreSQL credentials in ```hippo-pguser``` are regenerated at each deployment with the command: ```kubectl apply -k kustomize/prostgres```. So I need a way to put these newly generated credentials in my config map that will be read by PgBouncer Pod. The documentation doesn't explain clearly how to do that or at least I wasn't able to understand it.
Anyone can help?
