### ISSUE TITLE
Backrest S3 integration

### ISSUE THREAD

**Issue by aceeric** [CrunchyData/postgres-operator#2603]
Currently (as of release 4.7.0), to declaratively integrate backrest with S3, you specify literals in the Pgcluster resource. E.g.:
```
...
spec:
  backrestS3Bucket: my-bucket
  backrestS3Endpoint: minio.my-namespace.svc.cluster.local
...
```
Additionally, you configure the `aws-s3-ca.crt` key in your cluster `...backrest-repo-config` secret. When binding to dynamic provisioners like Minio, this introduces the requirement to create "glue" jobs that wait for Minio to complete its initialization, then read elements of the Minio `ConfigMap`s and `Secret`s and patch them into Crunchy resources.

It would be much easier for the integrator if the `Pgcluster` CR supported environment variable style initializers for all S3 integration elements. E.g.:
```
...
spec:
  backrestS3Bucket:
    valueFrom:
      configMapKeyRef:
        name: minio-config
        key: MINIO_BUCKET
  backrestS3Endpoint
    valueFrom:
      configMapKeyRef:
        name: minio-config
        key: MINIO_ENDPOINT
  backrestS3Ca:
    valueFrom:
      secretKeyRef:
        name: my-minio-ca-secret
        key: ca.crt
...
```
Then, as the Postgres operator is reconciling the `Pgcluster` resource if it can't resolve the referenced resource(s), it just logs and tries again in the next reconciliation loop. Once Minio completes its initialization, everything else just flows.
