### ISSUE TITLE
FATA[0000] failed to set up TLS client: client certificate/key loading: tls: failed to find any PEM data in certificate input

### ISSUE THREAD

**Issue by giovannicandido** [CrunchyData/postgres-operator#2628]
Setup pgo client in windows bash environment with https://access.crunchydata.com/documentation/postgres-operator/4.7.2/installation/postgres-operator/ and setup script

But when running pgo version I get the error
```
FATA[0000] failed to set up TLS client: client certificate/key loading: tls: failed to find any PEM data in certificate input
```

I export the service to a nodeport service using the yaml file:

```
piVersion: v1
kind: Service
metadata:
  namespace: pgo
  name: postgres-operator-nodeport
spec:
  type: NodePort
  selector:
    name: postgres-operator
  ports:
  - protocol: TCP
    port: 8443
    targetPort: 8443
```
And update env variable to point to the server:

export PGO_APISERVER_URL="https://xx.xxx.xxx.xx:xxxxx/"
