### ISSUE TITLE
PVC not bound to PV as PVC name was generated dynamically

### ISSUE THREAD

**Issue by sathishc58** [CrunchyData/postgres-operator#2649]
I installed `postgres operator` and `postgres cluster` by executing the following commands on CentOS 7 (bare-metal)

**Commands**

```
[root@re-ctrl01 postgres-operator-examples]# kubectl apply -k kustomize/install/
[root@re-ctrl01 postgres-operator-examples]# kubectl apply -k kustomize/postgres/
```

**Output of Pods**

```
[root@re-ctrl01 postgres-operator-examples]# kubectl get all -n postgres-operator
NAME                         READY   STATUS    RESTARTS   AGE
pod/hippo-instance1-pxld-0   0/3     Pending   0          3m35s
pod/hippo-repo-host-0        1/1     Running   0          3m35s
pod/pgo-54ff6dc755-j5gn9     1/1     Running   0          3m51s
```

**Output of PVCs**

```
[root@re-devk8s-control01 postgres-operator-examples]# kubectl get pvc -n postgres-operator
NAME                          STATUS    VOLUME     CAPACITY   ACCESS MODES   STORAGECLASS    AGE
hippo-instance1-pxld-pgdata   Pending                                                        4m57s
hippo-repo1                   Bound     hippo-pv   1Gi        RWO                            4m57s
```

I manually provisioned PV for pods 'hippo-repo' and  'hippo-instance1-*-pgdata'. 

However, PVC was not able bound to PV for 'hippo-instance1-**pxld**-pgdata' as the name of the PVC was **NOT** fixed.  Hence I am **NOT** able to mention to name of the PVC while provisioning PV

**PVC Definition**

```
apiVersion: v1
kind: PersistentVolume
metadata:
  name: hippo-instance1
  namespace: postgres-operator
  labels:
    type: local
spec:
  storageClassName: local-storage
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  claimRef:
    namespace: postgres-operator
    name: hippo-instance1-*-pgdata  --->  UNABLE TO PROVIDE A NAME AS THE CHARS ARE RANDOMLY GENERATED FOR '*'
  hostPath:
    path: "/mnt/data2"
```

Kindly let me know how to override this behavior
