### ISSUE TITLE
pgbouncer-config contatiner OOMKilled

### ISSUE THREAD

**Issue by momoadc** [CrunchyData/postgres-operator#2673]
Please ensure you do the following when reporting a bug:

- [x] Provide a concise description of what the bug is.
- [x] Provide information about your environment.
- [ ] Provide clear steps to reproduce the bug.
- [ ] Attach applicable logs. Please do not attach screenshots showing logs unless you are unable to copy and paste the log data.
- [ ] Ensure any code / output examples are [properly formatted](https://docs.github.com/en/github/writing-on-github/basic-writing-and-formatting-syntax#quoting-code) for legibility.

Note that some logs needed to troubleshoot may be found in the `/pgdata/<CLUSTERNAME>/pg_log` directory on your Postgres instance.

An incomplete bug report can lead to delays in resolving the issue or the closing of a ticket, so please be as detailed as possible.

If you are looking for [general support](https://access.crunchydata.com/documentation/postgres-operator/latest/support/), please view the [support](https://access.crunchydata.com/documentation/postgres-operator/latest/support/) page for where you can ask questions.

Thanks for reporting the issue, we're looking forward to helping you!

## Overview

Im running the PostgresCluster with resource requests and limits for the main components.
I noticed that the pgbouncer pod entring CrashLoopBack state every once in a while. 
While I digged deeper I noticed that the pgbouncer-config is OOMKilled. 
I configured resources for the pgbouncer pod but the resources for the pgboucner-config container are hardcoded.
Am i missing the configuration from the CRD or is it reallly hardcoded?
Apache Airflow is connected to the database using pgbouncer. There are less than 20 connections while the application is idle but the pgboucner-config is still receiving OOMKilled

## Environment

Please provide the following details:

- Platform: OpenShift
- Platform Version:  4.6.5
- PGO Image Tag: ubi-5.0.1-0
- Postgres Version: 13
- Storage: isilon storageclass

### REPRO

Provide steps to get to the error condition:

1. I created a Helm Chart to allow adding more features to the CR
2. I deployed the Chart with resources limits and requests under a namespace with ResourceQuota.
3. I connected Apache Airflow to the PostgresCluster using the pgbouncer URI
4. After some time, the pgbouncer-config container restarts due to OOMKilled

## Logs

I cannot add logs since I work in a restricted network.

**Comment by jkatz** [comment]
> I created a Helm Chart to allow adding more features to the CR

Can you provide the Helm chart? If you're "adding more features" that adds a major variable into trying to determine what's going on.

The lack of logs also will make this a bit trickier to assess.

**Comment by noamendel** [comment]
I can send the generated PostgresCluster manifest.

**Comment by noamendel** [comment]
I found out that if you define resources for the pgBouncer container the pgbouncer-config container will be defined with hardcoded resources
https://github.com/CrunchyData/postgres-operator/blob/b284ed4ee4e51bf009ed1060315baefadcb66811/internal/pgbouncer/reconcile.go#L205
When I monitored the pgBouncer pod I witnessed that the pgbouncer-config container have memory peaks of ~50Mi and therefore receives OOMKilled
Is it possible to allow customizable resources for the pgbouncer-config as well?

**Comment by cbandy** [comment]
Thank you for the report. I saw similar behavior in the past with a different version of the container command. The amount of memory required varies depending on the container runtime. We're considering how to expose the details of this sidecar in the spec.

I'd like to investigate this further with you if you're able. I'm curious how much memory is ultimately required in your environment.

The following patch to your PgBouncer deployment adds another sidecar with a different command. This one should require less memory and you can adjust the limit to find a suitable value for your runtime. Be sure to match the image to the one already in the deployment. What memory usage do you see and what limit eliminates restarts?

```bash
# add sidecar
oc patch deploy/mycluster1-pgbouncer -p "$(cat pgbouncer.yaml)"

# remove sidecar
oc patch deploy/mycluster1-pgbouncer -p '{"spec":{"template":{"spec":{"containers":[{"$patch":"delete","name":"pgbouncer-config-builtin"}]}}}}'
```

```yaml
spec:
  template:
    spec:
      containers:
      - name: pgbouncer-config-builtin
        image: registry.developers.crunchydata.com/crunchydata/crunchy-pgbouncer:centos8-1.15-1  # adjust image
        resources:
          limits: { cpu: 5m, memory: 16Mi }  # adjust resources
        command:
        - bash
        - -ceu
        - --
        - |-
          monitor() {
          exec {fd}<> <(:)
          while read -t 5 -u "${fd}" || true; do
            if [ "${directory}" -nt "/proc/self/fd/${fd}" ] && pkill --signal HUP --exact pgbouncer
            then
              exec {fd}>&- && exec {fd}<> <(:)
              stat --format='Loaded configuration dated %y' "${directory}"
            fi
          done
          }; export directory="$1"; export -f monitor; exec -a "$0" bash -ceu monitor
        - pgbouncer-config
        - /etc/pgbouncer
        securityContext:
          allowPrivilegeEscalation: false
          privileged: false
          readOnlyRootFilesystem: true
          runAsNonRoot: true
        volumeMounts:
        - { mountPath: /etc/pgbouncer, name: pgbouncer-config, readOnly: true }
```
