### ISSUE TITLE
Scheduled backup at cluster creation

### ISSUE THREAD

**Issue by boris-lenzinger** [CrunchyData/postgres-operator#2677]
**Description of the feature**

I have read in the documentation in version 5.0.0 that there is the possibility to create schedules for backup when creating the cluster (https://access.crunchydata.com/documentation/postgres-operator/5.0.0/tutorial/backup-management).

**Question about this feature**
Is this feature available in previous version under a different format ? I have tried with the syntax explained in the 5.0.0 documentation with 4.7.1 but I could not get it work.

If not available, how should I configure a scheduled backup using yaml ? In PGO code, one can read that PGO has a command to create a schedule that makes a call to the apiserver of PGO. This call creates a config map with labels. I have tried to create a schedule with the following yaml but it failed. Could you explain what is missing in this example ?

```yaml
apiVersion: v1
data:
  cluster-pgbackrest-full: '{"version":"v1","name":"cluster-pgbackrest-full","cluster":"cluster","schedule":"*/1
    * * * *","namespace":"pgclusters","type":"pgbackrest","pgbackrest":{"label":"pg-cluster=cluster,name=cluster,deployment-name=cluster","container":"database","type":"full","storageType":"s3","options":"--repo1-retention-full=3"},"policy":{}}'
kind: ConfigMap
metadata:
  labels:
    crunchy-scheduler: "true"
    pg-cluster: cluster
  name: cluster-pgbackrest-full
  namespace: pgclusters
```
