### ISSUE TITLE
Setup logical replication using operator v5

### ISSUE THREAD

**Issue by honne23** [CrunchyData/postgres-operator#2681]
I've been trying to setup permissions for `logical replication` in operator v5 and I can't seem to do so.  I'm running a custom `registry.developers.crunchydata.com/crunchydata/crunchy-postgres-ha:centos8-13.4-0` dockerfile that I've edited to run the `timescaledb` extension.

I've tried two methods to enable logical replication; one by editing `/opt/crunchy/conf/postgres-ha/pg_hba.conf` directly, and another by replacing /opt/crunchy/conf/postgres-ha/postgres-ha-pghba-bootstrap.yaml with my own file. Neither seem to be working as I keep getting the following error from my client: 

```
level=error msg="no slotName provided" error="FATAL: no pg_hba.conf entry for replication connection from host \"10.20.0.75\", user \"postgres\", SSL off (SQLSTATE 28000)"
```
I've been unable to set it up correctly so far, could someone please point me where I'm going wrong?

This is my dockerfile:
```Dockerfile
FROM registry.developers.crunchydata.com/crunchydata/crunchy-postgres-ha:centos8-13.4-0

USER root

RUN curl -sSL -o /etc/yum.repos.d/timescale_timescaledb.repo "https://packagecloud.io/install/repositories/timescale/timescaledb/config_file.repo?os=el&dist=8" && \
    yum --disablerepo=crunchypg13 update -y && \
    yum --disablerepo=crunchypg13 install -y timescaledb-2-postgresql-13 && \
    yum clean all

COPY schema.sql .
RUN ls /opt/crunchy/bin/postgres-ha/sql/
RUN sed -i '/shared_preload_libraries:/ s/$/,timescaledb/' /opt/crunchy/conf/postgres-ha/postgres-ha-initdb.yaml && \
    sed -i '/\\c "\${PGHA_DATABASE}"$/a CREATE EXTENSION IF NOT EXISTS timescaledb CASCADE;' /opt/crunchy/bin/postgres-ha/sql/setup.sql && \
    sed -i '/SET application_name="container_setup";$/a CREATE EXTENSION IF NOT EXISTS timescaledb CASCADE;' /opt/crunchy/bin/postgres-ha/sql/setup.sql && \
    cat schema.sql >> /opt/crunchy/bin/postgres-ha/sql/setup.sql && \
    echo "host    replication     all             0.0.0.0/0            trust" >> /opt/crunchy/conf/postgres-ha/pg_hba.conf
RUN rm /opt/crunchy/conf/postgres-ha/postgres-ha-pghba-bootstrap.yaml
COPY postgres-ha-pghba-bootstrap.yaml /opt/crunchy/conf/postgres-ha/
USER 26
```

My `postgres-ha-pghba-bootstrap.yaml`
```yaml
---
postgresql:
  pg_hba:
    - local all postgres peer
    - host replication postgres 0.0.0.0/0 trust
```

**Comment by honne23** [comment]
@jkatz if it was possible I would really love to see how to do via the custom resource, or point me to the custom resource docs, you would really be saving my bacon!

**Comment by honne23** [comment]
@jkatz After further investigation, it seems this feature was added in `5.1.0` whereas the operator example repo is only up to date with `v5.0.0`

**Comment by jkatz** [comment]
The examples repo is up to 5.0.2. Both Timescale and the ability to use logical replication are [available in 5.0.0](https://access.crunchydata.com/documentation/postgres-operator/v5/references/components/) and beyond. I was able to get logical replication running locally on my copy of 5.0.2 and have been in the process of preparing documentation.

If you need immediate [support](https://access.crunchydata.com/documentation/postgres-operator/v5/support/) please refer to the [support](https://access.crunchydata.com/documentation/postgres-operator/v5/support/) page.

**Comment by honne23** [comment]
@jkatz I've just tried applying host replication params by following [this related thread](https://github.com/CrunchyData/postgres-operator/issues/1193) and finding [this document](https://access.crunchydata.com/documentation/postgres-operator/5.0.1/tutorial/customize-cluster/) and I am still receiving errors when trying to create a replication connection:

```yaml
apiVersion: postgres-operator.crunchydata.com/v1beta1
kind: PostgresCluster
metadata:
  name: my-db
  namespace: postgres-operator
spec:
  image: eu.gcr.io/<my-db>/timescale-custom:v38
  postgresVersion: 13
  users:
    - name: postgres
    - name: pgdelta
      databases:
        - mydb
      options: "SUPERUSER"
  instances:
    - name: instance1
      replicas: 3
      dataVolumeClaimSpec:
        accessModes:
          - "ReadWriteOnce"
        resources:
          requests:
            storage: 100Gi
  patroni:
    dynamicConfiguration:
      postgresql:
        parameters:
          wal_level: logical
        pg_hba:
          - host replication postgres 0.0.0.0/0 trust
  backups:
    pgbackrest:
      image: registry.developers.crunchydata.com/crunchydata/crunchy-pgbackrest:centos8-2.33-2
      repoHost:
        dedicated: {}
      repos:
        - name: repo1
          volume:
            volumeClaimSpec:
              accessModes:
                - "ReadWriteOnce"
              resources:
                requests:
                  storage: 300Gi
```
