### ISSUE TITLE
Operator 5.0.2 / Backrest / Minio S3 / TLS

### ISSUE THREAD

**Issue by aceeric** [CrunchyData/postgres-operator#2685]
I'm integrating PGBackRest via the 5.0.2 operator with S3 storage managed by Minio. In this case, Minio uses a specific CA, and so the CA needs to be provided to all clients, including BackRest, so the client can negotiate the TLS handshake with Minio.

In the 4x version of the operator, we patched the CA into the `<cluster-name>-backrest-repo-config` secret. For 5.0.2, based on [this example](https://github.com/CrunchyData/postgres-operator-examples/blob/main/kustomize/s3/s3.conf.example) and [this backrest config guidance](https://pgbackrest.org/configuration.html#section-repository/option-repo-storage-ca-path) I create secret `pgo-s3-creds` as follows:
```
[global]
repo1-s3-key = MYKEY
repo1-s3-secret = MYSECRET
repo1-s3-uri-style = path
repo1-storage-ca-file = /run/secrets/kubernetes.io/serviceaccount/ca.crt
```
So I'm taking advantage of the fact that 1) Minio is using the cluster CA, and 2) the cluster CA is always mounted by Kubernetes at the above location. But if either of those assumptions were not true, I would need a way to project the S3 CA into the Crunchy cluster repo host pod. I don't believe there is a way to do this presently - at least I don't see it. If I'm correct, it might be a valuable feature to add to the `PostgresCluster` CR. Something like:

```
spec:
  backups:
    pgbackrest:
      repos:
      - name: repo1
        ca:
          valueFrom:
            secretKeyRef:
              name: my-backing-s3-secret
              key: ca.crt
```

**Comment by jkatz** [comment]
This should already be supported. You can do something like this in your Secret:

```yaml
apiVersion: v1
kind: Secret
metadata:
  name: mycoolbackrestsecret
  namespace: postgres-operator
stringData:
  mycoolbackrestsecret.conf: |
    [global]
    repo1-storage-ca-file=/etc/pgbackrest/conf.d/my-cool-ca.crt
  my-cool-ca.crt:
```

The pgBackRest Secret is mounted into the conf.d dir. If you include the CA file in it, you will just need to reference it as such.

I'll flag this as a potential example to document.
