### ISSUE TITLE
PGBouncer is not redployed after config update (v5)

### ISSUE THREAD

**Issue by ZuSe** [CrunchyData/postgres-operator#2688]
When adding additional parameters to the pgbouncer no rollout is processed.
I changed my settings (postgrecluster definiton) to ignore ssl_renegotiation_limit  (maybe consider adding it per default).

```
  proxy:
    pgBouncer:
      config:
        global:
          ignore_startup_parameters: extra_float_digits,ssl_renegotiation_limit
      image: registry.developers.crunchydata.com/crunchydata/crunchy-pgbouncer:centos8-1.15-2
      port: 5432
      replicas: 1
```

This does not seem to get applied at all, at least I don't see any rollout in the cluster.
