### ISSUE TITLE
Is it possible to switch timescaledb extension license with images of v5 ?

### ISSUE THREAD

**Issue by gjeusel** [CrunchyData/postgres-operator#2692]
Trying to modify it using patroni:
```yaml
  patroni:
    dynamicConfiguration:
      postgresql:
        parameters:
          shared_preload_libraries: timescaledb
          timescaledb.license: timescale  # instead of apache by default in crunchy
```
Result in:
```
postgres@localhost:tutorial> create extension timescaledb cascade;
could not access file "$libdir/timescaledb-tsl-2.4.0": No such file or directory
```
And indeed, this file does not exists at:
```sh
bash-4.4$ ls /usr/pgsql-13/lib/ | grep -i timescale
timescaledb-2.4.0.so
timescaledb.so
```

Would it be possible to build the docker images with this additional file ?
Even though I understand the reasons for the license to be kept as "apache" by default.

**Comment by gjeusel** [comment]
Sorry, maybe it would be more appropriate to open this issue at https://github.com/CrunchyData/crunchy-containers ?

**Comment by gjeusel** [comment]
A sample of customized dockerfile to get latest timescaledb is actually found in [another *unrelated* issue](https://github.com/CrunchyData/postgres-operator/issues/2681).

Still, the question remains, would it be possible to add the tsl file in the official image ? 🙏

**Comment by ludzzz** [comment]
Hi,
I bumped into this issue as well.
at first, I tried to use timescaledb function.
But got this error:
```
 ERROR: function "time_bucket_gapfill" is not supported under the current "apache" license
  Hint: Upgrade your license to 'timescale' to use this free community feature.
```
To fix that I found that we can do (what @gjeusel was doing in config):
```
ALTER SYSTEM SET timescaledb.license = 'timescale';
-- reload setting changes
SELECT pg_reload_conf();
```
And got the error:
```
 ERROR: could not access file "$libdir/timescaledb-tsl-2.4.0": No such file or directory
```

Same as @gjeusel Would it be possible to add that lib?

**Comment by johanjk** [comment]
The workaround refered to by gjerusel works.

Here is a complete working example:

Dockerfile:
```dockerfile
ARG VERSION
FROM registry.developers.crunchydata.com/crunchydata/crunchy-postgres-gis-ha:${VERSION}

USER root

RUN curl -sSL -o /etc/yum.repos.d/timescale_timescaledb.repo "https://packagecloud.io/install/repositories/timescale/timescaledb/config_file.repo?os=el&dist=8" && \
    yum --disablerepo=crunchypg13 update -y && \
    yum --disablerepo=crunchypg13 install -y timescaledb-2-postgresql-13 && \
    yum clean all
USER 26
# magical user used here: https://github.com/CrunchyData/crunchy-containers/blob/master/build/postgres-gis/Dockerfile
```

Build and push your dockerfile to a repository. 

Operator yaml:
```yaml
apiVersion: postgres-operator.crunchydata.com/v1beta1
kind: PostgresCluster
metadata:
  name: example-cluster
spec:
  image: {{ .Values.image }}
  imagePullSecrets:
   - name: dockersecret
  patroni:
    dynamicConfiguration:
      postgresql:
        parameters:
          shared_preload_libraries: timescaledb
          timescaledb.license: timescale  
```

`imagePullSecrets` is only required If you are using a private repository for your image.

**Comment by yash-kalwani** [comment]
@johanjk i tried using your dockerfile but it fails with the following logs

```
ERROR: MODE environment variable is not set, aborting.
```

any idea what might be going wrong

**Comment by johanjk** [comment]
I assume the log is an output from when you ran the container standalone using `docker run`, not through the crd of the operator?
In that case, see https://crunchydata.github.io/crunchy-containers/stable/container-specifications/crunchy-postgres/#running-modes to set the mode env var.

**Comment by kbmanseau** [comment]
Hello, is this something that progress might be made on? I am attempting to build a custom image as mentioned in this thread however I am hitting:

`#5 1.922 CentOS Linux 8 - AppStream                      146  B/s |  38  B     00:00    
#5 1.933 Error: Failed to download metadata for repo 'appstream': Cannot prepare internal mirrorlist: No URLs in mirrorlist`

I assume this is related to centos8 being EOL? 

@yash-kalwani were you able to build the image successfully?

**Comment by benjamin-bergia** [comment]
I am hitting the license issue too. The compression is not available with the Apache version. Honestly, without compression TS is pretty much unusable in production.

**Comment by kbmanseau** [comment]
@benjamin-bergia, I was able to get past this by building my own image. I have the following DOCKERFILE:
```
FROM registry.developers.crunchydata.com/crunchydata/crunchy-postgres:centos8-13.5-0
USER  root
RUN  curl  -sSL  -o  /etc/yum.repos.d/timescale_timescaledb.repo  "https://packagecloud.io/install/repositories/timescale/timescaledb/config_file.repo?os=el&dist=8"  &&  \
yum  --disablerepo=crunchypg13,appstream,baseos  update  -y  &&  \
yum  --disablerepo=crunchypg13,appstream,baseos  install  -y  timescaledb-2-postgresql-13  &&  \
yum  clean  all

USER  26
```

**Comment by benjamin-bergia** [comment]
Thanks a lot @kbmanseau !

I still to have some issues afterward:
```psql
 ALTER SYSTEM SET timescaledb.license = 'timescale';
ERROR:  could not access file "$libdir/timescaledb-tsl-2.5.0": No such file or directory
```

I modified the dockerfile slightly to add the promscale extension:
```dockerfile
FROM registry.developers.crunchydata.com/crunchydata/crunchy-postgres:centos8-13.5-0
USER  root
RUN  curl  -sSL  -o  /etc/yum.repos.d/timescale_timescaledb.repo  "https://packagecloud.io/install/repositories/timescale/timescaledb/config_file.repo?os=el&dist=8"  &&  \
yum  --disablerepo=crunchypg13,appstream,baseos update -y &&  \
yum  --disablerepo=crunchypg13,appstream,baseos install -y timescaledb-2-postgresql-13  &&  \
curl -sSL -O https://github.com/timescale/promscale_extension/releases/download/0.3.0/promscale_extension-0.3.0.pg13.x86_64.rpm && \
yum --disablerepo=crunchypg13,appstream,baseos localinstall -y promscale_extension-0.3.0.pg13.x86_64.rpm && \
rm promscale_extension-0.3.0.pg13.x86_64.rpm && \
yum clean all
USER 26
```

and here is my cluster config:
```yaml
  patroni:
    dynamicConfiguration:
      postgresql:
        parameters:
          shared_preload_libraries: timescaledb,promscale
          timescaledb.license: timescale
```
