### ISSUE TITLE
operator ignoring CCPImagePrefix

### ISSUE THREAD

**Issue by k1ng440** [CrunchyData/postgres-operator#270]
CCPImagePrefix is being ignored in manual deployment and downloading from crunchydata/crunchy-postgres:centos7-10.4-1.8.3

```
kd secrets apiserver-conf-secret -n pgo
Name:         apiserver-conf-secret
Namespace:    pgo
Labels:       <none>
Annotations:  <none>

Type:  Opaque

Data
====
pgo.load-template.json:   2072 bytes
pgo.lspvc-template.json:  987 bytes
pgo.yaml:                 1198 bytes
pgorole:                  472 bytes
pgouser:                  31 bytes
server.crt:               1334 bytes
server.key:               1704 bytes
```

```
Cluster:
  CCPImagePrefix:  cryptovalue
  CCPImageTag:  centos7-10.4-1.8.3
  Port:  5432
  User:  cryptovalue
  Database:  cryptovalue
  PasswordLength:  8
  Strategy:  1
  Replicas:  0
  ArchiveMode:  false
  ArchiveTimeout:  60
PrimaryStorage: storage1
BackupStorage: storage1
ReplicaStorage: storage1
Storage:
  storage1:
    StorageClass: fast
    AccessMode:  ReadWriteOnce
    Size:  100Gi
    StorageType:  create
    Fsgroup: 26
    SupplementalGroups:  65534
  storage2:
    AccessMode:  ReadWriteOnce
    Size:  333M
    StorageType:  dynamic
    StorageClass:  gluster-heketi
    Fsgroup:  26
  storage3:
    AccessMode:  ReadWriteOnce
    Size:  440M
    StorageType:  dynamic
    StorageClass:  fast
    Fsgroup:  26
DefaultContainerResource: 
ContainerResources:
  small:
    RequestsMemory:  512Mi
    RequestsCPU:  0.1
    LimitsMemory:  512Mi
    LimitsCPU:  0.1
  large:
    RequestsMemory:  2Gi
    RequestsCPU:  2.0
    LimitsMemory:  6Gi
    LimitsCPU:  4.0
Pgo:
  AutofailSleepSeconds:  9
  Audit:  true
  Metrics:  true
  LSPVCTemplate:  /config/pgo.lspvc-template.json
  LoadTemplate:  /config/pgo.load-template.json
  COImagePrefix:  crunchydata
  COImageTag:  centos7-3.1
```
