### ISSUE TITLE
Compile pgbackrest with zst support

### ISSUE THREAD

**Issue by james-callahan** [CrunchyData/postgres-operator#2706]
## Overview

Compile pgbackrest with zst support

## Use Case

Currently if you use the pgbackrest option `compress-type: "zst"` then it fails with:
> `level=info msg="stderr=[ERROR: [032]: pgBackRest not compiled with zst support\n]`

The zstandard compression is known to have the some of the best compression ratios for very reasonable encoding cost.

https://pgbackrest.org/configuration.html#section-general/option-compress-type

**Comment by clrxbl** [comment]
PostgreSQL 15.0 introduces zstd WAL compression. It would be great to have pgBackrest with zstd support alongside this.

**Comment by benjaminjb** [comment]
We made this change a little while ago, so I wanted to let you know that, as of our latest pgBackRest release, `zst` is an allowed option for compress-type. I just double-checked the pgbackrest 2.47 image to make sure, and it worked without a problem.

**Comment by KennyChenFight** [comment]
@benjaminjb I still cannot use zst and repo-block feature in `registry.developers.crunchydata.com/crunchydata/crunchy-pgbackrest:ubi8-2.47-2` image.
Am I miss something ?

**Comment by benjaminjb** [comment]
@KennyChenFight What's your spec look like?

**Comment by KennyChenFight** [comment]
@benjaminjb 

use this command `kubectl describe postgrescluster`
```yaml
Spec:
  Backups:
    Pgbackrest:
      Global:
        Process - Max:              2
        repo1-gcs-key-type:         auto
        repo1-path:                /repo1
        repo1-retention-diff:       7
        repo1-retention-full:       3
        repo1-retention-full-type:  count
        repo1-bundle:           y
        repo1-block:             y
        Compress - Type: zst
        Start - Fast:               y
```
