### ISSUE TITLE
pgo v4.7.3 - Pgpolicy not executed on cluster database when cluster created by manifest

### ISSUE THREAD

**Issue by kbelgadi** [CrunchyData/postgres-operator#2718]
Hi,

We are deploying a postgresql cluster on K3s.
We need to initialize our database by executing a schema creation and other configurations.

Everything is working well when we create a policy and a cluster using pgo client: the schema is created in our database.

But when we create the policy and the cluster using manifests and kubectl apply, the cluster and the database are created without the schema.

When we execute a `pgo apply policy` on the cluster created with manifest, the sql statement is executed and the schema is created.

It seems that the "policies" attribute in the Pgcluster yaml manifest is not processed by the operator.

Is there something wrong in our steps or manifest spec?
Is it a limitation on crunchydata postgresql-operator?

Any help would be much appreciated.

## Environment

- Platform: K3s on x86-64
- Platform Version: K3s: v1.19.7+k3s1 - PGO version: 4.7.3
- PGO Image Tag: centos8-4.7.3
- Postgres Version: centos8-13.4-4.7.2
- Storage: hostpath

## Steps to Reproduce

**The imperative way with pgo client:**

The sql statement to create the schema `prod`:
```
cat << EOF >> schema.sql
\connect my_prod_db;
CREATE SCHEMA IF NOT EXISTS prod AUTHORIZATION prodmy;
EOF
```

Create the policy:
`pgo -n pgo create policy my-prod-db-schema --in-file=schema.sql`

Create the cluster by specifying the previously created policy:
`pgo -n pgo create cluster my-prod-db --replica-count=1 --username prodmy --sync-replication --database=my_prod_db --pvc-size=1Gi  --pgbackrest-pvc-size=1Gi --policies=my-prod-db-schema`

Check database schemas:
`PGPASSWORD="blablabla" psql -h 127.0.0.1 -p 5432 -U prodmy my_prod_db -c "SELECT schema_name FROM information_schema.schemata;"`

Result: the schema `prod` has been created:
```
    schema_name     
--------------------
...
 prodmy
 prod
```

**The declarative way with kubectl apply on kubernetes manifests:**

Policy manifest:
```
cat << EOF >> pgpolicy.yaml
apiVersion: crunchydata.com/v1
kind: Pgpolicy
metadata:
  labels:
    pgouser: admin
  name: my-prod-db-schema
  namespace: pgo
spec:
  name: my-prod-db-schema
  sql: |
    \connect my_prod_db;
    CREATE SCHEMA IF NOT EXISTS prod AUTHORIZATION prodmy;
EOF
```

Cluster manifest:
```
cat << EOF >> pgcluster.yaml
apiVersion: crunchydata.com/v1
kind: Pgcluster
metadata:
  annotations:
    current-primary: my-prod-db
    primary-deployment: my-prod-db
  generation: 4
  labels:
    autofail: "true"
    crunchy-pgbadger: "false"
    crunchy-pgha-scope: my-prod-db
    deployment-name: my-prod-db
    name: my-prod-db
    pg-cluster: my-prod-db
    pgo-version: 4.7.3
    pgouser: admin
  name: my-prod-db
  namespace: pgo
spec:
  BackrestStorage:
    accessmode: ReadWriteOnce
    matchLabels: ""
    name: ""
    size: 1G
    storageclass: ""
    storagetype: dynamic
    supplementalgroups: ""
  PGAdminStorage:
    accessmode: ""
    matchLabels: ""
    name: ""
    size: ""
    storageclass: ""
    storagetype: ""
    supplementalgroups: ""
  PrimaryStorage:
    accessmode: ReadWriteOnce
    matchLabels: ""
    name: my-prod-db
    size: 1G
    storageclass: ""
    storagetype: dynamic
    supplementalgroups: ""
  ReplicaStorage:
    accessmode: ReadWriteOnce
    matchLabels: ""
    name: ""
    size: 1G
    storageclass: ""
    storagetype: dynamic
    supplementalgroups: ""
  WALStorage:
    accessmode: ""
    matchLabels: ""
    name: ""
    size: ""
    storageclass: ""
    storagetype: ""
    supplementalgroups: ""
  annotations:
    backrest: {}
    global: {}
    pgBouncer: {}
    postgres: {}
  backrestGCSBucket: ""
  backrestGCSEndpoint: ""
  backrestGCSKeyType: service
  backrestLimits: {}
  backrestRepoPath: ""
  backrestS3Bucket: ""
  backrestS3Endpoint: ""
  backrestS3Region: ""
  backrestS3URIStyle: ""
  backrestS3VerifyTLS: "true"
  backrestStorageTypes: []
  ccpimage: crunchy-postgres-ha
  ccpimageprefix: registry.developers.crunchydata.com/crunchydata
  ccpimagetag: centos8-13.4-4.7.2
  clustername: my-prod-db
  customconfig: ""
  database: my_prod_db
  disableAutofail: false
  exporter: false
  exporterLimits: {}
  exporterport: "9187"
  limits: {}
  name: my-prod-db
  nodeAffinity: {}
  passwordType: ""
  pgBadger: false
  pgBouncer:
    resources: {}
  namespace: pgo
  pgDataSource:
    restoreFrom: ""
    restoreOpts: ""
  pgbadgerport: "10000"
  pgoimageprefix: registry.developers.crunchydata.com/crunchydata
  podAntiAffinity:
    default: preferred
    pgBackRest: preferred
    pgBouncer: preferred
  policies: my-prod-db-schema
  port: "5432"
  user: prodmy
  userlabels:
    pgo-version: 4.7.3
EOF
```
Create the policy and the cluster:
```
kubectl apply -f pgpolicy.yaml
kubectl apply -f pgcluster.yaml
```

Check database schemas:
`PGPASSWORD="blablabla" psql -h 127.0.0.1 -p 5432 -U prodmy my_prod_db -c "SELECT schema_name FROM information_schema.schemata;"`

Result: the schema `prod` **not** created:
```
    schema_name     
--------------------
...
 prodmy
```

Create the schema by applying the policy using pgo client on the cluster created by manifest:
`pgo -n pgo apply my-prod-db-schema --selector=name=my-prod-db`

Result: the schema `prod` is now created:
```
    schema_name     
--------------------
...
 prodmy
 prod
```

Any help would be much appreciated.

**Comment by jkatz** [comment]
If this is a brand new deployment, I suggest starting with [v5](https://access.crunchydata.com/documentation/postgres-operator/v5/). The equivalent functionality to `pgo apply policy` will be available in a few weeks with #2667

Do the Postgres logs indicate that the query attempted to execute? You can find those in the `/pgdata/<clustername>/pg_logs` directory.

**Comment by kbelgadi** [comment]
Hi,

Thank you for your answer :-)

No trace of any sql execution when scrolling postgresql logs on v4.7.3 pgo version as you asked:

`kubectl -n pgo exec my-prod-db-cdf6b997c-w6jlc -- /bin/bash -c "cat /pgdata/my-prod-db/pg_log/postgresql-Thu.log"`

```
2021-09-23 08:09:25.922 UTC [174] LOG:  starting PostgreSQL 13.4 on x86_64-pc-linux-gnu, compiled by gcc (GCC) 8.4.1 20200928 (Red Hat 8.4.1-1), 64-bit
2021-09-23 08:09:25.922 UTC [174] LOG:  listening on IPv4 address "0.0.0.0", port 5432
2021-09-23 08:09:25.929 UTC [174] LOG:  listening on Unix socket "/tmp/.s.PGSQL.5432"
2021-09-23 08:09:25.944 UTC [177] LOG:  database system was shut down at 2021-09-23 08:09:25 UTC
2021-09-23 08:09:25.968 UTC [174] LOG:  database system is ready to accept connections
```

So it seems that the sql code  in the policy to create schema is not executed.

We also tried v5 pgo release as you suggested.
Our first tests seem working as expected but we need to test more intensively.

We did not find a way to initialize the database declaratively in v5. No concept equivalent to policy as in v4.x pgo release.
We tried `users` spec key with `databases` and `options` but those attributes seem not created to execute sql init scripts.
So we are eagerly following your [PR](https://github.com/CrunchyData/postgres-operator/pull/2667)

The manifest we used to create a cluster with pgo v5 inspired by your [examples](https://github.com/CrunchyData/postgres-operator-examples):
```
apiVersion: postgres-operator.crunchydata.com/v1beta1
kind: PostgresCluster
metadata:
  name: my-prod-db
spec:
  image: registry.developers.crunchydata.com/crunchydata/crunchy-postgres-ha:centos8-13.4-0
  postgresVersion: 13
  instances:
    - name: instance1
      dataVolumeClaimSpec:
        accessModes:
        - "ReadWriteOnce"
        resources:
          requests:
            storage: 1Gi
  users:
  - name: prodmy
    databases:
    - my_prod_db
    options: "SUPERUSER"
  backups:
    pgbackrest:
      image: registry.developers.crunchydata.com/crunchydata/crunchy-pgbackrest:centos8-2.33-2
      repoHost:
        dedicated: {}
      repos:
      - name: repo1
        volume:
          volumeClaimSpec:
            accessModes:
            - "ReadWriteOnce"
            resources:
              requests:
                storage: 1Gi
```
