### ISSUE TITLE
Incremental backup storage size

### ISSUE THREAD

**Issue by bilemedimkq** [CrunchyData/postgres-operator#2758]
Hello, I use postgres operator v5. I have set up the database to make incremental backups every 10 minutes to s3.

After the first back up is completed, the size of the s3 bucket was 1gb. It has been approximately 3 hours since the first back up and now the bucket's size is 4.3gb. Even though I set up an incremental back up, bucket's size is increasing rapidly. I couldn't exactly understand the problem.

pgbackrest configuration;

```
  backups:
    pgbackrest:
      image: registry.developers.crunchydata.com/crunchydata/crunchy-pgbackrest:centos8-2.33-2
      repoHost:
        dedicated: {}
      configuration:
      - secret:
          name: sm-pgo-db-creds
      global:
        repo2-path: /sm-pgo-db-repo2
        repo1-retention-full: "10"
        repo1-retention-full-type: time
        repo2-retention-full: "10"
        repo2-retention-full-type: time
      repos:
      - name: repo1
        volume:
          volumeClaimSpec:
            accessModes:
            - "ReadWriteOnce"
            resources:
              requests:
                storage: 100Gi
      - name: repo2
        schedules:
          incremental: "*/10 * * * *"
        s3:
          bucket: "bucket"
          endpoint: "endpoint"
          region: "region"
```
