### ISSUE TITLE
Following tuning guide, /dev/shm too small in GKE

### ISSUE THREAD

**Issue by haf** [CrunchyData/postgres-operator#2783]
I'm not sure whether this is a feature request or a support request, but given that the recommended approach for GKE doesn't work, and I can't find docs about it, and it seems it's only configurable via the operator, it might be a feature request. 

In short, I've followed https://blog.crunchydata.com/blog/optimize-postgresql-server-performance

I have 65 GiB nodes, allocating 55 GiB mem to pg. Then added the config options from the guide:

```
      postgresql:
        parameters:
          shared_buffers: 12.5GB
          wal_buffers: 64MB
          effective_cache_size: 37.5GB
          max_parallel_workers: 14
          max_worker_processes: 56
          wal_level: logical
          wal_sender_timeout: "10m"
          max_wal_senders: "10"
          statement_timeout: '10m'
```

Getting error

```
2021-10-15 14:07:01.404 UTC [125412] ERROR:  could not resize shared memory segment "/PostgreSQL.1516396529" to 4194304 bytes: No space left on device
```

And indeed `df -h` gives:

```
Filesystem      Size  Used Avail Use% Mounted on
overlay          95G  4.7G   90G   5% /
tmpfs            64M     0   64M   0% /dev
tmpfs            32G     0   32G   0% /sys/fs/cgroup
/dev/sda1        95G  4.7G   90G   5% /tmp
/dev/sdd        492G  118G  374G  24% /pgdata
tmpfs            32G   24K   32G   1% /pgconf/tls
tmpfs            32G   24K   32G   1% /etc/podinfo
tmpfs            32G   16K   32G   1% /etc/patroni
shm              64M   24K   64M   1% /dev/shm
tmpfs            32G   16K   32G   1% /etc/pgbackrest/conf.d
tmpfs            32G   12K   32G   1% /run/secrets/kubernetes.io/serviceaccount
tmpfs            32G     0   32G   0% /proc/acpi
tmpfs            32G     0   32G   0% /proc/scsi
tmpfs            32G     0   32G   0% /sys/firmware
```

There seems to be a workaround here https://stackoverflow.com/questions/46085748/define-size-for-dev-shm-on-container-engine/46434614#46434614 but it requires mounting a memory volume. So I was looking at https://access.crunchydata.com/documentation/postgres-operator/5.0.3/references/crd/ and trying to find some `volumes` key to set, but failed to find any...

Hence the question; if this is the "answer" to the shared memory not matching between the docker container configuration and the tuning guide; how am I supposed to tune pg with crunchy for large amounts of data?
