### ISSUE TITLE
Support S3 repositories without regions

### ISSUE THREAD

**Issue by benjamin-bergia** [CrunchyData/postgres-operator#2799]
## Overview

I am testing PGO in my organization and try to push the backups to our s3 compatible storage (Ceph). In our case, there is no AWS region. For most tools out there, the AWS region is optional, but apparently in the repo configuration part of my cluster the region field is mandatory and cannot be empty. Is there any way to get around this?

## Environment

- Platform: Kubernetes
- Platform Version: 1.21
- PGO Image Tag: 8-13.4-1
- Postgres Version 13
- Storage: s3

### REPRO
1. Clone https://github.com/CrunchyData/postgres-operator-examples
2. Remove the region here https://github.com/CrunchyData/postgres-operator-examples/blob/main/kustomize/s3/postgres.yaml#L28
3. rename `s3.conf.example` into `s3.conf`
4. run `kustomize build kustomize/s3 | kubectl apply -f -`

### EXPECTED

I would expect the pgbackrest to run

### ACTUAL
If the region is empty, pgbackrest is marked as not ready for backups:
```yaml
Status:
  Conditions:
    Last Transition Time:  2021-10-21T15:03:00Z
    Message:               pgBackRest replica create repo is not ready for backups
    Observed Generation:   2
    Reason:                StanzaNotCreated
    Status:                False
    Type:                  PGBackRestReplicaRepoReady
    Last Transition Time:  2021-10-21T15:03:00Z
    Message:               pgBackRest replica creation is not currently possible
    Observed Generation:   2
    Reason:                RepoBackupNotComplete
    Status:                False
    Type:                  PGBackRestReplicaCreate
```
If  the field is missing, `kubectl apply` fails:
>error: error validating "STDIN": error validating data: ValidationError(PostgresCluster.spec.backups.pgbackrest.repos[0].s3): missing required field "region" in com.crunchydata.postgres-operator.v1beta1.PostgresCluster.spec.backups.pgbackrest.repos.s3; if you choose to ignore these errors, turn validation off with --validate=false

## Logs
With the fields specified but set to an empty string:
`kubectl describe postgresclusters.postgres-operator.crunchydata.com hippo`
>Warning  UnableToCreateStanzas  90s (x59 over 11m)  postgrescluster-controller  command terminated with exit code 32: ERROR: [032]: section 'global', key 'repo1-s3-region' must have a value

## Additional Information
