### ISSUE TITLE
Affinity for Backups Jobs

### ISSUE THREAD

**Issue by maxsivkov** [CrunchyData/postgres-operator#2827]
Postgres Operator: 5.0.3

## Title
Backup Jobs do not respect affinity settings in the repoHost section (should they do?)

## Description
In my config I have two nodes labeled with `ckrole=db`.
Master and replica pods are running on a `db` nodes, each on a different node (thanks to pod anti affinity)
SS repo-host also has scheduled its pod to the `db` node, but it's job doesn't
```
NAME                                           READY   STATUS              RESTARTS   AGE   IP             NODE                            NOMINATED NODE   READINESS GATES
pod/postgres-cluster-lh-vl-backup-qgkj-fthws   0/1     ContainerCreating   0          62m   <none>         win-worker-01                   <none>           <none>
```
(we have one windows worker in the cluster)

## Deployment
postgres/postgres.yaml file from the `postgres-operator-examples` repo
```
apiVersion: postgres-operator.crunchydata.com/v1beta1
kind: PostgresCluster
metadata:
  name: postgres-cluster-lh-vl
spec:
  image: registry.developers.crunchydata.com/crunchydata/crunchy-postgres:centos8-13.4-1
  postgresVersion: 13
  users:
  - name: postgres
  - name: testuser-cl1
    databases:
    - testuser_cl1_db
  - name: testuser-cl2
    databases:
    - testuser_cl2_db
  instances:
  - name: instance1
    replicas: 2
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
            - matchExpressions:
              - key: ckrole
                operator: In
                values:
                - db
      podAntiAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
        - topologyKey: kubernetes.io/hostname
          labelSelector:
            matchLabels:
              postgres-operator.crunchydata.com/cluster: postgres-cluster-lh-vl
              postgres-operator.crunchydata.com/instance-set: instance1
    dataVolumeClaimSpec:
      accessModes:
      - "ReadWriteOnce"
      volumeMode: Filesystem
      storageClassName: longhorn-cluster
      resources:
        requests:
          storage: 1Gi
  backups:
    pgbackrest:
      image: registry.developers.crunchydata.com/crunchydata/crunchy-pgbackrest:centos8-2.35-0
      repoHost:
        affinity:
          nodeAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              nodeSelectorTerms:
                - matchExpressions:
                  - key: ckrole
                    operator: In
                    values:
                    - db
      repos:
      - name: repo1
        volume:
          volumeClaimSpec:
            accessModes:
            - "ReadWriteOnce"
            volumeMode: Filesystem
            storageClassName: longhorn-cluster
            resources:
              requests:
                storage: 1Gi
```

I didn't find affinity settings for the backup jobs, so I think they should respect repoHost settings. Should they?
