### ISSUE TITLE
Fresh install on GKE fails with exit code 1 for postgres-setup

### ISSUE THREAD

**Issue by Richard87** [CrunchyData/postgres-operator#2847]
Postgres-startup is in a crashloop backoff, but with no errors written to the log:
```
Initializing ...
::postgres-operator: uid::26
::postgres-operator: gid::26
::postgres-operator: postgres path::/usr/pgsql-13/bin/postgres
::postgres-operator: postgres version::postgres (PostgreSQL) 13.4
```
It is terminated with exit code `1`. 
(Its interresting to note that I requested Postgres 14 in my cluster.yaml!)

All other containers are waiting for postgres-startup to complete before running...

The Volume is bound and ready...

## Environment

Please provide the following details:

- Platform:  `GKE`
- Platform Version: `1.21`
- PGO Image Tag: (e.g. `ubi8-5.0.4-0`)
- Postgres Version (e.g. `14`)
- Storage: GKE

My cluster.yml:
```yaml
apiVersion: postgres-operator.crunchydata.com/v1beta1
kind: PostgresCluster
metadata:
  name: eportal
  namespace: richard
spec:
  image: registry.developers.crunchydata.com/crunchydata/crunchy-postgres:centos8-13.4-1
  backups:
    pgbackrest:
      image: registry.developers.crunchydata.com/crunchydata/crunchy-pgbackrest:centos8-2.35-0
      repos:
        - name: repo1
          volume:
            volumeClaimSpec:
              accessModes:
                - ReadWriteOnce
              resources:
                requests:
                  storage: 1Gi
  instances:
    - dataVolumeClaimSpec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
      name: main
  postgresVersion: 14
```

I ran `kubectl apply -k kustomize/install` and `kubectl kustomize -n richard kustomize/postgres` and modified the namespace.

Any help would be appreciated! :)
