### ISSUE TITLE
How to restore PGO version 5 operator data backup from s3 bucket when old cluster is deleted.

### ISSUE THREAD

**Issue by amitabhajana** [CrunchyData/postgres-operator#2875]
Kindly help me to understad how to restore pgo cluster directly from s3 bucket when old cluster is deleted.

**Comment by jkatz** [comment]
https://github.com/CrunchyData/postgres-operator/commit/02f2ff52f74a2b7fbe8d80cce3d57350c44fc69f adds documentation that addresses this.

**Comment by yash-kalwani** [comment]
@jkatz i went through the documentation and the entire process seems a little manual. Just want to make sure if i have understood everything properly consider this example

1. Cluster `Hippo` with namespace `postgres-operator` exists. Backups for this have been taken regularly
2. We delete the entire `Hippo` cluster
3. Deploy the same `Hippo` cluster with the same namespace

In this case when i connect it to the s3 repo that previously had backups it throws the error "backup and archive info files exist but do not match the database" from what i understand this has something to do with the system-id in the backup.info files?

In the above described case, do i have to follow the procedure described in the docs? Or is there some way to restore the cluster without having to create two repos with the standby attribute?

also what if my cluster name does not change then both repo1 and repo2 will have the same path?

Is there any docs on this that i am missing out on? Thanks for the help!

**Comment by yash-kalwani** [comment]
@jkatz can we also simply add this to our spec ( hippo is the name of the cluster and repoName is in the context of pgbackrest )

```
dataSource:
    postgresCluster:
      clusterName: hippo
      repoName: repo1
```

I am assuming the documentation is for when we want to switch from one running cluster to another one and dataSource can be used to spin up new clusters from existing backups?

I am using the above code to load our cluster with our existing backups in s3!!
@jkatz is this a good approach? Or is there a better way to achieve it?

Thanks!

**Comment by jkatz** [comment]
If you are migrating data from a non-PGO managed Postgres cluster to a PGO-managed one, you may want to read the guide on data migration (or possibly the PGO v4 to v5 guide):

https://access.crunchydata.com/documentation/postgres-operator/v5/guides/data-migration/
https://access.crunchydata.com/documentation/postgres-operator/v5/guides/v4tov5/

**Comment by amitabhajana** [comment]
@jkatz Sir is there any way to perform PITR directly from s3 bucket?
In my scenario my backup retention period is 10 days & i want to restore from backup of day 5 which is stored in s3 bucket.

**Comment by jkatz** [comment]
Yes. See https://github.com/CrunchyData/postgres-operator/issues/2875#issuecomment-1000411216 for performing a PITR to a new cluster and https://access.crunchydata.com/documentation/postgres-operator/v5/tutorial/disaster-recovery/#perform-an-in-place-point-in-time-recovery-pitr for performing a PITR in place.

**Comment by amitabhajana** [comment]
Actually when i am trying to restore backup from s3 bucket using standby cluster mode it restores only the last saved backup.
In my case it is the date of "01.01.2022" but the this date's data backup got corrupted, so i have to restore from the date of 31.12.2021. when i am trying to perform PITR from s3 bucket by using below manifest it restores only from last saved backup
which is  01.01.2022 not from 31.12.2021. Please help me on this
```
backups:
    pgbackrest:
       restore: 
         enabled: true
         repoName: repo1
         options:
         - --type=time
         - --target="2021-12-31 21:30:00-00"
       image: registry.developers.crunchydata.com/crunchydata/crunchy-pgbackrest:centos8-2.33-0
       configuration:
       - secret:
            name: pgo-creds
       global:
         repo1-path: /pgbackrest/postgres-operator/"my repo name"/repo1
       repos:
       - name: repo1
         s3:
           bucket: "************"
           endpoint: "********************"
           region: "**************"
standby:
    enabled: true
    repoName: repo1
```
