### ISSUE TITLE
Allow granting privileges to users

### ISSUE THREAD

**Issue by benjamin-bergia** [CrunchyData/postgres-operator#2880]
## Overview

I have existing databases that I imported into PGO managed clusters. I like the user management feature where it auto create secrets etc. Unfortunately I would like to fit these new users into my existing roles.

## Use Case
I have an existing database with an existing set of roles including specific privileges. I would like to grant this role to my newly created users and maybe also grant new privileges.

## Desired Behavior

In my cluster under `/spec/users`, I would like to do something like:
```yaml
- name: my_user
  databases:
    - test_db
  grants:
    - SELECT ON test_db
    - test_admin
```
which would basically run:
```sql
GRANT SELECT ON test_db TO my_user;
GRANT test_admin TO my_user;
```

I understand that you might want to keep the whole schema management out of the operator. In which can I would just like to be able to grant existing roles to the new users as in:

```yaml
- name: my_user
  databases:
    - test_db
  grants:
    - test_admin
```
This would force users to manage privileges themselves via roles but still allow PGO managed users to be granted existing roles.

## Environment

- Platform: Kubernetes
- Platform Version: 1.21
- PGO Image Tag: 8-13.4-1
- Postgres Version 13
- Storage: s3
