### ISSUE TITLE
Unable to start a restore when the previous restore has failed

### ISSUE THREAD

**Issue by timbrd** [CrunchyData/postgres-operator#2888]
I have tried to manually restore a database using postgres-operator v5. 

Therefore I haved added the following snippet to the postgrescluster CR as described in the manual:

```
      restore:
        enabled: true
        options:
        - --type=time
        - --target="2021-11-30 13:00:00+01"
        repoName: repo1
```

After annotating the CR with `kubectl annotate postgrescluster demo-db postgres-operator.crunchydata.com/pgbackrest-restore=id1`, a pgbackrest container has started, but stopped right after, since it didn't find a valid backup.

Now pgbackrest is not starting any more when configuring another PITR. I guess the operator checks the restore status field of the postgrescluster CR, which in my case states that there is still a restore running:

```
  pgbackrest:
    manualBackup:
      completionTime: "2021-11-30T16:07:03Z"
      finished: true
      id: Tue Nov 30 15:41:31 CET 2021
      startTime: "2021-11-30T14:41:33Z"
      succeeded: 1
    repos:
    - name: repo1
      replicaCreateBackupComplete: true
      repoOptionsHash: b9fcc886
      stanzaCreated: true
    restore:
      active: 1
      finished: false
      id: id1
      startTime: "2021-11-30T14:31:14Z"
[...]
```

Is this a bug or do I have to release / remove the initial restore somehow? I couldn't find any information on that in the documentation.
