### ISSUE TITLE
How to pass arguments to initdb?

### ISSUE THREAD

**Issue by bobbyd0g** [CrunchyData/postgres-operator#2924]
Hello, I was wondering how to create a database with initdb args `--lc-collate=C` and `--lc-ctype=C`, which are required by Matrix Synapse. I see nothing in the CRD reference for patroni bootstrap, nor in any other docs, is this configuration supported in PGO v5?

**Comment by jkatz** [comment]
Did you try:

```yaml
spec:
  patroni:
    dynamicConfiguration:
      bootstrap:
        initdb:
          - encoding=C
          - locale=C
```

**Comment by bobbyd0g** [comment]
A ha! Thank you for the prompt response. The operator creates the database, so this must be the right key, but still unfortunately not quite doing it. I tried many combinations of the flags I provided and the ones you suggested, with double dashes and quotes or without, but everything returned this from the app once connected:
```
     - 'COLLATE' is set to 'en_US.utf-8'. Should be 'C'
     - 'CTYPE' is set to 'en_US.utf-8'. Should be 'C'
```

**Comment by bobbyd0g** [comment]
Going a little deeper -- your input, 
```
  patroni:
    dynamicConfiguration:
      bootstrap:
        initdb:
          - encoding=C
          - locale=C
```
puts this in the /pgdata/pg13/patroni.dynamic.json file:
```
{"bootstrap": {"initdb": ["encoding=C", "locale=C"]}, "loop_wait": 10, "postgresql": {"parameters":  [ . . . ]
```
and generates these logs:
```
2021-12-18 00:36:26,546 INFO: No PostgreSQL configuration items changed, nothing to reload.
2021-12-18 00:36:26,555 INFO: Lock owner: None; I am hellsite-matrix-pgha1-nbln-0
2021-12-18 00:36:26,730 INFO: trying to bootstrap a new cluster
The files belonging to this database system will be owned by user "postgres".
This user must also own the server process.

The database cluster will be initialized with locale "en_US.utf-8".
The default text search configuration will be set to "english".
```
The app then fails to boot as described above

**Comment by bobbyd0g** [comment]
I've been looking through Patroni documentation today and am still having trouble finding the missing link between filling the initdb section of this json file, and getting the actual argument to initdb, or how to tell if it got there and was rejected and overridden somehow. I suppose it must be the right place in the schema, but the wrong inputs?

**Comment by bm-skutzke** [comment]
I've stumbled upon the same problem. As far as I understood the Patroni [bootstrap](https://patroni.readthedocs.io/en/latest/SETTINGS.html#bootstrap-configuration) documentation, we would need something like this in PGO:
```
spec:
  patroni:
    bootstrap:
      initdb:
        - encoding: C
        - locale: C
      dynamicConfiguration:
        postgresql:
          parameters:
            ...
```
Both, dynamic configuration settings and initdb, are part of bootstrap. Or am I wrong?
