### ISSUE TITLE
Document how to connect to read replica (and how pgBouncer interacts with it)

### ISSUE THREAD

**Issue by haf** [CrunchyData/postgres-operator#2933]
## Overview

It would be great to have [docs](https://stackoverflow.com/questions/70393223/connect-to-crunchy-operators-read-replica) for how to connect to replicas for read-only workloads.

## Use Case

Read only workloads.

## Desired Behavior

Setting up `instances: { replicas: 2 ... }` and `proxy: { pgBouncer: { replicas: 2 } }` gets you this setup of services

```
NAME                     TYPE        CLUSTER-IP      EXTERNAL-IP   PORT(S)    AGE   SELECTOR
analytics-ha             ClusterIP   172.16.16.194   <none>        5432/TCP   63d   <none>
analytics-ha-config      ClusterIP   None            <none>        <none>     63d   <none>
analytics-pgbouncer      ClusterIP   172.16.24.181   <none>        5432/TCP   63d   postgres-operator.crunchydata.com/cluster=analytics,postgres-operator.crunchydata.com/role=pgbouncer
analytics-pods           ClusterIP   None            <none>        <none>     63d   postgres-operator.crunchydata.com/cluster=analytics
analytics-primary        ClusterIP   None            <none>        5432/TCP   63d   <none>
```

Which of these should I connect to? The problem I'm having right now is that `dbt` are taking too much CPU, DoS-ing the DB.

**Furthermore https://access.crunchydata.com/documentation/crunchy-postgres-containers/5.0.3/examples/poolers/pgbouncer/ talks about `examples/pgbouncer` which doesn't exist.**

## Environment

Tell us about your environment:

Please provide the following details:

- Platform: (`Kubernetes`, `OpenShift`, `Rancher`, `GKE`, `EKS`, `AKS` etc.) GKE
- Platform Version: (e.g. `1.20.3`, `4.7.0`) 
- PGO Image Tag: (e.g. `ubi8-5.1.0-0`) 5.0.3 / centos8-13.4-1
- Postgres Version (e.g. `14`) 13
- Storage: (e.g. `hostpath`, `nfs`, or the name of your storage class) PVC
- Number of Postgres clusters: (`XYZ`) 1

**Comment by andrewlecuyer** [comment]
@haf you should see a "replica" service, e.g.:

```bash
$ kubectl get svc
NAME              TYPE        CLUSTER-IP      EXTERNAL-IP   PORT(S)    AGE
...
hippo-replicas    ClusterIP   10.104.67.131   <none>        5432/TCP   4s
```

Do you see any errors in your `operator` logs?  Also, can you provide a copy of your `PostgresCluster` spec?

**Comment by haf** [comment]
Hi, no replica service in sight, but there's is a replica when I check with patronictl.

No errors at all in the logs, all things working smoothly.

I have four DB:s running. One with pgBouncer (which I still don't know how to use, actually; do I connect to analytics-ha or it?) and three without.

Base:

```
apiVersion: postgres-operator.crunchydata.com/v1beta1
kind: PostgresCluster
metadata:
  name: analytics-ts
  namespace: db

spec:
  image: registry.developers.crunchydata.com/crunchydata/crunchy-postgres:centos8-13.4-1

  postgresVersion: 13

  customTLSSecret:
   name: analytics-ts-tls

  customReplicationTLSSecret:
   name: analytics-ts-repl-tls

  patroni:
    dynamicConfiguration:
      postgresql:
        parameters:
          shared_preload_libraries: timescaledb

  databaseInitSQL:
    name: analytics-ts-init
    key: init.sql

  users:
  - name: postgres

  - name: analytics-ts
    databases:
    - msgs
    options: "SUPERUSER"

  instances:
  - name: instance1
    replicas: 1

    resources:
      limits:
        cpu: 1000m
        memory: 2048Mi
      requests:
        cpu: 10m
        memory: 64Mi

    walVolumeClaimSpec:
      accessModes:
      - "ReadWriteMany"
      resources:
        requests:
          storage: 1Gi

    dataVolumeClaimSpec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 5Gi

  monitoring:
    pgmonitor:
      exporter:
        image: registry.developers.crunchydata.com/crunchydata/crunchy-postgres-exporter:ubi8-5.0.3-0

  backups:
    pgbackrest:
      image: registry.developers.crunchydata.com/crunchydata/crunchy-pgbackrest:centos8-2.35-0

      metadata:
        annotations: 
          # pgbackrest only tries once
          sidecar.istio.io/inject: "false"

      repos:
      - name: repo1
        volume:
          volumeClaimSpec:
            accessModes:
            - "ReadWriteOnce"
            resources:
              requests:
                storage: 5Gi
```

prod overlay:

```
apiVersion: postgres-operator.crunchydata.com/v1beta1
kind: PostgresCluster
metadata:
  name: analytics-ts
  namespace: db

spec:
  instances:
  - name: instance1
    # https://access.crunchydata.com/documentation/postgres-operator/5.0.3/architecture/high-availability/
    replicas: 2

    dataVolumeClaimSpec:
      storageClassName: pd-ssd-firstconsumer
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 50Gi

    resources:
      limits:
        cpu: 1000m
        memory: 2Gi
      requests:
        cpu: 500m
        memory: 256Mi

    tolerations:
    - effect: NoSchedule
      key: dedicated
      operator: Equal
      value: PostgreSQL

    topologySpreadConstraints: 
    - maxSkew: 1
      topologyKey: topology.kubernetes.io/zone
      whenUnsatisfiable: ScheduleAnyway
      labelSelector: 
        matchLabels:
          postgres-operator.crunchydata.com/instance-set: instance1

    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
          - matchExpressions:
            - key: dedicated
              operator: In
              values:
              - PostgreSQL

      podAntiAffinity:
        preferredDuringSchedulingIgnoredDuringExecution:
        - weight: 1
          podAffinityTerm:
            topologyKey: kubernetes.io/hostname
            labelSelector:
              matchLabels:
                postgres-operator.crunchydata.com/cluster: analytics-ts
                postgres-operator.crunchydata.com/instance-set: instance1

  backups:
    pgbackrest:
      # configuration:
      # - secret:
      #     name: analytics-ts

      manual:
        repoName: repo1
        options:
         - --type=full

      global:
        repo1-gcs-key-type: auto
        repo1-retention-full: "14"
        repo1-retention-full-type: time

      repos:
      - name: repo1
        schedules:
          full: "0 1 * * *"
          incremental: "0 */2 * * *"
        gcs:
          bucket: gke-backups-analytics-ts-pg
```
