### ISSUE TITLE
With istio sidecar injection jobs are in NotReady state

### ISSUE THREAD

**Issue by jebinjeb** [CrunchyData/postgres-operator#2945]
After injecting istio sidecar, jobs pods are in NotReady state because application pod done his job and sidecar is in running state. 
Fix suggested from istio is execute post request after application execution (curl -sf -XPOST http://127.0.0.1:15020/quitquitquit
)

How to update the entrypoint to execute curl POST after application execution ?

**Comment by jkatz** [comment]
Closing in favor of support question asked on mailing list.

**Comment by jebinjeb** [comment]
@jkatz didn't get any response from  mailing list, could you please help me the exact entrypoint ?

will this work ? command: ["/bin/bash", "-c", "pgbackrest && curl -X POST http://localhost:15020/quitquitquit"]
I can do the mutation using kyverno

**Comment by tolleiv** [comment]
We're using this Kyverno Policy to add the required sidecar:

```
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: cronjob-add-quitquitquit-sidecar-for-pgbackrest
  annotations:
    policies.kyverno.io/title: Add sidecar which quits the related pgbackrest istio-proxy
spec:
  validationFailureAction: enforce
  background: false
  webhookTimeoutSeconds: 30
  rules:
    - name: add-sidecar
      match:
        resources:
          kinds:
            - CronJob
      mutate:
        patchStrategicMerge:
          metadata:
            labels:
              (postgres-operator.crunchydata.com/pgbackrest-repo): "repo*"
          spec:
            jobTemplate:
              spec:
                template:
                  spec:
                    containers:
                      - name: istio-quitquitquit
                        command: [ "/bin/bash", "-c" ]
                        args: [ "sleep 5; while grep -q [p]gbackrest < <( ps aux ); do sleep 1; done; sleep 5; curl --max-time 2 -s -f -XPOST http://127.0.0.1:15000/quitquitquit" ]
                        image: "curlimages/curl"

```
