### ISSUE TITLE
pg_hba.conf settings not applied

### ISSUE THREAD

**Issue by cornel-masson** [CrunchyData/postgres-operator#2963]
##Environment
Platform: Kubernetes
Platform Version: 4.7.3
PGO Image Tag: centos8-4.7.
Postgres Version: 13

##Problem
My custom **pg_hba.conf** settings are not applied, it just uses the default settings.

##Steps
I followed the [custom config documentation](https://access.crunchydata.com/documentation/postgres-operator/4.7.3/advanced/custom-configuration/) to create a custom config-map with a `postgres-ha.yaml` entry. Below is a sample of that file. I've tried it as depicted without success. 

```
bootstrap:
  dcs:
    postgresql:
      parameters:
        shared_preload_libraries: pg_stat_statements.so,pgnodemx.so,timescaledb
        listen: '*'
postgresql:
  pg_hba:
	- local all postgres md5
	- host all all 127.0.0.1/32 md5
	- host all all 102.37.124.150/32 md5
	- host all all 102.37.217.33/32 md5
```

After cluster creation I view the **MYCLUSTER-pgha-config**, and there is always a _local_ section with default settings: my custom settings are nowhere. I tried moving the **pg_hba** entry to various other locations in `postgres-ha.yaml` without success:
- Under bootstrap.dcs
- Under bootstrap.dcs.postgresql
- Under local.postgresql
- etc.

I also don't know what the correct way is to define a "local" entry. The documentation discusses it, but doesn't give an example of how to format it in `postgres-ha.yaml`. I can see in the generated **MYCLUSTER-pgha-config** config-map that there is an entry: **MYCLUSTER-local-config**, but I can't see what my `postgres-ha.yaml` entry must look like to get something in that local-config section.

##Summary
1. I don't know where to put pg_hba config in my `postgres-ha.yaml`
2. I don't know, in general, how to define a "local" section in `postgres-ha.yaml`
