### ISSUE TITLE
Mapping Existing backup PVC (NFS) on postgres.yaml

### ISSUE THREAD

**Issue by hariyedlapalli** [CrunchyData/postgres-operator#2964]
Please ensure you do the following when reporting a bug:

- [ ] Provide a concise description of what the bug is.
- [ ] Provide information about your environment.
- [ ] Provide clear steps to reproduce the bug.
- [ ] Attach applicable logs. Please do not attach screenshots showing logs unless you are unable to copy and paste the log data.
- [ ] Ensure any code / output examples are [properly formatted](https://docs.github.com/en/github/writing-on-github/basic-writing-and-formatting-syntax#quoting-code) for legibility.

Note that some logs needed to troubleshoot may be found in the `/pgdata/<CLUSTERNAME>/pg_log` directory on your Postgres instance.

An incomplete bug report can lead to delays in resolving the issue or the closing of a ticket, so please be as detailed as possible.

If you are looking for [general support](https://access.crunchydata.com/documentation/postgres-operator/latest/support/), please view the [support](https://access.crunchydata.com/documentation/postgres-operator/latest/support/) page for where you can ask questions.

Thanks for reporting the issue, we're looking forward to helping you!

## Overview

Add a concise description of what the bug is.

## Environment

Please provide the following details:

- Platform: (`Kubernetes`, `OpenShift`, `Rancher`, `GKE`, `EKS`, `AKS` etc.)
- Platform Version: (e.g. `1.20.3`, `4.7.0`)
- PGO Image Tag: (e.g. `ubi8-5.1.0-0`)
- Postgres Version (e.g. `14`)
- Storage: (e.g. `hostpath`, `nfs`, or the name of your storage class)

### REPRO

Provide steps to get to the error condition:

1. Run `...`
1. Do `...`
1. Try `...`

### EXPECTED

1. Provide the behavior that you expected.

### ACTUAL

1. Describe what actually happens

## Logs

Please provided appropriate log output or any configuration files that may help troubleshoot the issue. **DO NOT** include sensitive information, such as passwords.

## Additional Information

Please provide any additional information that may be helpful.

**Comment by hariyedlapalli** [comment]
HI Team

Could you please guide me how can I use the existing PVC for BAckup on postgres.yaml file ?

24 backups:
25 pgbackrest:
26 image: registry.developers.crunchydata.com/crunchydata/crunchy-pgbackrest:centos8-2.36-0
27 repos:
28 - name: repo1
29 volume:
30 #persistanceVolume:
31 - name: crunchy-backup-pv
32 persistentVolumeClaim:
33 claimName: crunchy-backup

Error message :
postgres-operator-examples-main]$ ~/kubectl apply -k kustomize/postgres
error: error validating "kustomize/postgres": error validating data: ValidationError(PostgresCluster.spec.backups.pgbackrest.repos[0].volume): invalid type for com.crunchydata.postgres-operator.v1beta1.PostgresCluster.spec.backups.pgbackrest.repos.volume: got "array", expected "map"; if you choose to ignore these errors, turn validation off with --validate=false

existing PVC details :
NAME             STATUS    VOLUME              CAPACITY   ACCESS MODES   STORAGECLASS   AGE
crunchy-backup   Bound     crunchy-backup-pv   60G        RWO            nfs            149m

**Comment by hariyedlapalli** [comment]
Hi Jkatz
I could not able to use existing NFS PVC for Backup . Could you please guide with the postgres.yaml ..

**Comment by hariyedlapalli** [comment]
volumeClaimSpec:
  accessModes:
   - ReadWriteOnce 
  resources:
    requests: 
      storage: 60Gi
    volumeName: crunchy-backup-pv
    storageClassName: "nfs"
	
Error:
[postgres-operator-examples-main]$ ~/kubectl apply -k kustomize/postgres
error: error validating "kustomize/postgres": error validating data: ValidationError(PostgresCluster.spec.backups.pgbackrest.repos[0]): unknown field "volumeClaimSpec" in com.crunchydata.postgres-operator.v1beta1.PostgresCluster.spec.backups.pgbackrest.repos; if you choose to ignore these errors, turn validation off with --validate=false
-bash: fc: history specification out of range
[harikrishna@ap1sr1ljmp01 postgres-operator-examples-main]$

**Comment by hariyedlapalli** [comment]
Platform: (OpenShift, )
Platform Version: (OCP 4.6)
PGO Image Tag: (e.g. ubi8-5.1.0-0)
Postgres Version (e.g. 13)
Storage: ( nfs)

**Comment by hpe-ii-kaito** [comment]
Hi team. 
I am having a similar issue where the pvc is not created with the pv specified (local-pv-5b63a1d) in the pgbackrest. 
However the pvc for the instance is automatically created with local-pv-914c6e4c. Am I missing something in the manifest?


My environment and the manifest for the PostgresCluster is as follow.

Platform: OpenShift 4.10
Operator Version: Crunchy Postgres for Kubernetes 5.0.3
Storage: Local Storage Operator 

<details>

```yaml
apiVersion: postgres-operator.crunchydata.com/v1beta1
kind: PostgresCluster
metadata:
  name: example
  namespace: default
spec:
  port: 5432
  proxy:
    pgBouncer:
      port: 5432
      replicas: 1
  backups:
    pgbackrest:
      repos:
        - volume:
            volumeClaimSpec:
              accessModes:
                - ReadWriteOnce
              resources:
                requests:
                  storage: 1Gi
              storageClassName: local-sc
              volumeMode: FileSystem
              volumeName: local-pv-5b63a1d
          name: repo1
  patroni:
    leaderLeaseDurationSeconds: 30
    port: 8008
    syncPeriodSeconds: 10
  instances:
    - dataVolumeClaimSpec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
        volumeName: local-pv-914c6e4c
        volumeMode: Filesystem
        storageClassName: local-sc
      replicas: 1
  postgresVersion: 13
  openshift: true

```

</details>
