### ISSUE TITLE
The pgBackRest pod is not scheduled on another node ?

### ISSUE THREAD

**Issue by khalifaould** [CrunchyData/postgres-operator#2972]
In the event that the node is lost or the pgbackrest pod is running, the pod is not rescheduled on one of the other available nodes and it is no longer possible to make a backup or restore.
Is it normal ?
Is it possible to have several replicas of this pod as is the case for the base pods?

**Comment by jkatz** [comment]
There is not enough information here to begin troubleshooting. Information that is helpful for this can be found here: https://github.com/CrunchyData/postgres-operator/issues/new?template=bug_report.md

**Comment by khalifaould** [comment]
As part of our resilience tests we have a cluster with 3 master nodes on which we launched a crunchydata cluster with 3 replicas.
The list of pods
![image](https://user-images.githubusercontent.com/5902466/148931743-3f2d0313-f73a-436a-af18-570f9c118c9b.png)

We simulate the loss of the node on which the pgbackrest (dai-prod-db-repo-host-0) is launched.

We note that this pod is not replanted on one of the other available nodes

![image](https://user-images.githubusercontent.com/5902466/148931885-e2ef4ecc-b3c3-45b8-b938-3978cf751270.png)


In this case we can no longer make a backup or restore?

Is it possible to have several replicas of this pod as is the case for the base pods?

The cluster config

`apiVersion: postgres-operator.crunchydata.com/v1beta1
kind: PostgresCluster
metadata:
  name: db-cluster
  namespace: namespace
spec:
  image: registry.developers.crunchydata.com/crunchydata/crunchy-postgres:centos8-13.4-1
  postgresVersion: 13
  instances:
    - name: instance1
      replicas: 3
      dataVolumeClaimSpec:
        accessModes:
          - "ReadWriteOnce"
        resources:
          requests:
            storage: 3Gi
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - topologyKey: kubernetes.io/hostname
            labelSelector:
              matchLabels:
                postgres-operator.crunchydata.com/cluster: db-cluster
                postgres-operator.crunchydata.com/instance-set: instance1
  users:
    - name: proddai
      databases:
        - db_name
      options: "SUPERUSER"
  databaseInitSQL:
    key: create-schema.sql
    name: create-schema
  backups:
    pgbackrest:
      global:
        repo1-retention-full: "5"
      manual:
        repoName: repo1
        options:
          - --type=full
      image: registry.developers.crunchydata.com/crunchydata/crunchy-pgbackrest:centos8-2.35-0
      repos:
        - name: repo1
          schedules:
            full: "0 0 * * *"
          volume:      
            volumeClaimSpec:
              accessModes:
                - "ReadWriteOnce"
              resources:
                requests:
                  storage: 3Gi`

**Comment by khalifaould** [comment]
```
Cluster Config 

`apiVersion: postgres-operator.crunchydata.com/v1beta1
kind: PostgresCluster
metadata:
  name: db-cluster
  namespace: namespace
spec:
  image: registry.developers.crunchydata.com/crunchydata/crunchy-postgres:centos8-13.4-1
  postgresVersion: 13
  instances:
    - name: instance1
      replicas: 3
      dataVolumeClaimSpec:
        accessModes:
          - "ReadWriteOnce"
        resources:
          requests:
            storage: 3Gi
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - topologyKey: kubernetes.io/hostname
            labelSelector:
              matchLabels:
                postgres-operator.crunchydata.com/cluster: db-cluster
                postgres-operator.crunchydata.com/instance-set: instance1
  users:
    - name: proddai
      databases:
        - db_name
      options: "SUPERUSER"
  databaseInitSQL:
    key: create-schema.sql
    name: create-schema
  backups:
    pgbackrest:
      global:
        repo1-retention-full: "5"
      manual:
        repoName: repo1
        options:
          - --type=full
      image: registry.developers.crunchydata.com/crunchydata/crunchy-pgbackrest:centos8-2.35-0
      repos:
        - name: repo1
          schedules:
            full: "0 0 * * *"
          volume:      
            volumeClaimSpec:
              accessModes:
                - "ReadWriteOnce"
              resources:
                requests:
                  storage: 3Gi`

```
