### ISSUE TITLE
Exposing Service as type LoadBalancer on Amazon EKS appears to break backups and reconciliation

### ISSUE THREAD

**Issue by nseritti** [CrunchyData/postgres-operator#2976]
## Overview

Creating a cluster with a service type of LoadBalancer appears to break some functionality of the cluster including backups, and credentials from the secret.

## Environment

Please provide the following details:

- Platform: EKS
- Platform Version: 1.20
- PGO Image Tag: postgres-operator:ubi8-5.0.4-0
- Postgres Version centos8-13.5-0
- Storage: GP2

### REPRO

1. Create a cluster from the examples (Using a slightly modified s3 example here)
```yaml
apiVersion: postgres-operator.crunchydata.com/v1beta1
kind: PostgresCluster
metadata:
  name: location
spec:
  image: registry.developers.crunchydata.com/crunchydata/crunchy-postgres-gis:centos8-13.5-3.1-0
  postgresVersion: 13
  users:
    - name: postgres
    - name: location
      databases:
        - location
      options: "SUPERUSER"
  instances:
    - name: location1
      replicas: 2
      resources:
        limits:
          cpu: 2.0
          memory: 1Gi
      dataVolumeClaimSpec:
        accessModes:
        - "ReadWriteOnce"
        resources:
          requests:
            storage: 10Gi
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 1
            podAffinityTerm:
              topologyKey: kubernetes.io/hostname
              labelSelector:
                matchLabels:
                  postgres-operator.crunchydata.com/cluster: location
                  postgres-operator.crunchydata.com/instance-set: location1
  databaseInitSQL:
    key: init.sql
    name: location-init-sql

  monitoring:
    pgmonitor:
      exporter:
       image: registry.developers.crunchydata.com/crunchydata/crunchy-postgres-exporter:ubi8-5.0.4-0

  backups:
    pgbackrest:
      image: registry.developers.crunchydata.com/crunchydata/crunchy-pgbackrest:centos8-2.36-0
      configuration:
      - secret:
          name: pgo-s3-creds-location
      global:
        repo1-path: /pgbackrest/postgres-operator/location-s3
        repo1-retention-full: "14"
        repo1-retention-full-type: time
      repos:
      - name: repo1
        schedules:
          full: "0 0 14 * *"
        s3:
          bucket: "redacted"
          endpoint: "s3.us-east-1.amazonaws.com"
          region: "us-east-1"
      manual:
        repoName: repo1
        options:
         - --type=full
```

1. Port forward and connect with secret info
`√ s3 % kubectl apply -k .`

`configmap/location-init-sql unchanged`
`secret/pgo-s3-creds-location configured`
`postgrescluster.postgres-operator.crunchydata.com/location unchanged`

`√ s3 % kubectl get secret -n postgres-operator location-pguser-location -o yaml`
```yaml
apiVersion: v1
data:
  dbname: bG9jYXRpb24=
  host: --redacted--
  jdbc-uri: --redacted--
  password: --redacted--
  port: NTQzMg==
  uri: cG9zdGdyZXNxbDovL2xvY2F0aW9uOjM5My5EYS01JTI5aTBPaGxwQlI2JTJBJTI5SGQxLkBsb2NhdGlvbi1wcmltYXJ5LnBvc3RncmVzLW9wZXJhdG9yLnN2Yzo1NDMyL2xvY2F0aW9u
  user: bG9jYXRpb24=
  verifier: U0NSQU0tU0hBLTI1NiQ0MDk2Om5hUEJmZWVzNTBxcjdWYXZETVpZcmc9PSQwb0wyYXh0dmFPZ2EzQTgyOUJQRXdvSTVtdGtoWjBCbll2b3ZkdjBsSnpFPTplMGtPQkZKUzE1R0t3MXFEQnlHbUNnK1I3UWFHTVJqTTlhSjRsNkxJbk8wPQ==
kind: Secret
metadata:
  creationTimestamp: "2022-01-11T14:15:04Z"
  labels:
    postgres-operator.crunchydata.com/cluster: location
    postgres-operator.crunchydata.com/pguser: location
    postgres-operator.crunchydata.com/role: pguser
  name: location-pguser-location
  namespace: postgres-operator
  ownerReferences:
  - apiVersion: postgres-operator.crunchydata.com/v1beta1
    blockOwnerDeletion: true
    controller: true
    kind: PostgresCluster
    name: location
    uid: d641b9bc-bc62-41f4-8685-ed40db6da9a4
  resourceVersion: "197379241"
  uid: 9164f12d-9c13-4484-a14f-b5ea36f29888
type: Opaque
```
`?130 s3 % kubectl -n postgres-operator port-forward location-location1-8njt-0 5432:5432`
`Forwarding from 127.0.0.1:5432 -> 5432`
`Forwarding from [::1]:5432 -> 5432`

`√ s3 % psql -h localhost -U location`
```bash
Handling connection for 5432
Password for user location:
Handling connection for 5432
psql (14.1, server 13.5)
SSL connection (protocol: TLSv1.3, cipher: TLS_AES_256_GCM_SHA384, bits: 256, compression: off)
Type "help" for help.

location=# ^D\q`
```
The above works as expected

1. Delete the cluster
```bash
s3 % kubectl delete -k .
configmap "location-init-sql" deleted
secret "pgo-s3-creds-location" deleted
postgrescluster.postgres-operator.crunchydata.com "location" deleted```
1. Append the following to the postgres.yaml
```yaml
  service:
    type: LoadBalancer
```
1. Re-apply the kustomization
```bash
kubectl get service -n postgres-operator
#
NAME                        TYPE           CLUSTER-IP       EXTERNAL-IP                                                               PORT(S)          AGE
location-ha                 LoadBalancer   172.20.202.220   aa757880e068045d782d9fe1a9a22822-533924897.us-east-1.elb.amazonaws.com    5432:31210/TCP   2m39s
location-ha-config          ClusterIP      None             <none>                                                                    <none>           2m38s
location-pods               ClusterIP      None             <none>                                                                    <none>           2m39s
location-primary            ClusterIP      None             <none>                                                                    5432/TCP         2m38s
location-replicas           ClusterIP      172.20.184.28    <none>                                                                    5432/TCP         2m38s```

1. Attempt to connect via external name or port forward (with the newly created password from the secret)
```bash
s3 % psql -h aa757880e068045d782d9fe1a9a22822-533924897.us-east-1.elb.amazonaws.com -U location
Password for user location:
psql: error: connection to server at "aa757880e068045d782d9fe1a9a22822-533924897.us-east-1.elb.amazonaws.com" (52.200.204.21), port 5432 failed: FATAL:  password authentication failed for user "location"
s3 % psql -h localhost -U location
Password for user location:
psql: error: connection to server at "localhost" (::1), port 5432 failed: FATAL:  password authentication failed for user "location"
```

### EXPECTED

1. Expected successful connection to db

### ACTUAL

1. Password auth fails unless you manually connect to the container and update the password, backups also appear to not run.

## Logs
I see a number of these messages in the operator log after setting the service type to LoadBalancer:
```time="2022-01-11T14:40:02Z" level=error msg="Reconciler error" error="Service \"location-primary\" is invalid: spec.externalIPs[0]: Invalid value: \"\": must be a valid IP address, (e.g. 10.9.8.7 or 2001:db8::ffff)" file="internal/controller/postgrescluster/cluster.go:199" func="postgrescluster.(*Reconciler).reconcileClusterPrimaryService" name=location namespace=postgres-operator reconciler group=postgres-operator.crunchydata.com reconciler kind=PostgresCluster version=5.0.4-0```

## Additional Information

I would be be happy to provide any further information required
