### ISSUE TITLE
No `no pg_hba.conf` entry is created when creating a `REPLICATION` user

### ISSUE THREAD

**Issue by honne23** [CrunchyData/postgres-operator#2998]
Please ensure you do the following when reporting a bug:

- [ ] 
- This is running in kubernetes on GKE
- To reproduce, see the provided yaml, the `PGDELTA` golang project is used to access the slot here: https://github.com/hasura/pgdeltastream
- 
```
time="2022-01-27T15:18:31Z" level=error msg="unable to init session" error="FATAL: no pg_hba.conf entry for replication connection from host \"10.20.3.198\", user \"replicator\", SSL off (SQLSTATE 28000)"
```

## Overview

When creating a user using the `v5` chart with `REPLICATION` permissions, no `pg_hba.conf` entry is created for the user, thereby making it difficult to programmatically access a replication slot in the database.

## Environment

Please provide the following details:

- Platform: `GKE`
- Platform Version: `v1.22.2`
- PGO Image Tag: `centos8-2.33-2`
- Postgres Version: `13`
- Storage: Standard GKE storage class

## Steps to Reproduce
Create a user using the `v5` yaml with the `REPLICATION` option enabled.

### EXPECTED

1. A `pg_hba.conf` entry is created / appened upon database startup to give a replicated user the ability to create a slot.

### ACTUAL

1. A conf entry is not generated, instead the only way to access the replication slot is through `pg_recvlogical` rather than programmatically, such as using Golang.

## Logs

```
time="2022-01-27T15:18:31Z" level=error msg="unable to init session" error="FATAL: no pg_hba.conf entry for replication connection from host \"10.20.3.198\", user \"replicator\", SSL off (SQLSTATE 28000)"
```

**Comment by honne23** [comment]
Note this was resolved with the following config, however I think that added a replication user should edit `pg_hba.conf` as part of expected behaviour:

```yaml
apiVersion: postgres-operator.crunchydata.com/v1beta1
kind: PostgresCluster
metadata:
  name: my-company-db
spec:
  image: eu.gcr.io/my-company-295414/timescale-custom:v38
  postgresVersion: 13
  users:
    - name: postgres
      databases:
        - xworks
      options: "SUPERUSER REPLICATION"
    - name: replicator
      databases:
        - xworks
      options: "REPLICATION"
  instances:
    - name: instance1
      replicas: 3
      dataVolumeClaimSpec:
        accessModes:
          - "ReadWriteOnce"
        resources:
          requests:
            storage: 100Gi
  databaseInitSQL:
    key: init.sql
    name: my-company-init-sql
  patroni:
    dynamicConfiguration:
      postgresql:
        pg_hba:
          - "host all all 0.0.0.0/0 trust" # this line enabled logical replication with programmatic access
          - "host all postgres 127.0.0.1/32 md5"
  backups:
    pgbackrest:
      image: registry.developers.crunchydata.com/crunchydata/crunchy-pgbackrest:centos8-2.33-2
      repoHost:
        dedicated: {}
      repos:
        - name: repo1
          volume:
            volumeClaimSpec:
              accessModes:
                - "ReadWriteOnce"
              resources:
                requests:
                  storage: 300Gi
```

Additionally some guidance on making this more secure would be more than welcome / ideal.
