### ISSUE TITLE
Problem with scheduling PostgresCluster object with resource quota on namespace

### ISSUE THREAD

**Issue by lbartnicki92** [CrunchyData/postgres-operator#3000]
## Overview

PGO v.5.0.4 works fine when creating PG cluster in namespace mode. 
After creating simple resource quota in namespace, and creating postgrescluster object:

- operator pod starts and works fine
- pgo-repo-host starts and works fine
- postgres-primary not starting
- no info in logs, or K8s objects what is goin on

## Environment

- Platform: Kubernetes 
- Platform Version: v1.20.7
- PGO Image Tag: ubi8-5.0.4-0
- Postgres Version: 13
- Storage: Local Storage, Storage Class: DATA, WAL and BACKUP 

### REPRO

Steps to get to the error condition:

1. Install PGOperator v5.0.4
2. Create resource quota on namespace:
```apiVersion: v1
kind: ResourceQuota
metadata:
  name: quota
  namespace: system-dev
spec:
  hard:
    requests.cpu: "8.0"
    limits.cpu: "8.0"
    requests.memory: "20Gi"
    limits.memory: "20Gi"
```
3. Create PostgresCluster object with following YAML:
```
apiVersion: postgres-operator.crunchydata.com/v1beta1
kind: PostgresCluster
metadata:
  name: system-dev1
  namespace: system-dev
spec:
  image: harbor-repo/crunchydata/crunchydata/crunchy-postgres:centos8-13.5-0
  postgresVersion: 13
  service:
    type: NodePort
  instances:
    - name: primary
      replicas: 1
      resources:
        limits:
          cpu: "0.1"
          memory: "1Gi"
      dataVolumeClaimSpec:
        accessModes:
        - "ReadWriteOnce"
        storageClassName: "data"
        resources:
          requests:
            storage: "10Gi"
      walVolumeClaimSpec:
        accessModes:
        - "ReadWriteOnce"
        storageClassName: "wal"
        resources:
          requests:
            storage: "5Gi"
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/hostname
                operator: In
                values:
                - host1
  backups:
    pgbackrest:
      image: harbor-repo/crunchydata/crunchydata/crunchy-pgbackrest:centos8-2.36-0
      global:
        main-retention-full: "30"
      manual:
        repoName: repo1
        options:
         - --type=full
      repos:
      - name: repo1
        schedules:
          full: "0 17 * * *"
          incremental: "0 8 * * *"
        volume:
          volumeClaimSpec:
            accessModes:
            - "ReadWriteOnce"
            storageClassName: "backup"
            resources:
              requests:
                storage: "10Gi"
      repoHost:
        resources:
          limits:
            cpu: "0.1"
            memory: "1Gi"
        affinity:
          nodeAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              nodeSelectorTerms:
                - matchExpressions:
                  - key: kubernetes.io/hostname
                    operator: In
                    values:
                    - host2
  patroni:
    dynamicConfiguration:
      postgresql:
        parameters:
          max_parallel_workers: 2
          max_worker_processes: 2
          shared_buffers: "256MB"
          work_mem: "2MB"
  users:
    - name: system-dev
      databases:
       - "system-dev"
      options: "SUPERUSER"
  monitoring:
    pgmonitor:
      exporter:
       image: harbor-repo/crunchydata/crunchydata/crunchy-postgres-exporter:ubi8-5.0.4-0
```

### EXPECTED

PostgresCLuster deploying correctly. 

### ACTUAL

After creating pgo-repo-host nothing happen

## Additional Information

YAML with PostgresCluster definition works fine if there is not quota in namespaace, even when resources are definied in this YAML.
Kubernetes by design will not allow to deploy pods without resource settings set in namespace which has got quota defined. I look into Pod object and realized that there is no resource request for one of containers - replication-cert-copy. Output from succesful start without quota applied on namespace. 3 containers has got resource limits, replication-cert-copy doesn't have one:

```
kubectl describe system-dev1-primary-cl5s-0 -n system-dev
Name:         system-dev1-primary-cl5s-0
Namespace:    system-dev
Priority:     0
Node:         host1/10.2.241.7
Start Time:   Fri, 28 Jan 2022 11:35:04 +0100
Labels:       controller-revision-hash=system-dev1-primary-cl5s-59d959b4bf
              postgres-operator.crunchydata.com/cluster=system-dev1
              postgres-operator.crunchydata.com/crunchy-postgres-exporter=true
              postgres-operator.crunchydata.com/data=postgres
              postgres-operator.crunchydata.com/instance=system-dev1-primary-cl5s
              postgres-operator.crunchydata.com/instance-set=primary
              postgres-operator.crunchydata.com/patroni=system-dev1-ha
              postgres-operator.crunchydata.com/role=master
              statefulset.kubernetes.io/pod-name=system-dev1-primary-cl5s-0
Annotations:  cni.projectcalico.org/podIP: 10.233.122.93/32
              cni.projectcalico.org/podIPs: 10.233.122.93/32
              status:
                {"conn_url":"postgres://system-dev1-primary-cl5s-0.system-dev1-pods:5432/postgres","api_url":"https://system-dev1-primary-cl5s-0.system-dev1-pods:8008...
Status:       Running
IP:           10.233.122.93
IPs:
  IP:           10.233.122.93
Controlled By:  StatefulSet/system-dev1-primary-cl5s
Init Containers:
  postgres-startup:
    Container ID:  containerd://66188f34bb8fd8e8e197aa5b6b383ed6eaae07bda55083cb4b1af94af9a2f7c5
    Image:         harbor-repo/crunchydata/crunchydata/crunchy-postgres:centos8-13.5-0
    Image ID:      harbor-repo/crunchydata/crunchydata/crunchy-postgres@sha256:73b5dcf0c7de7d04e066133508a9a026f69de4bdccc7d0ab517ee0993e5389dd
    Port:          <none>
    Host Port:     <none>
    Command:
      bash
      -ceu
      --
      declare -r expected_major_version="$1" pgwal_directory="$2"
      results() { printf '::postgres-operator: %s::%s\n' "$@"; }
      safelink() (
        local desired="$1" name="$2" current
        current=$(realpath "${name}")
        if [ "${current}" = "${desired}" ]; then return; fi
        set -x; mv --no-target-directory "${current}" "${desired}"
        ln --no-dereference --force --symbolic "${desired}" "${name}"
      )
      echo Initializing ...
      results 'uid' "$(id -u)" 'gid' "$(id -G)"
      results 'postgres path' "$(command -v postgres)"
      results 'postgres version' "${postgres_version:=$(postgres --version)}"
      [[ "${postgres_version}" == *") ${expected_major_version}."* ]]
      results 'config directory' "${PGDATA:?}"
      postgres_data_directory=$([ -d "${PGDATA}" ] && postgres -C data_directory || echo "${PGDATA}")
      results 'data directory' "${postgres_data_directory}"
      [ "${postgres_data_directory}" = "${PGDATA}" ]
      bootstrap_dir="${postgres_data_directory}_bootstrap"
      [ -d "${bootstrap_dir}" ] && results 'bootstrap directory' "${bootstrap_dir}"
      [ -d "${bootstrap_dir}" ] && postgres_data_directory="${bootstrap_dir}"
      install --directory --mode=0700 "${postgres_data_directory}"
      install -D --mode=0600 -t "/tmp/replication" "/pgconf/tls/replication"/{tls.crt,tls.key,ca.crt}
      [ -f "${postgres_data_directory}/PG_VERSION" ] || exit 0
      results 'data version' "${postgres_data_version:=$(< "${postgres_data_directory}/PG_VERSION")}"
      [ "${postgres_data_version}" = "${expected_major_version}" ]
      safelink "${pgwal_directory}" "${postgres_data_directory}/pg_wal"
      results 'wal directory' "$(realpath "${postgres_data_directory}/pg_wal")"
      startup
      13
      /pgwal/pg13_wal
    State:          Terminated
      Reason:       Completed
      Exit Code:    0
      Started:      Fri, 28 Jan 2022 11:35:06 +0100
      Finished:     Fri, 28 Jan 2022 11:35:07 +0100
    Ready:          True
    Restart Count:  0
    Limits:
      cpu:     100m
      memory:  1Gi
    Requests:
      cpu:     100m
      memory:  1Gi
    Environment:
      PGDATA:  /pgdata/pg13
      PGHOST:  /tmp/postgres
      PGPORT:  5432
    Mounts:
      /pgconf/tls from cert-volume (ro)
      /pgdata from postgres-data (rw)
      /pgwal from postgres-wal (rw)
      /tmp from tmp (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from system-dev1-instance-token-5gxdm (ro)
  nss-wrapper-init:
    Container ID:  containerd://be964882596b111b4f69ffbebf1a43ca830f2e7d0f8ff9c640660e80ca2eefbd
    Image:         harbor-repo/crunchydata/crunchydata/crunchy-postgres:centos8-13.5-0
    Image ID:      harbor-repo/crunchydata/crunchydata/crunchy-postgres@sha256:73b5dcf0c7de7d04e066133508a9a026f69de4bdccc7d0ab517ee0993e5389dd
    Port:          <none>
    Host Port:     <none>
    Command:
      bash
      -c
      NSS_WRAPPER_SUBDIR=postgres CRUNCHY_NSS_USERNAME=postgres CRUNCHY_NSS_USER_DESC="postgres" /opt/crunchy/bin/nss_wrapper.sh
    State:          Terminated
      Reason:       Completed
      Exit Code:    0
      Started:      Fri, 28 Jan 2022 11:35:08 +0100
      Finished:     Fri, 28 Jan 2022 11:35:08 +0100
    Ready:          True
    Restart Count:  0
    Limits:
      cpu:     100m
      memory:  1Gi
    Requests:
      cpu:        100m
      memory:     1Gi
    Environment:  <none>
    Mounts:
      /tmp from tmp (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from system-dev1-instance-token-5gxdm (ro)
Containers:
  database:
    Container ID:  containerd://fe508cefacf236c4d63e973dca08716a9b101f5d39020f9450a81a2882686bc2
    Image:         harbor-repo/crunchydata/crunchydata/crunchy-postgres:centos8-13.5-0
    Image ID:      harbor-repo/crunchydata/crunchydata/crunchy-postgres@sha256:73b5dcf0c7de7d04e066133508a9a026f69de4bdccc7d0ab517ee0993e5389dd
    Port:          5432/TCP
    Host Port:     0/TCP
    Command:
      patroni
      /etc/patroni
    State:          Running
      Started:      Fri, 28 Jan 2022 11:35:09 +0100
    Ready:          True
    Restart Count:  0
    Limits:
      cpu:     100m
      memory:  1Gi
    Requests:
      cpu:      100m
      memory:   1Gi
    Liveness:   http-get https://:8008/liveness delay=3s timeout=5s period=10s #success=1 #failure=3
    Readiness:  http-get https://:8008/readiness delay=3s timeout=5s period=10s #success=1 #failure=3
    Environment:
      PGDATA:                              /pgdata/pg13
      PGHOST:                              /tmp/postgres
      PGPORT:                              5432
      PATRONI_NAME:                        system-dev1-primary-cl5s-0 (v1:metadata.name)
      PATRONI_KUBERNETES_POD_IP:            (v1:status.podIP)
      PATRONI_KUBERNETES_PORTS:            - name: postgres
                                             port: 5432
                                             protocol: TCP

      PATRONI_POSTGRESQL_CONNECT_ADDRESS:  $(PATRONI_NAME).system-dev1-pods:5432
      PATRONI_POSTGRESQL_LISTEN:           *:5432
      PATRONI_POSTGRESQL_CONFIG_DIR:       /pgdata/pg13
      PATRONI_POSTGRESQL_DATA_DIR:         /pgdata/pg13
      PATRONI_RESTAPI_CONNECT_ADDRESS:     $(PATRONI_NAME).system-dev1-pods:8008
      PATRONI_RESTAPI_LISTEN:              *:8008
      PATRONICTL_CONFIG_FILE:              /etc/patroni
      LD_PRELOAD:                          /usr/lib64/libnss_wrapper.so
      NSS_WRAPPER_PASSWD:                  /tmp/nss_wrapper/postgres/passwd
      NSS_WRAPPER_GROUP:                   /tmp/nss_wrapper/postgres/group
    Mounts:
      /dev/shm from dshm (rw)
      /etc/database-containerinfo from database-containerinfo (ro)
      /etc/patroni from patroni-config (ro)
      /etc/pgbackrest/conf.d from pgbackrest-config (rw)
      /etc/ssh from ssh (ro)
      /pgconf/tls from cert-volume (ro)
      /pgdata from postgres-data (rw)
      /pgwal from postgres-wal (rw)
      /tmp from tmp (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from system-dev1-instance-token-5gxdm (ro)
  replication-cert-copy:
    Container ID:  containerd://4813bb7e8bb91d309aafa6d5661ee05e703fec9a9acde66a695d35823567cca3
    Image:         harbor-repo/crunchydata/crunchydata/crunchy-postgres:centos8-13.5-0
    Image ID:      harbor-repo/crunchydata/crunchydata/crunchy-postgres@sha256:73b5dcf0c7de7d04e066133508a9a026f69de4bdccc7d0ab517ee0993e5389dd
    Port:          <none>
    Host Port:     <none>
    Command:
      bash
      -ceu
      --
      monitor() {
      declare -r directory="/pgconf/tls"
      exec {fd}<> <(:)
      while read -r -t 5 -u "${fd}" || true; do
        if [ "${directory}" -nt "/proc/self/fd/${fd}" ] &&
          install -D --mode=0600 -t "/tmp/replication" "${directory}"/{replication/tls.crt,replication/tls.key,replication/ca.crt} &&
          pkill -HUP --exact --parent=1 postgres
        then
          exec {fd}>&- && exec {fd}<> <(:)
          stat --format='Loaded certificates dated %y' "${directory}"
        fi
      done
      }; export -f monitor; exec -a "$0" bash -ceu monitor
      replication-cert-copy
    State:          Running
      Started:      Fri, 28 Jan 2022 11:35:09 +0100
    Ready:          True
    Restart Count:  0
    Environment:    <none>
    Mounts:
      /pgconf/tls from cert-volume (ro)
      /tmp from tmp (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from system-dev1-instance-token-5gxdm (ro)
  pgbackrest:
    Container ID:  containerd://b10c17a28b1ead4bf7b560cd72f3b48e9b54c1aa1b9c6695908ee8e254763bad
    Image:         harbor-repo/crunchydata/crunchydata/crunchy-pgbackrest:centos8-2.36-0
    Image ID:      harbor-repo/crunchydata/crunchydata/crunchy-pgbackrest@sha256:b2fac1254dd92886bf8563adc0ed80221fc0bbcb6ef2e77150ad01811b9b8e85
    Port:          <none>
    Host Port:     <none>
    Command:
      /usr/sbin/sshd
      -D
      -e
    State:          Running
      Started:      Fri, 28 Jan 2022 11:35:09 +0100
    Ready:          True
    Restart Count:  0
    Liveness:       tcp-socket :2022 delay=0s timeout=1s period=10s #success=1 #failure=3
    Environment:
      LD_PRELOAD:          /usr/lib64/libnss_wrapper.so
      NSS_WRAPPER_PASSWD:  /tmp/nss_wrapper/postgres/passwd
      NSS_WRAPPER_GROUP:   /tmp/nss_wrapper/postgres/group
    Mounts:
      /etc/pgbackrest/conf.d from pgbackrest-config (rw)
      /etc/ssh from ssh (ro)
      /pgdata from postgres-data (rw)
      /pgwal from postgres-wal (rw)
      /tmp from tmp (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from system-dev1-instance-token-5gxdm (ro)
  exporter:
    Container ID:  containerd://a65bcdaa8d8ea398d936aecbed389129e0afe5ba578bf1822f693d855755e5b0
    Image:         harbor-repo/crunchydata/crunchydata/crunchy-postgres-exporter:ubi8-5.0.4-0
    Image ID:      harbor-repo/crunchydata/crunchydata/crunchy-postgres-exporter@sha256:6d9e9f4886bf625b87b202aab14ff8ab844171aa551571931777870ba8ebebcc
    Port:          9187/TCP
    Host Port:     0/TCP
    Command:
      /opt/cpm/bin/start.sh
    State:          Running
      Started:      Fri, 28 Jan 2022 11:35:09 +0100
    Ready:          True
    Restart Count:  0
    Environment:
      CONFIG_DIR:                           /opt/cpm/conf
      POSTGRES_EXPORTER_PORT:               9187
      PGBACKREST_INFO_THROTTLE_MINUTES:     10
      PG_STAT_STATEMENTS_LIMIT:             20
      PG_STAT_STATEMENTS_THROTTLE_MINUTES:  -1
      EXPORTER_PG_HOST:                     localhost
      EXPORTER_PG_PORT:                     5432
      EXPORTER_PG_DATABASE:                 postgres
      EXPORTER_PG_USER:                     ccp_monitoring
      EXPORTER_PG_PASSWORD:                 <set to the key 'password' in secret 'system-dev1-monitoring'>  Optional: false
    Mounts:
      /conf from exporter-config (rw)
      /tmp from tmp (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from system-dev1-instance-token-5gxdm (ro)
Conditions:
  Type              Status
  Initialized       True
  Ready             True
  ContainersReady   True
  PodScheduled      True
Volumes:
  cert-volume:
    Type:                Projected (a volume that contains injected data from multiple sources)
    SecretName:          system-dev1-cluster-cert
    SecretOptionalName:  <nil>
    SecretName:          system-dev1-replication-cert
    SecretOptionalName:  <nil>
  postgres-data:
    Type:       PersistentVolumeClaim (a reference to a PersistentVolumeClaim in the same namespace)
    ClaimName:  system-dev1-primary-cl5s-pgdata
    ReadOnly:   false
  database-containerinfo:
    Type:  DownwardAPI (a volume populated by information about the pod)
    Items:
      limits.cpu -> cpu_limit
      requests.cpu -> cpu_request
      limits.memory -> mem_limit
      requests.memory -> mem_request
      metadata.labels -> labels
      metadata.annotations -> annotations
  postgres-wal:
    Type:       PersistentVolumeClaim (a reference to a PersistentVolumeClaim in the same namespace)
    ClaimName:  system-dev1-primary-cl5s-pgwal
    ReadOnly:   false
  patroni-config:
    Type:                Projected (a volume that contains injected data from multiple sources)
    ConfigMapName:       system-dev1-config
    ConfigMapOptional:   <nil>
    ConfigMapName:       system-dev1-primary-cl5s-config
    ConfigMapOptional:   <nil>
    SecretName:          system-dev1-primary-cl5s-certs
    SecretOptionalName:  <nil>
  ssh:
    Type:                Projected (a volume that contains injected data from multiple sources)
    ConfigMapName:       system-dev1-ssh-config
    ConfigMapOptional:   <nil>
    SecretName:          system-dev1-ssh
    SecretOptionalName:  <nil>
  pgbackrest-config:
    Type:               Projected (a volume that contains injected data from multiple sources)
    ConfigMapName:      system-dev1-pgbackrest-config
    ConfigMapOptional:  <nil>
  exporter-config:
    Type:  Projected (a volume that contains injected data from multiple sources)
  tmp:
    Type:       EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:
    SizeLimit:  16Mi
  dshm:
    Type:       EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:     Memory
    SizeLimit:  <unset>
  system-dev1-instance-token-5gxdm:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  system-dev1-instance-token-5gxdm
    Optional:    false
QoS Class:       Burstable
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/not-ready:NoExecute op=Exists for 300s
                 node.kubernetes.io/unreachable:NoExecute op=Exists for 300s
Events:
  Type    Reason     Age    From               Message
  ----    ------     ----   ----               -------
  Normal  Scheduled  2m11s  default-scheduler  Successfully assigned system-dev/system-dev1-primary-cl5s-0 to host1
  Normal  Pulled     2m9s   kubelet            Container image "harbor-repo/crunchydata/crunchydata/crunchy-postgres:centos8-13.5-0" already present on machine
  Normal  Created    2m9s   kubelet            Created container postgres-startup
  Normal  Started    2m9s   kubelet            Started container postgres-startup
  Normal  Pulled     2m7s   kubelet            Container image "harbor-repo/crunchydata/crunchydata/crunchy-postgres:centos8-13.5-0" already present on machine
  Normal  Created    2m7s   kubelet            Created container nss-wrapper-init
  Normal  Started    2m7s   kubelet            Started container nss-wrapper-init
  Normal  Started    2m6s   kubelet            Started container database
  Normal  Created    2m6s   kubelet            Created container database
  Normal  Pulled     2m6s   kubelet            Container image "harbor-repo/crunchydata/crunchydata/crunchy-postgres:centos8-13.5-0" already present on machine
  Normal  Pulled     2m6s   kubelet            Container image "harbor-repo/crunchydata/crunchydata/crunchy-postgres:centos8-13.5-0" already present on machine
  Normal  Created    2m6s   kubelet            Created container replication-cert-copy
  Normal  Started    2m6s   kubelet            Started container replication-cert-copy
  Normal  Pulled     2m6s   kubelet            Container image "harbor-repo/crunchydata/crunchydata/crunchy-pgbackrest:centos8-2.36-0" already present on machine
  Normal  Created    2m6s   kubelet            Created container pgbackrest
  Normal  Started    2m6s   kubelet            Started container pgbackrest
  Normal  Pulled     2m6s   kubelet            Container image "harbor-repo/crunchydata/crunchydata/crunchy-postgres-exporter:ubi8-5.0.4-0" already present on machine
  Normal  Created    2m6s   kubelet            Created container exporter
  Normal  Started    2m6s   kubelet            Started container exporter
```
