### ISSUE TITLE
pgbackrest restore nss-wrapper-init resources requests/limits

### ISSUE THREAD

**Issue by djtaylor** [CrunchyData/postgres-operator#3001]
## Overview

I am attempting to create a restore job in a namespace where resource requests/limits are mandatory. It is unclear how to set resources for the `nss-wrapper-init` container for the restore job. It is currently failing to start due to the lack of resources set on the container.

## Environment

Please provide the following details:

- Platform: `Kubernetes`
- Platform Version: `1.18.18`
- PGO Image Tag: `ubi8-5.0.4-0`
- Postgres Version `13`
- Storage: `s3`

## Steps to Reproduce

1.) Attempt to create a restore job via the process in https://access.crunchydata.com/documentation/postgres-operator/v5/tutorial/disaster-recovery/#perform-an-in-place-point-in-time-recovery-pitr, in a namespace that requires resources be set on all containers.

### EXPECTED

1. The Job starts up as expected.

### ACTUAL

`Error creating: pods "harbor-db-pgbackrest-restore-8drq8" is forbidden: failed quota: compute-resources: must specify limits.cpu,limits.memory,requests.cpu,requests.memory`

## Additional Information

The following is a snippet from my `postgrescluster` definition:

```yaml
spec:
  backups:
    pgbackrest:
      global: <redacted s3 information>
      jobs:
        resources:
          limits:
            cpu: 250m
            memory: 128Mi
          requests:
            cpu: 250m
            memory: 128Mi
      manual:
        options:
        - --type=full
        repoName: repo1
      repos:
      - name: repo1
        s3:
          bucket: <my bucket name>
          endpoint: <my s3 endpoint>
          region: <my s3 region>
        schedules:
          full: 0 1 * * *
          incremental: 0 */4 * * *
      restore:
        enabled: true
        options:
        - --type=time
        - --time="2022-01-29 21:30:00-00"
        repoName: repo1
        resources:
          limits:
            cpu: 500m
            memory: 256Mi
          requests:
            cpu: 500m
            memory: 256Mi
```

I am not sure if there is an additional `resources` block I need to define elsewhere to ensure that the `nss-wrapper-init` container has these values set, but I have not had the issue with other jobs, such as the backup job. Any information would be appreciated.
