### ISSUE TITLE
Not able to setup standby cluster

### ISSUE THREAD

**Issue by benjamin-bergia** [CrunchyData/postgres-operator#3004]
Hi,

I am trying to migrate our production database to PGO. I have setup pgbackrest on my current production machine, taken some backups and configured the archiving. Here is the configuration of pgbackrest on my current production machine:
```
[global]
log-path=/tmp
repo1-type=s3
repo1-path=/pgbackrest/myNamespace/myApp/
repo1-s3-bucket=mybucket
repo1-s3-endpoint=***
repo1-s3-region=test
repo1-s3-key=***
repo1-s3-key-secret=***
repo1-storage-verify-tls=n
start-fast=y

[db]
pg1-path=/pgdata/pg14
pg1-user=postgres
```
Here is my cluster manifest:
```yaml
apiVersion: postgres-operator.crunchydata.com/v1beta1
kind: PostgresCluster
metadata:
  name: postgres-myApp
  namespace: myNamespace
spec:
  backups:
    pgbackrest:
      configuration:
      - secret:
          name: myApp-s3-postgres-creds
      global:
        repo1-path: /pgbackrest/myNamespace/myApp/
      image: registry.developers.crunchydata.com/crunchydata/crunchy-pgbackrest:centos8-2.35-0
      repos:
      - name: repo1
        s3:
          bucket: myBucket
          endpoint: ***
          region: test
  image: registry.developers.crunchydata.com/crunchydata/crunchy-postgres:centos8-14.0-0
  instances:
  - dataVolumeClaimSpec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 1000Gi
      storageClassName: myStorageClass
    name: primary
    replicas: 1
    tolerations:
    - effect: NoSchedule
      key: reservedFor
      value: database
  monitoring:
    pgmonitor:
      exporter:
        image: registry.developers.crunchydata.com/crunchydata/crunchy-postgres-exporter:ubi8-5.0.4-0
  patroni:
    dynamicConfiguration:
      postgresql:
        parameters:
          effective_cache_size: 56GB
          maintenance_work_mem: 128MB
          max_connections: 300
          max_parallel_maintenance_workers: 8
          random_page_cost: 2
          shared_buffers: 8GB
  postgresVersion: 14
  proxy:
    pgBouncer:
      config:
        global:
          application_name_add_host: "1"
          default_pool_size: "100"
          max_client_conn: "300"
          pool_mode: session
      image: registry.developers.crunchydata.com/crunchydata/crunchy-pgbouncer:centos8-1.15-3
      replicas: 2
  standby:
    enabled: true
    repoName: repo1
  users:
  - name: myDB
    options: NOSUPERUSER
  - databases:
    - myDB
    name: userA
    options: NOSUPERUSER
  - databases:
    - myDB
    name: userB
    options: NOSUPERUSER
```
And the pgbackrest config that has been generated by the controller:
```
cat /etc/pgbackrest/conf.d/pgbackrest_instance.conf 
[global]
log-path=/tmp
repo1-path=/pgbackrest/myNamespace/myApp/
repo1-s3-bucket=mybucket
repo1-s3-endpoint=***
repo1-s3-region=test
repo1-type=s3

[db]
pg1-path=/pgdata/pg14
pg1-port=5432
pg1-socket-path=/tmp/postgres
```

When creating the cluster I get the following:
```
2022-01-31 08:56:40,873 INFO: Lock owner: None; I am postgres-myApp-primary-dbmh-0
2022-01-31 08:56:40,874 INFO: trying to bootstrap (without leader)
WARN: --delta or --force specified but unable to find 'PG_VERSION' or 'backup.manifest' in '/pgdata/pg14' to confirm that this is a valid $PGDATA directory.  --delta and --force have been disabled and if any files exist in the destination directories the restore will be aborted.
ERROR: [078]: unable to remap invalid link 'pg_wal'
2022-01-31 08:56:41,033 ERROR: Error creating replica using method pgbackrest: 'bash' '-ceu' '--' 'install --directory --mode=0700 "${PGDATA?}" && exec "$@"' '-' 'pgbackrest' 'restore' '--delta' '--stanza=db' '--repo=1' '--link-map=pg_wal=/pgdata/pg14_wal' exited with code=78
2022-01-31 08:56:41,033 ERROR: failed to bootstrap (without leader)
2022-01-31 08:56:41,033 INFO: Removing data directory: /pgdata/pg14
```

From the pod in question (the one created by the controller), I am able to see all my backups:
```
pgbackrest --stanza=db info
stanza: db
    status: ok
    cipher: none

    db (current)
        wal archive min/max (14): 000000010000117A0000004F/0000000100001199000000A5

        full backup: 20220126-115031F
            timestamp start/stop: 2022-01-27 15:21:27 / 2022-01-27 21:44:58
            wal start/stop: 0000000100001192000000FB / 000000010000119300000025
            database size: 584.7GB, database backup size: 584.7GB
            repo1: backup set size: 357GB, backup size: 357GB

        incr backup: 20220126-115031F_20220128-064935I
            timestamp start/stop: 2022-01-28 06:49:35 / 2022-01-28 09:42:07
            wal start/stop: 000000010000119400000054 / 00000001000011940000005C
            database size: 584.8GB, database backup size: 185.0GB
            repo1: backup set size: 357GB, backup size: 73.4GB
            backup reference list: 20220126-115031F

        full backup: 20220128-125406F
            timestamp start/stop: 2022-01-28 12:55:18 / 2022-01-28 23:37:36
            wal start/stop: 000000010000119400000092 / 0000000100001196000000A3
            database size: 584.8GB, database backup size: 584.8GB
            repo1: backup set size: 357.1GB, backup size: 357.1GB
```

I cleaned up some of the sensitive info but basically all the s3 config (bucket, endpoint, path, etc...) match on both config files. Also I had a previous attempt with the same dataset on a test machine and it worked. I have no idea what I am missing here.

Versions:
-  Kubernetes: 1.21
- PGO: ubi8-5.0.4-0
