### ISSUE TITLE
spec.users not creating any users in 4.7.4

### ISSUE THREAD

**Issue by stemid** [CrunchyData/postgres-operator#3031]
I'm using pgo 4.7.4.

[The docs for user management](https://access.crunchydata.com/documentation/postgres-operator/5.0.4/tutorial/user-management/) say I should use spec.users to define custom users.

But none of those users are being created, I only get the default users and when I login with postgres and run `\du+` I see no other users from that list.

I'm confused, are the docs for 4.7 or for 5.0? I noticed the master branch docs have a PostgresCluster kind while the 4.7 docs mention Pgcluster. What is the correct way to create users in 4.7 release?

Here is my manifest (in ansible template format); 

```
{% if pgo_clusters is defined %}
{% for cluster in pgo_clusters %}
{% if cluster.backrest_s3_bucket is defined %}
apiVersion: v1
kind: Secret
metadata:
  name: {{ cluster.name }}-backrest-s3-config
  namespace: {{ cluster.namespace }}
data:
  aws-s3-key: {{ cluster.backrest_s3_key | string | b64encode }}
  aws-s3-key-secret: {{ cluster.backrest_s3_secret | string | b64encode }}

---
{% endif %}

apiVersion: crunchydata.com/v1
kind: Pgcluster
metadata:
  annotations:
    current-primary: {{ cluster.name }}
  labels:
    crunchy-pgha-scope: {{ cluster.name }}
    deployment-name: {{ cluster.name }}
    name: {{ cluster.name }}
    pg-cluster: {{ cluster.name }}
    pgo-version: 4.7.4
    pgouser: admin
  name: {{ cluster.name }}
  namespace: {{ cluster.namespace }}
spec:
  BackrestStorage:
    accessmode: ReadWriteMany
    matchLabels: ""
    name: ""
    size: 10G
    storageclass: ""
    storagetype: dynamic
    supplementalgroups: ""
  PrimaryStorage:
    accessmode: ReadWriteMany
    matchLabels: ""
    name: {{ cluster.name }}
    size: 60G
    storageclass: ""
    storagetype: dynamic
    supplementalgroups: ""
  ReplicaStorage:
    accessmode: ReadWriteMany
    matchLabels: ""
    name: ""
    size: 60G
    storageclass: ""
    storagetype: dynamic
    supplementalgroups: ""
  annotations: {}
  backrestStorageTypes:
  - s3
  backrestS3Bucket: {{ cluster.backrest_s3_bucket }}
  backrestS3Endpoint: {{ cluster.backrest_s3_endpoint }}
  backrestS3Region: {{ cluster.backrest_s3_region }}
  backrestS3URIStyle: ""
  backrestS3VerifyTLS: ""
  ccpimage: crunchy-postgres-ha
  ccpimageprefix: registry.developers.crunchydata.com/crunchydata
  ccpimagetag: centos8-13.5-4.7.4
  clustername: {{ cluster.name }}
  database: {{ cluster.name }}
  exporterport: "9187"
  limits: {}
  name: {{ cluster.name }}
  pgDataSource:
    restoreFrom: ""
    restoreOpts: ""
  pgbadgerport: "10000"
  pgoimageprefix: registry.developers.crunchydata.com/crunchydata
  podAntiAffinity:
    default: preferred
    pgBackRest: preferred
    pgBouncer: preferred
  port: "5432"
  tolerations: []
  #user: {{ cluster.admin_username }}
  userlabels:
    pgo-version: 4.7.4
  users:
{% for user in cluster.users %}
    - name: {{ user.name }}
      databases:
{% for db in user.databases %}
        - {{ db }}
{% endfor %}
{% endfor %}

---

{% endfor %}
{% endif %}
```
