### ISSUE TITLE
pgAdmin in v5

### ISSUE THREAD

**Issue by rahulbreezo** [CrunchyData/postgres-operator#3032]
## Overview

I am trying to add pgAdmin in v5,   though there are no docs for pgAdminin v5 but PR for this seems merged: https://github.com/CrunchyData/postgres-operator/pull/2786

but When I tried to deploy pgAdmin using this :

```
  userInterface:
    pgAdmin:
      dataVolumeClaimSpec:
        accessModes:
          - 'ReadWriteOnce'
        storageClassName: resize-io2
      service:
        type: LoadBalancer
```

I get error: 
`error: error validating "db/patches/staging/": error validating data: ValidationError(PostgresCluster.spec): unknown field "userInterface" in com.crunchydata.postgres-operator.v1beta1.PostgresCluster.spec; if you choose to ignore these errors, turn validation off with --validate=false`, 

So I am not sure its releases in v5 or not,

## Environment

Please provide the following details:

- Platform: (`Kubernetes`, `EKS`)
- PGO Version: `5.0.4`
- Postgres Version `14`
