### ISSUE TITLE
PgBouncer can't connect to hippo-replicas service (SSL error) 

### ISSUE THREAD

**Issue by jashanbhullar** [CrunchyData/postgres-operator#3043]
## Overview

The pgbouncer can't connect to the replicas service because `hippo-replicas` is added as SAN in the primary certificate. 

## Environment

Please provide the following details:

- Platform: minikube
- Platform Version: 5.0.4
- PGO Image Tag: ubi8-5.0.4-0
- Postgres Version 13
- Storage: minikube-default 

## Steps to Reproduce

`kubectl apply -f [following-template]`
```
apiVersion: postgres-operator.crunchydata.com/v1beta1
kind: PostgresCluster
metadata:
  name: hippo
spec:
  image: registry.developers.crunchydata.com/crunchydata/crunchy-postgres-gis:centos8-13.5-3.1-0
  postgresVersion: 13
  instances:
    - name: instance1
      replicas: 2
      dataVolumeClaimSpec:
        accessModes:
          - "ReadWriteOnce"
        resources:
          requests:
            storage: 1Gi
  backups:
    pgbackrest:
      image: registry.developers.crunchydata.com/crunchydata/crunchy-pgbackrest:centos8-2.36-0
      repos:
        - name: repo1
          volume:
            volumeClaimSpec:
              accessModes:
                - "ReadWriteOnce"
              resources:
                requests:
                  storage: 1Gi
  users:
    - name: db-user
      databases:
        - sample-db
  proxy:
    pgBouncer:
      image: registry.developers.crunchydata.com/crunchydata/crunchy-pgbouncer:centos8-1.16-0
      replicas: 1
      config:
        databases:
          # Added separate endpoints for read-write instances
          "sample-db-read": "host=hippo-replicas port=5432 dbname=sample-db"
          "sample-db-read-write": "host=hippo-primary port=5432 dbname=sample-db"
```

while `sample-db-read-write` will work, `sample-db-read` won't be able to connect!

### REPRO

Provide steps to get to the error condition:

Try
```
kubectl port-forward svc/hippo-pgbouncer 5432:5432 -n postgres-operator
psql postgresql://db-user@localhost:5432/sample-db-read-write?sslmode=require # will work 
psql postgresql://db-user@localhost:5432/sample-db-read?sslmode=require # won't work 
```

### EXPECTED

1.Expected pgbouncer to connect to `hippo-replicas` services

## Logs

```
2022-02-17 10:30:38.503 UTC [7] LOG S-0x558692995600: sample-db-read/_crunchypgbouncer@10.98.194.133:5432 new connection to server (from 172.17.0.7:41908)
2022-02-17 10:30:38.508 UTC [7] WARNING TLS handshake error: name `hippo-replicas' not present in server certificate
2022-02-17 10:30:38.508 UTC [7] LOG S-0x558692995600: sample-db-read/_crunchypgbouncer@10.98.194.133:5432 closing because: server conn crashed? (age=0s)
2022-02-17 10:30:42.505 UTC [7] LOG stats: 0 xacts/s, 0 queries/s, in 0 B/s, out 6 B/s, xact 0 us, query 0 us, wait 288 us
```

## Additional Information

While our use case does not require us to use SSL so I tried disabling SSL and then connecting. That leads to a separate error. 
Disabling SSL via https://github.com/CrunchyData/postgres-operator/issues/2534#issuecomment-891202207 and https://github.com/CrunchyData/postgres-operator/issues/2769#issuecomment-995793809 leads 

```
2022-02-17 10:35:28.266 UTC [7] LOG S-0x55c3fe9e2530: sample-db-read-write/_crunchypgbouncer@10.103.241.29:5432 new connection to server (from 172.17.0.10:50990)
2022-02-17 10:35:28.269 UTC [7] WARNING server login failed: FATAL pg_hba.conf rejects connection for host "172.17.0.1", user "_crunchypgbouncer", database "sample-db", SSL off
2022-02-17 10:35:28.269 UTC [7] LOG S-0x55c3fe9e2530: sample-db-read-write/_crunchypgbouncer@10.103.241.29:5432 closing because: login failed (age=0s)
2022-02-17 10:35:29.333 UTC [7] LOG stats: 0 xacts/s, 0 queries/s, in 0 B/s, out 0 B/s, xact 0 us, query 0 us, wait 0 us 
```
Which is because `pg_hba.conf` looks like this in the pod 
```
# Do not edit this file manually!
# It will be overwritten by Patroni!
local all "postgres" peer
hostssl replication "_crunchyrepl" all cert
hostssl "postgres" "_crunchyrepl" all cert
host all "_crunchyrepl" all reject
hostssl all "_crunchypgbouncer" all scram-sha-256
host all "_crunchypgbouncer" all reject
hostnossl all all all md5
```
The second last line rejects the connection for `pgBouncer`. The code for this is at https://github.com/CrunchyData/postgres-operator/blob/master/internal/pgbouncer/postgres.go#L231-L232

For now, I was able to solve this by creating my certificates and adding `hippo-replicas` as SAN in the certificate. Not sure if that's the best approach. 

Not sure how you would want to handle a case as such. I checked the code with `Mandatory fields`  and it feels pretty solid to me. If you can guide, I contribute towards a patch to this!

**Comment by jmckulk** [comment]
Hey there, thanks for the detailed issue! I was able to replicate your issue when trying to connect pgBouncer to a replica service. This is not something that we directly support at the time but we think you are on the right track. If you do not require SSL you can lower the validation that pgBouncer uses to check the cert.
https://www.pgbouncer.org/config.html#server_tls_sslmode

```
      config:
        global:
          "server_tls_sslmode": "verify-ca"
        databases:
          # Added separate endpoints for read-write instances
          "sample-db-read": "host=hippo-replicas port=5432 dbname=sample-db"
          "sample-db-read-write": "host=hippo-primary port=5432 dbname=sample-db"
```

Try this out and let us know if it works for you
