### ISSUE TITLE
javax.net.ssl.SSLPeerUnverifiedException: peer not authenticated

### ISSUE THREAD

**Issue by nnachefski** [CrunchyData/postgres-operator#3048]
Hello,

I have a postgres DB created by Crunchydata operator (postgresoperator.v5.0.4)  deployed to an Openshift OKD 4.9 cluster.

I'm getting this error occasionally from the clients:

```
Failed to parse response from server when performing POST to URL https://<DB_NAME>-dev.apps.okd.<DOMAIM_NAME>/ - javax.net.ssl.SSLPeerUnverifiedException: peer not authenticated
ca.uhn.fhir.rest.client.exceptions.FhirClientConnectionException: Failed to parse response from server when performing POST to URL https://fhir-st-mpi-clinical-dev.apps.okd.healthconcourse.com/ - javax.net.ssl.SSLPeerUnverifiedException: peer not authenticated
	at ca.uhn.fhir.rest.client.impl.BaseClient.invokeClient(BaseClient.java:400)
```

Herre is my deployment config:

```
apiVersion: postgres-operator.crunchydata.com/v1beta1
kind: PostgresCluster
metadata:
  name: clinicalfhir
spec:
  image: registry.developers.crunchydata.com/crunchydata/crunchy-postgres:centos8-13.5-0
  postgresVersion: 13
  openshift: true
  databaseInitSQL:
    key: clinical-fhir-init.sql
    name: clinical-fhir-init-sql
  users:
    - name: pgadmin
      options: "SUPERUSER"
    - name: devfhir
      databases:
        - clinicalfhir
      options: "SUPERUSER"
  instances:
    - name: instance1
      replicas: 1
      resources:
        limits:
          cpu: 1.0
          memory: 2Gi
      dataVolumeClaimSpec:
        accessModes:
        - "ReadWriteOnce"
        resources:
          requests:
            storage: 10Gi
  backups:
    pgbackrest:
      image: registry.developers.crunchydata.com/crunchydata/crunchy-pgbackrest:centos8-2.36-0
      repoHost:
        dedicated: {}
      repos:
      - name: repo1
        volume:
          volumeClaimSpec:
            accessModes:
            - "ReadWriteOnce"
            resources:
              requests:
                storage: 10Gi
```

I dont see any SSL errors in the pgo operator itself.  Any help would be greatly appreciated.

-Nick
