### ISSUE TITLE
Reduce WAL pressure

### ISSUE THREAD

**Issue by benjamin-bergia** [CrunchyData/postgres-operator#3055]
I am currently struggling to run timescaledb on my instances. I have access to storage with a limited bandwidth and the huge amount of WALs that my instances generate with `wal_level = 'logical'` just doesn't cut it, despite using a separate PVC. I have pretty lax requirements. I do not need incremental backups and I can afford to lose the data between two full backups (daily full backup). I also don't use any standby, replica, etc.

After trying to set wal_level in the cluster definition using `patroni.dynamicConfiguration`, I noticed that it is overwritten. Is it possilble to have basic log archiving using the `minimal` log level and still have full backups?

**Comment by tjmoore4** [comment]
Hello @benjamin-bergia. It appears you are using PGO v5, but other details would be helpful as well. Your exact PGO version, your PostgresCluster definition and environment details (Kubernetes version, etc) would give a better idea of what options may be available.

**Comment by benjamin-bergia** [comment]
Sure,

I am using:
- Kubernetes v1.21
- [This kustomize file](https://github.com/CrunchyData/postgres-operator-examples/tree/main/kustomize/install) for the operator so the version should be 5.0.4

And here is my cluster definition:
```yaml
apiVersion: postgres-operator.crunchydata.com/v1beta1
kind: PostgresCluster
metadata:
  name: metrics-postgres
spec:
  image: myregistry/myproject/crunchy-postgres@sha256:94c1162fe12cde697049168a0c8474a7983bb28404c025c7d358cb021c451090
  postgresVersion: 13
  instances:
    - name: primary
      dataVolumeClaimSpec:
        storageClassName: 'io'
        accessModes:
          - 'ReadWriteOnce'
        resources:
          requests:
            storage: '2000Gi'
      walVolumeClaimSpec:
        storageClassName: 'io'
        accessModes:
          - 'ReadWriteOnce'
        resources:
          requests:
            storage: '300Gi'
      tolerations:
        - key: 'reservedFor'
          value: 'database'
          effect: 'NoSchedule'

  backups:
    pgbackrest:
      image: registry.developers.crunchydata.com/crunchydata/crunchy-pgbackrest:centos8-2.35-0
      global:
        archive-async: 'y'
        spool-path: '/pgwal/pgbackrest/spool'
        archive-push-queue-max: 200GB
        process-max: '4'
        repo1-path: '/pgbackrest/metrics-db/metrics-db'
        repo1-retention-full: '3'
        repo1-retention-full-type: time
        repo1-retention-archive-type: 'full'
        repo1-retention-archive: '1'
      configuration:
        - secret:
            name: ***
      repos:
        - name: repo1
          s3:
            endpoint: '***'
            region: '***'
            bucket: '***'
          schedules:
            full: '0 0/12 * * *'

  monitoring:
    pgmonitor:
      exporter:
        image: registry.developers.crunchydata.com/crunchydata/crunchy-postgres-exporter:ubi8-5.0.4-0

  users:
    - name: promscale
      options: 'SUPERUSER'

  patroni:
    dynamicConfiguration:
      postgresql:
        parameters:
          shared_preload_libraries: timescaledb,promscale
          timescaledb.license: timescale
          # Generated by timescaledb-tune
          shared_buffers: 14714MB
          effective_cache_size: 44143MB
          maintenance_work_mem: 2047MB
          work_mem: 4708kB
          timescaledb.max_background_workers: 8
          max_worker_processes: 43
          max_parallel_maintenance_workers: 12
          max_parallel_workers_per_gather: 16
          max_parallel_workers: 32
          wal_buffers: 16MB
          min_wal_size: 512MB
          max_wal_size: 4GB
          default_statistics_target: 500
          random_page_cost: 1.1
          checkpoint_completion_target: 0.9
          max_connections: 100
          max_locks_per_transaction: 512
          autovacuum_max_workers: 10
          autovacuum_naptime: 10
          effective_io_concurrency: 256
          log_checkpoints: t
          wal_level: replica
```
As explained in [here](https://github.com/CrunchyData/postgres-operator/issues/2692#issuecomment-1047148471), I am running a custom image based on the crunchy one just to switch the license and add the promscale extension.
