### ISSUE TITLE
Operator Version 5.0.5 PGBackRest Restore doesnt work when using web-id value for repo1-s3-key-type

### ISSUE THREAD

**Issue by MrBones757** [CrunchyData/postgres-operator#3069]
## Overview

When running operator v 5.0.5 and attempting to use the new spec.dataSource.pgbackrest options, the jobs fail to run because required parameters / config for web-id are not present

## Environment

Please provide the following details:

- Platform: EKS
- Platform Version: 1.21.5
- PGO Image Tag: ubi8-5.0.5-0
- Postgres Version: 12
- Storage: PGDATA - aws-csi (ebs), Backups - S3

## Steps to Reproduce

Attempt to restore a cluster from a backup using the web-identity method for pgbackrest

```yaml
 dataSource
    pgbackrest:
      stanza: db
      global:
        repo1-path: {{ backup_restore_path }}
        repo1-s3-key-type: web-id
      repo:
        name: repo1
        s3:
          bucket: your-cool-s3-bucket
          endpoint: s3.<region>.amazonaws.com
          region: <region>
 metadata:
    annotations:
      eks.amazonaws.com/role-arn: <your-cool-role-arn>
```

### EXPECTED

The restore is able to connect to S3 and download the backup files

### ACTUAL

The backup jobs fail continuously due to missing data and config

## Logs
WARN: unable to open log file '/pgdata/pgbackrest/log/db-restore.log': No such file or directory
NOTE: process will continue without log file.
WARN: --delta or --force specified but unable to find 'PG_VERSION' or 'backup.manifest' in '/pgdata/pg12' to confirm that this is a valid $PGDATA directory. --delta and --force have been disabled and if any files exist in the destination directories the restore will be aborted.
ERROR: [031]: option 'repo1-s3-key-type' is 'web-id' but 'AWS_ROLE_ARN' and 'AWS_WEB_IDENTITY_TOKEN_FILE' are not set

## Additional Information

I can not see any obvious way to set these parameters in the the new CRD sections
I suspect some wisdom used here: https://github.com/CrunchyData/postgres-operator/pull/2845 will be needed to resolve this

I'm not familiar enough with the codebase or golang to go making changes, however I suspect that the
reconcileRBACResources is needed to return the service account from the role annotation is required?

Also of note, the role annotation successfully appears on the pod, so it does just seem to be a case of access the right info in the right order.
