### ISSUE TITLE
Why is configuration split between global and type-specific stanzas?

### ISSUE THREAD

**Issue by larsks** [CrunchyData/postgres-operator#3077]
I wasn't sure if this counted as a bug or a feature request, so forgive the blank issue.

While configuring PGO for the first time (using version 5.0.4 of the operator in OpenShift), I'm confused about what options can be specified in the type-specific stanza under `backups.pgbackrest.repos`, and what options must go in `backups.pgbackrest.global`.  For example, consider an S3 backup configuration.  In `backs.repos` I have:

```
      - name: repo2
        schedules:
          full: ...
        s3:
          endpoint: "my-endpoint"
          bucket: netbox
          region: default
```

And I *also* have in `backups.pgbackrest.global`:

```
      global:
        repo2-s3-uri-style: path
        repo2-retention-full: "4"
```

Why can't these all put placed in the same section?  E.g, all in `backups.pgbackrest.repos`:

```
      - name: repo2
        retention:
          full: "4"
        schedules:
          full: ...
        s3:
          endpoint: "my-endpoint"
          bucket: bucket
          region: default
          uri-style: path
```

Or alternately, all in `backups.pgbackrest.global`:

```
      global:
        repo2-retention-full: "4"
        repo2-s3-bucket: "bucket"
        repo2-s3-endpoint: "my-endpoint"
        repo2-s3-region: default
        repo2-s3-uri-style: path
        repo2-schedule-full: ...
```

In fact, this model would let one place the entire configuration into a `ConfigMap` and eschew both the `pgbackrest.backups.global` and the `pgbackrest.backups.repos` sections completely in favor of `ConfigMap` references in `backups.pgbackrest.configuration`.

Is that possible now? If not, what's the reason for splitting configuration options like this?
