### ISSUE TITLE
Using existing Postgresql Persistent Volumes to spin a new cluster with the old data intact

### ISSUE THREAD

**Issue by InderpreetSaini** [CrunchyData/postgres-operator#3084]
Hi Team,

For Disaster Recovery Purposes, we are trying to see if the old Postgres Cluster-related Persistent Volumes for instances could be used to restore into a new cluster with the data staying persistent.

We tried the below code in the new cluster, it did not help:

```
 instances:
  - dataVolumeClaimSpec:
      accessModes:
      - ReadWriteOnce
      dataSource:
        kind: PersistentVolumeClaim
        name: claimapp80
      resources:
        requests:
          storage: 10Gi
    name: pgoharbor
    replicas: 1
```

This spins up a new Persistent Volume Claim, instead of using the existing one as shown below:
```
NAME                              STATUS    VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS     AGE
claimapp80                        Bound     pvc-094a1ad5-8e01-4180-8cc9-1160684a3ac2   10Gi       RWO            vsphere-csi-sc   39m
pgoharbor-pgoharbor-6xq9-pgdata   Pending                                                                                         13m
pgoharbor-repo1                   Bound     pvc-89f6b503-c1a2-4ba5-a382-cd7d6bde4117   10Gi       RWO            vsphere-csi-sc   13m
```

We have manually bound the PV from the old cluster to this new PVC claimapp80.

PostgreSQL version used for both old and new cluster is 5.0.4

Please advise on this, as we need to figure this out to be able to use it in Production environment.

**Comment by tjmoore4** [comment]
Hello @InderpreetSaini,

If I understand your use case correctly, I believe you should be able to use the [Storage Retention feature](https://access.crunchydata.com/documentation/postgres-operator/5.0.4/guides/storage-retention/) of PGO 5.0.4. You will note that the PV you wish to reuse will need to be labeled appropriately, then that label will be referenced similar to:
```
  instances:
    - name: instance1
      dataVolumeClaimSpec:
        accessModes:
        - "ReadWriteOnce"
        resources:
          requests:
            storage: 1Gi
        selector:
          matchLabels:
            pgo-postgres-cluster: postgres-operator-hippo
```
Hope this helps!
