### ISSUE TITLE
Primary and backup jobs are both running and successful but replica has postgres fails to start

### ISSUE THREAD

**Issue by faraonc** [CrunchyData/postgres-operator#3089]
I am completely lost in here. I have a primary Postgres instance that is completely functional, but for some reason the replca(s) fails to run. To be more specific, postgres process fails to start for the replica.

```
ms-db-hetzner-instance1-7558-0                        3/3     Running     0          35h     100.64.3.38     scw-k8s-minerva-modern-hetzner-eu-24dc2391bf36   <none>           <none>
ms-db-hetzner-instance1-gnbf-0                        2/3     Running     0          50m     100.64.53.181   scw-k8s-minerva-modern-hetzner-eu-3b62273a9ca4   <none>           <none>
```

```
apiVersion: postgres-operator.crunchydata.com/v1beta1
kind: PostgresCluster
metadata:
  name: ms-db-hetzner
  namespace: default
spec:
  image: registry.developers.crunchydata.com/crunchydata/crunchy-postgres-ha:centos8-13.4-0
  postgresVersion: 13
  patroni:
    dynamicConfiguration:
      postgresql:
        pg_hba:
          - host all all 0.0.0.0/0 md5
  users:
    - name: "super"
      databases:
        - minio_metastore
        - scaleway_metastore
        - wasabi_metastore
      options: "SUPERUSER"
    - name: "minio"
      databases:
        - minio_metastore
    - name: "scaleway"
      databases:
        - scaleway_metastore
        - scaleway_prod
    - name: "wasabi"
      databases:
        - wasabi_metastore
  instances:
    - name: instance1
      replicas: 2
      dataVolumeClaimSpec:
        storageClassName: openebs-hostpath
        accessModes:
          - "ReadWriteOnce"
        resources:
          requests:
            storage: 30Gi
      resources:
        limits:
          cpu: 1.0
          memory: 4Gi
        requests:
          cpu: 1.0
          memory: 4Gi
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - topologyKey: kubernetes.io/hostname
              labelSelector:
                matchLabels:
                  postgres-operator.crunchydata.com/cluster: ms-db-hetzner
  backups:
    pgbackrest:
      image: registry.developers.crunchydata.com/crunchydata/crunchy-pgbackrest:centos8-2.33-2
      metadata:
        annotations:
          sidecar.istio.io/inject: "false"
      configuration:
        - secret:
            name: pgo-s3-creds
      global:
        repo1-path: "<redacted>"
        repo1-retention-full: "5"
        repo1-retention-full-type: count
        log-level-console: debug
        io-timeout: "300"
      repos:
        - name: repo1
          schedules:
            full: "0 1 * * *"
            incremental: "0 */4 * * *"
          s3:
            bucket: "<redacted>"
            endpoint: "s3.fr-par.scw.cloud"
            region: "fr-par"
```

```
2022-03-11 06:08:30.093 P00   INFO: restore command end: completed successfully (619179ms)
2022-03-11 06:08:30.093 P00  DEBUG:     common/lock::lockRelease: (failOnNoLock: false)
2022-03-11 06:08:30.093 P00  DEBUG:     common/lock::lockRelease: => false
2022-03-11 06:08:30.093 P00  DEBUG:     common/exit::exitSafe: => 0
2022-03-11 06:08:30.093 P00  DEBUG:     main::main: => 0
2022-03-11 06:08:30,095 INFO: replica has been created using pgbackrest
2022-03-11 06:08:30,096 INFO: bootstrapped from leader 'ms-db-hetzner-instance1-7558-0'
2022-03-11 06:08:30,220 INFO: postmaster pid=250
2022-03-11 06:08:30.221 UTC [250] LOG:  pgaudit extension initialized
/tmp/postgres:5432 - no response
2022-03-11 06:08:30.233 UTC [250] LOG:  redirecting log output to logging collector process
2022-03-11 06:08:30.233 UTC [250] HINT:  Future log output will appear in directory "log".
/tmp/postgres:5432 - rejecting connections
/tmp/postgres:5432 - rejecting connections
2022-03-11 06:08:31,696 INFO: Lock owner: ms-db-hetzner-instance1-7558-0; I am ms-db-hetzner-instance1-gnbf-0
2022-03-11 06:08:31,872 INFO: bootstrap from leader 'ms-db-hetzner-instance1-7558-0' in progress
/tmp/postgres:5432 - rejecting connections
/tmp/postgres:5432 - rejecting connections
/tmp/postgres:5432 - rejecting connections
/tmp/postgres:5432 - no response
2022-03-11 06:08:35,269 WARNING: Postgresql is not running.
2022-03-11 06:08:35,269 INFO: Lock owner: ms-db-hetzner-instance1-7558-0; I am ms-db-hetzner-instance1-gnbf-0
2022-03-11 06:08:35,271 INFO: pg_controldata:
  pg_control version number: 1300
  Catalog version number: 202007201
  Database system identifier: 7010789821656772692
  Database cluster state: in production
  pg_control last modified: Fri Mar 11 03:51:43 2022
  Latest checkpoint location: 10/CC000060
  Latest checkpoint's REDO location: 10/CC000028
  Latest checkpoint's REDO WAL file: 0000002200000010000000CC
  Latest checkpoint's TimeLineID: 34
  Latest checkpoint's PrevTimeLineID: 34
  Latest checkpoint's full_page_writes: on
  Latest checkpoint's NextXID: 0:3737
  Latest checkpoint's NextOID: 70364
  Latest checkpoint's NextMultiXactId: 1
  Latest checkpoint's NextMultiOffset: 0
  Latest checkpoint's oldestXID: 478
  Latest checkpoint's oldestXID's DB: 1
  Latest checkpoint's oldestActiveXID: 3737
  Latest checkpoint's oldestMultiXid: 1
  Latest checkpoint's oldestMulti's DB: 1
  Latest checkpoint's oldestCommitTsXid: 0
  Latest checkpoint's newestCommitTsXid: 0
  Time of latest checkpoint: Fri Mar 11 03:51:43 2022
  Fake LSN counter for unlogged rels: 0/3E8
  Minimum recovery ending location: 0/0
  Min recovery ending loc's timeline: 0
  Backup start location: 0/0
  Backup end location: 0/0
  End-of-backup record required: no
  wal_level setting: logical
  wal_log_hints setting: on
  max_connections setting: 100
  max_worker_processes setting: 8
  max_wal_senders setting: 10
  max_prepared_xacts setting: 0
  max_locks_per_xact setting: 64
  track_commit_timestamp setting: off
  Maximum data alignment: 8
  Database block size: 8192
  Blocks per segment of large relation: 131072
  WAL block size: 8192
  Bytes per WAL segment: 16777216
  Maximum length of identifiers: 64
  Maximum columns in an index: 32
  Maximum size of a TOAST chunk: 1996
  Size of a large-object chunk: 2048
  Date/time type storage: 64-bit integers
  Float8 argument passing: by value
  Data page checksum version: 1
  Mock authentication nonce: da9664c82df487cc3031a42cb77e8efcfad2787fcb6d2544bbb8bfd628b02475

2022-03-11 06:08:35,435 INFO: doing crash recovery in a single user mode
2022-03-11 06:08:37,022 WARNING: Postgresql is not running.
2022-03-11 06:08:37,022 INFO: Lock owner: ms-db-hetzner-instance1-7558-0; I am ms-db-hetzner-instance1-gnbf-0
2022-03-11 06:08:37,025 INFO: pg_controldata:
  pg_control version number: 1300
  Catalog version number: 202007201
  Database system identifier: 7010789821656772692
  Database cluster state: shut down
  pg_control last modified: Fri Mar 11 06:08:37 2022
  Latest checkpoint location: 10/CE000028
  Latest checkpoint's REDO location: 10/CE000028
  Latest checkpoint's REDO WAL file: 0000002200000010000000CE
  Latest checkpoint's TimeLineID: 34
  Latest checkpoint's PrevTimeLineID: 34
  Latest checkpoint's full_page_writes: on
  Latest checkpoint's NextXID: 0:3737
  Latest checkpoint's NextOID: 70364
  Latest checkpoint's NextMultiXactId: 1
  Latest checkpoint's NextMultiOffset: 0
  Latest checkpoint's oldestXID: 478
  Latest checkpoint's oldestXID's DB: 1
  Latest checkpoint's oldestActiveXID: 0
  Latest checkpoint's oldestMultiXid: 1
  Latest checkpoint's oldestMulti's DB: 1
  Latest checkpoint's oldestCommitTsXid: 0
  Latest checkpoint's newestCommitTsXid: 0
  Time of latest checkpoint: Fri Mar 11 06:08:36 2022
  Fake LSN counter for unlogged rels: 0/3E8
  Minimum recovery ending location: 0/0
  Min recovery ending loc's timeline: 0
  Backup start location: 0/0
  Backup end location: 0/0
  End-of-backup record required: no
  wal_level setting: logical
  wal_log_hints setting: on
  max_connections setting: 100
  max_worker_processes setting: 8
  max_wal_senders setting: 10
  max_prepared_xacts setting: 0
  max_locks_per_xact setting: 64
  track_commit_timestamp setting: off
  Maximum data alignment: 8
  Database block size: 8192
  Blocks per segment of large relation: 131072
  WAL block size: 8192
  Bytes per WAL segment: 16777216
  Maximum length of identifiers: 64
  Maximum columns in an index: 32
  Maximum size of a TOAST chunk: 1996
  Size of a large-object chunk: 2048
  Date/time type storage: 64-bit integers
  Float8 argument passing: by value
  Data page checksum version: 1
  Mock authentication nonce: da9664c82df487cc3031a42cb77e8efcfad2787fcb6d2544bbb8bfd628b02475
```
