### ISSUE TITLE
Adding user does not update pgbouncer users

### ISSUE THREAD

**Issue by digitalcraig** [CrunchyData/postgres-operator#3095]
## Overview

On an existing cluster, I was able to successfully utilize several users and several databases through pgbouncer as a (loadbalancer) service. Once I added a new user and a new database, the new users could not login through the pgbouncer service. 

```
psql: error: FATAL:  no such user
```
The new user can login directly to the primary using port-forward.

## Environment

Please provide the following details:

- Platform: k3s
- Platform Version: v1.23.4+k3s1
- PGO Image Tag: ubi8-5.0.5-0
- Postgres Version: 13
- Storage: longhorn

### REPRO

Provide steps to get to the error condition:

1. Create cluster

```
apiVersion: postgres-operator.crunchydata.com/v1beta1
kind: PostgresCluster
metadata:
  name: postgres
  namespace: postgresql
spec:
  backups:
    pgbackrest:
      configuration:
      - secret:
          name: postgres-pgbackup-conf
      global:
        repo1-retention-full: "7"
        repo1-retention-full-type: time
      image: registry.developers.crunchydata.com/crunchydata/crunchy-pgbackrest:centos8-2.36-0
      manual:
        options:
        - --type=full
        repoName: repo1
      repos:
      - name: repo1
        schedules:
          full: 0 1 * * *
          incremental: 0 */4 * * *
        volume:
          volumeClaimSpec:
            accessModes:
            - ReadWriteMany
            resources:
              requests:
                storage: 24Gi
            storageClassName: nfs
            volumeName: pgbackup-repo1-vol-pv
      restore:
        enabled: true
        options:
        - --type=default
        repoName: repo1
  image: registry.developers.crunchydata.com/crunchydata/crunchy-postgres:centos8-13.5-0
  instances:
  - affinity:
      podAntiAffinity:
        preferredDuringSchedulingIgnoredDuringExecution:
        - podAffinityTerm:
            labelSelector:
              matchLabels:
                postgres-operator.crunchydata.com/cluster: postgres
                postgres-operator.crunchydata.com/instance-set: postgres-1
            topologyKey: kubernetes.io/hostname
          weight: 1
    dataVolumeClaimSpec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 8Gi
      storageClassName: longhorn
    name: postgres
    replicas: 3
  patroni:
    dynamicConfiguration:
      postgresql:
        parameters:
          max_parallel_workers: 3
          max_worker_processes: 3
          shared_buffers: 1GB
          work_mem: 2MB
    leaderLeaseDurationSeconds: 30
    port: 8008
    syncPeriodSeconds: 10
  port: 5432
  postgresVersion: 13
  proxy:
    pgBouncer:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - podAffinityTerm:
              labelSelector:
                matchLabels:
                  postgres-operator.crunchydata.com/cluster: postgres
                  postgres-operator.crunchydata.com/role: pgbouncer
              topologyKey: kubernetes.io/hostname
            weight: 1
      config:
        global:
          ignore_startup_parameters: extra_float_digits,search_path
      image: registry.developers.crunchydata.com/crunchydata/crunchy-pgbouncer:centos8-1.16-1
      port: 5432
      replicas: 2
      service:
        type: LoadBalancer
  users:
  - name: postgres
  - databases:
    - db1
    name: user1
```
2. Login as user1
```
export USER_SECRET=postgres-pguser-user1
export PGSSLMODE=require
export PGPASSWORD=`kubectl get secrets -n postgresql "${USER_SECRET}" -o jsonpath='{.data.password}' | base64 --decode`
export PGUSER=`kubectl get secrets -n postgresql "${USER_SECRET}" -o jsonpath='{.data.user}' | base64 --decode `
export PGHOST=pgdb.example.org
export PGPORT=5432

$ psql db1
psql (13.5 (Ubuntu 13.5-0ubuntu0.21.10.1))
SSL connection (protocol: TLSv1.3, cipher: TLS_AES_256_GCM_SHA384, bits: 256, compression: off)
Type "help" for help.

db1=> \du;
                                       List of roles
     Role name     |                         Attributes                         | Member of 
-------------------+------------------------------------------------------------+-----------
 _crunchypgbouncer |                                                            | {}
 _crunchyrepl      | Replication                                                | {}
 user1             |                                                            | {}
 postgres          | Superuser, Create role, Create DB, Replication, Bypass RLS | {}
```
3. Edit cluster and add additional user and database to spec:

```
  - databases:
    - db2
    name: user2
```
### EXPECTED

Expect to login to pgbouncer with user2 exactly as with user1.

### ACTUAL

Receive error from psql:

```
psql: error: FATAL:  no such user
```
Logging in as user1 still works and user2 shows in \du:

```
$ psql db1
psql (13.5 (Ubuntu 13.5-0ubuntu0.21.10.1))
SSL connection (protocol: TLSv1.3, cipher: TLS_AES_256_GCM_SHA384, bits: 256, compression: off)
Type "help" for help.

db1=> \du;
                                       List of roles
     Role name     |                         Attributes                         | Member of 
-------------------+------------------------------------------------------------+-----------
 _crunchypgbouncer |                                                            | {}
 _crunchyrepl      | Replication                                                | {}
 user1             |                                                            | {}
 user2             |                                                            | {}
 postgres          | Superuser, Create role, Create DB, Replication, Bypass RLS | {}
```

### WORKAROUND

Use port-forward directly to primary pod instead:

```
export USER_SECRET=postgres-pguser-user2
export PGSSLMODE=require
export PGPASSWORD=`kubectl get secrets -n postgresql "${USER_SECRET}" -o jsonpath='{.data.password}' | base64 --decode`
export PGUSER=`kubectl get secrets -n postgresql "${USER_SECRET}" -o jsonpath='{.data.user}' | base64 --decode `
export PGHOST=localhost
export PGPORT=5432
PG_CLUSTER_PRIMARY_POD=$(kubectl get pod -n postgresql -o name \
  -l postgres-operator.crunchydata.com/cluster=postgres,postgres-operator.crunchydata.com/role=master)
kubectl -n postgresql port-forward "${PG_CLUSTER_PRIMARY_POD}" 5432:5432 &

$ psql db2
Handling connection for 5432
psql (13.5 (Ubuntu 13.5-0ubuntu0.21.10.1))
SSL connection (protocol: TLSv1.3, cipher: TLS_AES_256_GCM_SHA384, bits: 256, compression: off)
Type "help" for help.

db2=# \conninfo
You are connected to database "db2" as user "user2" on host "localhost" (address "::1") at port "5432".
SSL connection (protocol: TLSv1.3, cipher: TLS_AES_256_GCM_SHA384, bits: 256, compression: off)
db2=# 
```
