### ISSUE TITLE
cannot connect via pgbouncer

### ISSUE THREAD

**Issue by shimon-elbaz** [CrunchyData/postgres-operator#3123]
hi , 
i have setup an environment on GKE using the provided samples.

my general environment:
pgo , pgbouncer , ha-postgress.

whenever i try to use the bouncer , i fail to connect to the database , but when i connect to the postgres-ha service i have the access i need.

it seems that i simply need to edit my pgbouncer settings, but i am unable to do so.
whenever i try to edit the YAML directly , it is overwritten by the pgo.
when i added a new config-map containing my file - it was ignored.

as far as i understand , i need to edit the files:
- pgbouncer.ini
- pg_hba.conf

can anyone please assist?

**Comment by luber** [comment]
I have the same issue.
```
  proxy:
    pgBouncer:
      image: registry.developers.crunchydata.com/crunchydata/crunchy-pgbouncer:ubi8-1.16-2
```

When I am trying to connect - this is what I see in logs:
```
2022-05-05 21:21:36.022 UTC [7] LOG kernel file descriptor limit: 1048576 (hard: 1048576); max_client_conn: 100, max expected fd use: 112
2022-05-05 21:21:36.022 UTC [7] LOG listening on 0.0.0.0:5432
2022-05-05 21:21:36.022 UTC [7] LOG listening on [::]:5432
2022-05-05 21:21:36.022 UTC [7] LOG process up: PgBouncer 1.16.1, libevent 2.1.8-stable (epoll), adns: c-ares 1.13.0, tls: OpenSSL 1.1.1k  FIPS 25 Mar 2021
2022-05-05 21:22:04.672 UTC [7] LOG C-0x560d3584bf70: (nodb)/(nouser)@10.42.2.0:37062 registered new auto-database: db=postgres
2022-05-05 21:22:04.691 UTC [7] WARNING DNS lookup failed: my-postgres-primary: result=0
2022-05-05 21:22:04.691 UTC [7] LOG S-0x560d3585bf10: postgres/_crunchypgbouncer@(bad-af):0 closing because: server DNS lookup failed (age=0s)
```

When I have logged in to the container and manually run `nslookup my-postgres-primary` command - it resolves correctly.

Could it be an issue with the outdated version of `adns: c-ares 1.13.0` (20-jun-2017)? I can see that there is a newer `1.8.1` (27-oct-2021) version available: [c-ares donwloads](https://c-ares.org/download/)

**Comment by nawarajshahi** [comment]
@luber what does your cluster configuration look like? I was able to get pgbouncer working for the primary database as well as replica and it requires certain configuration to be enabled/set ahead of time or edit the cluster after you deploy for it to leverage pgbouncer.

**Comment by luber** [comment]
@nawarajshahi here it is:
```
apiVersion: postgres-operator.crunchydata.com/v1beta1
kind: PostgresCluster
metadata:
  name: my-postgres
spec:
  image: registry.developers.crunchydata.com/crunchydata/crunchy-postgres:ubi8-14.2-1
  postgresVersion: 14
  service:
    type: NodePort    
  instances:
    - name: instance
      replicas: 3
      dataVolumeClaimSpec:
        storageClassName: "longhorn-single"
        accessModes:
        - "ReadWriteOnce"
        resources:
          requests:
            storage: 10Gi
      resources:
        limits:
          cpu: 2.0
          memory: 4Gi
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 1
            podAffinityTerm:
              topologyKey: kubernetes.io/hostname
              labelSelector:
                matchLabels:
                  postgres-operator.crunchydata.com/cluster: my-postgres
                  postgres-operator.crunchydata.com/instance-set: instance
  proxy:
    pgBouncer:
      image: registry.developers.crunchydata.com/crunchydata/crunchy-pgbouncer:ubi8-1.16-2
      replicas: 1
      service:
        type: NodePort
      config:
        global:
          pool_mode: transaction
          query_wait_timeout: "240"     
      resources:
        limits:
          cpu: 200m
          memory: 128Mi
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 1
            podAffinityTerm:
              topologyKey: kubernetes.io/hostname
              labelSelector:
                matchLabels:
                  postgres-operator.crunchydata.com/cluster: my-postgres
                  postgres-operator.crunchydata.com/role: pgbouncer
  backups:
    pgbackrest:
      image: registry.developers.crunchydata.com/crunchydata/crunchy-pgbackrest:ubi8-2.38-0
      repos:
      - name: repo1
        volume:
          volumeClaimSpec:
            storageClassName: "longhorn"
            accessModes:
            - "ReadWriteOnce"
            resources:
              requests:
                storage: 20Gi
      manual:
        repoName: repo1
        options:
          - --type=full
      global:
        repo1-retention-full: "14"
        repo1-retention-full-type: time
  monitoring:
    pgmonitor:
      exporter:
        image: registry.developers.crunchydata.com/crunchydata/crunchy-postgres-exporter:ubi8-5.1.0-0
  users:
    - name: postgres
    - name: admin
      options: "SUPERUSER"

  patroni:
    dynamicConfiguration:
      postgresql:
        parameters:
          shared_preload_libraries: timescaledb
```

**Comment by nawarajshahi** [comment]
@luber thanks for the spec. Upon looking more into it, I see that you need the following in your spec as well as some changes to be done once the cluster gets provisioned. 
```
  proxy:
    pgBouncer:
      image: registry.developers.crunchydata.com/crunchydata/crunchy-pgbouncer:ubi8-1.16-2
      replicas: 1
      service:
        type: NodePort
      config:
       databases:
          '*': host=pg-primary port=5432 #change this port if you're not using default 
        global:
          pool_mode: transaction
          query_wait_timeout: "240" 
          default_pool_size: "100"
          max_client_conn: "1000" #change depending on your app requirement
          server_tls_sslmode: verify-ca 
```
Deploy the pg cluster. 

Once deployed, find the primary pg pod and exec into primary pod
```
kubectl exec -it <pg-primary> -- bash -n <ns>
psql
\c <db-name>;
\ef pgbouncer.get_auth

#remove the line the following line
	#NOT pg_authid.rolsuper AND
#save and exit (wq)

\g 
\q

#if _crunchypgbouncer is not already a superuser you'll have to alter it to superuser 
psql
\du+ #to check the users and roles 
alter role _crunchypgbouncer with superuser;
\q
# This should be good enough! 

if you want to test this out, you can do 
psql postgres://<user-name>:<password>@pg-pgbouncer.pg.svc.cluster.local:5432/<db-name>
```
Hope this helps!
