### ISSUE TITLE
global.repo1-path not working

### ISSUE THREAD

**Issue by achetronic** [CrunchyData/postgres-operator#3141]
## Overview
If the following settings are set to change the repo1 path

```yaml
backups:
    pgbackrest:
      global:
        repo1-path: /pgbackrest/gitlab/gitlab-postgresql/repo1
```
The point is that the .conf is populated with the right values inside the pod, but the volume is equally mounted to the path `/pgbackrest/repo1` in the StatefulSet, so the backup can not be performed because the process can not write in the proper path you set on global parameters, because it has not permissions (Ready-Only) 

So the following DO works

```yaml
backups:
    pgbackrest:
      global:
        repo1-path: /pgbackrest/repo1
```

As you can see in the repo StatefulSet

```yaml
.
.
.
        volumeMounts:
        - mountPath: /etc/ssh
          name: ssh
          readOnly: true
        - mountPath: /pgbackrest/repo1
          name: repo1
        - mountPath: /etc/pgbackrest/conf.d
          name: pgbackrest-config
        - mountPath: /tmp
          name: tmp

```

## Environment

Please provide the following details:

- Platform: Kubernetes
- Platform Version: 1.21
- PGO Image Tag: centos8-14.2-0
- Postgres Version 14
- Storage: The default in Kind for testing purposes

### REPRO

1. Set the path to another for repo1, for example `/pgbackrest/gitlab/gitlab-postgresql/repo1` and the backups will try to be stored there, but the process can not write there

### EXPECTED

Simply mount the volume in the path you specify in globals to allow the backup process to write in the right place

### ACTUAL

The backup can only be performed in the default path, in the others Read-Only permissions avoid to do it

**Comment by andrewlecuyer** [comment]
@achetronic as you are seeing, when using a PVC-based pgBackRest repo volume, PGO will mount the volume using the following convention:

```
/pgbackrest/repoN
```

...with `N` corresponding to the number of the repository being configured.

(You can find a note about this in the [Backup Configuration documentation](https://access.crunchydata.com/documentation/postgres-operator/latest/tutorial/backups/).)

However, underneath that mount point you can configure a custom repository path per your specific needs/requirements.  For instance, by providing the following:

```yaml
backups:
    pgbackrest:
      global:
        repo1-path: /pgbackrest/repo1/pgbackrest/gitlab/gitlab-postgresql/repo1
```

...you would see the following at the root of the volume bound to the PVC:

```bash
pgbackrest/gitlab/gitlab-postgresql/repo1
```

Therefore, `repo1-path` does work as expected - you simply need to provide the proper mount point in addition to your custom path.
