### ISSUE TITLE
Feature request: Configure zero backups

### ISSUE THREAD

**Issue by kreempuff** [CrunchyData/postgres-operator#3152]
Have an idea to improve PGO? We'd love to hear it! We're going to need some information from you to learn more about your feature requests.

Please be sure you've done the following:

- [x] Provide a concise description of your feature request.
- [x] Describe your use case. Detail the problem you are trying to solve.
- [x] Describe how you envision that the feature would work.
- [x] Provide general information about your current PGO environment.

## Overview

Make backups optional. 

I get an error like this when I try to configure an empty `backups` section:

```
The PostgresCluster "example" is invalid: spec.backups.pgbackrest.repos: Invalid value: 0: spec.backups.pgbackrest.repos in body should have at least 1 items
```

## Use Case
Simpler configuration of inconsequential database clusters. Configuring a PG cluster requires the configuring a backup strategy even if the backups won't be used. For example, for dev databases or for testing purposes. 

## Desired Behavior
The validator should allow objects to be created without any backups configured. Omitting at any level would be acceptable:  

1. An empty repo list
```yaml
apiVersion: postgres-operator.crunchydata.com/v1beta1
kind: PostgresCluster
...
backups: 
    pgbackrest: 
      repos: []
```

2. An empty `pgbackrest` section
```yaml
apiVersion: postgres-operator.crunchydata.com/v1beta1
kind: PostgresCluster
...
backups: 
    pgbackrest: {}
```
3. An empty `backups` section 
```yaml
apiVersion: postgres-operator.crunchydata.com/v1beta1
kind: PostgresCluster
...
backups: {} 
```

4. No backups section
```yaml
apiVersion: postgres-operator.crunchydata.com/v1beta1
kind: PostgresCluster
...
instances:
  ...
postgresVersion: 13
```
## Environment

Tell us about your environment:

Please provide the following details:

EKS

- Platform: EKS
- Platform Version: 1.21
- PGO Image Tag: (e.g. `ubi8-5.1.0-0`)
- Postgres Version (e.g. `14`)
- Storage: (e.g. `hostpath`, `nfs`, or the name of your storage class)
- Number of Postgres clusters: (`XYZ`)

## Additional Information

Please provide any additional information that may be helpful.
