### ISSUE TITLE
K8s Multicluster support

### ISSUE THREAD

**Issue by Subetov** [CrunchyData/postgres-operator#3153]
Hello.
Is there any way / solution to setup active-active or active-standby cluster (in a separate DCs / Clusters) using PGO ?
Is there opportunity to create standby cluster from primary host like:
```
standby:
    enabled: true
    repoName: repo1
```
But create from primary host and not from "repo"
It is patroni option to create standby from primary:
```
bootstrap:
    dcs:
        standby_cluster:
            host: 1.2.3.4
            port: 5432
            primary_slot_name: patroni
            create_replica_methods:
            - basebackup
```
But I can't find any mentions in PGO's documentation.
Or maybe there is an option to stream WAL to s3 and make replica from s3 ?
I will be very grateful for your help.
Thank you very much in advance.
