### ISSUE TITLE
s3 uri style support for v5

### ISSUE THREAD

**Issue by nadendlaprasad** [CrunchyData/postgres-operator#3159]
Hi,

do you have plans to support path style support in version 5.X.X for s3 backups ?

**Comment by FabianPehlaAtos** [comment]
You can already do this with the existing operator. pgbackrest has a configuration option for uri-style `repoX-s3-uri-style`

Create a config map: 
```
kind: ConfigMap
apiVersion: v1
metadata:
  name: pgo-s3-conf
data:
  s3-conf.conf: |-
    [global]
    repo1-s3-uri-style=path
```

Then reference this configmap in your pgbackrest configuration. 
```
  backups:
    pgbackrest:
      configuration:
        - configMap:
            name: pgo-s3-conf
```

This works for me using path style s3 buckets. It is the same mechamism that is used to include a secret for the s3 credentials.

**Comment by cbandy** [comment]
@FabianPehlaAtos is exactly right! This option can also be set on the PostgresCluster [spec](https://access.crunchydata.com/documentation/postgres-operator/latest/references/crd/#postgresclusterspecbackupspgbackrest) without a ConfigMap:

```yaml
  backups:
    pgbackrest:
      global:
        repo1-s3-uri-style: path
```
