### ISSUE TITLE
Operator does not apply second PITR restore

### ISSUE THREAD

**Issue by bzdgn** [CrunchyData/postgres-operator#3167]
<h3>A. Summary</h3>

Regarding to [backup management documentation](https://access.crunchydata.com/documentation/postgres-operator/5.0.5/tutorial/backup-management/) and also [disaster recovery documentation](https://access.crunchydata.com/documentation/postgres-operator/5.0.5/tutorial/disaster-recovery/) I apply a postgres backup/restore test. After backup, the first restore is successful, a restore pod is initiated and database went back to the desired state. After that, a second restore is applied, and restore pod is not created, nothing is changed.

**Postgres Operator** version: 5.0.5
**OpenShift** version: 4.9

<h3>B. Scenario</h3>

- Deploy a CruncyData, create a table and apply an entry
- Wait some time and create a table and apply an entry
- Wait some time and apply backup via annotation
- Wait some time and delete the table entries
- Apply the 1st restore and Test Restore via database entries
- Apply the 2nd restore and Test Restore via database entries (here it fails)

<h3>C. Scenario Steps</h3>

**1. I've deployed a CrunchyData instance with the following yaml file;**

The command;

```
>kubectl apply -f deploy.yaml
postgrescluster.postgres-operator.crunchydata.com/my-postgres created
```

Yaml file;

```yaml
apiVersion: postgres-operator.crunchydata.com/v1beta1
kind: PostgresCluster
metadata:
  name: my-postgres
  namespace: bzk-koop-tst
spec:
  metadata:
    labels:
      group: test
      tier: vertrouwd
      egress-frontoffice-policy: allow
  image: harbor.cicd.s15m.nl/sp-bouwsteen-pub/crunchydata/crunchy-postgres:centos8-14.2-0
  postgresVersion: 14
  instances:
    - name: instance1
      replicas: 1
      resources:
        limits:
          cpu: 200m
          memory: 4Gi
        requests:
          cpu: 100m
          memory: 2Gi
      dataVolumeClaimSpec:
        accessModes:
        - "ReadWriteOnce"
        resources:
          requests:
            storage: 10Gi # Database storage/sizing
      affinity: 
        podAntiAffinity: # antiaffinity enables all instances to be scheduled on seperate nodes if no nodes are available the database wil not be deployed.
          requiredDuringSchedulingIgnoredDuringExecution:
            - topologyKey: kubernetes.io/hostname
              labelSelector:
                matchLabels:
                  postgres-operator.crunchydata.com/cluster: my-postgres
                  postgres-operator.crunchydata.com/instance-set: my-instance1
  users:
    - name: postgres
    - databases:
      - testdb
      name: testuser   
  backups:
    pgbackrest:
      #
      global:
        repo1-retention-full: "5"
        repo1-retention-full-type: time
      # when this option is added it enables to take one-off backup by adding annotation to the cluster. See https://access.crunchydata.com/documentation/postgres-operator/5.0.5/tutorial/backup-management/
      manual: 
        repoName: repo1
        options:
        - --type=full
      metadata:
        labels:
          group: test
          tier: vertrouwd
      image: harbor.cicd.s15m.nl/sp-bouwsteen-pub/crunchydata/crunchy-pgbackrest:centos8-2.36-1
      repos:
      - name: repo1 # information on each specific pgBackRest backup repository. This allows you to configure where and how your backups and WAL archive are stored. You can keep backups in up to four (4) different locations
        schedules:
          full: 0 1 * * *
          incremental: 0 */4 * * *
        volume:
          volumeClaimSpec:
            storageClassName: nfs
            accessModes:
            - "ReadWriteOnce"
            resources:
              requests:
                storage: 10Gi # Repository storage/sizing for storing backups and transaction logs.
      #In the above example, we assume that the Kubernetes cluster is using a default storage class. If your cluster does not have a default storage class, 
      #or you wish to use a different storage class, you will have to set spec.backups.pgbackrest.repos.volume.volumeClaimSpec.storageClassName.
  proxy:
    pgBouncer:
      metadata:
        labels:
          group: test
          tier: vertrouwd
      resources:
        limits: # Connection pool resource quota
          memory: 36Mi
      image: harbor.cicd.s15m.nl/sp-bouwsteen-pub/crunchydata/crunchy-pgbouncer:centos8-1.16-1
      replicas: 2
  monitoring:
    pgmonitor:
      exporter:
        image: harbor.cicd.s15m.nl/sp-bouwsteen-pub/crunchydata/crunchy-postgres-exporter:ubi8-5.0.5-0
```

**2. After pods are created, I've creatd the following table and add the entry as follows;**

```sql
CREATE TABLE WORKERS (
	id serial PRIMARY KEY,
	name VARCHAR ( 50 ) UNIQUE NOT NULL,
	age VARCHAR ( 50 ) NOT NULL,
	ts timestamp NOT NULL
);

INSERT INTO WORKERS (name, age, ts) VALUES
('worker1', '20', NOW());
```

The output is as follows;

`
1	"worker1"	"20"	"2022-04-24 23:03:47.909389"
`
**3. Waited some time and created the following entry;**

```sql
INSERT INTO WORKERS (name, age, ts) VALUES
('worker2', '30', NOW());
```

Now the database has two entries;

```
1	"worker1"	"20"	"2022-04-24 23:03:47.909389"
3	"worker2"	"30"	"2022-04-24 23:06:38.708635"
```

**4. Waited some time and applied a backup as documented in backup management, with the following command;**

```
>kubectl annotate postgrescluster/my-postgres --overwrite postgres-operator.crunchydata.com/pgbackrest-backup="my-backup"
postgrescluster.postgres-operator.crunchydata.com/my-postgres annotated
```

Backup pod created and pod logs are as below;

```
7 lines
time="2022-04-24T23:13:19Z" level=info msg="crunchy-pgbackrest starts"
time="2022-04-24T23:13:19Z" level=info msg="debug flag set to false"
time="2022-04-24T23:13:19Z" level=info msg="backrest backup command requested"
time="2022-04-24T23:13:19Z" level=info msg="command to execute is [pgbackrest backup --stanza=db --repo=1 --type=full]"
time="2022-04-24T23:13:47Z" level=info msg="output=[]"
time="2022-04-24T23:13:47Z" level=info msg="stderr=[]"
time="2022-04-24T23:13:47Z" level=info msg="crunchy-pgbackrest ends"
```

Applied a `pgbackrest info` to be sure that the adhoc backup is created;

```
sh-4.4$ date
Sun Apr 24 23:13:03 UTC 2022
sh-4.4$ pgbackrest info
stanza: db
    status: ok
    cipher: none

    db (current)
        wal archive min/max (14): 000000010000000000000001/000000010000000000000002

        full backup: 20220424-230137F
            timestamp start/stop: 2022-04-24 23:01:37 / 2022-04-24 23:02:37
            wal start/stop: 000000010000000000000002 / 000000010000000000000002
            database size: 33.9MB, database backup size: 33.9MB
            repo1: backup set size: 4.3MB, backup size: 4.3MB
sh-4.4$ date
Sun Apr 24 23:13:56 UTC 2022
sh-4.4$ pgbackrest info
stanza: db
    status: ok
    cipher: none

    db (current)
        wal archive min/max (14): 000000010000000000000001/000000010000000000000004

        full backup: 20220424-230137F
            timestamp start/stop: 2022-04-24 23:01:37 / 2022-04-24 23:02:37
            wal start/stop: 000000010000000000000002 / 000000010000000000000002
            database size: 33.9MB, database backup size: 33.9MB
            repo1: backup set size: 4.3MB, backup size: 4.3MB

        full backup: 20220424-231320F
            timestamp start/stop: 2022-04-24 23:13:20 / 2022-04-24 23:13:45
            wal start/stop: 000000010000000000000004 / 000000010000000000000004
            database size: 33.9MB, database backup size: 33.9MB
            repo1: backup set size: 4.3MB, backup size: 4.3MB
sh-4.4$ 
```

**5. Applied a PITR restore with the following command. The target date is: "2022-04-24 23:10:30+00"**

```
>kubectl patch postgrescluster/my-postgres -p "{\"spec\":{\"dataSource\":{\"postgresCluster\":{\"clusterName\":\"my-postgres\",\"repoName\":\"repo1\",\"options\":[\"--type=time\",\"--target=\\\"2022-04-24 23:10:30+00\\\"\"]}}}}" --type=merge
postgrescluster.postgres-operator.crunchydata.com/my-postgres patched

>kubectl get postgrescluster/my-postgres -o jsonpath='{.spec.dataSource}'
'{"postgresCluster":{"clusterName":"my-postgres","options":["--type=time","--target=\"2022-04-24 23:10:30+00\""],"repoName":"repo1"}}'
```

6. A restore pod is automatically created and destroyed and then, ensured that the database is at desired state. Deleted the database entries again.

7. Applied a PITR restore with the following command. The target date is: "2022-04-24 23:07:20+00"**

>kubectl patch postgrescluster/my-postgres -p "{\"spec\":{\"dataSource\":{\"postgresCluster\":{\"clusterName\":\"my-postgres\",\"repoName\":\"repo1\",\"options\":[\"--type=time\",\"--target=\\\"2022-04-24 23:07:20+00\\\"\"]}}}}" --type=merge
postgrescluster.postgres-operator.crunchydata.com/my-postgres patched

>kubectl get postgrescluster/my-postgres -o jsonpath='{.spec.dataSource}'
'{"postgresCluster":{"clusterName":"my-postgres","options":["--type=time","--target=\"2022-04-24 23:07:20+00\""],"repoName":"repo1"}}'

8. No restore pod is created, nothing happened, restore is not succesfull.

<h3>Further Notes</h3>

This is an example of **PITR** restore. I've also tried a **PITR In Place** restore. Both are done to the **Postgres Operator v5.0.5** documentation. In both cases, the initial restore is successful, with an automatically created restore-pod but the second or third restore tries are all failed because no any restore-pods are initiated.
