### ISSUE TITLE
create PostgresCluster , instances How to use storageclasses

### ISSUE THREAD

**Issue by jicki** [CrunchyData/postgres-operator#3186]
## instances How to use storageclasses
```yaml
apiVersion: postgres-operator.crunchydata.com/v1beta1
kind: PostgresCluster
metadata:
  name: hippo
spec:
  image: registry.developers.crunchydata.com/crunchydata/crunchy-postgres:ubi8-14.2-1
  postgresVersion: 14
  instances:
    - name: instance1
      dataVolumeClaimSpec:
        accessModes:
        - "ReadWriteOnce"
        resources:
          requests:
            storage: 1Gi
```
