### ISSUE TITLE
pgbackrest ERROR: [048]: invalid command 'server' 

### ISSUE THREAD

**Issue by bilalbokharee** [CrunchyData/postgres-operator#3187]
## Overview

pgbackrest container fails to spin up, crashes with error ERROR: [048]: invalid command 'server' sending the instance pod into crash loop. 

## Environment

Please provide the following details:

- Platform: (`Kubernetes`, `OpenShift`)
- Platform Version: ( 4.9.28 )
- PGO Image Tag: ( `ubi8-5.1.0-0`)
- Postgres Version: (`14.2`)
- Storage: ( `hostpath`)

### REPRO

Provide steps to get to the error condition:

1. Install Postgres Operator v5.0.5 from OperatorHub 
2. Create a postgres instance with following config

```yaml
apiVersion: postgres-operator.crunchydata.com/v1beta1
kind: PostgresCluster
metadata:
  name: postgres
  namespace: test
spec:
  patroni:
    dynamicConfiguration:
      postgresql:
        pg_hba:
          - "hostnossl all all all password"
  image: registry.developers.crunchydata.com/crunchydata/crunchy-postgres:centos8-14.2-0
  postgresVersion: 14
  instances:
    - name: testinstance
      dataVolumeClaimSpec:
        accessModes:
        - "ReadWriteOnce"
        resources:
          requests:
            storage: 100Gi
  backups:
    pgbackrest:
      image: registry.developers.crunchydata.com/crunchydata/crunchy-pgbackrest:centos8-13.6-4.7.5
      repos:
      - name: repo1
        volume:
          volumeClaimSpec:
            accessModes:
            - "ReadWriteOnce"
            resources:
              requests:
                storage: 1Gi
```

### EXPECTED

1. Postgres pod is ready with all containers running

### ACTUAL

1. database, replication-cert-copy and pgbackrest-config are running, while pgbackrest is in waiting state with the described error

## Logs

ERROR: [048]: invalid command 'server'
