### ISSUE TITLE
how to restore from S3 with specific backup

### ISSUE THREAD

**Issue by tirelibirefe** [CrunchyData/postgres-operator#3196]
Hello,
My operator version is 5.0.4.
My K8s work on AWS EKS.
```
Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.6", GitCommit:"ad3338546da947756e8a88aa6822e9c11e7eac22", GitTreeState:"clean", BuildDate:"2022-04-14T08:49:13Z", GoVersion:"go1.17.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"21+", GitVersion:"v1.21.5-eks-bc4871b", GitCommit:"5236faf39f1b7a7dabea8df12726f25608131aa9", GitTreeState:"clean", BuildDate:"2021-10-29T23:32:16Z", GoVersion:"go1.16.8", Compiler:"gc", Platform:"linux/amd64"}
WARNING: version difference between client (1.23) and server (1.21) exceeds the supported minor version skew of +/-1
```
here is backup config:

```
  backups:
    pgbackrest:
      image: registry.developers.crunchydata.com/crunchydata/crunchy-pgbackrest:ubi8-2.38-0
      configuration:
      - secret:
          name: psql-master-s3-creds
      - secret:
          name: master-pgbackrest-secrets
      manual:
        repoName: repo1
        options:
         - --type=full
      global:
        repo1-path: /repo1/master
        repo1-retention-full: "14"
        repo1-retention-full-type: time
        repo1-cipher-type: aes-256-cbc
      repos:
      - name: repo1
        schedules:
          full: "0 1 * * *"
          incremental: "0 */6 * * *"
        s3:
          bucket: crunchydata-backups
          endpoint: s3.eu-central-1.amazonaws.com:443
          region: eu-central-1
```
I can backup and restore psql from S3 successfully but pgBackRest restores from last backup.
![image](https://user-images.githubusercontent.com/45227339/167867216-99d90d8d-e542-4457-b865-4e97d655f5fb.png)

How can I restore from specific backup set?

Thanks & Regards

**Comment by andrewlecuyer** [comment]
@tirelibirefe as described in the Restore Section of the pgBackRest documentation, a `--set` option is available that allows you to select a specific set:

https://pgbackrest.org/command.html#command-restore

I also recommend you check out the various sections of the pgBackRest docs for additional details about performing restores (e.g. for performing a point-in-time recovery, etc.).

As for configuring a specific set during a restore initiated using PGO, this would be done using the `options` field, e.g.:

```yaml
spec:
  backups:
    pgbackrest:
      restore:
        enabled: true
        repoName: repo1
        options:
        - --set=20150131-153358F_20150131-153401I
```

**Comment by tirelibirefe** [comment]
Hello,
Wish to able to say "ok" but no. I tried adding what you advised; nothing changed. Only the last backup is restored. Pgo doesn't care what I set there.

```
  backups:
    pgbackrest:
      image: registry.developers.crunchydata.com/crunchydata/crunchy-pgbackrest:ubi8-2.38-0
      configuration:
      - secret:
          name: psql-ferahevler-s3-creds
      - secret:
          name: ferahevler-pgbackrest-secrets
      manual:
        repoName: repo1
        options:
         - --type=full
      global:
        repo1-path: /repo1/ferahevler
        repo1-retention-full: "14"
        repo1-retention-full-type: time
        repo1-cipher-type: aes-256-cbc
      repos:
      - name: repo1
        schedules:
          full: "0 1 * * *"
          incremental: "0 */6 * * *"
        s3:
          bucket: ku-eksdev1-crunchydata-backups
          endpoint: s3.eu-central-1.amazonaws.com:443
          region: eu-central-1
      restore:
        enabled: true
        repoName: repo1
        options:
        - --set=20220608-135823F
```

![image](https://user-images.githubusercontent.com/45227339/172671852-781ac00d-8353-447a-855a-ee69826a51bc.png)

**Comment by cbandy** [comment]
As described in the docs, a restore without any `--type` option replays the entire WAL stream.

> https://pgbackrest.org/command.html#command-restore

**Comment by tirelibirefe** [comment]
Hello @cbandy 
I am not trying to PITR; just want restore from a specific backup.
Maybe problem is in the manifest; because restore manifest ignores all parameters under options:

```
  backups:
    pgbackrest:
      image: registry.developers.crunchydata.com/crunchydata/crunchy-pgbackrest:ubi8-2.38-0
      restore:
        enabled: true
        repoName: repo1
        options:
          - --set=20220609-114755F
          - --type=immediate

```


I tried also following options, nothing changes logs; restore operation ignores all parameters under `options:`


      restore:
        enabled: true
        repoName: repo1
        options:
        - --set=20220609-114755F
        - --stanza=db
        - --type=immediate
        - --log-level-console=trace
        - --log-level-stderr=trace
        - --target-action=promote
        - --log-subprocess=y
        - --archive-mode=off' kustomize/psql-restore-$dbname/postgres-restored.yaml
