### ISSUE TITLE
Secondary cluster fails to connect to leader intermittently.

### ISSUE THREAD

**Issue by Shrivastava-Varsha** [CrunchyData/postgres-operator#3197]
After creating PostgresCluster CR instance with replica set to "2", the secondary  cluster fails to connect to leader intermittently.

## Environment

Please provide the following details:
- PGO : 5.1.0
- Platform: OpenShift
- Platform Version: 4.8
- PGO Image Tag:
- Postgres Version 13
- Storage: kubernetes PVC
- Storage Class: ibmc-block-bronze

attaching logs :
[postgres.log](https://github.com/CrunchyData/postgres-operator/files/8672011/postgres.log)

PostgresCluster yaml :
```
apiVersion: postgres-operator.crunchydata.com/v1beta1
kind: PostgresCluster
metadata:
  name: modelbuilder
spec:
  backups:
    pgbackrest:
      repoHost: {}
      repos:
        - name: repo1
          volume:
            volumeClaimSpec:
              accessModes:
                - ReadWriteOnce
              resources:
                requests:
                  storage: 20G
              storageClassName: ibmc-file-gold-gid
  instances:
    - dataVolumeClaimSpec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 20G
        storageClassName: ibmc-block-bronze
      name: instance1
      replicas: 2
  openshift: true
  port: 5432
  postgresVersion: 13
  users:
    - databases:
        - modelbuilder
      name: modelbuilder
    - name: postgres

```
