### ISSUE TITLE
Can't change pg_hba in version 5

### ISSUE THREAD

**Issue by suzdalnitski** [CrunchyData/postgres-operator#3204]
Unable to change `pg_hba` configuration in version 5 of the operator, because the documentation does not have any information on configuring `ph_hba`. None of the steps outlined in the documentation of version 4 work. As a result, it currently is impossible to connect to the Postgres from outside of the Kubernetes cluster.

**Comment by suzdalnitski** [comment]
Finally found the answer, the config should go in here:

```yaml
kind: PostgresCluster
spec:
  patroni:
    dynamicConfiguration:
      postgresql:
        pg_hba:
        - local     all  all  trust
        - host      all  all  0.0.0.0/0   md5
        - host      all  all  ::1/128     md5
```

**Comment by bhanotjyoti** [comment]
@suzdalnitski : 

I tried using the dynamic configuration 

```


apiVersion: "acid.zalan.do/v1"
kind: postgresql
metadata:
  name: release-name
  namespace: test
  labels:
    helm.sh/chart: release-name-1.10.2
    app.kubernetes.io/name: release-name
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/managed-by: Helm
spec:
  patroni:
    dynamicConfiguration:
      postgresql:
        pg_hba:
        - local   all             all                                   trust
        - host    all             all                127.0.0.1/32       trust
        - host    all             all                ::1/128            trust
        - local   replication     standby                    trust
        - hostssl replication     standby all                md5
        - hostnossl all           all                all                trust
        - hostssl all             +zalandos    all                pam
        - hostssl all             all                all                md5
```


I get this error `postgresql in version "v1" cannot be handled as a postgresql: strict decoding error: unknown field "spec.patroni.dynamicConfiguration"`
