### ISSUE TITLE
Unable to clone from S3 backup

### ISSUE THREAD

**Issue by tuan1nguyen** [CrunchyData/postgres-operator#3233]
## Overview

pgbackrest-restore could not complete with following errors:

```
Unable to attach or mount volumes: unmounted volumes=[postgres-data], unattached volumes=[tmp postgres-data pgbackrest-config]: timed out waiting for the condition
```

```
MountVolume.SetUp failed for volume "pvc-6cf6c52d-a6f7-4fcd-9194-549d51398828" : applyFSGroup failed for vol 192.168.100.37#srv/nfs#pvc-6cf6c52d-a6f7-4fcd-9194-549d51398828: open /var/snap/microk8s/common/var/lib/kubelet/pods/a91bfd56-104a-48fc-a3d2-4dcc5dfe9117/volumes/kubernetes.io~csi/pvc-6cf6c52d-a6f7-4fcd-9194-549d51398828/mount/pg14: permission denied
```

## Environment

```
apiVersion: postgres-operator.crunchydata.com/v1beta1
kind: PostgresCluster
metadata:
  name: hippo
  namespace: hippo
spec:
  dataSource:
    pgbackrest:
      stanza: db
      configuration:
      - secret:
          name: pgo-s3-creds
      global:
        repo1-path: /pgbackrest/hippo/postgres-ha/repo1
      repo:
        name: repo1        
        s3:
          bucket: hippo-backup
          endpoint: api.xxx.localdomain
          region: eu-central-1
  image: registry.developers.crunchydata.com/crunchydata/crunchy-postgres:ubi8-14.2-1
  postgresVersion: 14
  instances:
    - replicas: 1
      dataVolumeClaimSpec:
        storageClassName: nfs-csi
        accessModes:
        - "ReadWriteOnce"
        resources:
          requests:
            storage: 10Gi
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 1
            podAffinityTerm:
              topologyKey: kubernetes.io/hostname
              labelSelector:
                matchLabels:
                  postgres-operator.crunchydata.com/cluster: hippo
                  postgres-operator.crunchydata.com/instance-set: instance1
  monitoring:
    pgmonitor:
      exporter:
        image: registry.developers.crunchydata.com/crunchydata/crunchy-postgres-exporter:ubi8-5.1.0-0
  backups:
    pgbackrest:
      image: registry.developers.crunchydata.com/crunchydata/crunchy-pgbackrest:ubi8-2.38-0        
      configuration:
      - secret:
          name: pgo-s3-creds
      global:
        repo1-path: /pgbackrest/hippo/repo1
        repo1-retention-full: "14"
        repo1-retention-full-type: time
        repo1-storage-verify-tls: "n"        
      manual:
        repoName: repo1
        options:
         - --type=full        
      repos:
      - name: repo1
        schedules:
          full: "0 1 * * *"
          incremental: "0 */4 * * *"
        s3:
          bucket: hippo-backup
          endpoint: api.xxx.localdomain
          region: eu-central-1
  proxy:
    pgBouncer:
      image: registry.developers.crunchydata.com/crunchydata/crunchy-pgbouncer:ubi8-1.16-2
      replicas: 1
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 1
            podAffinityTerm:
              topologyKey: kubernetes.io/hostname
              labelSelector:
                matchLabels:
                  postgres-operator.crunchydata.com/cluster: hippo
                  postgres-operator.crunchydata.com/role: pgbouncer

```
Please provide the following details:

- Platform: `Microk8s Kubernetes`
- Platform Version: `1.24`
- PGO Image Tag: `ubi8-5.1.0`
- Postgres Version `14`
- Storage:  `nfs`

### REPRO

-

### EXPECTED

Postgres cluster could be cloned from S3 backup

### ACTUAL

pgbackrest-restore could not complete due to mount permission denied

## Logs

-
## Additional Information

-
