### ISSUE TITLE
successfulJobsHistoryLimit & failedJobsHistoryLimit configuration values

### ISSUE THREAD

**Issue by gloaec** [CrunchyData/postgres-operator#3247]
## Overview

Allow `CronJob` spec values customization in PostgresCluster CRD :

- `successfulJobsHistoryLimit: 3`
- `failedJobsHistoryLimit: 1`

At the time being, there is no way to specify those values, and defaults values are the ones shown above.

https://github.com/CrunchyData/postgres-operator/blob/bbe528db567b4d38e1782d27d57eea7afc4463a6/internal/controller/postgrescluster/pgbackrest.go#L2883

## Use Case

For customization purposes, it'd be nice to have some configuration options for those two values : `successfulJobsHistoryLimit` / `failedJobsHistoryLimit`

## Desired Behavior

We could use the `pgBackRestConfig.repos` array to specify the values like such :

```yaml
pgBackRestConfig:
  repos:
    - name: repo1
      s3: { ... }
      schedules:
        full: "0 4/6 * * *"
        incremental: "10/30 * * * *"
      successfulJobsHistoryLimit: 1
      failedJobsHistoryLimit: 2
```
