### ISSUE TITLE
Unable to switchover the primary to available active replica (PGO v5)

### ISSUE THREAD

**Issue by nawarajshahi** [CrunchyData/postgres-operator#3254]
***Overview***
We're trying to switchover one of the active replica pod to be the new primary and are using pgo v5.0.4 but upon trying to edit the spec as instructed [here](https://access.crunchydata.com/documentation/postgres-operator/v5/tutorial/administrative-tasks/), we get the error regarding api validation failing and unknown field. 

Trying to add the following spec to prepare for switchover
```
spec:
  patroni:
    switchover:
      enabled: true
```

***Environment***
Environment Details
    Platform: Kubernetes
    Platform Version: 1.21
    PGO : v5.0.4
    Postgres Version 14
    Storage: gp3

***Steps to Reproduce***
---
Cluster Spec before that was applied to create postgrescluster:
```
apiVersion: postgres-operator.crunchydata.com/v1beta1
kind: PostgresCluster
metadata:
  name: pg
spec:      
  patroni:
    dynamicConfiguration:
      postgresql:
        parameters:
          checkpoint_completion_target: 0.7
          default_statistics_target: 100
          effective_cache_size: 12GB
          effective_io_concurrency: 200
          maintenance_work_mem: 1GB
          max_connections: 3000
          max_parallel_maintenance_workers: 4
          max_parallel_workers: 8
          max_parallel_workers_per_gather: 4
          max_wal_size: 4GB
          max_worker_processes: 8
          min_wal_size: 1GB
          random_page_cost: 1.1
          shared_buffers: 4GB
          wal_buffers: 16MB
          work_mem: 349kB
  users:
  - name: postgres
  monitoring:
    pgmonitor:
      exporter:
        image: registry.developers.crunchydata.com/crunchydata/crunchy-postgres-exporter:ubi8-5.0.4-0        
  proxy:
    pgBouncer:
      image: registry.developers.crunchydata.com/crunchydata/crunchy-pgbouncer:centos8-1.16-0
      config:
        global:
          default_pool_size: "100"
          max_client_conn: "10000"
          pool_mode: transaction
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: node-use-pg
                operator: In
                values:
                - "true"
            - matchExpressions:                
              - key: node-use-postgres
                operator: In
                values:
                - "true"
      tolerations:
        - effect: NoSchedule
          key: node-use-pg
          operator: Equal
          value: "true"      
  image: registry.developers.crunchydata.com/crunchydata/crunchy-postgres:centos8-14.1-0 
  postgresVersion: 14
  instances:
    - name: pg
      replicas: 2
      resources:
        requests:
          cpu: 2
          memory: 2Gi
        limits:
          cpu: 4
          memory: 4Gi
      dataVolumeClaimSpec:
        storageClassName: gp3
        accessModes:
        - "ReadWriteOnce"
        resources:
          requests:
            storage: 50Gi
      tolerations:
        - effect: NoSchedule
          key: node-use-pg
          operator: Equal
          value: "true"      
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: node-use-pg
                operator: In
                values:
                - "true"
            - matchExpressions:                
              - key: node-use-postgres
                operator: In
                values:
                - "true"                
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              topologyKey: kubernetes.io/hostname
              labelSelector:
                matchLabels:
                  postgres-operator.crunchydata.com/cluster: pg
                  postgres-operator.crunchydata.com/instance-set: pg
  backups:
    pgbackrest: 
      configuration:
      - secret:
          name: pgo-s3-creds
      manual:
        repoName: repo1
        options:
          - --type=full          
      global:
        repo1-path: /stg-kcmh-a-1/repo1
        repo1-retention-full: "14"
        repo1-retention-full-type: time
      repos:
      - name: repo1
        schedules:
          full: 0 1 * * *
        s3:
          bucket: pg-bucket-name
          endpoint: s3.amazonaws.com
          region: us-east-2
```

`kubectl edit postgrescluster pg -n pg` 

And add the following under `spec.patroni` block: 
```
    switchover:
      enabled: true
```

**Expected** 
Expected to have successful modification of postgrescluster spec with the above block AND when issuing the following command, have current primary pod to switch its role with one of the active replicas. Thus, promoting one of the active replica to be the new primary and the former primary's role to switch to replica. 
```
kubectl annotate -n pg postgrescluster pg \
  postgres-operator.crunchydata.com/trigger-switchover="$(date)"
```

***Actual***
At the preparation stage of modifying the spec for switchover, we get the following error when editing the postgrescluster spec. 

ERROR: 
```
# Please edit the object below. Lines beginning with a '#' will be ignored,
# and an empty file will abort the edit. If an error occurs while saving this file will be
# reopened with the relevant failures.
#
# postgresclusters.postgres-operator.crunchydata.com "pg" was not valid:
# * <nil>: Invalid value: "The edited file failed validation": ValidationError(PostgresCluster.spec.patroni): unknown field "switchover" in com.crunchydata.postgres-operator.v1beta1.PostgresCluster.spec.patroni
#
apiVersion: postgres-operator.crunchydata.com/v1beta1
kind: PostgresCluster
```
