### ISSUE TITLE
pgo 5 | restore ignores "options" - only the last backup can be restored.

### ISSUE THREAD

**Issue by tirelibirefe** [CrunchyData/postgres-operator#3257]
Hello,
Actually my [existing support request](https://github.com/CrunchyData/postgres-operator/issues/3196) was closed (I don't know why it was closed), I needed to re-open it.

Here is the relevant part of yaml:

```
  backups:
    pgbackrest:
      image: registry.developers.crunchydata.com/crunchydata/crunchy-pgbackrest:ubi8-2.38-0
      configuration:
      - secret:
          name: psql-ferahevler-s3-creds
      - secret:
          name: ferahevler-pgbackrest-secrets
      manual:
        repoName: repo1
        options:
         - --type=full
      global:
        repo1-path: /repo1/ferahevler
        repo1-retention-full: "14"
        repo1-retention-full-type: time
        repo1-cipher-type: aes-256-cbc
      repos:
      - name: repo1
        schedules:
          full: "0 1 * * *"
          incremental: "0 */6 * * *"
        s3:
          bucket: ku-eksdev1-crunchydata-backups
          endpoint: s3.eu-central-1.amazonaws.com:443
          region: eu-central-1
      restore:
        enabled: true
        repoName: repo1
        options:
        - --set=20220608-135823F
```

I set non-existing backup; something like that:

```
      restore:\
        enabled: true\
        repoName: repo1\
        options:\
        - --set=dummytext12345\
        - --target-action=promote\
        - --type=immediate'\

```

nothing changes; the latest backup is restored; there is no any error messages in restore job.

I set dummy option something like that;

```
      restore:\
        enabled: true\
        repoName: repo1\
        options:\
        - --set=dummytext12345\
        - --target-action=promote\
        - --type=immediate'\
        - --dummy-text1234-dummy-text1234-dummy-text1234
```

nothing changes; the latest backup is restored; there is no any error messages in restore job.

PGO ignores whatever we set under `options`.

That's why unable to restore from specific backup.

I will be very appreciated if you can advise. This is very important factor to decide production usage of pgo.

Thanks & Regards

**Comment by tirelibirefe** [comment]
well, actually I asked there and got the answer; 
```
        - --set=20220608-135823F
        - --type=immediate
```

...but as I explained above, it looks like a "bug" to me more than a question, because pgo ignore whatever I set under "options".

Thanks & Regards

**Comment by cbandy** [comment]
@tirelibirefe how are you triggering the restore? Are you creating a new PostgresCluster object or are you annotating an existing one?

**Comment by tjmoore4** [comment]
Hello @tirelibirefe,

It's worth pointing out that when using a PITR recovery to create a new cluster (rather than when doing an 'in-place' recovery on an existing cluster), you will want to use the `spec.dataSource` section rather than the the `spec.backups.pgbackrest.restore` section of your manifest. This is decribed in the `Perform a Point-in-time-Recovery (PITR)` portion of the [Disaster Recovery tutorial](https://access.crunchydata.com/documentation/postgres-operator/5.1.1/tutorial/disaster-recovery/). The relevant manifest begins with
```
apiVersion: postgres-operator.crunchydata.com/v1beta1
kind: PostgresCluster
metadata:
  name: elephant
spec:
  dataSource:
    postgresCluster:
      clusterName: hippo
      repoName: repo1
      options:
      - --type=time
      - --target="2021-06-09 14:15:11-04"
...
```
where `elephant` is the new cluster and `hippo` is the existing cluster. Once the manifest is applied, this restore method won't require any annotations.

For clarification in case you've also been testing 'In-Place' restores, it is worth noting that any subsequent restore you wish to execute will require a unique annotation. Using the example from the `Perform an In-Place Point-in-time-Recovery (PITR)` section of the [same tutorial](https://access.crunchydata.com/documentation/postgres-operator/5.1.1/tutorial/disaster-recovery/), if your first in-place restore was initiated with
```
kubectl annotate -n postgres-operator postgrescluster hippo --overwrite \
  postgres-operator.crunchydata.com/pgbackrest-restore=id1
```
Your next in-place restore annotation would need a new value, e.g. `id2`. Hope this helps.
