### ISSUE TITLE
Set Postgres users' passwords declaratively

### ISSUE THREAD

**Issue by gricey432** [CrunchyData/postgres-operator#3262]
## Overview

#2807 provided a way to set a password for a user using `kubectl patch`.
But there doesn't seem to be a way to do this declaratively in my `postgres.yaml` file.

## Use Case

We're importing existing databases into a LAN-only k8s cluster and these clusters have existing passwords we'd like to keep using.

We're destroying and re-creating PGO clusters, but I can't fix their passwords in place.

## Desired Behavior

`PostgresCluster.spec.users[index].password` would provide a passthrough for `stringData` and/or `data`.

Or maybe explicit password and verifier fields, whatever makes more sense.

## Environment

Tell us about your environment:

Please provide the following details:

- Platform: EKS
- Platform Version: eks.2 k8s 1.22
- PGO Image Tag: `ubi8-14.2-1`
- Postgres Version: `14`
- Storage: `gp3`
- Number of Postgres clusters: `2`

**Comment by pere3** [comment]
any way of providing a password through secret/configmap ref would suffice, actually

**Comment by pere3** [comment]
https://access.crunchydata.com/documentation/postgres-operator/5.1.2/architecture/user-management/#custom-passwords there is a way tho

**Comment by gricey432** [comment]
> https://access.crunchydata.com/documentation/postgres-operator/5.1.2/architecture/user-management/#custom-passwords there is a way tho

Yeah, I've mentioned that in the first line of my ticket.
This is about being able to do it declaratively through manifests (AWS CDK in my case), this helps with repeatable deployments or high volumes.

**Comment by 0x86f** [comment]
Ist there any commitment or workaround (not the manual patch-way) for this enhancement? 

I would like to set a custom password by using a secretRef. The referenced secret would be created for example via sealedsecrets-operator.

We would like to use this enhancement for our Gitops-workflow.

**Comment by tony-landreth** [comment]
Hello, @gricey432! We've captured this request in our backlog. Thanks.

**Comment by arnouthoebreckx** [comment]
bump

**Comment by hdiass** [comment]
+1

**Comment by lukastopiarz** [comment]
+1  We would definitely love the possibility of secretRef for the external secret with password.
Currently, in our gitops workflow we have to create Kyverno policy to patch pguser secret (To allow sealed secrets controller patch and manage existing file) and then patching the password key using sealed secret.  Not a very nice gitops/declarative approach at all.

**Comment by kkapper** [comment]
+1

**Comment by rj-home** [comment]
+1

**Comment by dominik0711** [comment]
+1

**Comment by rj-home** [comment]
+1

**Comment by hdiass** [comment]
+1

**Comment by paretl** [comment]
+1

**Comment by koshrf** [comment]
I have a workaround I use with rancher fleet and sops operator, I can't change the secret directly with sops operator because the ownership, but I can save the password in a sopsecret and then run a job that patch the pgo secret. Probably not the best, but it works. PGO should be able to reference an external secret tho like other postgres operators. If you use external secret operator just read #3343 

This is just an example, adapt to your preferences.

```yaml
apiVersion: batch/v1
kind: Job
metadata:
  name: secret-patch-job
spec:
  backoffLimit: 6
  ttlSecondsAfterFinished: 3600
  template:
    metadata:
      name: secret-patch-job
    spec:
      serviceAccountName: secret-manager-sa
      containers:
      - name: secret-patch-container
        image: dtzar/helm-kubectl:latest #Just use whatever that can run kubectl commands and bash.
        command: ["/bin/bash", "-c"]
        env:
          - name: NAMESPACE
            value: "yourNamespace"
          - name: SOURCE_SECRET
            value: "sourceSecretOrSopsGeneratedSecret" #Contains: user, password, verify
          - name: TARGET_SECRET
            value: "database-pguser-database" 
        args:
          - |
            PASSWORD=$(kubectl get secret ${SOURCE_SECRET} -n ${NAMESPACE} -o jsonpath="{.data.password}" | base64 -d)
            USER=$(kubectl get secret ${SOURCE_SECRET} -n ${NAMESPACE} -o jsonpath="{.data.user}" | base64 -d)
            VERIFY=$(kubectl get secret ${SOURCE_SECRET} -n ${NAMESPACE} -o jsonpath="{.data.verify}" | base64 -d)
            #The job will retry if the secret doesn't exist, sops secrets aren't created instantly in some cases
            if [ -z "$PASSWORD" ] && [ -z "$USER" ]; then
              echo "Failed to retrieve secret."
              exit 1
            else
              echo "Password: ***************"
              echo "User: $USER"
              echo "Verify: $VERIFY"
              kubectl patch secret ${TARGET_SECRET} -n ${NAMESPACE} -p '{"stringData":{"user":"$(echo -n $USER | base64)","password":"$(echo -n $PASSWORD | base64)","verifier":"$(echo -n $VERIFY | base64)"}}'
            fi
      restartPolicy: Never
```

And remember to create the Service Account

```yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: secret-manager-sa

---

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: secret-access-role
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "patch", "list"]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: secret-access-binding
subjects:
- kind: ServiceAccount
  name: secret-manager-sa 
roleRef:
  kind: Role
  name: secret-access-role
  apiGroup: rbac.authorization.k8s.io

```

**Comment by Alansyf** [comment]
+1, all live postgresql hard to asking for a simple password change. (this require huge efforts to ask all application team to change their code and redeploy). 
All existing secrets are stored as k8s secret, thus a secretRef is the best thing we are looking for.

**Comment by gricey432** [comment]
I think this might actually be available in 5.6, relevant section in the docs: https://access.crunchydata.com/documentation/postgres-operator/latest/tutorials/basic-setup/user-management#creating-a-new-user-declaratively

I haven't tried it out yet myself so I can't comment on the behaviour, especially around things like what happens if you modify the password after cluster creation.

**Comment by koshrf** [comment]
> I think this might actually be available in 5.6, relevant section in the docs: https://access.crunchydata.com/documentation/postgres-operator/5.6/tutorials/basic-setup/user-management#creating-a-new-user-declaratively
> 
> I haven't tried it out yet myself so I can't comment on the behaviour, especially around things like what happens if you modify the password after cluster creation.

I hope this isn't the solution because it doesn't solve the issue. That just create an user with no privileges and without access to the database created on the cluster, it is pretty much worthless since it will require another job to set permissions right.

I don't think anyone asked to create users with a secret, what was asked was to use secrets to manipulate the current users on the PostgresCluster manifest. The PostgresCluster can already create users, don't know why would anyone want to create an user with no permission and outside the original PG cluster manifest, it feels anti-pattern.

**Comment by cloudcafetech** [comment]
Confluence does not accepting/recognize  grater than less than  " > < " sign in password. 
```
  patroni:
    dynamicConfiguration:
      postgresql:
        pg_hba:
          - host all all 0.0.0.0/0 md5
```
any suggestion ??
