### ISSUE TITLE
Scheduled backups not running

### ISSUE THREAD

**Issue by mariusstaicu** [CrunchyData/postgres-operator#3285]
## Overview

After upgrading to v5 version from v4, scheduled backups are not running anymore.

## Environment

Please provide the following details:

- Platform: Kubernetes
- Platform Version: v1.21.11-gke.900
- PGO Image Tag: ubi8-5.1.1-0
- Postgres Version: 13.6
- Storage: standard pd

## Steps to Reproduce

Provide steps to get to the error condition:

1. deploy operator - tried with both 5.1.0 and 5.1.1
2. deploy a PostgresCluster resource
```yaml
apiVersion: postgres-operator.crunchydata.com/v1beta1
kind: PostgresCluster
metadata:
  name: grafana-db
  namespace: infrastructure
spec:
  postgresVersion: 13
  instances:
    - replicas: 2
      dataVolumeClaimSpec:
        accessModes:
          - "ReadWriteOnce"
        resources:
          requests:
            storage: 2Gi
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 1
              podAffinityTerm:
                topologyKey: kubernetes.io/hostname
                labelSelector:
                  matchLabels:
                    postgres-operator.crunchydata.com/cluster: grafana-db
                    postgres-operator.crunchydata.com/instance-set: "00"
  backups:
    pgbackrest:
      global:
        repo1-retention-full: "14"
        repo1-retention-full-type: time
      repos:
        - name: repo1
          schedules:
            full: "0 1 * * 0"
            incremental: "0 1 * * 1-6"
          volume:
            volumeClaimSpec:
              accessModes:
                - "ReadWriteOnce"
              resources:
                requests:
                  storage: 5Gi
  monitoring:
    pgmonitor:
      exporter:
        image: registry.developers.crunchydata.com/crunchydata/crunchy-postgres-exporter:ubi8-5.1.1-0
  users:
    - name: grafana-db
      databases:
        - "grafana-db"
```        

### EXPECTED

backups should be made every night at 1 AM, with full backup on sunday and incremental backups on the other days

### ACTUAL

- a single full backup is made upon resource creation and no more backups are done after.
- wal size keeps growing continuously 

## Logs
I attached the logs from when the pgcluster is created. There are some errors, the operator complains that it cannot find the cluster, however the cluster gets created and it is there in that namespace.

[pgo.log](https://github.com/CrunchyData/postgres-operator/files/9029993/pgo.log)

## Additional Information

In the past, when scheduling backups, I noticed that some cronjobs were created in k8s.
I don't have any cronjobs in k8s, there is only one batch job created which apparently triggers the first full backup that is done upon pgcluster creation.
