### ISSUE TITLE
Setting up pgMonitor to expose metrics to Prometheus/Grafana

### ISSUE THREAD

**Issue by bilalbokharee** [CrunchyData/postgres-operator#3287]
## Overview

I have grafana and prometheus already setup in my cluster and I want to connect pg_monitor to it and expose metrics to use in pre-deployed grafana. I have only added `monitoring` section in cluster instance so far. [Documentation](https://access.crunchydata.com/documentation/postgres-operator/4.6.1/installation/metrics/postgres-operator-metrics/) tells me that I have to do some installations for PGO Monitoring stack separately, but the pgo-metrics-deployer-cm configMap contains keys like `grafana_install` and `prometheus_install` etc. I do not want to do fresh installations. I want to use my current setup and I want everything to come via gitops and nothing manually. the `monitoring` section i have added in cluster instance adds a new container in postgres instance pod and that fails with errors

`psql: error: connection to server at "localhost" (::1), port 5432 failed: FATAL: password authentication failed for user "ccp_monitoring"`
and
`connection to server at "localhost" (127.0.0.1), port 5432 failed: Connection refused
Is the server running on that host and accepting TCP/IP connections?`

What am I missing and what do I need to do to create this user? 
Also, documentation says that CR and CRB do not need to be created separately if created before? It's confusing. Can I not setup monitoring via OLM somehow? Or define all that needs to be defined in postgres instance CR manifest.

Side question: How do I specify time interval for pgBackRest to take backups. Its too frequent by default and fills up the storage pretty fast

## Environment

Please provide the following details:

- Platform: `OpenShift`
- Platform Version: `4.10.0`
- PGO Image Tag: `ubi8-5.1.0-0`
- Postgres Version `14.2`

### REPRO

Provide steps to get to the error condition:

```
apiVersion: postgres-operator.crunchydata.com/v1beta1
kind: PostgresCluster
metadata:
  name: postgres
  namespace: signport-dev
spec:
  patroni:
    dynamicConfiguration:
      postgresql:
        pg_hba:
          - "hostnossl all all all password"
  image: registry.developers.crunchydata.com/crunchydata/crunchy-postgres:centos8-14.2-0
  postgresVersion: 14
  instances:
    - name: instance1
      dataVolumeClaimSpec:
        accessModes:
        - "ReadWriteOnce"
        resources:
          requests:
            storage: 100Gi
  backups:
    pgbackrest:
      repos:
      - name: repo1
        volume:
          volumeClaimSpec:
            accessModes:
            - "ReadWriteOnce"
            resources:
              requests:
                storage: 1Gi
  monitoring:
    pgmonitor:
      exporter:
        image: registry.developers.crunchydata.com/crunchydata/crunchy-postgres-exporter:ubi8-5.1.1-0`
```
### EXPECTED

1. Monitoring container runs error free

### ACTUAL

1. Errors as described
