### ISSUE TITLE
Using an external secret manager for password/user

### ISSUE THREAD

**Issue by slamer59** [CrunchyData/postgres-operator#3343]
## Questions

Before using this operator, I wonder if it possible to use an external credential manager. I am using the External Secret Operator but it can be anything another logic. 

If possible, how would you do ?

**Comment by jlevertov** [comment]
I am using externalsecret operator as well. I managed to set to a custom password, by creating an external secret, which at the source has 2 keys: password and verifier
looks like this:
```json
{
  "password": <my password>,
  "verifier": "" (empty value)
}
```
In the external secret yaml I set the following:
```yaml
refreshRate: '0' (so it will fetch the secret only once)
target:
  creationPolicy: Merge (So it won't be the owner of the secret, but update it)
```
Also, I am using Helm to deploy my application, and I added the `post-install` helm hook to the external secret so it will be created after the postgres deployment was created by PGO.
