### ISSUE TITLE
Unable to set Job .template.metadata.annotations

### ISSUE THREAD

**Issue by npapapietro** [CrunchyData/postgres-operator#3368]
## Overview

The metadata exposed on the CRD only applies the metadata labels to the `.metadata` on the `Job` but not its `.spec.template.metadata` of the `Pod` kicked off by the job when a migration occurs.

For example if I configure my cluster as:

```yaml
apiVersion: postgres-operator.crunchydata.com/v1beta1
kind: PostgresCluster
metadata:
  name: cluster1
  namespace: someCluster
spec:
  metadata:
    annotations:
      sidecar.istio.io/inject: "false"
  // ...
  instances:
    - name: instance1
      metadata:
        annotations:
          sidecar.istio.io/inject: "false"
        // ...
  backups:
    pgbackrest:
      metadata:
        annotations:
          sidecar.istio.io/inject: "false"
        // ...

```
None of those make it to the job pod.  As you see in my example, this has a strong use case for working with [Istio](https://istio.io/)

### Code Links

 `Job.metadata` 
https://github.com/CrunchyData/postgres-operator/blob/master/internal/controller/postgrescluster/volumes.go#L435
 
`Job.metadata.spec.template.metadata` 
https://github.com/CrunchyData/postgres-operator/blob/master/internal/controller/postgrescluster/volumes.go#L477

## Environment

- Platform: EKS
- Platform Version: 1.23
- PGO Image Tag: `ubi8-5.1.2-0`
- Postgres Version: `12`
