### ISSUE TITLE
Pgo Upgrade documentation

### ISSUE THREAD

**Issue by Martin-Hogge** [CrunchyData/postgres-operator#3379]
Hi, I'm here because I feel like there is a lack of documentation about how we are supposed to upgrade PGO.

I actually run CrunchyData on kubernetes with the following docker image versions:
- `postgres-operator` at version `ubi8-5.1.0-0`
- `pgo-upgrade` at version `ubi8-5.1.0-0` (not sure what is the purpose of this one)
- postgres database at version `centos8-13.4-1`
- exporter at version `ubi8-5.0.3-0`
- pgbackrest at version `ubi8-2.38-0`

I used kustomize to install CrunchyData and to apply changes to my cluster.

My main issue is that I want to upgrade to the latest `5.2.0` version but I don't know by what to begin with. What is the best way to do an upgrade ?

- Should I make a fork of `postgres-example` and "simply" apply changes ?
- Should I update the postgres database's image before upgrading PGO ? Or maybe after ? Or maybe not at all ?
- Same for exporter and pgbackrest, should I manually upgrade the images ?
-  In my case I see that my database version is `centos...` while other images are `ubi8...`, should I switch to `ubi8` ? If yes
, how and what is the impact of not doing it?

One last question, does an upgrade means downtime ? Should I stop my services while executing the upgrade ?

Thank you.

**Comment by pere3** [comment]
kustomize allows you to use external yaml links in resources block, like this:

```
❯ cat sources/kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: postgres-operator

resources:
  - https://raw.githubusercontent.com/CrunchyData/postgres-operator-examples/main/kustomize/install/namespace/namespace.yaml
  - https://raw.githubusercontent.com/CrunchyData/postgres-operator-examples/main/kustomize/install/crd/bases/postgres-operator.crunchydata.com_pgupgrades.yaml
  - https://raw.githubusercontent.com/CrunchyData/postgres-operator-examples/main/kustomize/install/crd/bases/postgres-operator.crunchydata.com_postgresclusters.yaml
  - https://raw.githubusercontent.com/CrunchyData/postgres-operator-examples/main/kustomize/install/rbac/cluster/service_account.yaml
  - https://raw.githubusercontent.com/CrunchyData/postgres-operator-examples/main/kustomize/install/rbac/cluster/role.yaml
  - https://raw.githubusercontent.com/CrunchyData/postgres-operator-examples/main/kustomize/install/rbac/cluster/role_binding.yaml
  - https://raw.githubusercontent.com/CrunchyData/postgres-operator-examples/main/kustomize/install/rbac/cluster/service_account-upgrade.yaml
  - https://raw.githubusercontent.com/CrunchyData/postgres-operator-examples/main/kustomize/install/rbac/cluster/role-upgrade.yaml
  - https://raw.githubusercontent.com/CrunchyData/postgres-operator-examples/main/kustomize/install/rbac/cluster/role_binding-upgrade.yaml
  - https://raw.githubusercontent.com/CrunchyData/postgres-operator-examples/main/kustomize/install/manager/manager.yaml
  - https://raw.githubusercontent.com/CrunchyData/postgres-operator-examples/main/kustomize/install/manager/manager-upgrade.yaml
```

then `kustomize build sources > install.yaml` will combine all this specs into a single one, that later can be mentioned inside another kustomization.yaml with all needed patches and stuff:
```
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: postgres-operator

commonLabels:
  app.kubernetes.io/name: pgo
  app.kubernetes.io/version: 5.2.0

resources:
- ./install.yaml

images:
- name: postgres-operator
  newName: registry.developers.crunchydata.com/crunchydata/postgres-operator
  newTag: ubi8-5.2.0-0
- name: postgres-operator-upgrade
  newName: registry.developers.crunchydata.com/crunchydata/postgres-operator-upgrade
  newTag: ubi8-5.2.0-0

patchesJson6902:
- target: { group: apps, version: v1, kind: Deployment, name: pgo }
  path: ./patches/selectors.yaml
- target: { group: apps, version: v1, kind: Deployment, name: pgo-upgrade }
  path: ./patches/selectors.yaml
```

Last step is to server-side apply this kustomization (by hand or any application controller with gitops):
```kubectl apply --server-side -k ./```


About downtime, for me that was an unpleasant surprise, that pgo upgrade from 5.1.2 to 5.2.0 happens to perform a switchover on all of current pg-clusters - and now i'm wonder is this a controllable behaviour?

@andrewlecuyer can you please comment on this?
