### ISSUE TITLE
pgo 5.2.0, spec.instances.containers not working

### ISSUE THREAD

**Issue by pere3** [CrunchyData/postgres-operator#3402]
Please ensure you do the following when reporting a bug:

- [x] Provide a concise description of what the bug is.
- [x] Provide information about your environment.
- [x] Provide clear steps to reproduce the bug.
- [x] Attach applicable logs. Please do not attach screenshots showing logs unless you are unable to copy and paste the log data.
- [x] Ensure any code / output examples are [properly formatted](https://docs.github.com/en/github/writing-on-github/basic-writing-and-formatting-syntax#quoting-code) for legibility.

## Overview

Hello, crunchy team

version 5.2.0 introduced an ability to add custom sidecar containers to PostgreSQL pods
https://access.crunchydata.com/documentation/postgres-operator/latest/releases/5.2.0/#features

according to my tries - feature is not working, and containers stanza completely ignored by operator

## Environment

Please provide the following details:

- Platform: GKE
- Platform Version: 1.23.8-gke.1900
- PGO Image Tag: ubi8-5.2.0-0
- Postgres Version: 14
- Storage: pd-ssd

### REPRO

Deploy a PostgresCluster manifest with `containers` spec under instances:

```
apiVersion: postgres-operator.crunchydata.com/v1beta1
kind: PostgresCluster
metadata:
  name: db-template-vanilla
spec:
  image: registry.developers.crunchydata.com/crunchydata/crunchy-postgres:ubi8-14.5-1
  postgresVersion: 14
  users:
    - name: postgres
  instances:
    - replicas: 1
      containers:
        - name: pgbackrest-exporter
          ports:
            - containerPort: 9854
          image: woblerr/pgbackrest_exporter:v0.11.1
      resources:
        requests:
          cpu: '0.1'
          memory: '1Gi'
      dataVolumeClaimSpec:
        accessModes:
          - "ReadWriteOnce"
        resources:
          requests:
            storage: 32Gi
  backups:
    pgbackrest:
      image: registry.developers.crunchydata.com/crunchydata/crunchy-pgbackrest:ubi8-2.40-1
      repos:
        - name: repo1
          volume:
            volumeClaimSpec:
              accessModes:
                - "ReadWriteOnce"
              resources:
                requests:
                  storage: 4Gi
```

### EXPECTED

Expecting +1 container named `pgbackrest-exporter` inside StatefulSet pod.

### ACTUAL

`pgbackrest-exporter` not being created.

```
❯ kubectl get pods -l postgres-operator.crunchydata.com/cluster=db-template-vanilla
NAME                                    READY   STATUS      RESTARTS   AGE
db-template-vanilla-00-9xt5-0           4/4     Running     0          15m
db-template-vanilla-backup-zxgh-mzvhv   0/1     Completed   0          10m
db-template-vanilla-repo-host-0         2/2     Running     0          15m
```

```
❯ kubectl get pod db-template-vanilla-00-9xt5-0 -o jsonpath="{.spec.containers[*].name}"
database replication-cert-copy pgbackrest pgbackrest-config
```

## Logs

pgo logs shows ```stdout="Not changed\n"``` after PostgresCluster spec edit with corresponding configuration

```
      containers:
        - name: pgbackrest-exporter
          ports:
            - containerPort: 9854
          image: woblerr/pgbackrest_exporter:v0.11.1
```         

```time="2022-10-04T12:19:12Z" level=debug msg="replaced configuration" file="internal/patroni/api.go:150" func=patroni.Executor.ReplaceConfiguration name=db-template-vanilla namespace=postgres reconciler group=postgres-operator.crunchydata.com reconciler kind=PostgresCluster stderr= stdout="Not changed\n" version=5.2.0-0
time="2022-10-04T12:19:12Z" level=debug msg="reconciled instance" file="internal/controller/postgrescluster/instance.go:1130" func="postgrescluster.(*Reconciler).reconcileInstance" instance=db-template-vanilla-00-9xt5 name=db-template-vanilla namespace=postgres reconciler group=postgres-operator.crunchydata.com reconciler kind=PostgresCluster version=5.2.0-0
time="2022-10-04T12:19:12Z" level=debug msg="reconciled instance set" file="internal/controller/postgrescluster/instance.go:1026" func="postgrescluster.(*Reconciler).scaleUpInstances" instance-set=00 name=db-template-vanilla namespace=postgres reconciler group=postgres-operator.crunchydata.com reconciler kind=PostgresCluster version=5.2.0-0
time="2022-10-04T12:19:12Z" level=debug msg="reconciled cluster" file="internal/controller/postgrescluster/controller.go:351" func="postgrescluster.(*Reconciler).Reconcile" name=db-template-vanilla namespace=postgres reconciler group=postgres-operator.crunchydata.com reconciler kind=PostgresCluster version=5.2.0-0
time="2022-10-04T12:19:12Z" level=debug msg="patched cluster status" file="internal/controller/postgrescluster/controller.go:190" func="postgrescluster.(*Reconciler).Reconcile.func2" name=db-template-vanilla namespace=postgres reconciler group=postgres-operator.crunchydata.com reconciler kind=PostgresCluster version=5.2.0-0
time="2022-10-04T12:19:12Z" level=debug msg="replaced configuration" file="internal/patroni/api.go:150" func=patroni.Executor.ReplaceConfiguration name=db-template-vanilla namespace=postgres reconciler group=postgres-operator.crunchydata.com reconciler kind=PostgresCluster stderr= stdout="Not changed\n" version=5.2.0-0
time="2022-10-04T12:19:13Z" level=debug msg="reconciled instance" file="internal/controller/postgrescluster/instance.go:1130" func="postgrescluster.(*Reconciler).reconcileInstance" instance=db-template-vanilla-00-9xt5 name=db-template-vanilla namespace=postgres reconciler group=postgres-operator.crunchydata.com reconciler kind=PostgresCluster version=5.2.0-0
time="2022-10-04T12:19:13Z" level=debug msg="reconciled instance set" file="internal/controller/postgrescluster/instance.go:1026" func="postgrescluster.(*Reconciler).scaleUpInstances" instance-set=00 name=db-template-vanilla namespace=postgres reconciler group=postgres-operator.crunchydata.com reconciler kind=PostgresCluster version=5.2.0-0
time="2022-10-04T12:19:13Z" level=debug msg="reconciled cluster" file="internal/controller/postgrescluster/controller.go:351" func="postgrescluster.(*Reconciler).Reconcile" name=db-template-vanilla namespace=postgres reconciler group=postgres-operator.crunchydata.com reconciler kind=PostgresCluster version=5.2.0-0
```
