### ISSUE TITLE
How to re-populate (refresh) an existing cluster while keeping volume based (pvc) backups?

### ISSUE THREAD

**Issue by mzwettler2** [CrunchyData/postgres-operator#3406]
I created a new, fresh cluster my-clone from my actual production cluster my-prod.
I did this using the following spec.dataSource section:

```
  dataSource:
    postgresCluster:
      clusterNamespace: my-namespace
      clusterName: my-prod
      repoName: repo1
```
This worked as described in the documentation.

After a while I wanted to re-populate this clone with fresh data.
**I wanted to keep all my volume based (pvc) backups from my-clone to be able to restore my-clone to an old state before I re-populated it with fresh data**
So, I tried this refresh using the following spec.dataSource section:

```
  dataSource:
    postgresCluster:
      clusterNamespace: my-namespace
      clusterName: my-prod
      repoName: repo1
    volumes:
      pgDataVolume:
        pvcName: my-clone-instance1-54bf-pgdata
      pgBackRestVolume: 
        pvcName: my-clone-repo1
```
Nothing happend after I applied it.
I had to delete the whole cluster (kubectl delete postgrescluster my-clone) followed by an apply.

Afterwards, i found that **PGO did not reuse my old pv**'s. 
It created new, empty ones (pv).
So, all my volume based (pvc) backups which I wanted to keep where gone.

QUESTION: How can I achive what I want?

### Environment
- Platform: Anthos
- Platform Version: 1.10
- PGO Image Tag: ubi8-14.3-0
- Postgres Version: 14
- Storage: csi.vsphere.vmware.com

**Comment by QuingKhaos** [comment]
Hi @mzwettler2, you can use an in-place restore to restore the database cluster from another one:

```yaml
spec:
  backups:
    pgbackrest:
      restore:
        enabled: true
        clusterNamespace: my-namespace
        clusterName: my-prod
        repoName: repo1
```

and trigger it with the restore annotation:

```
kubectl annotate -n postgres-operator postgrescluster hippo --overwrite \
  postgres-operator.crunchydata.com/pgbackrest-restore=id1
```
