### ISSUE TITLE
Support metadata on PVC claims

### ISSUE THREAD

**Issue by QuingKhaos** [CrunchyData/postgres-operator#3412]
## Overview

Support adding labels and annotations to the PVC claims, so PGO reconciles the wanted annotations and labels on the PVCs created.

## Use Case

Starting with ODF 4.10, we can reclaim space on Ceph RDB by annotating the PVCs with the [`reclaimspace.csiaddons.openshift.io/schedule` annotation](https://access.redhat.com/documentation/en-us/red_hat_openshift_data_foundation/4.10/html-single/managing_and_allocating_storage_resources/index#enabling_reclaim_space_operation_using_annotating_persistentvolumeclaims) to create a `ReclaimSpaceCronJob` for the PVC.

Enabling this behavior on specific PVCs requires to add the annotation. Creating a `ReclaimSpaceCronJob` doesn't work in a GitOps workflow, as the PGO PVC names have a dynamic suffix (except the repo host).

## Desired Behavior

Feels weird to have metadata on the same level of the spec.

```yaml
spec:
  instances:
    - name: db
      dataVolumeClaimSpec:
        metadata:
          labels:
          annotations:
        storageClassName: ocs-storagecluster-ceph-rbd
      walVolumeClaimSpec:
        metadata:
          labels:
          annotations:
        storageClassName: ocs-storagecluster-ceph-rbd
  backups:
    pgbackrest:
      repos:
        - name: repo1
          volume:
            volumeClaimSpec:
              metadata:
                labels:
                annotations:
              storageClassName: ocs-storagecluster-ceph-rbd
```

Another design possibility would be to introduce new template keys (like stafeful sets), while keeping the old ones for BC. Feels more naturally to have `metadata` and `spec` side-by-side.

```yaml
spec:
  instances:
    - name: db
      dataVolumeClaimTemplate:
        metadata:
          labels:
          annotations:
        spec:
          storageClassName: ocs-storagecluster-ceph-rbd
      walVolumeClaimTemplate:
        metadata:
          labels:
          annotations:
        spec:
          storageClassName: ocs-storagecluster-ceph-rbd
  backups:
    pgbackrest:
      repos:
        - name: repo1
          volume:
            volumeClaimTemplate:
              metadata:
                labels:
                annotations:
              spec:
                storageClassName: ocs-storagecluster-ceph-rbd
```

## Environment

- Platform: `OpenShift`
- Platform Version: `4.10`
- PGO Operator Version: `5.2`
- Storage: ODF 4.10
