### ISSUE TITLE
Database & User mgmt does not support multiple users for single db

### ISSUE THREAD

**Issue by rhrytskiv** [CrunchyData/postgres-operator#3423]
```
users:
    - name: organizations-owner
      databases:
        - organizations
      options: "CREATEDB"
      password:
        type: AlphaNumeric

    - name: organizations-writer
      databases:
        - organizations
      password:
        type: AlphaNumeric
```

This for some reason does not result in organizations-writer having any access whatsoever.

**Comment by benjaminjb** [comment]
I just created a cluster with the above users and was able to log in with both users and check the db `organizations`. In what way are you having trouble getting acces?

**Comment by rhrytskiv** [comment]
@benjaminjb thanks. well, after the cluster is created I apply db migrations using organizations-owner creds and then I can't even select any data from those tables via organizations-writer, it has error 'permission denied for table'.

We've decided to switch from zalando pg operator to yours, and they had this neat feature where the cluster could be created with default users: owner, writer & reader. So I'm kind of trying to make that happen with your operator too, also tried to do it via db init sql script but it is not being applied, see https://github.com/CrunchyData/postgres-operator/issues/3422

**Comment by benjaminjb** [comment]
Ha, good timing, I was looking into that one right now, let me post what I have there, but I'm still looking into it.

**Comment by benjaminjb** [comment]
OK, I may or may not have got something working. Can you try this:

in the spec, add the users (but don't create the cluster yet till we have the configmap ready):

```
users:
    - name: "organizations-owner"
      databases:
        - organizations
      options: "CREATEDB"
      password:
        type: AlphaNumeric

    - name: "organizations-writer"
      databases:
        - organizations
      password:
        type: AlphaNumeric

    - name: "organizations-reader"
      databases:
        - organizations
      password:
        type: AlphaNumeric
    
    - name: "partners-owner"
      databases:
        - partners
      options: "CREATEDB"
      password:
        type: AlphaNumeric

    - name: "partners-writer"
      databases:
        - partners
      password:
        type: AlphaNumeric

    - name: "partners-reader"
      databases:
        - partners
      password:
        type: AlphaNumeric
```
Note: I had to put the names in quotes, something about that dash was interfering.

Second, in your db init sql, try something like this as an experiment:

```
    \set ON_ERROR_STOP
    \echo "EXECUTING DB INIT SCRIPT"

    \c partners
    ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO "partners-writer";
    ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT ON TABLES TO "partners-reader";

    \c organizations
    GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO "organizations-writer";
    GRANT SELECT                         ON ALL TABLES IN SCHEMA public TO "organizations-reader";
```
Note: from the PG docs: "ALTER DEFAULT PRIVILEGES allows you to set the privileges that will be applied to objects created in the future." ([here](https://www.postgresql.org/docs/9.4/sql-alterdefaultprivileges.html))

Now, if you create that configmap and then create the cluster and then run your loading script, does it work on the `partners` database and fail on the `organizations` database? I hope so!
