### ISSUE TITLE
Cluster get delete while In-place PITR

### ISSUE THREAD

**Issue by yasser1chihab** [CrunchyData/postgres-operator#3458]
**platform :  GKE version : 1.21.14-gke.3000
postgres operator version :  5.2
postgres version: 14** 
 

Expected behaviour : make in place PITR for a new created cluster  based on PVC of and old cluster
Resulted behaviour: delete the cluster Statefulset, and no restore was done

Configuration : 
```
apiVersion: postgres-operator.crunchydata.com/v1beta1
  kind: PostgresCluster
  metadata:
    name: cluster-pg-xxxx
    namespace: pg
  spec:
    image: registry.developers.crunchydata.com/crunchydata/crunchy-postgres:centos8-14.0-0
    postgresVersion: 14
    dataSource:
      volumes:
        pgBackRestVolume:
          pvcName: cluster-old-pvc-claim-name
    instances:
      - name: postgres-ad-manager
        replicas: 1
        resources:
          requests:
            cpu: ${var.db_request_cpu}
            memory: ${var.db_request_memory}
        dataVolumeClaimSpec:
          accessModes:
          - "ReadWriteOnce" 
          storageClassName: "ssd-retain"
          resources:
            requests:
              storage: 20Gi
        tolerations:
         - key: "dedicated"
           value: "pg-xxxx"
           operator: "Equal"
           effect: "NoSchedule"
        affinity:
          nodeAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              nodeSelectorTerms:
              - matchExpressions:
                  - key: "workload"
                    operator: In
                    values: 
                    - "pg-xxxx"
          podAntiAffinity:
            requiredDuringSchedulingIgnoredDuringExecution::
              - labelSelector:
                  matchExpressions:
                    - key: "postgres-operator.crunchydata.com/cluster"
                      operator: In
                      values:
                        - "cluster-pg-xxxx"
                topologyKey: "kubernetes.io/hostname"
    users:
      - name : admin
        options : "SUPERUSER"
    backups:
      pgbackrest:
        restore:
          enabled: true
          repoName: repo1
          options:
          - --type=time
          - --target="2022-11-14 07:00:00-00"
        global:
          repo1-retention-full: "4"
          repo1-retention-full-type: count
          repo1-path: /pgbackrest/repo1
        repoHost:
          tolerations:
            - key: "dedicated"
              value: "pg-xxxx"
              operator: "Equal"
              effect: "NoSchedule"
          affinity:
            nodeAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
                nodeSelectorTerms:
                - matchExpressions:
                    - key: "workload"
                      operator: In
                      values: 
                      - "pg-xxxx"
            podAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
                - labelSelector:
                    matchExpressions:
                      - key: "postgres-operator.crunchydata.com/role"
                        operator: In
                        values:
                          - "master"
                  topologyKey: "kubernetes.io/hostname"  
        repos:
        - name: repo1
          schedules:
            full: "0 3 * * 0"
          volume:
            volumeClaimSpec:
              accessModes:
              - "ReadWriteOnce"
              storageClassName: "ssd-retain"
              resources:
                requests:
                  storage: 20Gi
```

**P.S: the old pvc was successfully mounted to the repo-host pod of the new cluster**

pg-pgbackrest-restore pod log:
```
+ pgbackrest restore --type=time '--target=2022-11-14 07:00:00-00' --stanza=db --pg1-path=/pgdata/pg14 --repo=1 --delta --target-action=promote --link-map=pg_wal=/pgdata/pg14_wal
WARN: configuration file contains invalid option 'repo1-host-ca-file'
WARN: configuration file contains invalid option 'repo1-host-cert-file'
WARN: configuration file contains invalid option 'repo1-host-key-file'
WARN: configuration file contains invalid option 'repo1-host-type'
ERROR: [125]: remote-0 process on 'pg-repo-host-0.cluster-pg-xxxx-pods.pg.svc.cluster.local.' terminated unexpectedly [255]: ssh: connect to host pg-repo-host-0.cluster-pg-xxxx-pods.pg.svc.cluster.local. port 22: Connection refused
```
