### ISSUE TITLE
Restore from PV full backup

### ISSUE THREAD

**Issue by karloramone** [CrunchyData/postgres-operator#3459]
## Overview

Not able to create a new cluster from a full backup on PV - ceph.

## Environment

Please provide the following details:

- Platform: `Rancher`
- Platform Version: `v1.20.15`
- PGO Image Tag: `ubi8-5.2.0-0`
- Postgres Version `14`
- Storage: `ceph-rbd` 

## Steps to Reproduce

I am testing the operator for production and there is one disaster recovery procedure I'm not able to do. 
I created a cluster with backup repo1 to the ceph-rbd volume. 

```
apiVersion: postgres-operator.crunchydata.com/v1beta1
kind: PostgresCluster
metadata:
  name: test6
spec:
  postgresVersion: 14
  instances:
    - name: "instance1"
      replicas: 1
      dataVolumeClaimSpec:
        storageClassName: ceph-rbd
        accessModes:
        - "ReadWriteOnce"
        resources:
          requests:
            storage: "1Gi"
      resources:
        limits:
          cpu: "500m"
          memory: "1Gi"
  backups:
    pgbackrest:
      configuration:
      - secret:
          name: test6-pgbackrest-secret
      global:
      repos:
      - name: repo1
        volume:
          volumeClaimSpec:
            storageClassName: ceph-rbd
            accessModes:
            - "ReadWriteOnce"
            resources:
              requests:
                storage: "2Gi"
  proxy:
    pgBouncer:
      replicas: 1
  patroni:
    dynamicConfiguration:
      postgresql:
        parameters:
          synchronous_commit: "on"
      synchronous_mode: true
  users:
    - databases:
      - citadel
      name: rick
      options: CREATEDB CREATEROLE
    - databases:
      - citadel
      name: morty
  databaseInitSQL:
    name: "kvstore-init"
    key: "init.sql"
```
Some data was injected. A full backup is triggered and done, I've checked the content of a repo1 directory. 

```
[postgres@test6-repo-host-0 db]$ ls -l /pgbackrest/repo1/backup/db
total 20
drwxr-s--- 3 postgres postgres 4096 Nov 16 09:18 20221116-091804F
drwxr-s--- 3 postgres postgres 4096 Nov 16 09:31 20221116-093123F
drwxr-s--- 3 postgres postgres 4096 Nov 16 09:18 backup.history
-rw-r----- 1 postgres postgres 1712 Nov 16 09:31 backup.info
-rw-r----- 1 postgres postgres 1712 Nov 16 09:31 backup.info.copy
lrwxrwxrwx 1 postgres postgres   16 Nov 16 09:31 latest -> 20221116-093123F

```
The PV reclaim policy is set to Retain and the cluster was deleted. 
I am trying to create a new cluster from the backup. 
The procedure for restoring from the full backup on the S3 bucket is documented and it works, but I can't figure out how to set the`.spec.dataSource.pgbackrest` configuration for restoring from PV.

New cluster CRD:

```
apiVersion: postgres-operator.crunchydata.com/v1beta1
kind: PostgresCluster
metadata:
  name: pv-restore
spec:
  image: registry.developers.crunchydata.com/crunchydata/crunchy-postgres:ubi8-14.5-1
  postgresVersion: 14
  dataSource:
    pgbackrest:
      stanza: db
      global:
        repo1-path: /pgbackrest/repo1
      repo:
        name: repo1
        volume:
          volumeClaimSpec:
            volumeName: pvc-dabb7794-b250-4c26-8f64-4569ff6123c2
            resources:
              requests:
                storage: 2Gi
            storageClassName: ceph-rbd
            accessModes:
              - "ReadWriteOnce"
  instances:
    - dataVolumeClaimSpec:
        storageClassName: ceph-rbd
        accessModes:
        - "ReadWriteOnce"
        resources:
          requests:
            storage: 1Gi
  backups:
    pgbackrest:
      image: registry.developers.crunchydata.com/crunchydata/crunchy-pgbackrest:ubi8-2.40-1
      configuration:
      - secret:
          name: pgo-s3-creds
      global:
        repo1-path: /pgbackrest/postgres-operator/pv-restore/repo1
      repos:
      - name: repo1
        s3:
          bucket: "pgbackup"
          endpoint: "https://s3.ceph.xxx.com"
          region: "local"
```

### EXPECTED

1. New cluster is created with the restored data.

### ACTUAL

1. PVC not created and therefore not mounted in the restore pod.

## Logs

```
Defaulted container "pgbackrest-restore" out of: pgbackrest-restore, nss-wrapper-init (init)
+ pgbackrest restore --stanza=db --pg1-path=/pgdata/pg14 --repo=1 --delta --link-map=pg_wal=/pgdata/pg14_wal
WARN: unable to open log file '/pgdata/pgbackrest/log/db-restore.log': No such file or directory
      NOTE: process will continue without log file.
WARN: --delta or --force specified but unable to find 'PG_VERSION' or 'backup.manifest' in '/pgdata/pg14' to confirm that this is a valid $PGDATA directory.  --delta and --force have been disabled and if any files exist in the destination directories the restore will be aborted.
WARN: repo1: [FileMissingError] unable to load info file '/pgbackrest/repo1/backup/db/backup.info' or '/pgbackrest/repo1/backup/db/backup.info.copy':
      FileMissingError: unable to open missing file '/pgbackrest/repo1/backup/db/backup.info' for read
      FileMissingError: unable to open missing file '/pgbackrest/repo1/backup/db/backup.info.copy' for read
      HINT: backup.info cannot be opened and is required to perform a backup.
      HINT: has a stanza-create been performed?
ERROR: [075]: no backup set found to restore

```

Am I missing something in the CRD or this scenario is simply not possible?

**Comment by karloramone** [comment]
The issue is resolved.
1.  problem was that repo pod is writing the backup files to `/pgbackrest/repo1/backup/db` to the PV. 
Later, when restore pod mounted the backup the files are now somehow in `/pgdata` and not in `/pgbackrest/repo1/backup/db`  as they were before. 
```
dataSource:
    pgbackrest:
      stanza: db
      global:
        repo1-path: /pgdata
      repo:
        name: repo1
        volume:
          volumeClaimSpec:
            volumeName: pvc-28c1382b-921e-4831-bd56-fa1d0ef9fce6
```

2. The claimRef need to be deleted from the PV so it can be Bounded to restore PVC.
