### ISSUE TITLE
Align PGO secret keys with PG* environment variables

### ISSUE THREAD

**Issue by laurivosandi** [CrunchyData/postgres-operator#3461]
## Overview

Using CrunchyData provisioned secrets with `psql` is kind of a hassle, a style example follows:

```
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: scripts
data:
  create-table.sql: |
    CREATE TABLE IF NOT EXISTS app_user (
      username varchar(45) NOT NULL,
      password varchar(450) NOT NULL,
      enabled integer NOT NULL DEFAULT '1',
      PRIMARY KEY (username)
    )
---
apiVersion: batch/v1
kind: Job
metadata:
  name: create-table
spec:
  template:
    spec:
      volumes:
        - name: scripts
          configMap:
            name: scripts
      containers:
        - name: create-table
          image: postgres
          command:
            - psql
            - -f
            - /scripts/create-table.sql
          volumeMounts:
            - name: scripts
              mountPath: /scripts
          env:
            - name: PGHOST
              valueFrom:
                secretKeyRef:
                  name: postgres-pguser-postgres
                  key: host
            - name: PGUSER
              valueFrom:
                secretKeyRef:
                  name: postgres-pguser-postgres
                  key: user
            - name: PGDATABASE
              valueFrom:
                secretKeyRef:
                  name: postgres-pguser-postgres
                  key: dbname
            - name: PGPASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-pguser-postgres
                  key: password
            - name: PGPORT
              valueFrom:
                secretKeyRef:
                  name: postgres-pguser-postgres
                  key: port
```

## Use Case

I want to run various SQL scripts with Kubernetes. To simplify matters it would be great if PGO would use standard Postgres environment vartiables as key names. This makes it easier to use PGO.

## Desired Behavior

If env variables would have 1:1 mapping with configmap keys we could do something like this:

```
---
apiVersion: batch/v1
kind: Job
metadata:
  name: create-table
spec:
  template:
    spec:
      volumes:
        - name: scripts
          configMap:
            name: scripts
      containers:
        - name: create-table
          image: postgres
          command:
            - psql
            - -f
            - /scripts/create-table.sql
          volumeMounts:
            - name: scripts
              mountPath: /scripts
          envFrom:
            - configMapRef:
                name: postgres-pguser-postgres
```

## Environment

Tell us about your environment:

Please provide the following details:

- Platform: Kubernetes
- Platform Version: 1.25
- PGO Image Tag: ghcr.io/jelmer/postgres-operator:rocky9-v4.5.0-855-g1b8413409
- Postgres Version 14
- Storage: openebs-localpath

**Comment by cbandy** [comment]
I've experienced this as well.

Right now, for `psql`, you can reduce some toil by using the connection URI available in that same secret:

```yaml
          command:
            - psql
            - '$(URI)'
            - -f
            - /scripts/create-table.sql
          env:
            - name: URI
              valueFrom:
                secretKeyRef:
                  name: postgres-pguser-postgres
                  key: uri
```

If that user has access to other databases, you can switch to them as part of the `psql` command:

```yaml
          command:
            - psql
            - '$(URI)'
            - -c
            - '\c somedb' # or '\c $(SOME_VAR)' when it is defined in env
            - -f
            - /scripts/create-table.sql
          env:
            - name: URI
              valueFrom:
                secretKeyRef:
                  name: postgres-pguser-postgres
                  key: uri
```
