### ISSUE TITLE
Pgadmin oauth2 

### ISSUE THREAD

**Issue by rgherta** [CrunchyData/postgres-operator#3501]
According to pgadmin docs below ouath2 should easily integrate with any oauth2 provider
https://www.pgadmin.org/docs/pgadmin4/development/oauth2.html

However this configuration fails

```
  userInterface:
    pgAdmin:
      image: registry.developers.crunchydata.com/crunchydata/crunchy-pgadmin4:ubi8-4.30-6
      config:
        settings:
          #https://www.pgadmin.org/docs/pgadmin4/development/oauth2.html
          AUTHENTICATION_SOURCES: ['oauth2', 'internal']
          OAUTH2_NAME: "gitlab"
          OAUTH2_DISPLAY_NAME: "Gitlab"
          OAUTH2_CLIENT_ID: XXXXX
          OAUTH2_CLIENT_SECRET: XXXXX
          OAUTH2_TOKEN_URL: https://mydomain/oauth/token
          OAUTH2_AUTHORIZATION_URL: https://mydomain/oauth/authorize
          OAUTH2_API_BASE_URL: https://mydomain/oauth/
          OAUTH2_USERINFO_ENDPOINT: userinfo
          OAUTH2_SCOPE: "read_user email profile openid"
          OAUTH2_ICON: "fa-gitlab"
          OAUTH2_BUTTON_COLOR: "red"
          #OAUTH2_USERNAME_CLAIM:
          OAUTH2_AUTO_CREATE_USER: True
```
