### ISSUE TITLE
Additional user login failure

### ISSUE THREAD

**Issue by ricrug** [CrunchyData/postgres-operator#3502]
After adding an additional user, this is duly created, 
I can log into pgAdmin but the connection to the server is blocked with a password prompt.

```
spec:
  image: registry.developers.crunchydata.com/crunchydata/crunchy-postgres:ubi8-14.6-0
  postgresVersion: 14
  users:
    - name: additional-user
      databases:
        - pgha
        - postgres
```
