### ISSUE TITLE
Failed upgrade from 12 to 13(or 14) using 5.1.0/5.2.0/5.3.0

### ISSUE THREAD

**Issue by EugenMayer** [CrunchyData/postgres-operator#3516]
I'am using the docs at https://www.crunchydata.com/blog/easy-major-postgresql-upgrades-using-pgo-v51 and https://access.crunchydata.com/documentation/postgres-operator/5.3.0/guides/major-postgres-version-upgrade/ to do a major update.

Currentlt running pgo 5.3.0 based on the kustomize/install example using the `default` deployment (did so from the start from 5.0.1). 
I'am currently running on an older crunchydata 12 image (since the old one have been unpulished) - i just pulled / pushed those without changes (into our own registry).

```
apiVersion: postgres-operator.crunchydata.com/v1beta1
kind: PostgresCluster
metadata:
  name: pg-cluster
spec:
  image: kwcr.io/infra/crunchydata/crunchy-postgres:centos8-12.9-0
  postgresVersion: 12
  instances:
    - name: pg-instance-v4
      replicas: 3
      dataVolumeClaimSpec:
        storageClassName: local-path
        accessModes:
          - 'ReadWriteOnce'
        resources:
          requests:
            storage: 15Gi
```

When upgrading using this job

```
kubectl create -f - <<EOF
apiVersion: postgres-operator.crunchydata.com/v1beta1
kind: PGUpgrade
metadata:
  name: pg-kw-upgrade
  namespace: postgres
spec:
  postgresClusterName: pg-cluster
  fromPostgresVersion: 12
  toPostgresVersion: 14
  image: registry.developers.crunchydata.com/crunchydata/crunchy-upgrade:ubi8-5.3.0-0
EOF
```

i end up with

```
Performing PostgreSQL upgrade from version "12" to "14" ...

Step 1: Making new pgdata directory...

Step 2: Initializing new pgdata directory...

The files belonging to this database system will be owned by user "postgres".
This user must also own the server process.

The database cluster will be initialized with locale "en_US.utf-8".
The default database encoding has accordingly been set to "UTF8".
The default text search configuration will be set to "english".

Data page checksums are enabled.

fixing permissions on existing directory /pgdata/pg13 ... ok
creating subdirectories ... ok
selecting dynamic shared memory implementation ... posix
selecting default max_connections ... 100
selecting default shared_buffers ... 128MB

.
.
.

check for "/usr/pgsql-12/bin" failed: No such file or directory
```

I tried to upgrade to `13` using `ubi8-5.1.0-0` too, same result.

**Comment by EugenMayer** [comment]
The answer here is, it is not intended to upgrade from pg12 since the pgupgrade images from 5.1.0 (that are available) do no include pg12.

I used 5.3.0 as a base an created a new image including pg12: ghcr.io/eugenmayer/crunchydata/crunchy-upgrade:ubi8-5.3.0-0-pg12

What i did is

```
docker run -u root --entrypoint /bin/bash -it registry.developers.crunchydata.com/crunchydata/crunchy-upgrade:ubi8-5.3.0-0
```

Then i copied the /usr/pgsql-12 folder from the old pg12 image `ghcr.io/eugenmayer/crunchy-postgres:centos8-12.9-0` into the running container

then i saved the actual running container as a new image

```
docker commit --change="USER 26" 8dc71cc09d32 ghcr.io/eugenmayer/crunchydata/crunchy-upgrade:ubi8-5.3.0-0-pg12-2
```

And pushed it. 

You can use it like this

```
kubectl create -f - <<EOF
apiVersion: postgres-operator.crunchydata.com/v1beta1
kind: PGUpgrade
metadata:
  name: pg-kw1-upgrade
  namespace: postgres
spec:
  postgresClusterName: pg-cluster
  fromPostgresVersion: 12
  toPostgresVersion: 14
  image: ghcr.io/eugenmayer/crunchydata/crunchy-upgrade:ubi8-5.3.0-0-pg12-0
EOF
```

Of course, just replace your name / namespace and so forth, the magic is using ` image: ghcr.io/eugenmayer/crunchydata/crunchy-upgrade:ubi8-5.3.0-0-pg12-0`
