### ISSUE TITLE
PGO V5 Postgres Pgbouncer issue

### ISSUE THREAD

**Issue by shusaan** [CrunchyData/postgres-operator#3517]
Hi,
Here is Postgres cluster config, I have disabled **TLS** on this cluster

```
apiVersion: postgres-operator.crunchydata.com/v1beta1
kind: PostgresCluster
metadata:
  name: db
  namespace: dev-test
spec:
  backups:
    pgbackrest:
      image: registry.developers.crunchydata.com/crunchydata/crunchy-pgbackrest:ubi8-2.41-2
      repos:
      - name: repo1
        volume:
          volumeClaimSpec:
            accessModes:
            - ReadWriteOnce
            resources:
              requests:
                storage: 5Gi
            storageClassName: nfs-storage
  image: registry.developers.crunchydata.com/crunchydata/crunchy-postgres:ubi8-13.9-2
  instances:
  - affinity:
      podAntiAffinity:
        preferredDuringSchedulingIgnoredDuringExecution:
        - podAffinityTerm:
            labelSelector:
              matchLabels:
                postgres-operator.crunchydata.com/cluster: db
                postgres-operator.crunchydata.com/instance-set: db
            topologyKey: kubernetes.io/hostname
          weight: 1
    dataVolumeClaimSpec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 5Gi
    name: db
    replicas: 1
  patroni:
    dynamicConfiguration:
      postgresql:
        parameters:
          max_connections: 500
          shared_buffers: 500MB
          synchronous_commit: "on"
        pg_hba:
        - hostnossl all all all md5
    leaderLeaseDurationSeconds: 30
    port: 8008
    syncPeriodSeconds: 10
  port: 5432
  postgresVersion: 13
  proxy:
    pgBouncer:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - podAffinityTerm:
              labelSelector:
                matchLabels:
                  postgres-operator.crunchydata.com/cluster: db
                  postgres-operator.crunchydata.com/role: pgbouncer
              topologyKey: kubernetes.io/hostname
            weight: 1
      config:
        databases:
          '*': host=db-primary port=5432
        global:
          client_tls_sslmode: disable
          default_pool_size: "100"
          max_client_conn: "500"
          pool_mode: transaction
          query_wait_timeout: "240"
          server_tls_sslmode: disable
      image: registry.developers.crunchydata.com/crunchydata/crunchy-pgbouncer:ubi8-1.17-5
      port: 5432
      replicas: 1
  users:
  - name: postgres
    options: SUPERUSER
```

When I Connect through `db-primary` service it is working 
![image](https://user-images.githubusercontent.com/28586582/210286569-a113104e-9092-44ab-9f79-cfe75079f968.png)

But when I use the **pgbouncer** service  `db-pgbouncer`
Here is the error I am facing,
![image](https://user-images.githubusercontent.com/28586582/210286537-2e80c771-4749-4ec0-833f-4475058fe309.png)
 Please Help
### Environment

Please provide the following details:

- Platform: (`Kubernetes`, RKE2.)
- Postgres Version (e.g. `13`)
