### ISSUE TITLE
Unable to install Crunchy Postgres for Kubernetes on OpenShift 4.8.z

### ISSUE THREAD

**Issue by mjurc** [CrunchyData/postgres-operator#3523]
Please ensure you do the following when reporting a bug:

- [x] Provide a concise description of what the bug is.
- [x] Provide information about your environment.
- [x] Provide clear steps to reproduce the bug.
- [x] Attach applicable logs. Please do not attach screenshots showing logs unless you are unable to copy and paste the log data.
- [x] Ensure any code / output examples are [properly formatted](https://docs.github.com/en/github/writing-on-github/basic-writing-and-formatting-syntax#quoting-code) for legibility.

Note that some logs needed to troubleshoot may be found in the `/pgdata/<CLUSTERNAME>/pg_log` directory on your Postgres instance.

An incomplete bug report can lead to delays in resolving the issue or the closing of a ticket, so please be as detailed as possible.

If you are looking for [general support](https://access.crunchydata.com/documentation/postgres-operator/latest/support/), please view the [support](https://access.crunchydata.com/documentation/postgres-operator/latest/support/) page for where you can ask questions.

Thanks for reporting the issue, we're looking forward to helping you!

## Overview

Currently, I am unable to install Crunchy Postgres for Kubernetes from OperatorHub on OpenShift 4.8.z.

## Environment

Please provide the following details:

- Platform: OpenShift
- Platform Version: 4.8.55
- PGO Image Tag: N/A
- Postgres Version: N/A
- Storage: N/A

### REPRO

Provide steps to get to the error condition:

1. Add a subscription to PGO from OperatorHub in OCP 4.8, e.g.

```
cat <<-EOF | ./oc apply -f -
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: crunchy-postgres-operator
  namespace: openshift-operators
spec:
  source: certified-operators
  sourceNamespace: openshift-marketplace
  name: crunchy-postgres-operator
  installPlanApproval: Automatic
  channel: v5
EOF
```

### EXPECTED

1. The operator installs

### ACTUAL

1. Operator installation fails with the following failure on `pgo` deployment:

```
Failed to pull image "registry.connect.redhat.com/crunchydata/postgres-operator@sha256:4ad944f4f01a85249aa7678521e61fe48ed150ac43f3c38f33b42f7a32eb9961": rpc error: code = Unknown desc = Error reading manifest sha256:4ad944f4f01a85249aa7678521e61fe48ed150ac43f3c38f33b42f7a32eb9961 in registry.connect.redhat.com/crunchydata/postgres-operator: manifest unknown: manifest unknown
```
