### ISSUE TITLE
Issues connecting through PgBouncer

### ISSUE THREAD

**Issue by ricrug** [CrunchyData/postgres-operator#3525]
- Platform: OpenShift/OKD
- Platform Version: 4.11.0-0.okd-2022-12-02-145640
- PGO Image Tag: ubi8-5.3.0-0
- Postgres Version ubi8-14.6-0
- Storage: GP3

Can't connect through pgbouncer, but it works if I connect using *-primary URI.

```
~ $ export PGHOST="willywonka-pgbouncer.willywonka.svc"
~ $ psql "sslmode=require"
psql: error: connection to server at "willywonka-pgbouncer.willywonka.svc" (172.30.107.108), port 5432 failed: FATAL:  no such user

~ $ export PGHOST="willywonka-primary.willywonka.svc"
~ $ psql "sslmode=require"
psql (14.5, server 14.6)
SSL connection (protocol: TLSv1.3, cipher: TLS_AES_256_GCM_SHA384, bits: 256, compression: off)
Type "help" for help.

willywonka=#
```
### PgBouncer Log:
```
2023-01-09 15:21:40.601 UTC [7] LOG process up: PgBouncer 1.17.0, libevent 2.1.8-stable (epoll), adns: evdns2, tls: OpenSSL 1.1.1k FIPS 25 Mar 2021
2023-01-09 15:22:40.601 UTC [7] LOG stats: 0 xacts/s, 0 queries/s, in 0 B/s, out 0 B/s, xact 0 us, query 0 us, wait 0 us
2023-01-09 15:22:48.330 UTC [7] LOG C-0x55767c70a2e0: (nodb)/(nouser)@10.129.2.104:60330 registered new auto-database: db=willywonka
2023-01-09 15:22:48.344 UTC [7] LOG S-0x55767c71ac20: willywonka/_crunchypgbouncer@172.30.230.151:5432 new connection to server (from 10.129.3.252:50514)
2023-01-09 15:22:48.347 UTC [7] LOG S-0x55767c71ac20: willywonka/_crunchypgbouncer@172.30.230.151:5432 SSL established: TLSv1.3/TLS_AES_256_GCM_SHA384/ECDH=prime256v1
2023-01-09 15:22:48.356 UTC [7] LOG C-0x55767c70a2e0: willywonka/(nouser)@10.129.2.104:60330 login failed: db=willywonka
2023-01-09 15:22:48.356 UTC [7] LOG C-0x55767c70a2e0: willywonka/(nouser)@10.129.2.104:60330 closing because: no such user (age=0s)
2023-01-09 15:22:48.356 UTC [7] LOG S-0x55767c71ac20: willywonka/_crunchypgbouncer@172.30.230.151:5432 closing because: client disconnect before everything was sent to the server (age=0s)
2023-01-09 15:22:48.356 UTC [7] WARNING C-0x55767c70a2e0: willywonka/(nouser)@10.129.2.104:60330 pooler error: no such user
```

### Generated config file for PgBouncer:
```
[pgbouncer]
%include /etc/pgbouncer/pgbouncer.ini

[pgbouncer]
auth_file = /etc/pgbouncer/~postgres-operator/users.txt
auth_query = SELECT username, password from pgbouncer.get_auth($1)
auth_user = _crunchypgbouncer
client_tls_ca_file = /etc/pgbouncer/~postgres-operator/frontend-ca.crt
client_tls_cert_file = /etc/pgbouncer/~postgres-operator/frontend-tls.crt
client_tls_key_file = /etc/pgbouncer/~postgres-operator/frontend-tls.key
client_tls_sslmode = require
conffile = /etc/pgbouncer/~postgres-operator.ini
default_pool_size = 600
ignore_startup_parameters = extra_float_digits
listen_addr = *
listen_port = 5432
max_client_conn = 1000
max_db_connections = 600
min_pool_size = 500
pool_mode = transaction
reserve_pool_size = 600
server_tls_ca_file = /etc/pgbouncer/~postgres-operator/backend-ca.crt
server_tls_sslmode = verify-full
unix_socket_dir =

[databases]
* = host=willywonka-primary port=5432
```

**Comment by David-Angel** [comment]
Just in case this is similar to an issue we saw...

@ricrug in your PostgresCluster verify the user is not a sysadmin.
And or include the user definition from your cluster.

pgbouncer does not work with users defined as sysadmin.

**Comment by tunatoksoz** [comment]
It should also not be able to initiate a replication. Not being superuser is not enough.

**Comment by cristianrat** [comment]
I have this issue in one namespace, but not in the other
I looked at the resources and they're pretty much identical
:\

**Comment by nevros** [comment]
Think I experienced the same issue as @cristianrat 

At deployment a user was defined with 3 databases and no superuser access. Using the pgbouncer dns address the user could connect to only the first database that was listed.

Can only connect to the other databases using the pgbouncer user (defined in the secret hippo-pgbouncer). Of cause direct connection to primary works but it keeps getting disconnected for some reason.

Creating additional users post deployment did not work with pgbouncer. Seems to only like only having access to one database.

What I wanted to do is have 3 different users that each owned a database that could connect via pgboucer. Now I have one, and the other two are owned by pgboucer user.

**Comment by benjaminjb** [comment]
Hello @nevros @cristianrat and @ricrug, I'm looking at pgbouncer (and some of our documentation around that) right now. 

If you are still experiencing this issue, could you share your postgrescluster spec. (I would also like to hear your PGO version and platforms, but the spec will really help diagnose the problem.) (@cristianrat, in your case, I'd like to see the specs for both the non-working and the working cluster.)

Hope we can figure this out, cheers!

**Comment by cristianrat** [comment]
@benjaminjb Honestly can't remember even what version I was at that specific time.
However, funny enough, it started misbehaving again, and for the last couple of weeks, at least once a day it drops connections complaining about ssl missing, for about 2-3 minutes and then it's fine (django throws the error, and pgbouncer can't connect to db)
almost daily for the last 2 weeks, after working fine for months. It drove me nuts and I just spun up an AWS RDS - but happy to help if it keeps happening in dev (which it seems to, but not today for some reason)

**Comment by cassanellicarlo** [comment]
I have the same issue. 

OpenSgh

```
 login attempt: db=..... user=..... tls=TLSv1.3/TLS_AES_256_GCM_SHA384

4742023-07-20 13:10:51.185 UTC [7] LOG C-0x561fc3d0c400: @ closing because: password authentication failed (age=0s)

4752023-07-20 13:10:51.185 UTC [7] WARNING C-0x561fc3d0c400: @:40360 pooler error: password authentication failed

```

```
proxy:

    pgBouncer:

      config:

        databases:

          <name>: >-

            host=<primary postgres instance>.svc.cluster.local

            dbname=<dbname> reserve_pool=20

          <name>: >-

            host=<primary postgres instance>.svc.cluster.local

            dbname=<dbname> reserve_pool=20

        global:

          default_pool_size: '80'

          ignore_startup_parameters: 'search_path, extra_float_digits'

          max_client_conn: '5000'

        users:

          <user1>: pool_mode=session

          <user2>: pool_mode=session
```

**Comment by nevros** [comment]
Platform: Kubernetes running on Linode
Storage: Linone block storage with encryption 


`
spec:
  image: registry.developers.crunchydata.com/crunchydata/crunchy-postgres:ubi8-14.7-0
  postgresVersion: 14

  users:
    - name: hellodjango
      databases:
        - Redacted
      options: "SUPERUSER"

  proxy:
    pgBouncer:
      image: registry.developers.crunchydata.com/crunchydata/crunchy-pgbouncer:ubi8-1.18-0
      replicas: 2
      minAvailable: 1
      priorityClassName: critical-priority-preempting
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 1
            podAffinityTerm:
              topologyKey: kubernetes.io/hostname
              labelSelector:
                matchLabels:
                  postgres-operator.crunchydata.com/cluster: hippous
                  postgres-operator.crunchydata.com/role: pgbouncer
  patroni:
    switchover:
      enabled: false
    dynamicConfiguration:
      synchronous_mode: true
      postgresql:
        parameters:
          synchronous_commit: "on"


  instances:
    - name: instanceus
      replicas: 3
      minAvailable: 2
      priorityClassName: critical-priority-preempting
      resources:
      dataVolumeClaimSpec:
        storageClassName: linode-retain-gp2-enc
        accessModes:
        - "ReadWriteOnce"
        resources:
          requests:
            storage: 20Gi
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - topologyKey: kubernetes.io/hostname
            labelSelector:
              matchLabels:
                postgres-operator.crunchydata.com/cluster: hippous
                postgres-operator.crunchydata.com/instance-set: instanceus
 `

**Comment by Nanako0129** [comment]
Same here

Platform: RKE1, Kubernetes Version: v1.22.17
PGO version: 5.4.3

```yaml
apiVersion: postgres-operator.crunchydata.com/v1beta1
kind: PostgresCluster
metadata:
  name: hippo
spec:
  image: registry.developers.crunchydata.com/crunchydata/crunchy-postgres:ubi8-15.4-1
  postgresVersion: 15
  users:
    - name: postgres
    - name: gitlab
      databases:
        - gitlabhq_production
      options: "SUPERUSER"
    - name: praefect
      databases:
        - praefect
      options: "SUPERUSER"
  service:
    metadata:
      annotations:
        my-annotation: value1
      labels:
        my-label: value2
    type: NodePort
    nodePort: 32000
  instances:
    - name: instance1
      replicas: 3
      resources:
        requests:
          cpu: 2.0
          memory: 2Gi
        limits:
          cpu: 8.0
          memory: 5Gi
      dataVolumeClaimSpec:
        accessModes:
        - "ReadWriteOnce"
        resources:
          requests:
            storage: 100Gi
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 1
            podAffinityTerm:
              topologyKey: kubernetes.io/hostname
              labelSelector:
                matchLabels:
                  postgres-operator.crunchydata.com/cluster: hippo
                  postgres-operator.crunchydata.com/instance-set: instance1
  patroni:
    dynamicConfiguration:
      synchronous_mode: true
      postgresql:
        parameters:
          synchronous_commit: "on"
          shared_buffers: 1GB
          max_connections: 500
          effective_cache_size: 3GB
          maintenance_work_mem: 256MB
          checkpoint_completion_target: 0.9
          wal_buffers: 16MB
          default_statistics_target: 100
          random_page_cost: 4
          effective_io_concurrency: 2
          work_mem: 524kB
          huge_pages: off
          min_wal_size: 1GB
          max_wal_size: 4GB
          max_worker_processes: 8
          max_parallel_workers_per_gather: 4
          max_parallel_workers: 8
          max_parallel_maintenance_workers: 4
        pg_hba:
          - "host all all 0.0.0.0/0 trust" # this line enabled logical replication with programmatic access
          - "host all postgres 127.0.0.1/32 md5"
  backups:
    pgbackrest:
      image: registry.developers.crunchydata.com/crunchydata/crunchy-pgbackrest:ubi8-2.47-1
      repos:
      - name: repo1
        volume:
          volumeClaimSpec:
            accessModes:
            - "ReadWriteOnce"
            resources:
              requests:
                storage: 100Gi
  proxy:
    pgBouncer:
      image: registry.developers.crunchydata.com/crunchydata/crunchy-pgbouncer:ubi8-1.19-5
      replicas: 2
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 1
            podAffinityTerm:
              topologyKey: kubernetes.io/hostname
              labelSelector:
                matchLabels:
                  postgres-operator.crunchydata.com/cluster: hippo
                  postgres-operator.crunchydata.com/role: pgbouncer
  monitoring:
    pgmonitor:
      exporter:
        image: registry.developers.crunchydata.com/crunchydata/crunchy-postgres-exporter:ubi8-5.4.3-0
```
cmd
```shell
root@psql:/# psql -h hippo-pgbouncer.postgres-operator.svc -p 5432 -d gitlabhq_production -U gitlab -W
Password:
psql: error: connection to server at "hippo-pgbouncer.postgres-operator.svc" (10.xx.xx.xx), port 5432 failed: FATAL:  no such user
connection to server at "hippo-pgbouncer.postgres-operator.svc" (10.xx.xx.xx), port 5432 failed: FATAL:  SSL required
```
log
```log
2023-11-08 08:08:54.163 UTC [7] LOG S-0x55d0a0df60c0: gitlabhq_production/_crunchypgbouncer@10.43.6.202:5432 new connection to server (from 10.42.2.34:42074)
2023-11-08 08:08:54.165 UTC [7] LOG S-0x55d0a0df60c0: gitlabhq_production/_crunchypgbouncer@10.43.6.202:5432 SSL established: TLSv1.3/TLS_AES_256_GCM_SHA384/ECDH=prime256v1
2023-11-08 08:08:54.172 UTC [7] LOG C-0x55d0a0de4da0: gitlabhq_production/(nouser)@10.42.2.49:38130 login failed: db=gitlabhq_production
2023-11-08 08:08:54.172 UTC [7] LOG C-0x55d0a0de4da0: gitlabhq_production/(nouser)@10.42.2.49:38130 closing because: no such user (age=0s)
2023-11-08 08:08:54.172 UTC [7] LOG S-0x55d0a0df60c0: gitlabhq_production/_crunchypgbouncer@10.43.6.202:5432 closing because: client disconnect before everything was sent to the server (age=0s)
2023-11-08 08:08:54.172 UTC [7] WARNING C-0x55d0a0de4da0: gitlabhq_production/(nouser)@10.42.2.49:38130 pooler error: no such user
```
