### ISSUE TITLE
Cannot spawn new cluster w/ backups: expected value '2.38' for greeting key 'version' but got '2.41'...

### ISSUE THREAD

**Issue by haf** [CrunchyData/postgres-operator#3549]
## Overview

With the latest release v5.3, you can't create backups locally (testing with kind)

```
db                   0s          Warning   UnableToCreateStanzas          postgrescluster/hippo                                        command terminated with exit code 39: ERROR: [039]: expected value '2.38' for greeting key 'version' but got '2.41'...
```

## Environment

Please provide the following details:

- Platform: kind / arm64/M1
- Platform Version: kind v0.17.0 go1.19.3 darwin/arm64
- PGO Image Tag: `registry.developers.crunchydata.com/crunchydata/crunchy-pgbackrest:ubi8-2.41-2`
- Postgres Version (e.g. `14`): 13
- Storage: (e.g. `hostpath`, `nfs`, or the name of your storage class)

<img width="878" alt="image" src="https://user-images.githubusercontent.com/193115/214849872-752bf831-a89c-416c-928b-31163cbc7aa6.png">

### REPRO

Provide steps to get to the error condition:

1. Deploy the examples and configure pgbackrest

### EXPECTED

I expected the [examples](https://github.com/CrunchyData/postgres-operator-examples/blob/5371692f26f97eb26eae4b54e4ef8848a76a278d/kustomize/install/manager/manager.yaml) to be deployable. I've verified I'm using the latest versions of everything, including pgbackrest's image inside the `postgres` crd instance declaration for my database.

### ACTUAL

`db                   0s          Warning   UnableToCreateStanzas          postgrescluster/hippo                                        command terminated with exit code 39: ERROR: [039]: expected value '2.38' for greeting key 'version' but got '2.41'...`

**Comment by haf** [comment]
Can I provide any other details to make this easily reproducible?

**Comment by haf** [comment]
Can I get a set of versions from you that work, please? Previous versions are fine.

**Comment by haf** [comment]
Ping it's been two week. Anyone there?

**Comment by andrewlecuyer** [comment]
The pgBackRest and PostgreSQL containers you are using (i.e. the  PG 13 and pgBackRest related images currently defined for the operator Deployment in the [examples](https://github.com/CrunchyData/postgres-operator-examples) repo) contain the correct/valid version of pgBackRest (`v2.41`):

```bash
$ podman run registry.developers.crunchydata.com/crunchydata/crunchy-postgres:ubi8-13.9-2 pgbackrest version
...
pgBackRest 2.41
$ podman run registry.developers.crunchydata.com/crunchydata/crunchy-pgbackrest:ubi8-2.41-2 pgbackrest version
...
pgBackRest 2.41
```

Additionally, I just tried out current `kustomize` installation in the [examples](https://github.com/CrunchyData/postgres-operator-examples) repo and did not run into any issues.  In other words, the stanza created successfully, and PGO was then able to create a backup.

Here is the `PostgresCluster` spec utilized for this test:

```yaml
apiVersion: postgres-operator.crunchydata.com/v1beta1
kind: PostgresCluster
metadata:
  name: hippo
spec:
  postgresVersion: 13
  instances:
    - name: instance1
      dataVolumeClaimSpec:
        accessModes:
        - "ReadWriteOnce"
        resources:
          requests:
            storage: 1Gi
  backups:
    pgbackrest:
      repos:
      - name: repo1
        volume:
          volumeClaimSpec:
            accessModes:
            - "ReadWriteOnce"
            resources:
              requests:
                storage: 1Gi
```

It therefore appears as though there is a mis-configuration on your end.  Can you provide your `PostgresCluster` spec?
