### ISSUE TITLE
Backup to azure blob fails.

### ISSUE THREAD

**Issue by FateGrandOrder** [CrunchyData/postgres-operator#3554]
My configuration is as follows

```
apiVersion: postgres-operator.crunchydata.com/v1beta1
kind: PostgresCluster
metadata:
  name: hippo-azure
spec:
  image: registry.developers.crunchydata.com/crunchydata/crunchy-postgres:ubi8-14.6-2
  postgresVersion: 14
  instances:
    - dataVolumeClaimSpec:
        accessModes:
        - "ReadWriteOnce"
        resources:
          requests:
            storage: 32Gi
  backups:
    pgbackrest:
      image: registry.developers.crunchydata.com/crunchydata/crunchy-pgbackrest:ubi8-2.41-2
      configuration:
      - secret:
          name: pgo-azure-creds
      global:
        repo2-path: /pgbackrest/repo2
      repos:
      - name: repo1
        volume:
          volumeClaimSpec:
            accessModes:
              - "ReadWriteOnce"
            resources:
              requests:
                storage: 32Gi
      - name: repo2
        azure:
          container: "pgo"
  patroni:
    dynamicConfiguration:
      postgresql:
        pg_hba:
          - "host all all 0.0.0.0/0 trust" 
          - "host all postgres 127.0.0.1/32 md5"
  users:
    - name: qixin
      databases:
        - iot
        - lowcode
      options: "SUPERUSER"
  service:
    type: LoadBalancer
```

My storage account name is pgobackup, container name is pgo.
The content of azure.conf is as follows.

```
[global]
repo2-azure-account=pgobackup
repo2-azure-key=aXdafScEP28el......JpkYa28nh5V+AStNtZ5Lg== 
```
But there are no files on the blob
Also I executed the following command for a one time backup

```
kubectl annotate -n postgres-operator postgrescluster hippo-azure  postgres-operator.crunchydata.com/pgbackrest-backup="$( date '+%F_%H:%M:%S' )" --overwrite=true
```

I also tried scheduled backups, but that also failed

```
      - name: repo2
        schedules:
          full: "18 * * * *"
          differential: "0 1 * * 1-6"
        azure:
          container: "pgo"
```
[Taken from the official documentation.](https://i.stack.imgur.com/BXPU7.png)
The official document says that cronjob will be created, but no Job or Cronjob is created.
Can anyone give me some advice?
Thx！
