### ISSUE TITLE
Issue with failed jobs in PGBackRest config

### ISSUE THREAD

**Issue by markamber** [CrunchyData/postgres-operator#3562]
### Issue I am having

I am continuing to get a failed job on just 1 of my postgres clusters related to backups. My intention is that backups should be going to S3 storage, which seems to be working, however the backups also seem to be still trying to go to local disk storage. There are different names for the backups as I understand (repo1, repo2) 

Here are the logs of the failed jobs (about 1 per hour, sometimes). I have to clean these jobs up manually it would seem. Note that I have not attempted to restore the database from the cloud backup but it does look like it is working.

```
time="2023-02-05T01:00:09Z" level=info msg="debug flag set to false"
time="2023-02-05T01:00:09Z" level=info msg="backrest backup command requested"
time="2023-02-05T01:00:09Z" level=info msg="command to execute is [pgbackrest backup --stanza=db --repo=1 --type=full]"
time="2023-02-05T01:00:09Z" level=info msg="output=[]"
time="2023-02-05T01:00:09Z" level=info msg="stderr=[WARN: option 'repo2-retention-full' is not set for 'repo2-retention-full-type=count', the repository may run out of space\n HINT: to retain full backups indefinitely (without warning), set option 'repo2-retention-full' to the maximum.\nWARN: option 'repo3-retention-full' is not set for 'repo3-retention-full-type=count', the repository may run out of space\n HINT: to retain full backups indefinitely (without warning), set option 'repo3-retention-full' to the maximum.\nERROR: [072]: backup command must be run on the repository host\n]"
time="2023-02-05T01:00:09Z" level=fatal msg="command terminated with exit code 72"
```

Here is the relevant section of my `PostgresCluster` yaml

```yaml
spec:
  port: 5432
  users:
    - name: postgres
    - databases:
        - ******
      name: ******
    - databases:
        - ******
      name: ***** # all these redacted strings are internal names, only lowercase letters
  userInterface:
    pgAdmin:
      dataVolumeClaimSpec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 10Gi
      image: >-
        registry.developers.crunchydata.com/crunchydata/crunchy-pgadmin4:ubi8-4.30-2
      replicas: 1
  proxy:
    pgBouncer:
      port: 5432
      replicas: 3
  backups:
    pgbackrest:
      configuration:
        - secret:
            name: pg-bak-creds
      global:
        repo1-path: /*********/*******/repo1 # a string with letters, hyphens
        repo1-retention-full: '90'
        repo1-retention-full-type: time
      repos:
        - name: repo1
          s3:
            bucket: *************
            endpoint: s3.us-east-1.amazonaws.com
            region: us-east-1
          schedules:
            differential: 0 1 * * 1-6
            full: 0 1 * * 0
          volume:
            volumeClaimSpec:
              accessModes:
                - ReadWriteOnce
              resources:
                requests:
                  storage: 50Gi
        - name: repo2
          volume:
            volumeClaimSpec:
              accessModes:
                - ReadWriteOnce
              resources:
                requests:
                  storage: 50Gi
  openshift: true
  patroni:
    leaderLeaseDurationSeconds: 30
    port: 8008
    switchover:
      enabled: true
      type: Switchover
    syncPeriodSeconds: 10
  instances:
    - dataVolumeClaimSpec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 50Gi
      name: pm-saas
      replicas: 4
  postgresVersion: 14
status:
  observedGeneration: 15
  usersRevision: 55b8c4c658
  monitoring:
    exporterConfiguration: 559c4c97d6
  userInterface:
    pgAdmin:
      usersRevision: 7d9ff4ff59
  proxy:
    pgBouncer:
      postgresRevision: 8bdc5fd6d
      readyReplicas: 3
      replicas: 3
  pgbackrest:
    repoHost:
      apiVersion: apps/v1
      kind: StatefulSet
      ready: true
    repos:
      - bound: true
        name: repo1
        stanzaCreated: false
        volume: pvc-7e03a913-95a2-4bab-8b9f-81c3bf6ca66e
      - bound: true
        name: repo2
        stanzaCreated: true
        volume: pvc-c88d7bcc-8482-48fb-929a-6519fae53c4e
    scheduledBackups:
      - cronJobName: pm-stack-pg-repo1-diff
        failed: 7
        repo: repo1
        startTime: '2023-02-06T01:00:00Z'
        type: diff
      - cronJobName: pm-stack-pg-repo1-full
        failed: 7
        repo: repo1
        startTime: '2023-02-05T01:00:00Z'
        type: full
  databaseRevision: c74f78c98
  conditions:
    - lastTransitionTime: '2023-01-17T17:12:37Z'
      message: pgBackRest replica create repo is not ready for backups
      observedGeneration: 15
      reason: StanzaNotCreated
      status: 'False'
      type: PGBackRestReplicaRepoReady
    - lastTransitionTime: '2023-01-17T17:12:37Z'
      message: pgBackRest replica creation is not currently possible
      observedGeneration: 15
      reason: RepoBackupNotComplete
      status: 'False'
      type: PGBackRestReplicaCreate
    - lastTransitionTime: '2022-12-16T19:30:21Z'
      message: Deployment has minimum availability.
      observedGeneration: 15
      reason: MinimumReplicasAvailable
      status: 'True'
      type: ProxyAvailable
    - lastTransitionTime: '2023-01-17T17:12:54Z'
      message: pgBackRest dedicated repository host is ready
      observedGeneration: 15
      reason: RepoHostReady
      status: 'True'
      type: PGBackRestRepoHostReady
  patroni:
    systemIdentifier: '7165670078157004890'
  instances:
    - name: pm-saas
      readyReplicas: 4
      replicas: 4
      updatedReplicas: 4
```

You can see that I am attempting a local and remote backup, remote is repo1, local is repo2. I have another cluster that is seemingly set up identically. And no errors there, but it also does not seem like it has created any data on the local volume.

Here is the config for the NON-Problem cluster

```yaml
spec:
  port: 5432
  users:
    - name: postgres
    - databases:
        - **********
      name: *********
    - databases:
        - ********
      name: ******* # lowercase and numbers redacted
  userInterface:
    pgAdmin:
      dataVolumeClaimSpec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 50Gi
      image: >-
        registry.developers.crunchydata.com/crunchydata/crunchy-pgadmin4:ubi8-4.30-2
      replicas: 1
  proxy:
    pgBouncer:
      port: 5432
      replicas: 3
  backups:
    pgbackrest:
      configuration:
        - secret:
            name: pg-bak-creds
      global:
        repo1-path: /*********/*********/repo1 # lowercase and hyphens redacted
        repo1-retention-full: '90'
        repo1-retention-full-type: time
      repos:
        - name: repo1
          s3:
            bucket: ***************
            endpoint: s3.us-east-1.amazonaws.com
            region: us-east-1
          schedules:
            differential: 0 1 * * 1-6
            full: 0 1 * * 0
        - name: repo2
          volume:
            volumeClaimSpec:
              accessModes:
                - ReadWriteOnce
              resources:
                requests:
                  storage: 15Gi
  openshift: true
  patroni:
    leaderLeaseDurationSeconds: 30
    port: 8008
    switchover:
      enabled: true
      type: Switchover
    syncPeriodSeconds: 10
  instances:
    - dataVolumeClaimSpec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 75Gi
      name: pm-saas
      replicas: 4
  postgresVersion: 14
status:
  observedGeneration: 4
  usersRevision: 6c9f65bc98
  monitoring:
    exporterConfiguration: 559c4c97d6
  userInterface:
    pgAdmin:
      usersRevision: 65d985dbb6
  proxy:
    pgBouncer:
      postgresRevision: 5c4bddcdfd
      readyReplicas: 3
      replicas: 3
  pgbackrest:
    repoHost:
      apiVersion: apps/v1
      kind: StatefulSet
      ready: true
    repos:
      - name: repo1
        replicaCreateBackupComplete: true
        repoOptionsHash: 567c6b4465
        stanzaCreated: true
    restore:
      completionTime: '2022-10-24T12:55:49Z'
      finished: true
      id: ~pgo-bootstrap-pm-saas-postgres
      startTime: '2022-10-24T12:54:16Z'
      succeeded: 1
    scheduledBackups:
      - completionTime: '2023-02-03T01:00:19Z'
        cronJobName: pm-saas-postgres-repo1-diff
        repo: repo1
        startTime: '2023-02-03T01:00:00Z'
        succeeded: 1
        type: diff
      - completionTime: '2023-02-04T01:00:20Z'
        cronJobName: pm-saas-postgres-repo1-diff
        repo: repo1
        startTime: '2023-02-04T01:00:00Z'
        succeeded: 1
        type: diff
      - completionTime: '2023-02-06T01:00:18Z'
        cronJobName: pm-saas-postgres-repo1-diff
        repo: repo1
        startTime: '2023-02-06T01:00:00Z'
        succeeded: 1
        type: diff
      - completionTime: '2023-01-22T01:01:46Z'
        cronJobName: pm-saas-postgres-repo1-full
        repo: repo1
        startTime: '2023-01-22T01:00:00Z'
        succeeded: 1
        type: full
      - completionTime: '2023-01-29T01:01:46Z'
        cronJobName: pm-saas-postgres-repo1-full
        repo: repo1
        startTime: '2023-01-29T01:00:00Z'
        succeeded: 1
        type: full
      - completionTime: '2023-02-05T01:01:45Z'
        cronJobName: pm-saas-postgres-repo1-full
        repo: repo1
        startTime: '2023-02-05T01:00:00Z'
        succeeded: 1
        type: full
  databaseRevision: 5dfd477978
  conditions:
    - lastTransitionTime: '2022-10-24T12:55:50Z'
      message: pgBackRest restore completed successfully
      observedGeneration: 1
      reason: PGBackRestRestoreComplete
      status: 'True'
      type: PostgresDataInitialized
    - lastTransitionTime: '2023-01-03T18:12:34Z'
      message: pgBackRest dedicated repository host is ready
      observedGeneration: 4
      reason: RepoHostReady
      status: 'True'
      type: PGBackRestRepoHostReady
    - lastTransitionTime: '2022-12-11T17:30:40Z'
      message: pgBackRest replica create repo is ready for backups
      observedGeneration: 4
      reason: StanzaCreated
      status: 'True'
      type: PGBackRestReplicaRepoReady
    - lastTransitionTime: '2022-12-11T17:32:19Z'
      message: pgBackRest replica creation is now possible
      observedGeneration: 4
      reason: RepoBackupComplete
      status: 'True'
      type: PGBackRestReplicaCreate
    - lastTransitionTime: '2023-01-18T02:09:30Z'
      message: Deployment has minimum availability.
      observedGeneration: 4
      reason: MinimumReplicasAvailable
      status: 'True'
      type: ProxyAvailable
    - lastTransitionTime: '2023-02-06T16:19:42Z'
      message: One or more volumes cannot be resized
      observedGeneration: 4
      reason: Invalid
      status: 'False'
      type: PersistentVolumeResizing
  patroni:
    systemIdentifier: '7148893784935739473'
  instances:
    - name: pm-saas
      readyReplicas: 4
      replicas: 4
      updatedReplicas: 4
```

Indeed, for the problem cluster, I can see that two PVC are bound, one ending in repo1, one ending in repo2. And both have a bit of data in them (when only repo2 is actually supposed to be a local backup). But on the second cluster which works fine only the repo2 shows up as a PVC. In any case any of these PVC that are bound are only using less than 1% of their size, so the message in the logs about being out of space does not make sense from the context of storage space. The storage itself is plentiful that vmware is using.

### Environment

Please provide the following details:

- Platform: Openshift (OKD)
- Platform Version: `4.11.0-0.okd-2023-01-14-152430`
- PGO Image Tag: `ubi8-5.3.0-0`
- Postgres Version `14`
- Storage: `vmware`

### Troubleshooting steps

I have tried to delete the configuration for the backups and move around the repo numbers, and it seems like they either get recreated or I am just losing my brain here. I think because I first created my cluster with a simple 

```yaml
spec:
  backups:
    pgbackrest:
      configuration:
        - name: repo1
          volume:
            volumeClaimSpec:
              accessModes:
                - ReadWriteOnce
              resources:
                requests:
                  storage: 15Gi
```

It basically has never given up trying to do this backup.

I am pulling my hair out a little here want a little guidance before I retry troubleshooting since this is a production database and I am unable to recreate the issue despite my best recollection of steps on a non-production DB cluster. So my appologies that is why I don't exactly remember the troubleshooting steps because at a certain point I was not feeling confident enough to continue and began a fruitless effort of trying to recreate this.
