### ISSUE TITLE
Users don't get CREATE permissions with postgresVersion: 15 

### ISSUE THREAD

**Issue by dbackeus** [CrunchyData/postgres-operator#3568]
When creating a `PostgresCluster` using `postgresVersion: 14` it's possible to use either the default or explicitly created users + databases and have all the expected CRUD privileges enabled for that user.

However when using `postgresVersion: 15` we get `ERROR:  permission denied for schema public` when trying to eg. `CREATE TABLE ...` for the default user and database.

I'm guessing this is related to the following mentioned in the Postgres 15 [release notes](https://www.postgresql.org/about/news/postgresql-15-released-2526/):
> PostgreSQL 15 also [revokes the CREATE permission from all users](https://www.postgresql.org/docs/15/ddl-schemas.html#DDL-SCHEMAS-PATTERNS) except a database owner from the public (or default) schema.

But this begs the question how users / database management in PGO is supposed to work when using Postgres 15?

**Comment by andrewlecuyer** [comment]
@dbackeus thanks for reaching out! 

As you mentioned, the behavior you're seeing is simply a result of the change you referenced in PG 15.

Is there any specific behavior you're looking here?  For instance, is there something else you'd like and/or expect PGO to be doing here?

As you're seeing, our current approach is to simply align with the new PG 15 behavior here, but we're open to thoughts, suggestions, etc. as to how to best approach this.

**Comment by saosebastiao** [comment]
To clarify, this is an intended behavioral change introduced in PG15, nothing to do with the Postgres Operator. 

https://fluca1978.github.io/2022/07/15/PostgreSQL15PublicSchema.html

**Comment by dbackeus** [comment]
Right. After realizing that perhaps it isn't in the scope of PGO to give a convenient solution for this we figured out that we could solve this via `databaseInitSQL`.

Eg:
```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: init-sql
data:
  init.sql: |
    \c <database>
    GRANT CREATE ON SCHEMA public TO "<user>";
---
apiVersion: postgres-operator.crunchydata.com/v1beta1
kind: PostgresCluster
metadata:
  name: my-cluster
spec:
  postgresVersion: 15
  databaseInitSQL:
    key: init.sql
    name: init-sql
  # ...
```
