### ISSUE TITLE
PGO 5.3.0: pgAdmin is not deployed

### ISSUE THREAD

**Issue by mzwettler2** [CrunchyData/postgres-operator#3570]
## Overview

We upgraded to PGO 5.3.0. 

pgAdmin is not deployed anymore.

## Environment

Please provide the following details:

Platform: Anthos
Platform Version: 1.10 (afaik)
PGO Image Tag: postgres-operator:ubi8-5.3.0-0
Postgres Version: 13
Storage: vm ware csi
Number of Postgres clusters: several

### REPRO

Deployed the yaml below with PGO 5.3.0.

### EXPECTED

pgAdmin is deployed.

### ACTUAL

pgAdmin is not deployed.

## Additional Information

```
spec:
  backups:
    pgbackrest:
      global:
        repo1-retention-full: '2'
        repo1-retention-full-type: count
      image: >-
        europe-west6-docker.pkg.dev/szh-connect/cmp-docker/pgo/crunchy-pgbackrest:ubi8-2.41-2
      jobs:
        resources:
          limits:
            cpu: 100m
            memory: 256Mi
          requests:
            cpu: 100m
            memory: 256Mi
      manual:
        options:
          - '--archive-copy'
          - '--start-fast'
          - '--type=full'
        repoName: repo1
      repos:
        - name: repo1
          schedules:
            full: 0 23 * * *
          volume:
            volumeClaimSpec:
              accessModes:
                - ReadWriteOnce
              resources:
                requests:
                  storage: 2Gi
  databaseInitSQL:
    key: bootstrap.sql
    name: cmpg-cl-eng-005
  image: >-
    europe-west6-docker.pkg.dev/szh-connect/cmp-docker/pgo/crunchy-postgres:ubi8-13.9-2
  imagePullPolicy: Always
  instances:
    - dataVolumeClaimSpec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 2Gi
      name: instance1
      replicas: 1
      resources:
        limits:
          cpu: 1000m
          memory: 2Gi
        requests:
          cpu: 500m
          memory: 1Gi
  metadata:
    annotations:
      prometheus.io/path: /metrics
      prometheus.io/port: '9187'
      prometheus.io/scheme: http
      prometheus.io/scrape: 'true'
      prometheus.io/type: prometheus
      traffic.sidecar.istio.io/excludeOutboundPorts: '5432'
  monitoring:
    pgmonitor:
      exporter:
        image: ''
  patroni:
    dynamicConfiguration:
      postgresql:
        parameters:
          archive_timeout: 1800
          checkpoint_timeout: 900
          datestyle: 'iso, dmy'
          default_text_search_config: pg_catalog.german
          effective_cache_size: 256MB
          idle_session_timeout: 3600000
          lc_messages: en_US.UTF-8
          log_connections: 'on'
          log_destination: 'stderr, csvlog'
          log_directory: log
          log_disconnections: 'on'
          log_filename: postgresql-%d.log
          log_line_prefix: '%t : %h=>%u@%d : %p-%l=>%c : %e '
          log_rotation_age: 1d
          log_rotation_size: 0
          log_statement: ddl
          log_timezone: Europe/Zurich
          log_truncate_on_rotation: 'on'
          logging_collector: 'off'
          max_connections: 500
          max_wal_size: 5GB
          min_wal_size: 80MB
          shared_buffers: 256MB
          timezone: Europe/Zurich
          track_activity_query_size: 32768
          track_functions: all
          track_io_timing: 'on'
          wal_buffers: 16MB
          wal_compression: 'on'
          work_mem: 10MB
      synchronous_mode: true
    switchover:
      enabled: true
  postgresVersion: 13
  userInterface:
    pgAdmin:
      dataVolumeClaimSpec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
      resources:
        limits:
          cpu: 200m
          memory: 512Mi
        requests:
          cpu: 100m
          memory: 256Mi
  users:
    - name: monitor
      options: SUPERUSER
    - databases:
        - cmppgdb001
      name: cmppgdb001	  

```
