### ISSUE TITLE
Certificate verification error pgbackrest

### ISSUE THREAD

**Issue by Cl0udius** [CrunchyData/postgres-operator#3611]
## Overview

When we want to configure backup on our cluster we recieve certificate errors in the logs of the postgres operator.
Backup seems to not be configured on the repo host.

## Environment

Please provide the following details:

- Platform:  Kubernetes
- Platform Version: 1.23.15
- PGO Image Tag: postgres-operator:ubi8-5.3.1-0
- Postgres Version 14
- Storage: (e.g. `hostpath`, `nfs`, or the name of your storage class)

## Steps to Reproduce

Deploy the following config:

````
apiVersion: postgres-operator.crunchydata.com/v1beta1
kind: PostgresCluster
metadata:
  name: db1
spec:
  postgresVersion: 14
  instances:
    - name: pgha1
      replicas: 2
      dataVolumeClaimSpec:
        storageClassName: "postgres"
        accessModes:
        - "ReadWriteOnce"
        resources:
          requests:
            storage: 50Gi
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 1
            podAffinityTerm:
              topologyKey: kubernetes.io/hostname
              labelSelector:
                matchLabels:
                  postgres-operator.crunchydata.com/cluster: db1
                  postgres-operator.crunchydata.com/instance-set: pgha1
  backups: 
    pgbackrest:
      global:
        repo1-retention-full: "2"
        repo1-storage-verify-tls: 'n'
      repos:
      - name: repo1
        schedules:
          full: "* */24 * * *"
          differential: "* */12 * * *"
          incremental: "* */1 * * *"
        volume:
          volumeClaimSpec:
            accessModes:
            - "ReadWriteOnce"
            resources:
              requests:
                storage: 40Gi
  proxy:
    pgBouncer:
      replicas: 3
      config:
        global:
          server_tls_sslmode: verify-ca
          client_tls_sslmode: disable
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 1
            podAffinityTerm:
              topologyKey: kubernetes.io/hostname
              labelSelector:
                matchLabels:
                  postgres-operator.crunchydata.com/cluster: db1
                  postgres-operator.crunchydata.com/role: pgbouncer
````

### REPRO

Provide steps to get to the error condition:

1. Run `...`
1. Do `...`
1. Try `...`

### EXPECTED

Backups can be scheduled

### ACTUAL

Scheduling does not happen.

## Logs

````
time="2023-03-21T16:13:21Z" level=error msg="unable to create stanza" controller=postgrescluster controllerGroup=postgres-operator.crunchydata.com controllerKind=PostgresCluster error="command terminated with exit code 95: ERROR: [095]: unable to verify certificate presented by '<internal hostname of repo1 pod>.:8432': [19] self signed certificate in certificate chain\n" file="internal/controller/postgrescluster/pgbackrest.go:2584" func="postgrescluster.(*Reconciler).reconcileStanzaCreate" name=db1 namespace=awx postgresCluster=awx/db1 reconcileID=e2473252-da5f-465f-8bb7-be073666426d reconciler=pgBackRest version=5.3.1-0
````

## Additional Information

Please provide any additional information that may be helpful.

**Comment by Cl0udius** [comment]
I think i found the rootcause:

As we are using istio, a sidecar container with an istio proxy was injected to the repo pod. As all communication flows now accros the proxy, which brings in its own cert, the cert can not be verified anymore.

As a workaround you can do the following in the pgbackrest section:

```
....
  backups: 
    pgbackrest:
      metadata:
        labels:
          sidecar.istio.io/inject: 'false'
...
```

This will stop injecting the proxy.
