### ISSUE TITLE
 CustomResourceDefinition.apiextensions.k8s.io "postgresclusters.postgres-operator.crunchydata.com" is invalid: metadata.annotations: Too long: must have at most 262144 bytes

### ISSUE THREAD

**Issue by marcellodesales** [CrunchyData/postgres-operator#3633]
## Overview

Can't install from kustomize if specified

## Environment

Please provide the following details:

- Platform: `Kubernetes`

## Steps to Reproduce

1. Create the kustomization file

- Added the following, adding the token `includeCRDs: true`

```yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# https://stackoverflow.com/questions/57594001/how-can-i-create-a-namespace-with-kustomize/57640208#57640208
# NOTE: THIS MUST MATCH THE VALUE IN argocd-app.yaml
namespace: direktiv

helmCharts:
  # https://github.com/direktiv/direktiv-charts/blob/gh-pages/index.yaml#L492
- name: pgo
  repo: https://chart.direktiv.io
  releaseName: postgres
  namespace: direktiv
  version: 5.3.1
  includeCRDs: true

resources:
# https://github.com/kubernetes-sigs/kustomize/blob/master/examples/remoteBuild.md
#- https://github.com/CrunchyData/postgres-operator-examples//kustomize/install/crd/?ref=main
- namespace.yaml
- postgres.yaml
```

### EXPECTED

It would have been installed just like helm (without the description)

```console
$ helm install -n postgres --create-namespace postgres direktiv/pgo --version 5.3.1
NAME: postgres
LAST DEPLOYED: Sat Apr 15 17:41:56 2023
NAMESPACE: postgres
STATUS: deployed
REVISION: 1
TEST SUITE: None
NOTES:
Thank you for deploying PGO v5.3.1!

                          ((((((((((((((((((((((
                    (((((((((((((%%%%%%%(((((((((((((((
                (((((((((((%%%             %%%%((((((((((((
            (((((((((((%%(   (((( (            %%%(((((((((((
          (((((((((((((%%     (( ,((               %%%(((((((((((
        (((((((((((((((%%         *%%/            %%%%%%%((((((((((
      (((((((((((((((((((%%(( %%%%%%%%%%#(((((%%%%%%%%%%#((((((((((((
    ((((((((((((((((((%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%((((((((((((((
  *((((((((((((((((((((%%%%%%     /%%%%%%%%%%%%%%%%%%%((((((((((((((((
  (((((((((((((((((((((((%%%/      .%,             %%%((((((((((((((((((,
  ((((((((((((((((((((((%                             %#(((((((((((((((((
(((((((((((((((%%%%%%                                 #%(((((((((((((((((
((((((((((((((%%                                         %%(((((((((((((((,
((((((((((((%%%#%                                     %   %%(((((((((((((((
((((((((((((%.                      %                 %     #((((((((((((((
(((((((((((%%                        %               %%*     %(((((((((((((
#(###(###(#%%                      %%%    %%        %%%      #%%#(###(###(#
###########%%%%%   /%%%%%%%%%%%%%       %%       %%%%%         ,%%#######
###############%%       %%%%%%        %%%    %%%%%%%%             %%#####
  ################%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%   %%               %%##
  ################%%        %%%%%%%%%%%%%%%%%      %%%%               %
    ##############%#        %%   (%%%%%%%           %%%%%%
    #############%     %%%%%                      %%%%%%%%%%%
      ###########%       %%%%%%%%%%%            %%%%%%%%%
        #########%%     %%            %%%%%%%%%%%%%%%#
          ########%%   %%                  %%%%%%%%%
              ######%% %%                      %%%%%%
                ####%%%                        %%%%%  %
                      %%                         %%%%
```

### ACTUAL

It fails with the error message 

```console
Error from server (Invalid): error when creating "STDIN": CustomResourceDefinition.apiextensions.k8s.io "postgresclusters.postgres-operator.crunchydata.com" is invalid: metadata.annotations: Too long: must have at most 262144 bytes
```

## Logs

```console
$ kubectl kustomize --enable-helm dependencies/direktiv | kubectl apply -f - 
namespace/direktiv created
customresourcedefinition.apiextensions.k8s.io/pgupgrades.postgres-operator.crunchydata.com created
serviceaccount/pgo created
serviceaccount/pgo-upgrade created
clusterrole.rbac.authorization.k8s.io/pgo created
clusterrole.rbac.authorization.k8s.io/pgo-upgrade created
clusterrolebinding.rbac.authorization.k8s.io/pgo created
clusterrolebinding.rbac.authorization.k8s.io/pgo-upgrade created
deployment.apps/pgo created
deployment.apps/pgo-upgrade created
Error from server (Invalid): error when creating "STDIN": CustomResourceDefinition.apiextensions.k8s.io "postgresclusters.postgres-operator.crunchydata.com" is invalid: metadata.annotations: Too long: must have at most 262144 bytes
Error from server (NotFound): error when creating "STDIN": the server could not find the requested resource (post postgresclusters.postgres-operator.crunchydata.com)
```
