### ISSUE TITLE
Install Postgres Cluster via Helm from OCI Registry

### ISSUE THREAD

**Issue by DCAL12** [CrunchyData/postgres-operator#3641]
## Overview

Allow helm install of PostgresCluster resources via Helm in the same way as PGO operator.

## Use Case

As with installing the operator via Helm (see #2231), automation tools require installing PostgresCluster via Helm from a hosted repository. Currently we must build each version from https://github.com/CrunchyData/postgres-operator-examples/tree/main/helm/postgres and push to our own OCI registry.

## Desired Behavior

A "postgres-cluster" helm chart is hosted alongside the PGO Helm chart at oci://registry.developers.crunchydata.com/crunchydata/pgo. It can be installed in a similar manner as the operator as documented [here](https://access.crunchydata.com/documentation/postgres-operator/v5/installation/helm/), and updated with each release.

## Environment

Tell us about your environment:

Please provide the following details:

- Platform: `Kubernetes`
- Platform Version: `5.3.1`
- Number of Postgres clusters: `12`

**Comment by tony-landreth** [comment]
I've captured a story for our backlog about your request. Thanks for sharing the additional details!

**Comment by ProbstDJakob** [comment]
As a workaround, you could use [helm-git](https://github.com/aslafy-z/helm-git) or [helmfile](https://github.com/helmfile/helmfile) (which just uses the git plugin under the hood) and reference the repository as follows (for `helmfile`):

```yaml
repositories:
  - name: crunchydata
    url: git+https://github.com/CrunchyData/postgres-operator-examples.git@helm?ref=main

releases:
  - name: postgres
    chart: crunchydata/postgrescluster
    values:
      - path/to/your/values.yaml
```

If the example chart will be published as an official OCI Image, it would be nice, if the `databaseInitSQL` key does not receive a reference to a existing `ConfigMap`, but rather a string which will be saved in a `ConfigMap` maintained by the chart (if the string is not empty). This would provide the benefit that one must not write their own helm chart which only holds the `ConfigMap` and then reference this by hand in your chart.

**Comment by zadjadr** [comment]
@tony-landreth Any progress on this?

**Comment by Tostino** [comment]
Just FYI, you can deal with this with Helm by installing the following plugin:
```
helm plugin install https://github.com/aslafy-z/helm-git
```
and then you can do the following in your Chart.yaml for the dependencies:
```
apiVersion: v2
name: demo
description: Demo
type: application
version: 1.0.0
appVersion: "1.0.0"

dependencies:
  - name: postgrescluster
    version: "5.7.2"
    repository: "git+https://github.com/CrunchyData/postgres-operator-examples@helm/postgres"
```

Then you just change your values.yaml to configure the the cluster.
