### ISSUE TITLE
Restore from s3 in not working 

### ISSUE THREAD

**Issue by idanl21** [CrunchyData/postgres-operator#3649]
Im trying to Create PostgresCluster in my EKS using the Operator. 
thats my YAML - 

```
apiVersion: postgres-operator.crunchydata.com/v1beta1
kind: PostgresCluster
metadata:
  name: rhino
spec:
  image: registry.developers.crunchydata.com/crunchydata/crunchy-postgres:ubi8-14.7-0
  postgresVersion: 14
  dataSource:
    pgbackrest:
      stanza: db
      configuration:
      - secret:
          name: my-secret
      global:
        repo1-path: /backrestrepo/pgo-002-backrest-shared-repo/backup/db/20230420-104207F/
      repo:
        name: repo1
        s3:
          bucket: "pgo-prod-bck-002"
          endpoint: "s3.us-east-1.amazonaws.com"
          region: "us-east-1"
  instances:
    - dataVolumeClaimSpec:
        accessModes:
        - "ReadWriteOnce"
        resources:
          requests:
            storage: 50Gi
  backups:
    pgbackrest:
      image: registry.developers.crunchydata.com/crunchydata/crunchy-pgbackrest:ubi8-2.41-4
      repos:
      - name: repo1
        volume:
          volumeClaimSpec:
            accessModes:
            - "ReadWriteOnce"
            resources:
              requests:
                storage: 50Gi
```                
Somehow im getting that error from the `rhino-pgbackrest-restore-XXXX` pod - 
```
Defaulted container "pgbackrest-restore" out of: pgbackrest-restore, nss-wrapper-init (init)
+ pgbackrest restore --stanza=db --pg1-path=/pgdata/pg14 --repo=1 --delta --link-map=pg_wal=/pgdata/pg14_wal
ERROR: [037]: restore command requires option: repo1-s3-key
```

my-secret Secret - 
Created with the command 
`kubectl create secret generic my-secret --from-file=my-secret.yaml`
my-secret.yaml : 
```
[global]
repo1-s3-key=XXXXXXXXXXXXXXXXXXX
repo1-s3-key-secret=XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
```

how can i make sure that the restoration command is with `repo1-s3-key` parameter ?
