### ISSUE TITLE
auto-scaling of storage

### ISSUE THREAD

**Issue by Eric-zch** [CrunchyData/postgres-operator#3652]
Hi There,
Is it possible to extend the storage size automatically based on some criteria, like utilization?
```
apiVersion: postgres-operator.crunchydata.com/v1beta1
kind: PostgresCluster
metadata:
  name: pnst
spec:
  (ignore)
  instances:
    - name: instance1
      replicas: 2
      dataVolumeClaimSpec:
        accessModes:
        - "ReadWriteOnce"
        resources:
          requests:
            storage: 200Gi
```
