### ISSUE TITLE
Missing libraries on upgrade from 14 to 15 with 5.3.1/5.4.2

### ISSUE THREAD

**Issue by EugenMayer** [CrunchyData/postgres-operator#3666]
Upgrading my cluster (major version) from 14 to 15 as usual on 5.3.1 (or 5.4.2, see below)

```
kubectl create -f - <<EOF
apiVersion: postgres-operator.crunchydata.com/v1beta1
kind: PGUpgrade
metadata:
  name: pg-kw1-upgrade
  namespace: postgres
spec:
  image: registry.developers.crunchydata.com/crunchydata/crunchy-upgrade:ubi8-5.3.1-0
  postgresClusterName: pg-cluster
  fromPostgresVersion: 14
  toPostgresVersion: 15
EOF
```

```
kubectl patch postgrescluster -n postgres pg-cluster --type=merge -p '{"spec":{"shutdown":true}}'
kubectl annotate postgrescluster --overwrite -n postgres pg-cluster postgres-operator.crunchydata.com/allow-upgrade=pg-kw1-upgrade
```

The upgrade starts but errors with:

```
creating configuration files ... ok
running bootstrap script ... ok
performing post-bootstrap initialization ... ok
syncing data to disk ... ok


Success. You can now start the database server using:

    /usr/pgsql-15/bin/pg_ctl -D /pgdata/pg15 -l logfile start

initdb: warning: enabling "trust" authentication for local connections
initdb: hint: You can change this by editing pg_hba.conf or using the option -A, or --auth-local and --auth-host, the next time you run initdb.

Step 3: Setting the expected permissions on the old pgdata directory...

Step 4: Copying shared_preload_libraries setting to new postgresql.conf file...

Step 5: Running pg_upgrade check...

Performing Consistency Checks
-----------------------------
Checking cluster versions                                   ok
Checking database user is the install user                  ok
Checking database connection settings                       ok
Checking for prepared transactions                          ok
Checking for system-defined composite types in user tables  ok
Checking for reg* data types in user tables                 ok
Checking for contrib/isn with bigint-passing mismatch       ok
Checking for presence of required libraries                 fatal

Your installation references loadable libraries that are missing from the
new installation.  You can add these libraries to the new installation,
or remove the functions using them from the old installation.  A list of
problem libraries is in the file:
    /pgdata/pg15/pg_upgrade_output.d/20230604T094332.260/loadable_libraries.txt

Failure, exiting

real	0m1.577s
user	0m0.061s
sys	0m0.025s
```

In production, i run the most recent crunchy-data images

```
registry.developers.crunchydata.com/crunchydata/crunchy-postgres:ubi8-14.7-0
```
`registry.developers.crunchydata.com/crunchydata/postgres-operator` and
`registry.developers.crunchydata.com/crunchydata/postgres-operator-upgrade` are both on `ubi8-5.3.1-0`

I'am not sure what is wrong here - do i have to provide my own upgrade image and if, why? i'am running pg entirely stock (for my understanding) - not sure what i would need in "addition".

Apparently i cannot provide `/pgdata/pg15/pg_upgrade_output.d/20230604T094332.260/loadable_libraries.txt` the container has shutdown and the folder has not been created on the volume of the prod images either

(i'am aware this is similar to https://github.com/CrunchyData/postgres-operator/issues/3572 but different versions, iam upgrading from 14 to 15 which should be perfectly support, while 13 to 14 is no longer supported AFAICS)

**Comment by jmckulk** [comment]
Hi @EugenMayer,

Can you share the spec for the cluster you are trying to upgrade? Maybe that will provide some insight into the missing library, but we will likely need to see the contents of that file. If the container/pod still exists, then perhaps something like kubectl debug would help? If not, I have been able to quickly exec into a running pod before it fails to get access to logs.

Upgrades are supported between all supported pg versions to the latest pg version. For example, in 5.3.1 you can upgrade from PG 11 through PG 14 to the latest version of PG 15.

> while 13 to 14 is no longer supported AFAICS

In the linked issue, they were trying to upgrade a PostGIS cluster and that is not currently supported.

**Comment by EugenMayer** [comment]
> Upgrades are supported between all supported pg versions to the latest pg version. For example, in 5.3.1 you can upgrade from PG 11 through PG 14 to the latest version of PG 15.

This is not true for 11-13 IMHO, and was not true before - sorry. You / crunchy data unpublished the upgrade images. This is the reason https://github.com/users/EugenMayer/packages/container/package/crunchydata%2Fcrunchy-upgrade exist .. and not to mention the entire discussion here https://github.com/CrunchyData/postgres-operator/issues/3516 

> Can you share the spec for the cluster you are trying to upgrade?
Sure

```yaml
apiVersion: postgres-operator.crunchydata.com/v1beta1
kind: PostgresCluster
metadata:
  name: pg-cluster
spec:
  users: [ ]
  postgresVersion: 14
  patroni:
    dynamicConfiguration:
      postgresql:
        parameters:
          max_connections: 600
    - name: pg-instance-v4
      replicas: 3
      dataVolumeClaimSpec:
        storageClassName: local-path
        accessModes:
          - 'ReadWriteOnce'
        resources:
          requests:
            storage: 25Gi
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 1
              podAffinityTerm:
                topologyKey: kubernetes.io/hostname
                labelSelector:
                  matchLabels:
                    postgres-operator.crunchydata.com/cluster: pg-cluster
                    postgres-operator.crunchydata.com/instance-set: pg-instance-v4
```

I use pg-bouncer and assume this will not play any role during the upgrade

```yaml
apiVersion: postgres-operator.crunchydata.com/v1beta1
kind: PostgresCluster
metadata:
  name: pg-cluster
spec:
  proxy:
    pgBouncer:
      replicas: 3
      config:
        global:
          max_client_conn: "500"
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 1
              podAffinityTerm:
                topologyKey: kubernetes.io/hostname
                labelSelector:
                  matchLabels:
                    postgres-operator.crunchydata.com/cluster: pg-cluster
                    postgres-operator.crunchydata.com/role: pgbouncer
```

To provide the contents of `/pgdata/pg15/pg_upgrade_output.d/20230604T094332.260/loadable_libraries.txt` i will need to have another try .. since i tried this on prod, i cannot repeat this anytime / easy and have to schedule it.

Can i somehow change which "non regular" pg14 library i use - or list which libraries the current pg15 instance uses?

**Comment by EugenMayer** [comment]
Used `SELECT oid, extname, extversion FROM pg_extension;` to list the extensions installed on the prod cluster

```
  oid  |      extname       | extversion 
-------+--------------------+------------
 13734 | plpgsql            | 1.0
 29712 | pgaudit            | 1.4.2
 29711 | pg_stat_statements | 1.9
 29713 | pgnodemx           | 1.4
```

Anything that looks special in this regard

**Comment by EugenMayer** [comment]
So as you requested @jmckulk the output of the `loadable_libraries.txt `

```
at pg_upgrade_output.d/20230611T175222.817/loadable_libraries.txt 
could not load library "$libdir/pgnodemx": ERROR:  pgnodemx: must be loaded via shared_preload_libraries
In database: postgres
```

So `pgnodemx` is the module in question. Looking up https://github.com/CrunchyData/pgnodemx i assume this can be related to pgmonitor in some sense?

**Comment by jmckulk** [comment]
Thank you for providing the additional information.

Based on the error shown, as well as the various extensions listed within your database, it appears as though certain details about your deployment are missing from this issue (and the various spec's, configurations, etc. provided).  For instance, while `pgnodemx` is enabled & configured by PGO automatically when using the metrics/monitoring stack, and can also be manually enabled, I do not see either configuration reflected in the spec you provided.

- https://access.crunchydata.com/documentation/postgres-operator/latest/guides/extension-management/#pgnodemx
- https://access.crunchydata.com/documentation/postgres-operator/latest/tutorial/monitoring/

And overall, using the various configurations, specs, etc. provided, we have not been able to replicate this issue in any of our environments.

Therefore, if you have any additional details about your deployment (e.g. exactly how `pgnodemx` was enabled in your cluster, etc.), please let us know.  Otherwise, this does not appear to reproducible error in the version of the operator that you are currently using (meaning there must be something else unique about this cluster/deployment).

**Comment by EugenMayer** [comment]
@jmckulk we deploy using https://github.com/CrunchyData/postgres-operator-examples/tree/main/kustomize/install with the overrides i gave you above.

in addition we add this kustomizations

pgbouncer
```yaml
apiVersion: postgres-operator.crunchydata.com/v1beta1
kind: PostgresCluster
metadata:
  name: pg-cluster
spec:
  proxy:
    pgBouncer:
      replicas: 3
      config:
        global:
          max_client_conn: "500"
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 1
              podAffinityTerm:
                topologyKey: kubernetes.io/hostname
                labelSelector:
                  matchLabels:
                    postgres-operator.crunchydata.com/cluster: pg-cluster
                    postgres-operator.crunchydata.com/role: pgbouncer
```

we add pgmonitor via

```yaml
apiVersion: postgres-operator.crunchydata.com/v1beta1
kind: PostgresCluster
metadata:
  name: pg-cluster
# @see https://access.crunchydata.com/documentation/postgres-operator/5.0.5/tutorial/monitoring/
spec:
  monitoring:
    pgmonitor:
      exporter:
        # implicitly set via modules/core/modules/storage/modules/postgres/kustomize/external/crunchy_data_operator_install/manager/manager.yaml
        # image: registry.developers.crunchydata.com/crunchydata/crunchy-postgres-exporter:ubi8-5.3.0-0

**Comment by EugenMayer** [comment]
Any chance to work on this - anything needed or i can provide?

**Comment by EugenMayer** [comment]
Today i tried it using the new operator with the combined upgrade operator binary. 

So using

```
kubectl create -f - <<EOF
apiVersion: postgres-operator.crunchydata.com/v1beta1
kind: PGUpgrade
metadata:
  name: ourcluster-upgrade
  namespace: postgres
spec:
  image: registry.developers.crunchydata.com/crunchydata/crunchy-upgrade:ubi8-5.4.2-0
  postgresClusterName: pg-cluster
  fromPostgresVersion: 14
  toPostgresVersion: 15
```
with the same issue as above.

```
Performing Consistency Checks
-----------------------------
Checking cluster versions                                   ok
Checking database user is the install user                  ok
Checking database connection settings                       ok
Checking for prepared transactions                          ok
Checking for system-defined composite types in user tables  ok
Checking for reg* data types in user tables                 ok
Checking for contrib/isn with bigint-passing mismatch       ok
Checking for presence of required libraries                 fatal

Your installation references loadable libraries that are missing from the
new installation.  You can add these libraries to the new installation,
or remove the functions using them from the old installation.  A list of
problem libraries is in the file:
    /pgdata/pg15/pg_upgrade_output.d/20230923T185404.915/loadable_libraries.txt

Failure, exiting
```

Again, we never installed any additional PG plugins, this is a vanilla installation. So it is again 

```
at pg_upgrade_output.d/20230611T175222.817/loadable_libraries.txt 
could not load library "$libdir/pgnodemx": ERROR:  pgnodemx: must be loaded via shared_preload_libraries
In database: postgres
``` 

That is causing it, which is a crunchydata vanilla shipped plugin. I cannot explain why it fails and i'am not sure why there is no more interest on this issue, since this should afffect any upgrade from 14 to 15 - on any vanilla installation.

Or i'am missing the point here and something is "special" and a "rare configuration case" - but i cannot find that here (myself).

**Comment by dsessler7** [comment]
@EugenMayer, is your monitoring stack running properly? Based on the way that you are installing it, I wouldn't expect it to see exporter as enabled since `spec.monitoring.pgmonitor.exporter` is `nil`. You can have it implicitly use the RELATED_IMAGE set in the manager.yaml by leaving `image` blank; however, `exporter` itself can't be blank. Try setting your pgMonitor spec like so and see if this helps:
```
apiVersion: postgres-operator.crunchydata.com/v1beta1
kind: PostgresCluster
metadata:
  name: pg-cluster
spec:
  monitoring:
    pgmonitor:
      exporter: {}
        # implicitly set via modules/core/modules/storage/modules/postgres/kustomize/external/crunchy_data_operator_install/manager/manager.yaml
        # image: registry.developers.crunchydata.com/crunchydata/crunchy-postgres-exporter:ubi8-5.3.0-0
```

**Comment by EugenMayer** [comment]
@dsessler7 wow, that fixed it! Thank you!

Applying this (i just repeat it so people know what has been changed)

From 

```yaml
apiVersion: postgres-operator.crunchydata.com/v1beta1
kind: PostgresCluster
metadata:
  name: pg-cluster
# @see https://access.crunchydata.com/documentation/postgres-operator/5.0.5/tutorial/monitoring/
spec:
  monitoring:
    pgmonitor:
      exporter: 
        # implicitly set via modules/core/modules/storage/modules/postgres/kustomize/external/crunchy_data_operator_install/manager/manager.yaml
        # image: registry.developers.crunchydata.com/crunchydata/crunchy-postgres-exporter:ubi8-5.3.0-0
```

to 

```yaml
apiVersion: postgres-operator.crunchydata.com/v1beta1
kind: PostgresCluster
metadata:
  name: pg-cluster
# @see https://access.crunchydata.com/documentation/postgres-operator/5.0.5/tutorial/monitoring/
spec:
  monitoring:
    pgmonitor:
      exporter: {}
        # implicitly set viamodules/core/modules/storage/modules/postgres/kustomize/external/crunchy_data_operator_install/manager/manager.yaml
        # image: registry.developers.crunchydata.com/crunchydata/crunchy-postgres-exporter:ubi8-5.3.0-0
```

As dsessler pointed out, the empty exporter object would case issues otherwise.

Doing the upgrade right after that worked without any issues. Wonderful!

@dsessler7 any change to explain how the actual error message corresponds to the issue? If i may throw in an assumption - p15 did spun up without the exporter plugin active, since the object was empty and it was assuming 'no exporter plugin needed'. PG14 though will spin up the instance with the exporter plugin active, even if the export object is empty. When migrating, the plugins do not match and thus the migration fails.

Did i miss this change somewhere in the changelogs - could we add those here so people have a reference? Do you think it might make sense running a validator on the pgmonitor settings to avoid this issue for people not aware of the actual implication of it from pg14 to pg15?

Again, thank you for taking this on and helping, very appreciated!
