### ISSUE TITLE
PGO 5.1.2 - replicas cannot join cluster after recovery from backup -  system ID mismatch, node [X] belongs to a different cluster

### ISSUE THREAD

**Issue by johnswarbrick-napier** [CrunchyData/postgres-operator#3670]
## Overview

I'm using PGO 5.1.2 to deploy a PostgreSQL cluster called "operations" on Azure Kubernetes (AKS). WAL logs and backups are written to Azure object storage.

As a backup test I deleted the cluster and intended to rebuilt it from backups. After initialising the new cluster it recognised the backups in the Azure blob storage. Using those backups I successfully recovered the leader and it startup up with the backed up data.

The problem is that I cannot get the replicas to rejoin the cluster due to a cluster ID mismatch. The two replicas report the error:

```
2023-06-11 19:37:03,615 INFO: No PostgreSQL configuration items changed, nothing to reload.
2023-06-11 19:37:03,621 CRITICAL: system ID mismatch, node operations-instance1-zpt8-0 belongs to a different cluster: 7176625477264674931 != 7241689302123126907
```

I tried deleting the PVCs of the two replicas, to force a full rebuild, but the mismatch error persists.

I cannot re-init the replicas using `patronictl` because they are not recognised as being a member of the cluster.

While the recovered cluster has a functioning leader node, there is no resilience to further failures without the replicas.

Would really appreciate if anyone here can provide some guidance on how to resolve!

Or maybe I should be doing recoveries in a different way entirely.

## Environment

Please provide the following details:

- Platform: Azure Kubernetes
- Platform Version: v1.24.9
- PGO Image Tag: ubi8-5.1.2-0
- Postgres Version: ubi8-13.7-1
- Storage: disk.csi.azure.com

## Steps to Reproduce

1. Provision a new AKS cluster with version v1.24.9
2. Deploy PGO 5.1.2
3. Provision a new three node cluster called "operations" with the following configuration:
```
operations:
  users:
  - name: operations
    databases:
      - operations
  name: operations
  patroni:
    dynamicConfiguration:
      kubernetes:
        use_endpoints: true
  instanceSize: 64Gi
  instanceReplicas: 3
  pgBackRestConfig:
    global:
      compress-type: bz2
      repo1-retention-full: "30"
      repo1-retention-full-type: time
      repo1-retention-archive: "5"
      repo1-retention-archive-type: diff
      repo1-path: "/pgbackrest/repo1/operations"
    repos:
    - name: repo1
      schedules:
        full: "0 3 * * 0"
        differential: "0 3 * * 1-6"
      azure:
        container: "operations"
    restore:
        enabled: false
        repoName: repo1
```
4. Insert some data, run some backups, confirm backups were successful
5. Completely delete the AKS cluster
6. Rebuild the cluster with exactly the same configuration (i.e. same PostgreSQL cluster name, backup settings, etc)
7. Verify the PostgreSQL cluster "operations" is running, albeit with no data
8. Enable recovery mode with `kubectl edit postgrescluster operations` and modifying the `restore` option to:
```
    restore:
        enabled: true
        repoName: repo1
        options:
        - --type=time
        - --target="2023-06-06 01:59:59"
```
9.  Trigger the restore operation with command `kubectl annotate postgrescluster operations --overwrite postgres-operator.crunchydata.com/pgbackrest-restore=operations[UNIQUE-NUMBER]`
10. Monitor as the backup data is downloaded from the Azure object storage to the leader node
11. Disable the recovery mode with `kubectl edit postgrescluster operations` and modifying the `restore` option to:
```
    restore:
        enabled: false
        repoName: repo1
```
12. Observe the leader node successfully starts
13. Observe the replica nodes are in constant CrashLoopBackOff due to error:
```
2023-06-11 19:37:03,615 INFO: No PostgreSQL configuration items changed, nothing to reload.
2023-06-11 19:37:03,621 CRITICAL: system ID mismatch, node operations-instance1-zpt8-0 belongs to a different cluster: 7176625477264674931 != 7241689302123126907
```
14. Attempt to delete the PVCs of the two replicas, delete the pods. Note they continue to display CrashLoopBackOff with the same error

### EXPECTED

Expecting to recover the entire cluster from backups, including replicas, not just the leader

### ACTUAL

Only the leader node starts. Replicas fail with `CRITICAL: system ID mismatch` errors
