### ISSUE TITLE
How do I add an entry to pg_hba?

### ISSUE THREAD

**Issue by batulziiy** [CrunchyData/postgres-operator#3671]
It would be great if we could add an entry to pg_hba.conf file. I tried both #2534 and #2769 , unfortunately no luck at all. 

Deployment looks like : 

```
apiVersion: postgres-operator.crunchydata.com/v1beta1
kind: PostgresCluster
metadata:
  name: hippo
spec:
  image: registry.developers.crunchydata.com/crunchydata/crunchy-postgres:ubi8-14.6-2
  postgresVersion: 14
  instances:
    - name: instance1
      dataVolumeClaimSpec:
        accessModes:
        - "ReadWriteOnce"
        resources:
          requests:
            storage: 1Gi
  patroni:
    dynamicConfiguration:
      postgresql:
        parameters:
          pg_hba:
            - "hostnossl all all all md5"
  backups:
    pgbackrest:
      image: registry.developers.crunchydata.com/crunchydata/crunchy-pgbackrest:ubi8-2.41-2
      repos:
      - name: repo1
        volume:
          volumeClaimSpec:
            accessModes:
            - "ReadWriteOnce"
            resources:
              requests:
                storage: 1Gi
```

- Platform: Kubernetes 1.25.7
- Platform Version: 1.25.7
- PGO Image Tag: 8.14.6-2
- Postgres Version 14 (i have v14 for dev and v15 for prod env)
- Storage: longhorn

**Comment by batulziiy** [comment]
Hello @jmckulk,

Thanks for your response. The file is still not being updated even after restarting statefulset. If possible could you please try to update the existing cluster instead of a fresh new cluster creation. It would be more identical to my situation. 
Below are the pg_hba.conf file and the image tag : 
pg_hba.conf
![image](https://github.com/CrunchyData/postgres-operator/assets/76592232/7e4e3d79-f197-4b8f-a166-30a07443a39b)
Image tag : 
registry.developers.crunchydata.com/crunchydata/postgres-operator:ubi8-5.3.0-0

**Comment by jmckulk** [comment]
I just realized that the `pg_hba.conf` that I shared wasn't using `hostnossl`. You are correct, the spec that you provided isn't actually setting the pg_hba. After looking again, the `pg_hba` section should be under `postgresql`, not `parameters`.

This:

```
  patroni:
    dynamicConfiguration:
      postgresql:
        parameters:
          pg_hba:
            - "hostnossl all all all md5"
```

should actually be, this:
```
  patroni:
    dynamicConfiguration:
      postgresql:
        pg_hba:
          - "hostnossl all all all md5"
```

Please give this a try and make sure it works for you. On a quick look, I'm not seeing any good documentation on how to configure/update pg_hba. I'll get a story created to review our documentation around this.

**Comment by batulziiy** [comment]
Thank you @jmckulk . Updated the configuration according to your recommendation and it worked well, hooray :)

**Comment by jmckulk** [comment]
Nice! Glad we could get it working

**Comment by tuan-phan** [comment]
Make sure you update the encryption method to md5 too
```
  patroni:
    dynamicConfiguration:
      postgresql:
        parameters:
          shared_preload_libraries: "timescaledb"
          ssl: "off"
          password_encryption: "md5"
        pg_hba:
          - "hostnossl all all all md5"
```
