### ISSUE TITLE
PgAdmin4 not working

### ISSUE THREAD

**Issue by duke-bartholomew** [CrunchyData/postgres-operator#3672]
## Overview

Deploying a PostgresCluster through the operator with UserInterface PGAdmin4 does deploy the database correctly, but pgadmin seems not to work.  Trying to navigate to pgadmin (from browser or curl) renders a `500 Internal Server` error.

```
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>500 Internal Server Error</title>
</head><body>
<h1>Internal Server Error</h1>
<p>The server encountered an internal error or
misconfiguration and was unable to complete
your request.</p>
<p>Please contact the server administrator at 
 root@localhost to inform them of the time this error occurred,
 and the actions you performed just before this error.</p>
<p>More information about this error may be available
in the server error log.</p>
</body></html>
```

## Environment

- Platform: `Kubernetes`,  `AKS`
- Platform Version: `1.25.5`
- PGO Image Tag: `ubi8-5.3.0-0`
- Postgres Version: `14`
- Istio: `rancher-istio` version `102.0.0+up1.15.3`

### REPRO

1. deploy the PostgresCluster CR
1. wait for the database and pgadmin pods to come up
1. Try `curl http://127.0.0.1:5050` in the pgadmin POD

### EXPECTED

1. able to navigate to the pgadmin login page
2. able to login using the username/password from the provisioned database user

### ACTUAL

1. Unable to get to the pgadmin login page

### PgAdmin logs:

```
Thu Jun  8 15:24:30 UTC 2023 INFO: TLS disabled. Applying http configuration..
Thu Jun  8 15:24:30 UTC 2023 INFO: Starting Apache web server..
[Thu Jun 08 15:24:30.757865 2023] [so:warn] [pid 18:tid 140010226479360] AH01574: module wsgi_module is already loaded, skipping
```
No further logs when trying to navigate to it.

### PostgresCluster CR:

```
apiVersion: postgres-operator.crunchydata.com/v1beta1
kind: PostgresCluster
metadata:
  name: bucke
  namespace: tenant-bucke-dev
  databaseInitSQL: bucke-sql
  instances:
    - name: db
      readyReplicas: 2
      replicas: 2
      updatedReplicas: 2
spec:
  backups:
    pgbackrest:
      configuration:
        - secret:
            name: bucke-azure-creds
      global:
        repo1-path: /pgo/bucke/repo1
        repo1-retention-full: '3'
        repo1-retention-full-type: count
        repo1-retention-history: '365'
      metadata:
        annotations:
          sidecar.istio.io/inject: 'false'
      repos:
        - azure:
            container: bucke-backups
          name: repo1
          schedules:
            full: 0 0 1 * *
            incremental: 0 6 * * 7
  databaseInitSQL:
    key: db-init.sql
    name: bucke-sql
  instances:
    - affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - podAffinityTerm:
                labelSelector:
                  matchLabels:
                    postgres-operator.crunchydata.com/cluster: bucke
                    postgres-operator.crunchydata.com/instance-set: db
                topologyKey: kubernetes.io/hostname
              weight: 1
      dataVolumeClaimSpec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 5Gi
      minAvailable: 1
      name: db
      replicas: 2
      resources:
        limits:
          memory: 512Mi
        requests:
          cpu: 10m
          memory: 512Mi
  patroni:
    dynamicConfiguration:
      postgresql:
        pg_hba:
          - hostnossl all all all md5
    leaderLeaseDurationSeconds: 30
    port: 8008
    syncPeriodSeconds: 10
  port: 5432
  postgresVersion: 14
  userInterface:
    pgAdmin:
      dataVolumeClaimSpec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 5Gi
      replicas: 1
      resources:
        limits:
          cpu: 1000m
          memory: 128Mi
        requests:
          cpu: 10m
          memory: 128Mi
  users:
    - databases:
        - bucke
      name: bucke
      options: CREATEDB
      password:
        type: AlphaNumeric
```

### from the PgAdmin POD:

`ps -ef`
```
UID          PID    PPID  C STIME TTY          TIME CMD
daemon         1       0  0 Jun08 ?        00:00:00 bash -c CRUNCHY_DIR=${CRUNCHY_DIR:-'/opt/crunchy'} PGADMIN_DIR=/usr/lib/python3.6/site-packages/pgadmin4-web APACHE_PIDFILE='/tmp/httpd.pid' . . .
daemon        18       1  0 Jun08 ?        00:00:10 /usr/sbin/httpd -D FOREGROUND
daemon        19      18  0 Jun08 ?        00:00:00 /usr/sbin/httpd -D FOREGROUND
daemon        21      18  0 Jun08 ?        00:01:17 /usr/sbin/httpd -D FOREGROUND
daemon        23      18  0 Jun08 ?        00:01:13 /usr/sbin/httpd -D FOREGROUND
daemon        49      18  0 Jun08 ?        00:01:15 /usr/sbin/httpd -D FOREGROUND
daemon       370      18  0 Jun08 ?        00:01:17 /usr/sbin/httpd -D FOREGROUND
daemon     15801      18  0 12:13 ?        00:00:00 /usr/sbin/httpd -D FOREGROUND
```
Sqlite:
`sqlite3 /var/lib/pgadmin/pgadmin4.db`

```
SQLite version 3.26.0 2018-12-01 12:34:55
Enter ".help" for usage hints.
sqlite> select * from user;
1|admin|admin|$pbkdf2-sha512$25000$z9l7T.ndG4PwPmcspVQqhQ$Er2iqGqBOyjup2EsD.C3x92swcSTtNuCqOXqLiUdbz5SCyTTI2wrn9C5cwmthPVmA/rPgRW1vw7drJfixt0LPg|1|||internal
```

**Comment by duke-bartholomew** [comment]
I'm not specifying an image in my deployment.  I let the operator choose it.
The one that gets deployed in my setup is : `registry.developers.crunchydata.com/crunchydata/crunchy-pgadmin4:ubi8-4.30-8`

**Comment by jmckulk** [comment]
I did a quick deploy and was able to access pgadmin with 5.3.0 and the image that you shared. I'd like some more info to debug further.

Can you list the pods and services for that cluster? The command should be:
```
kubectl get pods,services -l postgres-operator.crunchydata.com/cluster=bucke
```

If you set up a port-forward for the pgadmin service, can you access the gui through your local browser at `localhost:5050`?

Something like:
```
kubectl port-forward svc/bucke-pgadmin 5050:5050
```

**Comment by duke-bartholomew** [comment]
@jmckulk I tried the same: locally running the pgadmin container works, but when deployed from the postgres-operator (by defining `userInterface: pgAdmin` it doesn't.

port-forwarding to the pgadmin service (on the cluster) gives me the mentioned error: `500 Internal Server Error`
also directly (from a shell into the pgadmin container) executing `curl http://localhost:5050` gives the `Internal Server Error`

I also tried the same setup inside and outside of the Istio mesh: **same result**.

Pods/Services (on the cluster):
```
NAME                  READY   STATUS    RESTARTS   AGE
pod/bucke-db-4dm2-0   4/4     Running   0          17m
pod/bucke-db-ml2j-0   4/4     Running   0          16m
pod/bucke-pgadmin-0   2/2     Running   0          19h

NAME                      TYPE        CLUSTER-IP     EXTERNAL-IP   PORT(S)    AGE
service/bucke-ha          ClusterIP   10.0.153.227   <none>        5432/TCP   19h
service/bucke-ha-config   ClusterIP   None           <none>        <none>     19h
service/bucke-pgadmin     ClusterIP   10.0.58.210    <none>        5050/TCP   19h
service/bucke-pods        ClusterIP   None           <none>        <none>     19h
service/bucke-primary     ClusterIP   None           <none>        5432/TCP   19h
service/bucke-replicas    ClusterIP   10.0.196.85    <none>        5432/TCP   19h
```

**Comment by jmckulk** [comment]
Thanks for sharing that. I don't see anything in your spec that looks incorrect, and I'm still not seeing any issues in my environment. When I deployed a cluster with your `userInterface` and `users` spec, I was able to access the UI with port-forward and `curl localhost` from inside the pgadmin container.

It is odd that you are seeing the `reconcilePGAdminUsers` error, but I doubt that would cause an issue when trying to access the login page. If you just couldn't log in, then I would be worried about it.

I think the next debugging step would be to simplify your spec. Can you connect to a new cluster if you only define required sections and pgadmin? Something like: 
```
apiVersion: postgres-operator.crunchydata.com/v1beta1
kind: PostgresCluster
metadata:
  name: hippo
spec:
  postgresVersion: 14
  instances:
    - name: instance1
      dataVolumeClaimSpec:
        accessModes:
        - "ReadWriteOnce"
        resources:
          requests:
            storage: 1Gi
  backups:
    pgbackrest:
      repos:
      - name: repo1
        volume:
          volumeClaimSpec:
            accessModes:
            - "ReadWriteOnce"
            resources:
              requests:
                storage: 1Gi
  userInterface:
    pgAdmin:
      dataVolumeClaimSpec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
      replicas: 1
```

**Comment by duke-bartholomew** [comment]
@jmckulk hmmmm .. the plot thickens ...
I can confirm that your `hippo` example does work, inside and outside of our Istio mesh.
I'm able to launch pgAdmin and connect to the hippo database.
![Screenshot from 2023-06-15 09-50-53](https://github.com/CrunchyData/postgres-operator/assets/10145739/42259ee6-d583-4dfb-841d-09e69aa9c34c)

I'll do a couple more tests on my `bucke` database to see if I can figure out what's causing that.
I can also say that on our platform this is not an isolated issue.  We have more postgres setups running besides the `bucke` one, and they are all suffering from the same issue: `500 Internal Server Error` when starting pgAdmin.  The way they are deployed is comparable to our `bucke` one.

Can it be that this is somehow related to the use of a `databaseInitSQL` script?

**Comment by duke-bartholomew** [comment]
@jmckulk I found the issue.
In my original PostgresCluster configuration I had this on pgAdmin:
```
      resources:
        limits:
          cpu: 1000m
          memory: 128Mi
        requests:
          cpu: 10m
          memory: 128Mi
```
That is causing the issue.  `128 MB` seems way to low for pgAdmin.
I now configured it to `1 GB` and all is working fine.
It still bothers me a bit that this went by rather silently.  No pgAdmin container was crashing or OOM killed or something.
All stayed nicely up and running, only apache web-server throwing this `500` response.

This would also explain the `reconciler error` we saw in the operator logs: `command terminated with exit code 137`
