### ISSUE TITLE
PGO v5.4.0 issue with PostgreSQL 13 image

### ISSUE THREAD

**Issue by paulbadcock** [CrunchyData/postgres-operator#3690]
## Overview

PGO v5.4.0 has broken all instances of PostgreSQL 13 clusters. It's not generating the image to use in the stateful set but it works for version 14 and 15 clusters.

## Environment

Please provide the following details:

- Platform: `OpenShift`
- Platform Version:  `4.12.22`
- PGO Image Tag: `ubi8-5.4.0-0`
- Postgres Version  `13`
- Storage: `thin-vmdk`

### REPRO

Provide steps to get to the error condition:

1. Install the community operator version of PGO 5.4.0
2. Create a new instance of a PostgreSQL 13 database like so:

```yaml
kind: PostgresCluster
apiVersion: postgres-operator.crunchydata.com/v1beta1
metadata:
  name: example
  namespace: example
spec:
  backups:
    pgbackrest:
      repos:
        - name: repo1
          volume:
            volumeClaimSpec:
              accessModes:
                - ReadWriteOnce
              resources:
                requests:
                  storage: 1Gi
  instances:
    - dataVolumeClaimSpec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
      replicas: 1
  postgresVersion: 13
```

4. Observe failure to start as the stateful set is missing the image line for the container

### EXPECTED

1. Database to start

### ACTUAL

1. Stateful set and the database is offline due to the missing image definition

## Logs

Stateful set will have the following events:

```text
Create Pod example-instance1-4stl-0 in StatefulSet example-instance1-4stl failed error: Pod "example-instance1-4stl-0" is invalid: [spec.containers[0].image: Required value, spec.containers[1].image: Required value, spec.initContainers[0].image: Required value, spec.initContainers[1].image: Required value]
```

## Additional Information

Using a PostgreSQL version 14 or 15 works as expected, this only breaks with a v13.

If you update the PostgresCluster spec file of the database with an image tag from the v5.3.0 operator the database will startup fine on v5.4.0 but this isn't correct but is a break fix work around.

```yaml
kind: PostgresCluster
apiVersion: postgres-operator.crunchydata.com/v1beta1
metadata:
  name: example
  namespace: example
spec:
  backups:
    pgbackrest:
      repos:
        - name: repo1
          volume:
            volumeClaimSpec:
              accessModes:
                - ReadWriteOnce
              resources:
                requests:
                  storage: 1Gi
  instances:
    - dataVolumeClaimSpec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
      replicas: 1
  image: >-
    registry.connect.redhat.com/crunchydata/crunchy-postgres@sha256:1c336e8a3a7447be70a19235b0e9bcd19663955c8f480949281f5d24463637e5
  postgresVersion: 13
```

**Comment by deanpeterson** [comment]
I can confirm this broke the Crunchy DB instances when my Openshift Cluster updated the Operator!!!!!!!

**Comment by venkatgankidi** [comment]
I can confirm that this broke the databases on our open shift clusters, I applied above mentioned break fix , thanks for sharing the breakfix @paulbadcock

**Comment by tadamo** [comment]
The same problem happened to me on our OpenShift 4.12 cluster.

I'm attempting the work around by changing the image:

```
apiVersion: postgres-operator.crunchydata.com/v1beta1
kind: PostgresCluster
metadata:
  name: keycloak
  namespace: keycloak-postgres-db-qa
spec:
  image: >-
    registry.connect.redhat.com/crunchydata/crunchy-postgres@sha256:1c336e8a3a7447be70a19235b0e9bcd19663955c8f480949281f5d24463637e5
  postgresVersion: 13
  openshift: true
  port: 5432
```

But the DB doesn't seem to come up. I see the following errors:

```
keycloak-instance2-42t5-0 database 2023-07-14 13:39:04,306 ERROR: Exception when working with leader
keycloak-instance2-42t5-0 database Traceback (most recent call last):
keycloak-instance2-42t5-0 database   File "/usr/local/lib/python3.6/site-packages/patroni/postgresql/rewind.py", line 68, in check_leader_is_not_in_recovery
keycloak-instance2-42t5-0 database     with get_connection_cursor(connect_timeout=3, options='-c statement_timeout=2000', **conn_kwargs) as cur:
keycloak-instance2-42t5-0 database   File "/usr/lib64/python3.6/contextlib.py", line 81, in __enter__
keycloak-instance2-42t5-0 database     return next(self.gen)
keycloak-instance2-42t5-0 database   File "/usr/local/lib/python3.6/site-packages/patroni/postgresql/connection.py", line 44, in get_connection_cursor
keycloak-instance2-42t5-0 database     conn = psycopg.connect(**kwargs)
keycloak-instance2-42t5-0 database   File "/usr/lib64/python3.6/site-packages/psycopg2/__init__.py", line 122, in connect
keycloak-instance2-42t5-0 database     conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
keycloak-instance2-42t5-0 database psycopg2.OperationalError: could not make a writable connection to server "keycloak-instance2-c2c5-0.keycloak-pods:5432"
keycloak-instance2-42t5-0 database
keycloak-instance2-c2c5-0 database 2023-07-14 13:39:04,306 INFO: promoted self to leader because I had the session lock
keycloak-instance2-42t5-0 database 2023-07-14 13:39:04,316 INFO: no action. I am (keycloak-instance2-42t5-0), a secondary, and following a leader (keycloak-instance2-c2c5-0)
keycloak-instance2-c2c5-0 database server promoting
keycloak-instance2-c2c5-0 database 2023-07-14 13:39:04,322 INFO: cleared rewind state after becoming the leader
keycloak-instance2-c2c5-0 exporter ts=2023-07-14T13:39:12.536Z caller=server.go:74 level=info msg="Established new database connection" fingerprint=localhost:5432
keycloak-instance2-c2c5-0 exporter ts=2023-07-14T13:39:12.536Z caller=collector.go:194 level=error msg="collector failed" name=replication_slot duration_seconds=0.000536145 err="dial tcp [::1]:5432: connect: connection refused"
keycloak-instance2-c2c5-0 exporter ts=2023-07-14T13:39:12.537Z caller=collector.go:194 level=error msg="collector failed" name=database duration_seconds=0.000989165 err="dial tcp [::1]:5432: connect: connection refused"
keycloak-instance2-c2c5-0 exporter ts=2023-07-14T13:39:12.537Z caller=collector.go:194 level=error msg="collector failed" name=bgwriter duration_seconds=0.001166954 err="dial tcp [::1]:5432: connect: connection refused"
keycloak-instance2-c2c5-0 exporter ts=2023-07-14T13:39:13.537Z caller=postgres_exporter.go:716 level=error err="Error opening connection to database (postgresql://ccp_monitoring:PASSWORD_REMOVED@localhost:5432/postgres?): dial tcp [::1]:5432: connect: connection refused"
keycloak-instance2-c2c5-0 database 2023-07-14 13:39:14,653 WARNING: Postgresql is not running.
```

Anyone see something similar?
