### ISSUE TITLE
S3 backup does not work

### ISSUE THREAD

**Issue by vit-h** [CrunchyData/postgres-operator#3702]
## Overview

S3 backup does not work
Seems like host incorrectly constructed.
Also due to this the wal files folder grows furiousely ignoring the limit, so my cluster went down.

How to correctly setup s3 backup and restore connection and policies to s3?

## Environment

- Platform: `AKS` 
- Platform Version: K8s `1.25.11`
- PGO Image Tag: 
Using latest helm.
imagePostgres: registry.developers.crunchydata.com/crunchydata/crunchy-postgres-gis:ubi8-15.3-3.3-2
imagePgBackRest: registry.developers.crunchydata.com/crunchydata/crunchy-pgbackrest:ubi8-2.45-2 # default
- Postgres Version: `15`
- Storage: instanceStorageClassName: "hostpath" # default

## Steps to Reproduce

```
multiBackupRepos:
  - volume:
      backupsSize: 2Gi
  - s3:   # => host: bucket-backup.s3.wasabisys.com
      bucket: "bucket-backup"
      endpoint: "s3.us-east-1.wasabisys.com"
      region: "us-east-1"
      key: "theKey"
      keySecret: "theSecret"
  - s3:   # => host: bucket-backup.s3.us-east-1.wasabisys.com
      bucket: "bucket-backup"
      endpoint: "s3.us-east-1.wasabisys.com"
      region: "us-east-1"
      key: "theKey"
      keySecret: "theSecret"
```

### EXPECTED

s3 backup works

### ACTUAL

host: bucket-backup.s3.wasabisys.com
I think the host should be: s3.us-east-1.wasabisys.com 
and path: /bucket-backup

## Logs

```
Time="2023-08-08T17:37:41Z" level=error msg="unable to create stanza" controller=postgrescluster controllerGroup=postgres-operator.crunchydata.com controllerKind=PostgresCluster error="command terminated with exit code 39: ERROR: [039]: HTTP request failed with 403 (Forbidden):
       *** Path/Query ***:
       HEAD /pgbackrest/pgo/itfdb/repo2/archive/db/archive.info
       *** Request Headers ***:
       authorization: <redacted>
       content-length: 0
       host: bucket-backup.s3.wasabisys.com
       x-amz-content-sha256: e3b.....2b855
       x-amz-date: <redacted>
       *** Response Headers ***:
       content-type: application/xml
       date: Tue, 08 Aug 2023 17:37:41 GMT
       server: WasabiS3/7.15.2121-2023-07-18-0ee420c377 (head05)
       x-amz-id-2: qL7.....vTp
       x-amz-request-id: 99.....2:B
" file="internal/controller/postgrescluster/pgbackrest.go:2618" func="postgrescluster.(*Reconciler).reconcileStanzaCreate" name=itfdb namespace=pgo postgresCluster=pgo/itfdb reconcileID=097035a0-6bff-472a-a07b-cb51f9563064 reconciler=pgBackRest version=5.4.0-0
```

**Comment by ValClarkson** [comment]
Hi @vit-h,

What type of S3 is this? for example is it minio etc?

**Comment by vit-h** [comment]
@ValClarkson it is https://console.wasabisys.com/
Just S3.

I was able to run it with kustomize and I see files created in the bucket.

**Comment by vit-h** [comment]
@ValClarkson 
Just got a closer look.
The full, diff and incr backups does not work.
Seems there I hava just a WAL sync.

```
pgo show backup itfdb --repoName=repo2 -n pgo
stanza: db
    status: error (no valid backups)
    cipher: none

    db (current)
        wal archive min/max (15): 000000010000000000000001/00000001000000000000003D
```

```
kubectl exec -it itfdb-i1-4ppk-0 -n pgo -- bash
kubectl exec [POD] [COMMAND] is DEPRECATED and will be removed in a future version. Use kubectl exec [POD] -- [COMMAND] instead.
Defaulted container "database" out of: database, replication-cert-copy, pgbackrest, pgbackrest-config, postgres-startup (init), nss-wrapper-init (init)
bash-4.4$ patronictl list
+ Cluster: itfdb-ha (7267015936833986633) -----+---------+---------+----+-----------+
| Member          | Host                       | Role    | State   | TL | Lag in MB |
+-----------------+----------------------------+---------+---------+----+-----------+
| itfdb-i1-4ppk-0 | itfdb-i1-4ppk-0.itfdb-pods | Replica | running | 25 |         0 |
| itfdb-i1-9hjz-0 | itfdb-i1-9hjz-0.itfdb-pods | Leader  | running | 25 |           |
+-----------------+----------------------------+---------+---------+----+-----------+
```

```
get pods -n pgo
NAME                              READY   STATUS      RESTARTS   AGE
itfdb-backup-4px6-6jzxl           0/1     Error       0          12h
itfdb-backup-4px6-72zk9           0/1     Error       0          12h
itfdb-backup-4px6-bfrb9           0/1     Error       0          12h
itfdb-backup-4px6-dcdfn           0/1     Error       0          12h
itfdb-backup-4px6-dpxgt           0/1     Error       0          12h
itfdb-backup-4px6-jhk9v           0/1     Error       0          12h
itfdb-backup-4px6-q7492           0/1     Error       0          12h
itfdb-backup-5jt6-2hqkc           0/1     Completed   0          12h
itfdb-i1-4ppk-0                   4/4     Running     0          12h
itfdb-i1-9hjz-0                   4/4     Running     0          12h
itfdb-repo-host-0                 2/2     Running     0          12h
itfdb-repo1-diff-28254600-qzxns   0/1     Completed   0          11h
itfdb-repo1-diff-28255080-g49lf   0/1     Completed   0          3h9m
itfdb-repo1-full-28254840-rbmt9   0/1     Completed   0          7h9m
itfdb-repo1-incr-28255140-zndhz   0/1     Completed   0          129m
itfdb-repo1-incr-28255200-zhj9k   0/1     Completed   0          69m
itfdb-repo1-incr-28255260-s597l   0/1     Completed   0          9m15s
itfdb-repo2-diff-28255080-jvb7j   0/1     Error       0          3h9m
itfdb-repo2-diff-28255080-k7trk   0/1     Error       0          3h6m
itfdb-repo2-diff-28255080-kfqdx   0/1     Error       0          3h9m
itfdb-repo2-diff-28255080-lcjhx   0/1     Error       0          3h8m
itfdb-repo2-diff-28255080-p6vmk   0/1     Error       0          3h7m
itfdb-repo2-diff-28255080-t28qb   0/1     Error       0          3h8m
itfdb-repo2-diff-28255080-xrxw2   0/1     Error       0          3h3m
itfdb-repo2-full-28254840-4l625   0/1     Error       0          7h9m
itfdb-repo2-full-28254840-4sdxr   0/1     Error       0          7h8m
itfdb-repo2-full-28254840-5ghgf   0/1     Error       0          7h9m
itfdb-repo2-full-28254840-9rgwc   0/1     Error       0          7h7m
itfdb-repo2-full-28254840-mmrzq   0/1     Error       0          7h8m
itfdb-repo2-full-28254840-mz72w   0/1     Error       0          7h6m
itfdb-repo2-full-28254840-ztc57   0/1     Error       0          7h3m
itfdb-repo2-incr-28255200-5d5x8   0/1     Error       0          68m
itfdb-repo2-incr-28255200-5vmc4   0/1     Error       0          69m
itfdb-repo2-incr-28255200-6hcfl   0/1     Error       0          66m
itfdb-repo2-incr-28255200-6rb86   0/1     Error       0          69m
itfdb-repo2-incr-28255200-cll22   0/1     Error       0          68m
itfdb-repo2-incr-28255200-ld7tl   0/1     Error       0          63m
itfdb-repo2-incr-28255200-t27b8   0/1     Error       0          67m
itfdb-repo2-incr-28255260-2cppx   0/1     Error       0          8m32s
itfdb-repo2-incr-28255260-46zk5   0/1     Error       0          8m56s
itfdb-repo2-incr-28255260-7ptjv   0/1     Error       0          9m10s
```
kubectl pgo backup itfdb --repoName="repo2" --options="--type=full --log-level-console=debug" -n pgo
postgresclusters/itfdb backup initiated
[Explore-logs-2023-09-21 12_56_23.txt](https://github.com/CrunchyData/postgres-operator/files/12689930/Explore-logs-2023-09-21.12_56_23.txt)

How to make it work?

here is my setup:

```
apiVersion: v1
data:
  init.sql: |
    \c itfdb
    GRANT CREATE ON SCHEMA public TO "itfdb";
kind: ConfigMap
metadata:
  name: init-sql
  namespace: pgo
---
apiVersion: v1
data:
  s3.conf: |
    W2dsb2JhbF0NCnJlcG8yLXMzLWtleT1TWS4uLg0KcmVwbzItczMta2V5LXNlY3JldD16RG
    UuLi4NCg==
kind: Secret
metadata:
  name: pgo-s3-creds
  namespace: pgo
type: Opaque
---
apiVersion: postgres-operator.crunchydata.com/v1beta1
kind: PostgresCluster
metadata:
  name: itfdb
  namespace: pgo
spec:
  backups:
    pgbackrest:
      configuration:
      - secret:
          name: pgo-s3-creds
      global:
        repo2-path: /itfdb
      image: registry.developers.crunchydata.com/crunchydata/crunchy-pgbackrest:ubi8-2.45-2
      repos:
      - name: repo1
        schedules:
          differential: 0 2,6,14,18,22 * * *
          full: 0 10 * * *
          incremental: 0 0,1,3,4,5,7,8,9,11,12,13,15,16,17,19,20,21,23 * * *
        volume:
          volumeClaimSpec:
            accessModes:
            - ReadWriteOnce
            resources:
              requests:
                storage: 4Gi
      - name: repo2
        s3:
          bucket: dvbackups
          endpoint: s3.us-east-1.wasabisys.com
          region: us-east-1
        schedules:
          differential: 0 2,6,14,18,22 * * *
          full: 0 10 * * *
          incremental: 0 0,1,3,4,5,7,8,9,11,12,13,15,16,17,19,20,21,23 * * *
  databaseInitSQL:
    key: init.sql
    name: init-sql
  image: registry.developers.crunchydata.com/crunchydata/crunchy-postgres-gis:ubi8-15.3-3.3-2
  instances:
  - dataVolumeClaimSpec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 20Gi
    name: i1
    replicas: 2
  patroni:
    dynamicConfiguration:
      postgresql:
        parameters:
          max_wal_size: 256MB
  postgresVersion: 15
```
