### ISSUE TITLE
PGSQL clients fail to reconnect following leader election

### ISSUE THREAD

**Issue by johnswarbrick-napier** [CrunchyData/postgres-operator#3717]
I'm not sure if this is a bug or an implementation issue, but it seems on Kubernetes, PGSQL clients do not automatically re-establish connections following a leader election event. This results in create, update, delete activities failing with `org.postgresql.util.PSQLException: ERROR: cannot execute INSERT in a read-only transaction` errors.

I have a three node PostgreSQL 13 cluster managed by PGO 5.3.2 running in Azure AKS on Kubernetes 1.25.11.

PGSQL client applications are connecting to the leader node of the cluster using the details in the `pguser` Kubernetes secret that is automatically created by PGO.

The client applications use the `host` parameter which resolves to Kubernetes service `transactions-primary.aml.svc`

The connection is established using a persistent TCP connection.

Everything works fine until there is a leader election event within the cluster, and the leader role moves to one of the other two pods in the cluster.

At this point the PGSQL client applications are still connected to the previous leader (now a replica) and any write activities result in a `org.postgresql.util.PSQLException: ERROR: cannot execute INSERT in a read-only transaction` error.

The PGSQL client application pods have to be deleted, forcing a new connection to Kubernetes service `transactions-primary.aml.svc` when then connects the client application to the new leader.

How are the PGSQL client applications mean to detect the leader re-election event and teardown/re-create their connections?

Or is our implementation wrong, and PGSQL clients should be connecting using a different method which is resilient to failover?

**Environment**
Please provide the following details:

PGO: 5.3.2
Platform: Azure AKS
Platform Version: Kubernetes v1.25.11
PGO Image Tag: ubi8-5.3.2-0
Postgres Version: ubi8-13.7-1
Storage: disk.csi.azure.com

**Extra Information**
Output of patronictl list:

![image](https://github.com/CrunchyData/postgres-operator/assets/105818625/2fa4495f-2827-4bb8-a166-080a3d8cd3c9)

Example secret:

```
data:
  dbname: transactions
  host: transactions-primary.aml.svc
  jdbc-uri: jdbc:postgresql://transactions-primary.aml.svc:5432/transactions?password=XXXXXXXXXXXXXXXXXXXXX&user=transactions)
  password: XXXXXXXXXXXXXXXXXXXXX
  port: 5432
  uri: postgresql://transactions:XXXXXXXXXXXXXXXXXXXXX@transactions-primary.aml.svc:5432/transactions)
  user: transactions
```

Kubernetes services:

![image](https://github.com/CrunchyData/postgres-operator/assets/105818625/7282de63-2d99-4ec7-b6a2-8a9d91958be2)
