### ISSUE TITLE
Allow user defined pod annotations based on features/containers in pods

### ISSUE THREAD

**Issue by pbolduc** [CrunchyData/postgres-operator#3734]
Have an idea to improve PGO? We'd love to hear it! We're going to need some information from you to learn more about your feature requests.

Please be sure you've done the following:

- [x] Provide a concise description of your feature request.
- [x] Describe your use case. Detail the problem you are trying to solve.
- [x] Describe how you envision that the feature would work.
- [x] Provide general information about your current PGO environment.

## Overview

It would be useful to allow people to add custom annotations when enabling various features like pgmonitor.

## Use Case

Describe your use case. Why do you want this feature? What problem will it solve? Why will it help you? Why will it make it easier to use PGO?

In some clusters, the prometheus instance is shared across multiple projects. In our case, we use [Sysdig](https://sysdig.com/) which can scrape metrics from our pods. Our cluster is quite large and serves numerous project teams across multiple departments. Being a shared instance, teams do not have ability to install operators. The cluster admins have already installed postgres-operator. Having our cluster admins already committed to using Sysdig, we should be consolidating our metrics in Sysdig. Having teams install their own prometheus deployment is a waste of resources.

Sysdig will scrape prometheus metrics from pods which are annotated with `prometheus.io/scrape=true`, `prometheus.io/path` and `prometheus.io/port`. We need the ability to add these metrics to the pods needing scraping, ie those running postgres_exporter.

Adding a feature in postgres-operator. to add these specific annotations is not really something great. There will always be others wanting to add other annotations. A better solution would be to extend the CRD to support custom `metadata.annotations` (and labels?) at the lower level on features that are being enabled.  For example,

```yaml
  monitoring:
    pgmonitor:
      metadata:
        annotations:
          prometheus.io/scrape: 'true'
          prometheus.io/port: 9187
      exporter:
           ...
```

These annotations (whatever the user specifies) would be merged/appended to the pod's annotations for those pods getting the postgres_exporter container. Note, I may not have the level correct in the example above. If this should only apply to the pods containing the postgres_exporter, then perhaps it would be more appropriate to have these properties nested under the exporter property.

## Desired Behavior

Describe how the feature would work. How do you envision interfacing with it?

Users could optionally add metadata annotations to pods by updating their CRDs.

## Environment

Tell us about your environment:

Please provide the following details:

- Platform: (`Kubernetes`, `OpenShift`, `Rancher`, `GKE`, `EKS`, `AKS` etc.)
  - OpenShift
  - k3s (test lab)
- Platform Version: (e.g. `1.20.3`, `4.7.0`)
- PGO Image Tag: (e.g. `ubi8-5.x.y-0`)
- Postgres Version (e.g. `15`)
- Storage: (e.g. `hostpath`, `nfs`, or the name of your storage class)
- Number of Postgres clusters: (`XYZ`)

## Additional Information

Please provide any additional information that may be helpful.

Related: [#3368]

**Comment by dsessler7** [comment]
The `crunchy-postgres-exporter` container runs in the instance Pod. You can add annotations only to the instance Pod (rather than all Pods in the PostgresCluster) by adding them to `spec.instances[index].metadata.annotations`.

**Comment by pbolduc** [comment]
Thank you. For others, the example provided on discord was:

```yaml
apiVersion: postgres-operator.crunchydata.com/v1beta1
kind: PostgresCluster
metadata:
  name: hippo-ha
spec:
  image: registry.developers.crunchydata.com/crunchydata/crunchy-postgres:ubi8-15.4-0
  postgresVersion: 15
  instances:
    - name: pgha1
      metadata:
        annotations:
          prometheus.io/scrape: 'true'
```
