### ISSUE TITLE
Cluster constantly terminates and restart

### ISSUE THREAD

**Issue by shaharl-sternum** [CrunchyData/postgres-operator#3751]
When running an example cluster for testing, the instances are always terminated and restart
example yaml
---
```yaml
# Source: postgrescluster/templates/postgres.yaml
apiVersion: postgres-operator.crunchydata.com/v1beta1
kind: PostgresCluster
metadata:
  name: postgres-cluster
  namespace: datalayer
spec:
  postgresVersion: 15
  instances:
    - name: "instance1"
      replicas: 3
      dataVolumeClaimSpec:
        accessModes:
        - "ReadWriteOnce"
        resources:
          requests:
            storage: "10Gi"
  backups:
    pgbackrest:
      repos:
      - name: repo1
        volume:
          volumeClaimSpec:
            accessModes:
            - "ReadWriteOnce"
            resources:
              requests:
                storage: "10Gi"
```
