### ISSUE TITLE
Docs should mention this error: provided port is not in the valid range

### ISSUE THREAD

**Issue by luatnd** [CrunchyData/postgres-operator#3752]
Hi I've just accidentally struggled with this issue and figured out how to fix it.

So I think it's better if we can have a line in the docs that mentions:
> spec.service.nodePort: The range of valid ports is 30000-32767"

I know it's Kubernetes default NodePort range, not from the pgo side. But somehow set the incorrect port.

---
More verbose on my case:
I follow the docs and expose cluster as NodePort:
```
service:
    metadata:
      labels:
        app: foo-api
    type: NodePort
    nodePort: 35432    # with the idea of default pg port is 5432, I added 3 as prefix
```
`kubectl apply -k kustomize/postgres` did not create any pod with this config.

Finally, 
I set `CRUNCHY_DEBUG` to true then read the logs in `pgo` deployment and see the error:
```
provided port is not in the valid range. The range of valid ports is 30000-32767" f │
│ ile="internal/controller/postgrescluster/patroni.go:310" func="postgrescluster.(*Reconciler).reconcilePatroniLeaderLease" name=hippo namespace=postgres-operator postgresC │
│ luster=postgres-operator/hippo reconcileID=e1b0c2f1-a34f-4dd1-a471-00bbe330494e version=5.4.2-0-arm64  
```
