### ISSUE TITLE
[Community question] What's the different of HA benefit between `spec.instances.replicas` and `spec.instances`?

### ISSUE THREAD

**Issue by luatnd** [CrunchyData/postgres-operator#3754]
## Questions
I'm using Postgres operator but got confused about these two configs in the [docs](https://access.crunchydata.com/documentation/postgres-operator/5.0.1/tutorial/high-availability/):

> PGO provides several ways to add replicas to make a HA cluster:
> - Increase the `spec.instances.replicas` value
> - Add an additional entry in `spec.instances`

Can anyone help me to reveal the secret, what is the difference (in terms of HA benefit) between:
```yml
spec:
  instances:
    - name: i1
      replicas: 2
```
vs
```yml
spec:
  instances:
    - name: i1
      replicas: 1
    - name: i2
      replicas: 1
```
And why should I use first config over second config?

Many thanks for your help in advance.

### Environment
don't need to
