### ISSUE TITLE
Multi repo backup fails due to Azure Blob repo

### ISSUE THREAD

**Issue by batulziiy** [CrunchyData/postgres-operator#3779]
If you believe you have found have found a bug, please open up [Bug Report](https://github.com/CrunchyData/postgres-operator/issues/new?template=bug_report.md)

If you have a feature request, please open up a [Feature Request](https://github.com/CrunchyData/postgres-operator/issues/new?template=feature_request.md)

You can find information about general PGO [support](https://access.crunchydata.com/documentation/postgres-operator/latest/support/) at:

[https://access.crunchydata.com/documentation/postgres-operator/latest/support/](https://access.crunchydata.com/documentation/postgres-operator/latest/support/)

## Questions
Hi all, I wonder how do you guys make multi repo backup work? I have a cluster with local-repo and azure-blob repo set. The multi repo backup worked for a few days, then started throwing an error while backup job is running. It says 
`WARNING:  archiving write-ahead log file "0000000C0000041100000023" failed too many times, will try again later
ERROR: [045]: WAL file '0000000C0000041100000023' already exists in the repo2 archive with a different checksum`

I can manually delete them on the Azure container. However, want to find out the root cause which is raising the problem.
I suspect it might be caused by poorly defined backup policy . My question is do you set schedule for both repo when setting up multi repo backup? Or just set schedule for the first one and let the second run without schedule? 
The below is pg-instance manifest : 
```
apiVersion: postgres-operator.crunchydata.com/v1beta1
kind: PostgresCluster
metadata:
  name: prod001
  namespace: prod001
spec:
  image: registry.developers.crunchydata.com/crunchydata/crunchy-postgres:ubi8-15.2-0
  postgresVersion: 15
  instances:
    - name: instance1
      dataVolumeClaimSpec:
        accessModes:
          - "ReadWriteOnce"
        resources:
          requests:
            storage: 1000Gi
  backups:
    pgbackrest:
      image: registry.developers.crunchydata.com/crunchydata/crunchy-pgbackrest:ubi8-2.41-4
      configuration:
      - secret:
          name: azure-creds
      global:
        repo1-retention-full: "1"
        repo1-retention-full-type: count
        repo2-path: /backup/prod001/repo2
        repo2-retention-full: "1"
        repo2-retention-full-type: count
      repos:
        - name: repo1
          schedules:
            full: "59 23 * * 1"
            differential: "59 23 * * 2-5"
          volume:
            volumeClaimSpec:
              accessModes:
                - "ReadWriteOnce"
              resources:
                requests:
                  storage: 1000Gi
        - name: repo2
          azure:
            container: "container-name-here"
          schedules:
            full: "59 1 * * 1"
            differential: "59 1 * * 2-5"
```
For questions that are neither bugs nor feature requests, please be sure to

- [ ] Provide information about your environment (see below for more information).
- [ ] Provide any steps or other relevant details related to your question.
- [ ] Attach logs, where applicable. Please do not attach screenshots showing logs unless you are unable to copy and paste the log data.
- [ ] Ensure any code / output examples are [properly formatted](https://docs.github.com/en/github/writing-on-github/basic-writing-and-formatting-syntax#quoting-code) for legibility.

Besides Pod logs, logs may also be found in the `/pgdata/pg<MAJOR_VERSION>/log` directory on your Postgres instance.

If you are looking for [general support](https://access.crunchydata.com/documentation/postgres-operator/latest/support/), please view the [support](https://access.crunchydata.com/documentation/postgres-operator/latest/support/) page for where you can ask questions.

### Environment

Please provide the following details:

- Platform: (`Kubernetes`, `OpenShift`, `Rancher`, `GKE`, `EKS`, `AKS` etc.) Kubernetes K3S
- Platform Version: (e.g. `1.20.3`, `4.7.0`) v1.26.3+k3s1
- PGO Image Tag: (e.g. `ubi8-5.x.y-0`) ubi8-15.2-0
- Postgres Version (e.g. `15`) 15
- Storage: (e.g. `hostpath`, `nfs`, or the name of your storage class) for local-repo longhorn, for azure repo Azure blob
