### ISSUE TITLE
Ability to set service externalTrafficPolicy & internalTrafficPolicy to Local

### ISSUE THREAD

**Issue by yarosq** [CrunchyData/postgres-operator#3797]
## Overview
We have some clients connecting to our databases from outside the Kubernetes cluster. By default service with type Loadbalancer set externalTrafficPolicy/internalTrafficPolicy to Cluster which mask the source IP with the Kubernetes nodes IP. In this case we can not control the access to the cluster based on source IP.

## Use Case
Setting  externalTrafficPolicy/internalTrafficPolicy to local allows us to preserve IPs of the client, thus we can restrict/allow access via pg_hba.

## Desired Behavior

Ability to set service externalTrafficPolicy & internalTrafficPolicy to Local

```
kind: PostgresCluster
spec:
  service:
    externalTrafficPolicy: Local
    internalTrafficPolicy: Local
...
```
