### ISSUE TITLE
Backup on standby

### ISSUE THREAD

**Issue by Pluggi** [CrunchyData/postgres-operator#3799]
## Overview

I would like to be able to run backups from a standby instead of the primary.

## Use Case

Pgbackrest backups can use a lot of CPU and I/O. To avoid reduced performance of the master, pgbackrest implemented a mode to run backups from a standby.
To do so, it must be aware of all the pods of the cluster as explained [in the documentation](https://pgbackrest.org/user-guide.html#standby-backup).
I don't think we can manually set all these `pgX-host` configs in the Custom Resource as they will change whenever patroni performs a failover.
I think it is the responsibility of PGO to set these properly according to the state of Patroni.

## Desired Behavior

I'd expect something like the following spec

```yaml
apiVersion: postgres-operator.crunchydata.com/v1beta1
kind: PostgresCluster
metadata:
  name: hippo
  namespace: hippo
spec:
  backups:
    pgbackrest:
      backupFromStandby: true # <== new key
      repos:
        - azure:
            container: hippo
          name: repo1
```

## Environment

- Platform: AKS
- Platform Version: 1.27.3
- PGO Image Tag: ubi8-5.5.0-0
- Postgres Version: 14
- Storage: Azure Storage Account

**Comment by benjaminjb** [comment]
Hmmm, out of curiosity, what do you see when you add the `backup-standby` config to the pgbackrest settings and kick-off a manual backup?

```
  backups:
    pgbackrest:
      global:
        backup-standby: y
      manual:
        repoName: repo1
        options:
         - --type=full
         - --log-level-console=detail
```

(I added the `log-level-console` option just to get more details from a backup.)
