### ISSUE TITLE
Repo host using what seems like much more storage than it should be given db size

### ISSUE THREAD

**Issue by danfinn** [CrunchyData/postgres-operator#3814]
Ideally I'd just turn off backups for this particular situation but from what I've read that is not an option yet.  I've got a pgsql instance that is deployed by PGO and it's relatively small, the DB is only using around 900 MB.  Our repo host continues to require more and more space, it's currently at 44 GB and growing!

Most of the space is used by the /pgbackrest/repo1/archive/db directory.  I have configured this instance to only keep 1 full backup and it does appear to be respecting that.  How can I control the amount of archives that are being kept or taken?

Here is the yaml for my instance:

```
apiVersion: v1
items:
- apiVersion: postgres-operator.crunchydata.com/v1beta1
  kind: PostgresCluster
  metadata:
    creationTimestamp: "2023-12-11T19:34:07Z"
    finalizers:
    - postgres-operator.crunchydata.com/finalizer
    generation: 2
    name: grafanapgsql
    namespace: grafana
  spec:
    backups:
      pgbackrest:
        global:
          repo1-retention-full: "1"
          repo1-retention-full-type: count
        image: registry.developers.crunchydata.com/crunchydata/crunchy-pgbackrest:ubi8-2.47-1
        jobs:
          affinity:
            nodeAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
                nodeSelectorTerms:
                - matchExpressions:
                  - key: kubernetes.io/os
                    operator: In
                    values:
                    - linux
        repoHost:
          affinity:
            nodeAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
                nodeSelectorTerms:
                - matchExpressions:
                  - key: kubernetes.io/os
                    operator: In
                    values:
                    - linux
        repos:
        - name: repo1
          volume:
            volumeClaimSpec:
              accessModes:
              - ReadWriteOnce
              resources:
                requests:
                  storage: 80Gi
    image: registry.developers.crunchydata.com/crunchydata/crunchy-postgres:ubi8-15.4-1
    instances:
    - affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/os
                operator: In
                values:
                - linux
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - podAffinityTerm:
              labelSelector:
                matchLabels:
                  postgres-operator.crunchydata.com/cluster: grafanapgsql
                  postgres-operator.crunchydata.com/instance-set: instance1
              topologyKey: kubernetes.io/hostname
            weight: 1
      dataVolumeClaimSpec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 20Gi
      name: instance1
      replicas: 2
    openshift: false
    port: 5432
    postgresVersion: 15
    users:
    - databases:
      - grafanapgsql
      name: grafanapgsql
      options: SUPERUSER
      password:
        type: AlphaNumeric
```
