### ISSUE TITLE
Incorrect regular expression in CRDs for spec.userInterface.pgAdmin.dataVolumeClaimSpec.resources.requests.storageClassName

### ISSUE THREAD

**Issue by maudrid** [CrunchyData/postgres-operator#3819]
## Overview

Specifying a storage class name for pgAdmin in a cluster definition causes an error. 
The CRD does not allow valid storage class names but instead requires string like "100Mi", "1Gi", etc. as is used for storage size.

## Environment

Using Minikube 1.31.2 (not relevant)
PGO CRDs from version:
```
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.8.0
  creationTimestamp: null
  labels:
    app.kubernetes.io/name: pgo
    app.kubernetes.io/version: 5.5.0
  name: postgresclusters.postgres-operator.crunchydata.com
  ```

### REPRO

Provide steps to get to the error condition:

1. Run Create the following yaml file:
```
apiVersion: postgres-operator.crunchydata.com/v1beta1
kind: PostgresCluster
metadata:
  name: mypostgres
spec:
  postgresVersion: 14
  instances:
    - name: "instance1"
      replicas: 1
      dataVolumeClaimSpec:
        accessModes:
        - "ReadWriteOnce"
        resources:
          requests:
            storage: "1Gi"
  backups:
    pgbackrest:
      repos:
      - name: repo1
        volume:
          volumeClaimSpec:
            accessModes:
            - "ReadWriteOnce"
            resources:
              requests:
                storage: "1Gi"
  userInterface:
    pgAdmin:
      dataVolumeClaimSpec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: "100Mi"
            storageClassName: "standard-minikube"
```
2. Use `kubectl apply -f` to try and apply the manifest.

### EXPECTED

1. Manifest is applied to the Kubernetes cluster

### ACTUAL

1. An error is displayed:
```
The PostgresCluster "mypostgres" is invalid: spec.userInterface.pgAdmin.dataVolumeClaimSpec.resources.requests.storageClassName: Invalid value: "standard-minikube": spec.userInterface.pgAdmin.dataVolumeClaimSpec.resources.requests.storageClassName in body should match '^(\+|-)?(([0-9]+(\.[0-9]*)?)|(\.[0-9]+))(([KMGTPE]i)|[numkMGTPE]|([eE](\+|-)?(([0-9]+(\.[0-9]*)?)|(\.[0-9]+))))?$'
```

**Comment by dsessler7** [comment]
Hey @maudrid,

You're getting that error because your spec isn't formatted correctly. The `storageClassName` is a property on `dataVolumeClaimSpec`, not `dataVolumeClaimSpec.resources.requests`. So your yaml should look like this:

```yaml
  userInterface:
    pgAdmin:
      dataVolumeClaimSpec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: "100Mi"
        storageClassName: "standard-minikube"
```
