### ISSUE TITLE
pgo create cluster not able to create cluster on Kubernetes on AWS

### ISSUE THREAD

**Issue by chandresh-pancholi** [CrunchyData/postgres-operator#382]
**I'm submitting a ...**

 
 - [ x] bug report
 - [ ] feature request
 - [x ] support request

**Do you want to request a *feature* or report a *bug*?**

Bug

**What is the current behavior?**

We are running Crunchydata postgres operator on KUbernetes 1.10 on AWS. PVCs are not getting attached to cluster pod. Postgres cluster pod is in "Pending" stage.

**If the current behavior is a bug, please provide the steps to reproduce:**
Kubernetes 1.10
AWS
Crunchydata 3.2.0
PVC storage class postgres-demo

**What is the expected behavior?**

pgo create cluster should create postgres cluster.

**What is the motivation or use case for changing the behavior?**

**Other information** (e.g. detailed explanation, related issues, suggestions how to fix, etc)

**Please tell us about your environment:**

 - Operating System:
 - Container Image Tag:
 - Operator Version:
 - PostgreSQL Version:
 - Platform (Docker, Kubernetes, OpenShift):
 - Platform Version:

**Comment by jmccormick2001** [comment]
are you specifying FsGroup: 26 in your pgo.yaml file?

**Comment by chandresh-pancholi** [comment]
Yes,
```
Cluster:
  CCPImagePrefix:  crunchydata
  Metrics:  true
  Badger:  true
  CCPImageTag:  centos7-10.5-2.1.0
  Port:  5432
  User:  carto
  Database:  cartodb
  PasswordAgeDays:  60
  PasswordLength:  8
  Strategy:  1
  Replicas:  0
  ArchiveMode:  true
  ArchiveTimeout:  60
  ServiceType:  ClusterIP
  Backrest:  true
  Autofail:  true
PrimaryStorage: storage1
BackupStorage: storage1
ReplicaStorage: storage1
Storage:
  storage1:
    AccessMode:  ReadWriteOnce
    Size:  10Gi
    StorageType:  dynamic
    StorageClass:  postgres-demo
    Fsgroup:  26
  storage2:
    AccessMode:  ReadWriteOnce
    Size:  50Gi
    StorageType:  dynamic
    StorageClass:  postgres-medium
    Fsgroup:  26
  storage3:
    AccessMode:  ReadWriteOnce
    Size:  100Gi
    StorageType:  dynamic
    StorageClass:  postgres-large
    Fsgroup:  26
DefaultContainerResource:
ContainerResources:
  small:
    RequestsMemory:  512Mi
    RequestsCPU:  0.1
    LimitsMemory:  512Mi
    LimitsCPU:  0.1
  large:
    RequestsMemory:  2Gi
    RequestsCPU:  2.0
    LimitsMemory:  2Gi
    LimitsCPU:  4.0
Pgo:
  AutofailSleepSeconds:  9
  Audit:  true
  LSPVCTemplate:  /config/pgo.lspvc-template.json
  LoadTemplate:  /config/pgo.load-template.json
  COImagePrefix:  crunchydata
  COImageTag:  centos7-3.2.0

```
**Command to create PG cluster**

> pgo create cluster testcluster --metrics --pgpool --autofail --pgbadger --pgbackrest --custom-config=pgo-pgbackrest-config
