### ISSUE TITLE
Documentation Bug - Missing Key

### ISSUE THREAD

**Issue by mzwettler2** [CrunchyData/postgres-operator#3871]
[Docs](https://access.crunchydata.com/documentation/postgres-operator/latest/tutorials/backups-disaster-recovery/disaster-recovery#perform-an-in-place-point-in-time-recovery-pitr) are talking about **_spec.backups.pgbackrest.restore.enabled_** ==>
```
spec:
  backups:
    pgbackrest:
      restore:
        enabled: false
```
But there is nothing in the [CRD Reference](https://access.crunchydata.com/documentation/postgres-operator/latest/references/crd/5.5.x/postgrescluster#postgresclusterspecbackupspgbackrestrestore) about it.

Seems to be a small documentation bug.
