### ISSUE TITLE
Default requests/limits for containers in PostgresCluster CR

### ISSUE THREAD

**Issue by jeremych1000** [CrunchyData/postgres-operator#3898]
Hello! I want to ask if there is a way to specify requests and limits by default for all containers. I'm struggling to define all resources/limits in my `postgrescluster` CR.

**We have Kyverno blocking any pods/containers that do not have requests/limits defined. This is a hard requirement and includes all containers incl. init containers from pods, jobs, etc.**

Searching `.resources` on https://access.crunchydata.com/documentation/postgres-operator/latest/references/crd/5.5.x/postgrescluster gives me 42 results - there is no way I define 42 requests/limits in my CR!!!

I've added requests/limits to the following already:
- `postgrescluster.spec.instances[index].resources`
- `postgrescluster.spec.backups.pgbackrest.jobs.resources`
- `postgrescluster.spec.backups.pgbackrest.repoHost.resources`
- `postgrescluster.spec.backups.pgbackrest.restore.resources`
- `postgrescluster.spec.proxy.pgBouncer.resources`

However in ArgoCD the pods still refuse to come up. If I look at the stateful set there are 4 containers!

Where are these defined in the CR? I don't define every single container in my `postgrescluster.spec.instances`, so I assume they must be generated - why don't they take the resources definition from the parent?

Container 1 - `database` - this has requests defined
Container 2 - `replication-cert-copy` - BLANK requests
Container 3 - `pgbackrest` - BLANK requests
Container 4 - `pgbackrest-config` - BLANK requests

Init container 1 - `postgres-startup` - this has requests defined
Init container 2 - `nss-wrapper-init` - this has requests defined

### Environment

Please provide the following details:

- Platform: `Kubernetes`
- Platform Version: `v1.28.6`
- PGO Image Tag: `crunchy-postgres:ubi8-16.2-0`, `crunchy-pgbackrest:ubi8-2.49-0`
- Postgres Version: `16`

## Redacted CR
```
apiVersion: postgres-operator.crunchydata.com/v1beta1
kind: PostgresCluster
metadata:
  name: `<redacted>`
spec:
  postgresVersion: 16
  instances:
    - name: `<redacted>`
      replicas: {{ .Values.postgres.replicas }}
      resources:
        {{- toYaml .Values.postgres.resources | nindent 8 }}
<...>
 
  backups:
    pgbackrest:
      jobs:
        resources:
          {{- toYaml .Values.postgres.backups.resources | nindent 10 }}
      repoHost:
        resources:
          {{- toYaml .Values.postgres.backups.resources | nindent 10 }}
      restore:
        enabled: false # change to true when enabling restores
        repoName: repo1 # references the pgbackrest repo defined below
        resources:
          {{- toYaml .Values.postgres.backups.resources | nindent 10 }}
      repos:
      - name: repo1
        volume:
          volumeClaimSpec:
            {{- .Values.postgres.backups.volumeClaimSpec | toYaml | nindent 12 }}

  proxy:
    pgBouncer:
      replicas: {{ .Values.postgres.proxy.replicas }}
      resources:
        {{- toYaml .Values.postgres.proxy.resources | nindent 8 }}
<...>
```

**Comment by Mahidhar-K** [comment]
I'm also looking for this information, but it seems to be missing from the crunchy documentation. 
Could someone shed some light on the defaults that can be assigned to all containers, including main containers, sidecars, and init containers? 
I'm curious about the reasons behind having multiple containers and which ones are mandatory, especially when it comes to sidecars. 
I'd like to hear about the advantages and disadvantages of using sidecars versus not using them.

- pgo 
- pgo upgrade   
- database
- replication-cert-copy
- pgbackrest-config
- pgbackrest
- pg-backup-repo-host 
- exporter
- Init container 1 - postgres-startup 
- Init container 2 - nss-wrapper-init 

Lastly,  pgo upgrade  pod is not seen in the pgo 5.5 manifest files? is this expected?

**Comment by jeremych1000** [comment]
Ok I've fixed it. Was missing the sidecar resources. Will leave this open for now so that @Mahidhar-K 's question can be answered as I'm interested in it as well.

```
in instances:
      sidecars:
        replicaCertCopy:
          resources:
            requests:
              cpu: 50m
              memory: 10Mi
            limits:
              memory: 30Mi

in backups:
      sidecars:
        pgbackrestConfig:
          resources:
            requests:
              cpu: 50m
              memory: 10Mi
            limits:
              memory: 50Mi
        pgbackrest:
          resources:
            {{- toYaml .Values.postgres.backups.resources | nindent 12 }}
```
