### ISSUE TITLE
Pgadmin URL is not working post adding userInterface in the PGO CRD.

### ISSUE THREAD

**Issue by syerram123** [CrunchyData/postgres-operator#3912]
Environment

- Platform: Openshift V4.10.62
- Platform Version: 1.23
- PGO Image Tag:  Postgres Operator V5.2.0
- PGadmin Image Tag: registry.connect.redhat.com/crunchydata/crunchy-pgadmin4@sha256:0666d86fc8b208df9d670b13e0c87523357d03f116b40a4282d579014709a83a
- Postgres Version : 13
Here is the pgadmin configuration added to the PGO CRD spec.

```
userInterface:
    pgAdmin:
      dataVolumeClaimSpec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
        storageClassName: ocs-storagecluster-ceph-rbd
      image: >-
        registry.connect.redhat.com/crunchydata/crunchy-pgadmin4@sha256:0666d86fc8b208df9d670b13e0c87523357d03f116b40a4282d579014709a83a
      replicas: 1
      resources:
        limits:
          cpu: 200m
          memory: 512Mi
        requests:
          cpu: 200m
          memory: 512Mi
```

I am getting below internal server error when I do curl from pgadmin pod terminal pod.

```
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>500 Internal Server Error</title>
</head><body>
<h1>Internal Server Error</h1>
<p>The server encountered an internal error or
misconfiguration and was unable to complete
your request.</p>
<p>Please contact the server administrator at 
 root@localhost to inform them of the time this error occurred,
 and the actions you performed just before this error.</p>
<p>More information about this error may be available
in the server error log.</p>
</body></html>
```
I have checked the pgadmin logs and here it is for reference.
```
[Fri May 10 04:17:19.994950 2024] [core:warn] [pid 18:tid 140286570278336] AH00098: pid file /etc/httpd/run/httpd.pid overwritten -- Unclean shutdown of previous Apache run?
[Fri May 10 04:17:20.000995 2024] [mpm_event:notice] [pid 18:tid 140286570278336] AH00489: Apache/2.4.37 (Red Hat Enterprise Linux) OpenSSL/1.1.1k mod_wsgi/4.6.4 Python/3.6 configured -- resuming normal operations
[Fri May 10 04:17:20.001092 2024] [core:notice] [pid 18:tid 140286570278336] AH00094: Command line: '/usr/sbin/httpd -D FOREGROUND'
[Fri May 10 04:30:56.196828 2024] [wsgi:error] [pid 20:tid 140286268610304] WARNING: Failed to set ACL on the directory containing the configuration database:
[Fri May 10 04:30:56.196905 2024] [wsgi:error] [pid 20:tid 140286268610304]            [Errno 1] Operation not permitted: '/var/lib/pgadmin'
[Fri May 10 04:30:56.196916 2024] [wsgi:error] [pid 20:tid 140286268610304] 
[Fri May 10 04:30:56.196988 2024] [wsgi:error] [pid 20:tid 140286268610304] HINT   : You may need to manually set the permissions on
[Fri May 10 04:30:56.196995 2024] [wsgi:error] [pid 20:tid 140286268610304]          /var/lib/pgadmin to allow pgadmin to write to it.
[Fri May 10 04:30:56.197001 2024] [wsgi:error] [pid 20:tid 140286268610304] 
[Fri May 10 04:30:56.391776 2024] [wsgi:error] [pid 20:tid 140286268610304] [remote ::1:33062] mod_wsgi (pid=20): Failed to exec Python script file '/usr/lib/python3.6/site-packages/pgadmin4-web/pgAdmin4.wsgi'.
[Fri May 10 04:30:56.391825 2024] [wsgi:error] [pid 20:tid 140286268610304] [remote ::1:33062] mod_wsgi (pid=20): Exception occurred processing WSGI script '/usr/lib/python3.6/site-packages/pgadmin4-web/pgAdmin4.wsgi'.
[Fri May 10 04:30:56.392338 2024] [wsgi:error] [pid 20:tid 140286268610304] [remote ::1:33062] Traceback (most recent call last):
[Fri May 10 04:30:56.392371 2024] [wsgi:error] [pid 20:tid 140286268610304] [remote ::1:33062]   File "/usr/lib/python3.6/site-packages/pgadmin4-web/pgAdmin4.wsgi", line 36, in <module>
[Fri May 10 04:30:56.392375 2024] [wsgi:error] [pid 20:tid 140286268610304] [remote ::1:33062]     from pgAdmin4 import app as application
[Fri May 10 04:30:56.392381 2024] [wsgi:error] [pid 20:tid 140286268610304] [remote ::1:33062]   File "/usr/lib/python3.6/site-packages/pgadmin4-web/pgAdmin4.py", line 94, in <module>
[Fri May 10 04:30:56.392384 2024] [wsgi:error] [pid 20:tid 140286268610304] [remote ::1:33062]     app = create_app()
[Fri May 10 04:30:56.392388 2024] [wsgi:error] [pid 20:tid 140286268610304] [remote ::1:33062]   File "/usr/lib/python3.6/site-packages/pgadmin4-web/pgadmin/__init__.py", line 347, in create_app
[Fri May 10 04:30:56.392392 2024] [wsgi:error] [pid 20:tid 140286268610304] [remote ::1:33062]     if not os.path.exists(SQLITE_PATH) or get_version() == -1:
[Fri May 10 04:30:56.392396 2024] [wsgi:error] [pid 20:tid 140286268610304] [remote ::1:33062]   File "/usr/lib/python3.6/site-packages/pgadmin4-web/pgadmin/setup/db_version.py", line 19, in get_version
[Fri May 10 04:30:56.392400 2024] [wsgi:error] [pid 20:tid 140286268610304] [remote ::1:33062]     return version.value
[Fri May 10 04:30:56.392415 2024] [wsgi:error] [pid 20:tid 140286268610304] [remote ::1:33062] AttributeError: 'NoneType' object has no attribute 'value'
```

The DB pods are running fine and able to connect to the database as well. I am not sure what I am missing here. 

could you please help me.
