### ISSUE TITLE
Not able to set the container securityContext

### ISSUE THREAD

**Issue by andreasgeisslerdt** [CrunchyData/postgres-operator#3964]
## Overview

I would like to update the container securityContext of the pgBouncer.
According to the CRD (https://access.crunchydata.com/documentation/postgres-operator/latest/references/crd/5.5.x/postgrescluster#postgresclusterspecproxypgbouncercontainersindex) I set it like:

```
---
apiVersion: postgres-operator.crunchydata.com/v1beta1
kind: PostgresCluster
...
spec:
  proxy:
    pgBouncer:
    ...
      containers:
        - name: pgbouncer
          securityContext:
            capabilities:
              drop:
                - ALL
                - CAP_NET_RAW
        - name: pgbouncer-config
          securityContext:
            capabilities:
              drop:
                - ALL
                - CAP_NET_RAW
```

but the pgbouncer pods are not changed.

## Environment

Please provide the following details:

- Platform: (`Kubernetes`)
- Platform Version: (`1.29.1`)
- PGO Image Tag: (`ubi8-5.5.0-0`)
- Postgres Version (`16`)
- Storage: (e.g. `hostpath`, `nfs`, or the name of your storage class)

### REPRO

Provide steps to get to the error condition:

1. Set the container settings above
2. Check pgbouncer pod

### EXPECTED

1. SecurityPolicies are updated

### ACTUAL

1. SecurityContext is not changed

```
...
  containers:
    - name: pgbouncer
      ...
      securityContext:
        capabilities:
          drop:
            - ALL
        privileged: false
        runAsNonRoot: true
        readOnlyRootFilesystem: true
        allowPrivilegeEscalation: false

```
