### ISSUE TITLE
Question/Support for automatic creation of user schemas

### ISSUE THREAD

**Issue by ffppmm** [CrunchyData/postgres-operator#3986]
Hi,

I try to get the automatic creation of user schemas working, but somehow it doesn't work :( I followed these articels/docs:
* [Automatically Creating Per-User Schemas](https://access.crunchydata.com/documentation/postgres-operator/latest/tutorials/basic-setup/user-management#automatically-creating-per-user-schemas)
* https://www.crunchydata.com/blog/be-ready-public-schema-changes-in-postgres-15

Steps to reproduce:
* Using the Crunchy Operater Community version (5.6.1 provided by Crunchy Data) of the openshift Marketplace
* apply PostgresCluster yaml with annotation
```yaml
apiVersion: postgres-operator.crunchydata.com/v1beta1
kind: PostgresCluster
metadata:
  name: hippo
  namespace: ops-playground
  annotations:
    postgres-operator.crunchydata.com/autoCreateUserSchema: "true"
spec:
  users:
    - name: someone
      databases: [someone]
  backups:
    pgbackrest:
      global:
        repo1-retention-full: '14'
        repo1-retention-full-type: time
      repos:
        - name: repo1
          volume:
            volumeClaimSpec:
              accessModes:
                - ReadWriteOnce
              resources:
                requests:
                  storage: 10Gi
  instances:
    - dataVolumeClaimSpec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
      name: instance1
      replicas: 1
      resources:
        limits:
          cpu: 1000m
          memory: 2Gi
  monitoring:
    pgmonitor:
      exporter:
        image: 'registry.developers.crunchydata.com/crunchydata/crunchy-postgres-exporter:ubi8-0.15.0-7'
  openshift: true
  port: 5432
  postgresVersion: 15
```
* Wait for cluster
* connect to cluster with User someone 
* create table fails with:
```
someone=> CREATE TABLE my_test_data (id integer);

ERROR:  permission denied for schema public
LINE 1: CREATE TABLE my_test_data (id integer);
```
* If I create the shema in someone with:
```sql
someone=# CREATE SCHEMA someone AUTHORIZATION someone;
CREATE SCHEMA
```
* Everything works fine
```sql
someone=> CREATE TABLE my_test_data (id integer);
CREATE TABLE
```
Any help, am I missing something or is the annotation "wrong"? Please Help,

Regards Philipp
### Environment

Please provide the following details:

- Platform: OpenShift
- Platform Version: 4.14
- PGO Image Tag: ubi8-5.6.1-0
- Postgres Version: 15
- Storage: ceph PV

**Comment by andrewlecuyer** [comment]
Hi @ffppmm!  Just to confirm ... did you enable the `AutoCreateUserSchema` feature gate in your operator Deployment, as described here?

https://access.crunchydata.com/documentation/postgres-operator/latest/tutorials/basic-setup/user-management#how-can-i-enable-this-feature-for-my-cluster

Also, once connected via `psql`, you should be able to confirm the schema has been created by running `/dn`:

```bash
someone=> \dn
        List of schemas
   Name    |       Owner       
-----------+-------------------
 pgbouncer | postgres
 public    | pg_database_owner
 someone   | someone
(3 rows)
```

Do you see the `someone` schema when you run this command?  I did just do a quick test myself, and per the above output everything does appear to be working normally.

**Comment by ffppmm** [comment]
Hi,

I found the spot, it was in the ClusterServiceVersion, there you can define env variables. Wouldn't it be nice to have this feature enabled by default and let everybody use it with the annotation? Are there any security concerns about enabling it by default?

regards Philipp

**Comment by rubiktubik** [comment]
How can enable `AutoCreateUserSchema` when using helm?

**Comment by ffppmm** [comment]
Hi,

if you are using the examples you have to modify the template, haven't seen any parameter from the values.yaml that provides this functionality:
https://github.com/CrunchyData/postgres-operator-examples/blob/main/helm/install/templates/manager.yaml#L27C1-L27C9
```yaml
        - name: PGO_FEATURE_GATES
          value: AutoCreateUserSchema=true
```
please check the indentation!

After that you have to annotate the PostgresCluster:
```yaml
metadata:
  annotations:
    postgres-operator.crunchydata.com/autoCreateUserSchema: 'true'
```

This is from the Doku:
https://access.crunchydata.com/documentation/postgres-operator/latest/tutorials/basic-setup/user-management#how-can-i-enable-this-feature-for-my-cluster

Regards Philipp
