### ISSUE TITLE
Install postgres-operator via infrastructure as code via flux

### ISSUE THREAD

**Issue by totycro** [CrunchyData/postgres-operator#4067]
## Overview

I would like to be able to install postgres-operator via the [flux helm operator]( https://fluxcd.io/flux/components/source/helmrepositories/).

It supports oci repositories as helm chart source, but there seems to be some incompatibility because the helm operator 

## Use Case

An infrastructure as code approach such as flux can help a lot when managing multiple clusters, so it would be great if it's possible to install postgres-operator this way.

## Desired Behavior

The crunchydata oci repository should support being queried by flux via a declaration like this:

```
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: crunchydata
  namespace: default
spec:
  type: "oci"
  interval: 5m0s
  url: oci://registry.developers.crunchydata.com/crunchydata
  ```
  
  Unfortunately I cannot provide you with an error message, the flux reconciliation just shows the generic kubernetes error: `Wait returned an error: context deadline exceeded`

## Environment

Tell us about your environment:

Please provide the following details:

- Platform: Kubernetes (AWS and OTC)
- Platform Version: 1.28
- PGO Chart: Tag:  5.7
- Postgres Version (e.g. `15`): unknown, the installation doesn't proceed
- Storage: (e.g. `hostpath`, `nfs`, or the name of your storage class)
- Number of Postgres clusters: (`XYZ`)

**Comment by totycro** [comment]
Sorry, it seems that it's now working by using the OCIRepository CRD by flux, so the OCI registry is probably fine.

**Comment by totycro** [comment]
In case anybody finds this, this is the flux configuration i ended up using:

```yaml
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: OCIRepository
metadata:
  name: pgo
  namespace: default
spec:
  interval: 10m
  url: oci://registry.developers.crunchydata.com/crunchydata/pgo
  ref:
    tag: 5.7.0
```

```yaml
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: pgo
  namespace: default
spec:
  interval: 10m
  releaseName: pgo
  chartRef:
    kind: OCIRepository
    name: pgo
    namespace: default
  values:
    disable_check_for_upgrades: true
```
Maybe it's necessary to specify a fixed version in the helm repo source in order for this to work.
