### ISSUE TITLE
`repo1-s3-key-secret`, when present, appears to prevent DB user creation

### ISSUE THREAD

**Issue by cawilliams97** [CrunchyData/postgres-operator#4074]
Not sure whether I've found a bug or I'm just doing something wrong. I'm trying to set up, via YAML, a `PostgresCluster` that backs up to MinIO. However, whenever I inject `repo1-s3-key-secret` into the pgbackrest config, the DB user `sedaro-admin` fails to get created - no matter what the value of `repo1-s3-key-secret` is. And as expected, when I don't inject this key, backups cannot proceed because the stanza cannot be created and, obviously, pgbackrest cannot connect to MinIO.

## Environment

Please provide the following details:

- Platform: Kubernetes
- Platform Version: 1.31.0
- PGO Image Tag: (e.g. `ubi8-5.x.y-0`) `registry.developers.crunchydata.com/crunchydata/postgres-operator:ubi8-5.7.2-0`
- Postgres Version (e.g. `15`) 15
- Storage: (e.g. `hostpath`, `nfs`, or the name of your storage class) local PersistentVolume for the DB; MinIO for the backups

## PostgresCluster Configuration

```
apiVersion: postgres-operator.crunchydata.com/v1beta1
kind: PostgresCluster
metadata:
  name: primary-cluster
  namespace: sedaro-postgres
  labels:
    clusterName: primary-cluster
  annotations:
    postgres-operator.crunchydata.com/init-sql-config: init-sql
spec:
  postgresVersion: 15
  instances:
    - name: "main-instance"
      replicas: 3
      dataVolumeClaimSpec:
        accessModes:
        - "ReadWriteOnce"
        resources:
          requests:
            storage: "1Gi"
        selector:
          matchLabels:
            clusterName: primary-cluster
      metadata:
        labels:
          clusterName: primary-cluster
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 1
            podAffinityTerm:
              topologyKey: kubernetes.io/hostname
              labelSelector:
                matchLabels:
                  postgres-operator.crunchydata.com/cluster: primary-cluster
                  postgres-operator.crunchydata.com/instance-set: main-instance
      metadata:
        labels:
          clusterName: primary-cluster
  users:
    - name: sedaro-admin
      databases:
        - sedaro-satellite-db
        - sedaro_authdb
      options: "SUPERUSER, CREATEDB"
  backups:
    pgbackrest:
      global:
        repo1-s3-uri-style: path
        repo1-path: /backups
        repo1-host-config-include-path: /conf/pgbackrest/conf.d
        repo1-s3-key: <REDACTED>
        repo1-s3-key-secret: <REDACTED> ####### MARKED LINE
      repos:
      - name: repo1
        schedules:
          full: " */2 * * * * " # for testing - for real use: "0 0 * * 0" # weekly
          incremental: "1-59/2 * * * *" # for testing - for real use: "0 */6 * * *" # every 6 hours
        s3: # actually MinIO
          bucket: sedaro-backups
          endpoint: minio-service.sedaro:9000
          region: us-east-1 # value doesn't actually matter
  patroni:
    dynamicConfiguration:
      synchronous_mode: true
      synchronous_mode_strict: true
      postgresql:
        pg_hba:
        - host all all all md5
        parameters:
          log_destination: 'stderr'
          log_statement: 'all'
          log_min_duration_statement: 0
          synchronous_commit: 'on'
  databaseInitSQL:
    name: init-sql
    key: init.sql
```

In case it's relevant, the user is given a specific password via a Secret:

```
apiVersion: v1
kind: Secret
metadata:
  name: primary-cluster-pguser-sedaro-admin
  namespace: sedaro-postgres
  labels:
    postgres-operator.crunchydata.com/cluster: primary-cluster
    postgres-operator.crunchydata.com/pguser: sedaro-admin
stringData:
  password: <REDACTED>
```

NB: I'm aware that the preferred way to inject the `key` and `key-secret` is via a Secret rather than inline. I was just trying to get this to work at all, so I see that as outside the scope of the immediate issue.

## The Problem

When I comment out the "MARKED LINE" above, I get the following:

### DB User Creation (good)

```
(main-env) ➜  sedaro-app git:(crunchy-pgo) ✗ kubectl exec -it $(kubectl get pods -n sedaro-postgres --selector=postgres-operator.crunchydata.com/role=master | grep -v "NAME" |  awk '{ print $1 }') -n sedaro-postgres -- psql postgres -c "SELECT *  FROM pg_user";
Defaulted container "database" out of: database, replication-cert-copy, pgbackrest, pgbackrest-config, postgres-startup (init), nss-wrapper-init (init)
   usename    | usesysid | usecreatedb | usesuper | userepl | usebypassrls |  passwd  | valuntil | useconfig 
--------------+----------+-------------+----------+---------+--------------+----------+----------+-----------
 postgres     |       10 | t           | t        | t       | t            | ******** |          | 
 _crunchyrepl |    16384 | f           | f        | t       | f            | ******** |          | 
 sedaro-admin |    16413 | f           | f        | f       | f            | ******** |          | 
(3 rows)
```

### Stanza creation (failed)

```
(main-env) ➜  sedaro-app git:(crunchy-pgo) ✗ kubectl logs -n sedaro-postgres $(kubectl get pods -n sedaro-postgres | grep operator | awk '{ print $1 }') | grep -i stanza | tail -2
time="2025-01-22T00:23:07Z" level=error msg="unable to create stanza" PostgresCluster=sedaro-postgres/primary-cluster controller=postgrescluster controllerGroup=postgres-operator.crunchydata.com controllerKind=PostgresCluster error="command terminated with exit code 37: " file="internal/controller/postgrescluster/pgbackrest.go:2698" func="postgrescluster.(*Reconciler).reconcileStanzaCreate" name=primary-cluster namespace=sedaro-postgres reconcileID=8ea45604-2e29-4641-88d7-c238bd9a373a reconciler=pgBackRest version=5.7.2-0
time="2025-01-22T00:23:07Z" level=debug msg="command terminated with exit code 37: " object="{PostgresCluster sedaro-postgres primary-cluster 7267f10f-3b11-48f7-aa16-e1ae5a961f0e postgres-operator.crunchydata.com/v1beta1 876059 }" reason=UnableToCreateStanzas type=Warning version=5.7.2-0
```

When I uncomment out the "MARKED LINE", I instead get:

### DB User Creation (failure)

```
(main-env) ➜  sedaro-app git:(crunchy-pgo) ✗ kubectl exec -it $(kubectl get pods -n sedaro-postgres --selector=postgres-operator.crunchydata.com/role=master | grep -v "NAME" |  awk '{ print $1 }') -n sedaro-postgres -- psql postgres -c "SELECT *  FROM pg_user";
Defaulted container "database" out of: database, replication-cert-copy, pgbackrest, pgbackrest-config, postgres-startup (init), nss-wrapper-init (init)
   usename    | usesysid | usecreatedb | usesuper | userepl | usebypassrls |  passwd  | valuntil | useconfig 
--------------+----------+-------------+----------+---------+--------------+----------+----------+-----------
 postgres     |       10 | t           | t        | t       | t            | ******** |          | 
 _crunchyrepl |    16384 | f           | f        | t       | f            | ******** |          | 
(2 rows)
```

### Stanza creation (success - as indicated by lack of error logs)
```
(main-env) ➜  sedaro-app git:(crunchy-pgo) ✗ kubectl logs -n sedaro-postgres $(kubectl get pods -n sedaro-postgres | grep operator | awk '{ print $1 }') | grep -i stanza | tail -2
(main-env) ➜  sedaro-app git:(crunchy-pgo) ✗ 
```

I can't imagine that a complete inability to use MinIO with PGO would have gone undetected, so I suspect this is most user error on my end rather than a bug. Assuming this is the case, what am I doing wrong and how do I fix it?
