### ISSUE TITLE
PGAdmin returns a loading screen

### ISSUE THREAD

**Issue by srmklive** [CrunchyData/postgres-operator#4132]
Hi everyone,

I am facing an issue where pgadmin is not working. I have setup everything according to the docs. 

## Overview

I am utlizing terraform to provision the postgres cluster. The cluster is working, and i have connected it to various applications. The problem is with pgadmin. I have setup an ingress on the domain (e.g manager.example.com), i am able to see the login screen, but after i login with the credentials for pgadmin, i get the loading screen.

## Environment

- Platform: GKE
- Platform Version: 1.31
- PGO Image Tag: ubi8.5
- Postgres Version: 17
- Storage: PVC

### pgadmin manifest
```
apiVersion: postgres-operator.crunchydata.com/v1beta1
kind: PGAdmin
metadata:
  name: ${NAME}
  namespace: ${NAMESPACE}
spec:
  users:
  - username: ${PGADMIN_USER}
    role: Administrator
    passwordRef:
      name: ${CLUSTER_NAME}-pguser-${USER}
      key: password
  serviceName: ${NAME}
  dataVolumeClaimSpec:
    accessModes:
    - "ReadWriteOnce"
    resources:
      requests:
        storage: ${DISK_SIZE}Gi
  serverGroups:
    - name: supply
      postgresClusterSelector: {}
  config:
    settings:
      AUTHENTICATION_SOURCES: ['internal']

```
The values being passed are:

$NAME: pgadmin
$NAMESPACE: database
$PGADMIN_USER: sc@example.com
$CLUSTER_NAME: database-cluster
$USER: sc
$DISK_SIZE: 10

## Steps to Reproduce

I am using terraform to provision the infra, and i am utilizing the kubectl_manifest to deploy the manifests. The deployment is successful every time changes are deployed: 

## Logs

Following is the attached screenshot of the logs for the pgadmin pod inside GKE:

<img width="1728" alt="Image" src="https://github.com/user-attachments/assets/defd0d0c-109f-4d89-b6d9-edf4b79b9a72" />

I really hope you guys can help me figure out this issue.
