### ISSUE TITLE
I think the SecurityContext for pgdata-move-job pods is too strict and breaks migrations

### ISSUE THREAD

**Issue by seano-vs** [CrunchyData/postgres-operator#4133]
## Overview

TL;DR: When [migrating cluster data files in order to boostrap a new cluster](https://access.crunchydata.com/documentation/postgres-operator/latest/guides/data-migration), the `pgdata-move-job` pod's SecurityContext settings are too strict to actually perform the tasks in the migration list. 

Note: I reference the custom image `cdpgvecto.rs` but have confirmed the behavior to its vanilla counterpart, `crunchy-postgres:ubi8-16.8-0`

## Environment

Please provide the following details:

- Platform: (`Kubernetes`)
- Platform Version: `k3s version v1.31.6+k3s1 (6ab750f9)`, `go version go1.22.12`
- PGO Image Tag: (e.g. `ubi8-16.8-0`, `ghcr.io/chkpwd/cdpgvecto.rs:ubi8-16.4-0-v0.3.0`)
- Postgres Version (`16`)
- Storage: (`hostpath`)

### REPRO

So I botched a re-install of a cluster, and when my pgbackrest backups weren't working, the only option I had available were to try and [bootstrap a new cluster with the old files](https://access.crunchydata.com/documentation/postgres-operator/latest/guides/data-migration) from a previous k8s cluster. I've performed all the steps on the relevant docs page. 

I created a pv/pvc that contained the old pv files:

```yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: immich-persist
  namespace: immich
spec:
  storageClassName: local-path
  volumeName: immich-persist
  resources:
    requests:
      storage: 100Gi
  accessModes:
    - ReadWriteOnce

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: immich-persist
  namespace: immich
spec:
  capacity:
    storage: 100Gi
  storageClassName: local-path
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /var/lib/rancher/k3s/storage
  accessModes:
    - ReadWriteOnce
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - fridge
```

and ensured that all the files are chown-ed to uid 26. I confirm being able to mount this directory in other crunchy pods and interact with the directory just fine. I added the appropriate boostrapping details to the config:

```yaml
apiVersion: postgres-operator.crunchydata.com/v1beta1
kind: PostgresCluster
metadata:
  name: crunchy-immich
  namespace: immich
spec:
  # the below was added to bootstrap
  dataSource:
    volumes:
      pgDataVolume:
        pvcName: immich-persist
        directory: import
  image: ghcr.io/chkpwd/cdpgvecto.rs:ubi8-16.4-0-v0.3.0
  #image: registry.developers.crunchydata.com/crunchydata/crunchy-postgres:ubi8-16.8-0
  postgresVersion: 16
  # I don't think this works
  databaseInitSQL: 
    key: init.sql
    name: init-sql
  users:
    - name: postgres
    - name: immich
      databases:
        - immich
      options: "NOSUPERUSER INHERIT CREATEDB LOGIN NOREPLICATION NOBYPASSRLS"
  patroni:
    dynamicConfiguration:
      postgresql:
        synchronous_commit: "on"
        parameters:
          shared_preload_libraries: "vectors.so"
          search_path: '"$user", public, vectors'
  instances:
    - name: immich
      replicas: 1
      dataVolumeClaimSpec:
        accessModes:
        - "ReadWriteOnce"
        resources:
          requests:
            storage: 10Gi
  backups:
    pgbackrest:
      image: registry.developers.crunchydata.com/crunchydata/crunchy-pgbackrest:ubi8-2.54.1-1
      global:
        repo1-retention-full: "14"
        repo1-retention-full-type: time
      manual:
        repoName: repo1
      repos:
      - name: repo1
        schedules:
          full: "0 1 * * 0"
          differential: "0 1 * * 1-6"
        volume:
          volumeClaimSpec:
            accessModes:
            - "ReadWriteOnce"
            storageClassName: nfs
            resources:
              requests:
                storage: 10Gi
```

However, every time I reference this in the `dataSource` line of the PostgresCluster config, the pod would fail with:

```sh
Preparing cluster crunchy-immich volumes for PGO v5.x
pgdata_pvc=immich-persist
Current PG data directory volume contents:
ls: cannot open directory '/pgdata': Permission denied
```

The pod details said that the [exit code was 2](https://unix.stackexchange.com/questions/477390/ls-error-code-2), which implied something a little more suspicious than a typical permissions error.

I spun up a different pod with the same image, tried to mount it, and everything worked fine:

```yaml

apiVersion: v1
kind: Pod
metadata:
  name: mypod
  namespace: immich
spec:
  containers:
    - name: postgres
      image: ghcr.io/chkpwd/cdpgvecto.rs:ubi8-16.4-0-v0.3.0
      command: ["/bin/bash"]
      args: ["-c", "while true; do ping localhost; sleep 60;done"]
      volumeMounts:
      - mountPath: "/pgdata"
        name: mypd
  volumes:
    - name: mypd
      persistentVolumeClaim:
        claimName: immich-persist
```

HOWEVER, this is where things got tricky. When the crunchy operator creates the `pgdata-move-job` pod that performs this work, it does so with the following security context:

```yaml
      securityContext:
        runAsUser: 26
        allowPrivilegeEscalation: false
        capabilities:
          drop: 
            - ALL
        privileged: false
        readOnlyRootFilesystem: true
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
```

and when I apply this context to my test pod, is.... breaks with an error code 2. 

### EXPECTED

1. the SecurityContext ([set here](https://github.com/CrunchyData/postgres-operator/blob/e19f3fefba338ecd6672d7d6876bd0d2e366975c/internal/controller/postgrescluster/volumes.go#L520)) is relaxed to allow the [script operations](https://github.com/CrunchyData/postgres-operator/blob/e19f3fefba338ecd6672d7d6876bd0d2e366975c/internal/controller/postgrescluster/volumes.go#L479-L489) to complete.

### ACTUAL

1. it can't access the mounted pvc
