### ISSUE TITLE
CIFS Backup Repo not working since Update 5.8.0

### ISSUE THREAD

**Issue by MSandro** [CrunchyData/postgres-operator#4156]
## Overview

I've updated PGO to 5.8.0, now all my Repo-Hosts are upgrading and are not able to come up because of the pgbackrest-log-dir Init-Container.
```
chmod: changing permissions of '/pgbackrest/repo1/log': Operation not permitted
```
I've viewed the command and noticed 0775 permissions are trying to apply on /pgbackrest/repo1/log
Now I have created a new CIFS Volume with the exact permissions set to 0775, but still the same problem.

## Environment

Please provide the following details:

- Platform: Kubernetes RKE2
- Platform Version: v1.32.3
- PGO Image Tag: ubi9-5.8.0-0
- Postgres Version: 17.4
- Storage: vsphere-csi for data, and SMB / CIFS for Backups

### REPRO
1. install PGO 5.8.0
2. create a CIFS/SMB StorageClass
3. apply
```
apiVersion: postgres-operator.crunchydata.com/v1beta1
kind: PostgresCluster
metadata:
  name: test
  namespace: default
spec:
  backups:
    pgbackrest:
      global:
        repo1-retention-archive: '1'
        repo1-retention-diff: '1'
        repo1-retention-full: '1'
        repo1-type: cifs
      repos:
        - name: repo1
          schedules:
            full: 0 1 * * *
          volume:
            volumeClaimSpec:
              accessModes:
                - ReadWriteOnce
              resources:
                requests:
                  storage: 10Gi
              storageClassName: smb
  instances:
    - dataVolumeClaimSpec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 5Gi
      name: ''
      replicas: 1
  port: 5432
  postgresVersion: 17
  users:
    - databases:
        - test
      name: test
```
4. database and repo host are not getting ready

### EXPECTED

1. it should work like bevore (PGO 5.7.4)

### ACTUAL
1. container pgbackrest-log-dir:  `chmod: changing permissions of '/pgbackrest/repo1/log': Operation not permitted`
