### ISSUE TITLE
Custom Cluster Role

### ISSUE THREAD

**Issue by parzhevi** [CrunchyData/postgres-operator#4184]
We use PGO helm definition `registry.developers.crunchydata.com/crunchydata/pgo:5.7.0` in out deployment on kubernetes. After scanning for security vulnerabilities, Trivy Scan reported two security issues related to templates: 
1. `AVD-KSV-0041 (CRITICAL): ClusterRole 'pgo' shouldn't have access to manage resource 'secrets'`
2. `AVD-KSV-0050 (CRITICAL): ClusterRole 'pgo' should not have access to resources ["roles", "rolebindings"] for verbs ["create", "update", "delete", "deletecollection", "impersonate", "*"]`

This has to do with hardcoded definition in role.yaml file, specifically these parts:
```yaml
- apiGroups:
  - ''
  resources:
  - configmaps
  - persistentvolumeclaims
  - secrets
  - serviceaccounts
  - services
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - watch
```
```yaml
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - rolebindings
  - roles
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - watch
```

The only solution would be to re-define locally the whole chart, which makes updating with new releases complicated. 
Is it really necessary to give all these rights for the cluster? If not, would it be possible to make role definable throught the values.yaml? 

## Overview

If possible, role definition should be (partly) rendered from the values file.

## Use Case

This feature will ease maintenance and updates of the chart and prevent security vulnerabilities. 

## Desired Behavior

One could define resources and verbs in values file. 

## Environment

- Platform: `Kubernetes`
- Platform Version:  `1.29.10`
- PGO Image Tag: `5.7.0`
- Postgres Version  `17`
- Storage: (e.g. `hostpath`, `nfs`, or the name of your storage class)
- Number of Postgres clusters: `1`
