### ISSUE TITLE
created clusters do not have roles/passwords specified in .pgo.yaml

### ISSUE THREAD

**Issue by jar349** [CrunchyData/postgres-operator#48]
Here's my `.pgo.yaml` (located in `~/.pgo/yaml`):
```yaml
KUBECONFIG:  /Users/jar349/.kube/config
CLUSTER:
  CCP_IMAGE_TAG:  centos7-9.6-1.4.1
  PORT:  5432
  PG_MASTER_USER: admin
  PG_MASTER_PASSWORD:  password
  PG_USER:  admin
  PG_PASSWORD:  password
  PG_DATABASE:  test1
  PG_ROOT_PASSWORD:  password
  STRATEGY:  1
  REPLICAS:  1
  PASSWORD_AGE_DAYS:  3650
MASTER_STORAGE:
  STORAGE_CLASS:  gp2
  PVC_ACCESS_MODE:  ReadWriteOnce
  PVC_SIZE:  1Gi
  STORAGE_TYPE:  dynamic
  FSGROUP:  26
REPLICA_STORAGE:
  STORAGE_CLASS:  gp2
  PVC_ACCESS_MODE:  ReadWriteOnce
  PVC_SIZE:  1Gi
  STORAGE_TYPE:  dynamic
  FSGROUP:  26
BACKUP_STORAGE:
  STORAGE_CLASS:  gp2
  PVC_ACCESS_MODE:  ReadWriteOnce
  PVC_SIZE:  5Gi
  STORAGE_TYPE:  dynamic
  FSGROUP:  26
PGO:
  LSPVC_TEMPLATE:  /Users/jar349/.pgo.lspvc-template.json
  CO_IMAGE_TAG:  centos7-1.5.2
  DEBUG:  true
```
I create a `test1` cluster:
```
$ pgo create cluster --namespace default test1
DEBU[0000] kubeconfig path is /Users/jar349/.kube/config 
DEBU[0000] namespace is                                 
DEBU[0000] ConnectToKube called                         
DEBU[0000] connected to kube. at /Users/jar349/.kube/config 
DEBU[0000] create cluster called                        
DEBU[0000] no policies are specified                    
DEBU[0000] create cluster called for test1              
DEBU[0000] pgcluster test1 not found so we will create it 
created PgCluster test1
```
Then I port-forward the pod...
```
$ kl port-forward test1-1519893712-t1421 5432
Forwarding from 127.0.0.1:5432 -> 5432
Forwarding from [::1]:5432 -> 5432
```
I load up pgadmin and can't connect.  On a hunch, I try a password-less login with `postgres` and I'm in and I see:

![screen shot 2017-09-22 at 5 50 45 pm](https://user-images.githubusercontent.com/290154/30765622-96c9ff6c-9fbe-11e7-9b81-38c87a0773c7.png)

Have I done something wrong?  Why isn't there an `admin` role with the password `password`?
