### ISSUE TITLE
[Helm Chart] [V3.4] Image definitions in pgo.yaml are wrong

### ISSUE THREAD

**Issue by iboware** [CrunchyData/postgres-operator#480]
**Describe the bug**

Helm Chart for V3.4 needs to be updated. Images inside `pgo.yaml` are not available in Docker repository. 
```yaml
Cluster:
  CCPImageTag:  rhel7-10.6-2.2.0-rc8
Pgo:
  COImageTag:  rhel7-3.4.0-rc2
```

**To Reproduce**

**Expected behavior**

**Screenshots**

**Please tell us about your environment:**

**Additional context**
