### ISSUE TITLE
Pod Anti-affinity for high availability

### ISSUE THREAD

**Issue by chendo** [CrunchyData/postgres-operator#518]
**What is the motivation or use case for the change?**

Multiple pods belonging to the same cluster should not be running on the same host as another pod. Manually applying a pod anti-affinity rule causes a deployment to happen and also triggers a failover if `--autofail` is in use.

**Describe the solution you'd like**

A cluster deployment should apply relevant pod anti-affinity rules by default to attempt to schedule on different hosts.

Example:

```
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: pg-cluster
                      operator: In
                      values:
                        - some-database-cluster
                topologyKey: kubernetes.io/hostname
              weight: 100
```
