### ISSUE TITLE
crunchy-pgpool: "true" / crunchy-pgbouncer: "true" disables pod tagging

### ISSUE THREAD

**Issue by Sayrus** [CrunchyData/postgres-operator#637]
**Describe the bug**
When a cluster has a pgpool, deployments are created with `crunchy-pgpool: true`.
They won't get a service-name. Hence, they won't be accessible by using the corresponding service (selector `service-name: <cluster_name>`). This means that pgpool can't access them, that replica are stuck waiting for the master node and that the master node is waiting for connections but no one can connect (except by direct ClusterIP).

As far as I understand the code, `controller/podcontroller.go::isPostgresPod` will return false if the pod has `crunchy-pgpool` equal to `true`. However, any pod in a cluster with pgpool (except for the primary deployment after an update) will have the `crunchy-pgpool`.

**To Reproduce**
As far as my cluster is concerned:
1. `pgo create cluster <cluster_name> --pgpool --replica-count=2`
or
1. `pgo create cluster <cluster_name>`
2. `pgo add pgpool <cluster_name>`
3. Delete a pod, newly spawned pod will never be tagged with `service-name: <cluster_name>-replica`

**Expected behavior**
Deployment and pod should be correctly tagged with `service-name: <cluster_name>` or `service-name: <cluster_name>-replica`.
Replica use `<cluster_name>` service as primary.
pgpool use `<cluster_name>` service as primary and `<cluster_name>-replica` service as primary.

**Screenshots**
![image](https://user-images.githubusercontent.com/22404472/54301136-a7090600-45be-11e9-8e0f-a184c89c7991.png)
![image](https://user-images.githubusercontent.com/22404472/54301198-c4d66b00-45be-11e9-86ad-013252e2cf07.png)

**Please tell us about your environment:**

* Operating System: Linux 4.9.0-8-amd64 #1 SMP Debian 4.9.110-3+deb9u6 (2018-10-08) x86_64 GNU/Linux
* Where is this running ( Local, Cloud Provider): Local
* Storage being used (NFS, Hostpath, Gluster, etc): CephFS (with initContainers for fs permissions)
* Container Image Tag: 

> crunchydata/crunchy-postgres:centos7-11.2-2.3.1
> crunchydata/crunchy-collect:centos7-11.2-2.3.1
> crunchydata/crunchy-pgpool:centos7-11.2-2.3.1
> crunchydata/pgo-apiserver:centos7-3.5.1
> crunchydata/postgres-operator:centos7-3.5.1
> crunchydata/pgo-scheduler:centos7-3.5.1

* PostgreSQL Version: ?
* Platform (Docker, Kubernetes, OpenShift): Kubernetes
* Platform Version: v1.10.11

**Additional context**
---

**Comment by tumluliu** [comment]
The same problem still happens from my side with 4.0.0-rc14. When I created a cluster with `pgo create cluster democluster --pgpool --replica-count 1`, the created service `democluster` could not get any endpoint because of its selector
```
...
selector:
    service-name: democluster
...
```
could not match the corresponding deployment with labels
```
labels:
    crunchy-pgpool: "true"
    crunchy_collect: "true"
    deployment-name: democluster
    name: democluster
    pg-cluster: democluster
    pgo-version: 4.0.0
    pgpool-secret: ""
    vendor: crunchydata
```
because there is no such a label `service-name: democluster` . 
Would be great if this issue can be reopened and tagged with 4.0.0 @Sayrus

**Comment by jmccormick2001** [comment]
can you provide the labels from the database pods?  we are not seeing this issue.  The service-name label on the pods is what the service selector will be matching against.

**Comment by tumluliu** [comment]
Thank you @jmccormick2001 . 
This is the pod labels:
```
labels:
    crunchy-pgpool: "true"
    crunchy_collect: "true"
    custom-config: pgo-custom-pg-config
    deployment-name: democluster
    name: democluster
    pg-cluster: democluster
    pgo-version: 4.0.0
    pgpool-secret: ""
    pod-template-hash: 788d84f964
    vendor: crunchydata
```
I don't see the `service-name` on it. And the service could not get an endpoint as a result. 
btw, I created this new cluster with 4.0.0-rc15.
