### ISSUE TITLE
Postgres fails to start bacause it's being ran as root

### ISSUE THREAD

**Issue by jprukner** [CrunchyData/postgres-operator#768]
**Describe the bug**
Cluster fails to start because postgres container is being ran as root.

```
Tue May 21 08:57:44 UTC 2019 INFO: Setting PGROOT to /usr/pgsql-11.
Tue May 21 08:57:44 UTC 2019 INFO: The PGUSER secret exists.
Tue May 21 08:57:44 UTC 2019 INFO: The PGROOT secret exists.
Tue May 21 08:57:44 UTC 2019 INFO: The PGPRIMARY secret exists.
Tue May 21 08:57:44 UTC 2019 INFO: Cleaning up the old postmaster.pid file..
Tue May 21 08:57:44 UTC 2019 INFO: User ID is set to uid=0(root) gid=0(root) groups=0(root),26(postgres).
Tue May 21 08:57:44 UTC 2019 INFO: Setting LOG_MIN_DURATION_STATEMENT to 60000.
Tue May 21 08:57:44 UTC 2019 INFO: Setting LOG_STATEMENT to none.
Tue May 21 08:57:44 UTC 2019 INFO: Working on primary..
Tue May 21 08:57:44 UTC 2019 INFO: Initializing the primary database..
Tue May 21 08:57:44 UTC 2019 INFO: PGDATA is empty. ID is uid=0(root) gid=0(root) groups=0(root),26(postgres). Creating the PGDATA directory..
Tue May 21 08:57:44 UTC 2019 INFO: Checking for restore..
total 0
Tue May 21 08:57:44 UTC 2019 INFO: No backup file found.
Tue May 21 08:57:44 UTC 2019 INFO: Starting initdb..
Tue May 21 08:57:44 UTC 2019 INFO: XLOGDIR not found. Using default pg_wal directory..
Tue May 21 08:57:44 UTC 2019 INFO: Data checksums enabled.  Setting initdb to use data checksums..
Tue May 21 08:57:44 UTC 2019 INFO: Running initdb command: initdb -D /pgdata/differentcluster  --locale=en_US.UTF8 --data-checksums > /tmp/initdb.stdout 2> /tmp/initdb.stderr
Tue May 21 08:57:44 UTC 2019 ERROR: Initializing the database (initdb): Unable to initialize the database: 
initdb: cannot be run as root
Please log in (using, e.g., "su") as the (unprivileged) user that will
own the server process.
```

**To Reproduce**
1. Deploy operator
2. Create cluster
3. Delete pod of the cluster e.g. "mycluster-5864798b69-crqbk" and let start new one.
4. New pod fails to start.

**Expected behavior**
Run the container as non-root.

**Please tell us about your environment:**

* OS: Ubuntu 18.04, Kernel: 4.18.0-20-generic
* Where is this running: Packet.com
* Storage being used: rook
* Container Image Tag: centos7-3.5.3
* PostgreSQL Version: centos7-11.3-2.3.2
* Platform: Kubernetes
* Platform Version: 1.14.1

**Additional context**
Deleting the cluster and creating it backagain does not solve the issue. Redeploying the operator does not solve the issue.

pgo.yaml
```
Cluster:
  PrimaryNodeLabel:  
  ReplicaNodeLabel:  
  CCPImagePrefix:  crunchydata
  Metrics:  false
  Badger:  false
  CCPImageTag:  centos7-11.3-2.3.2
  Port:  5432
  User:  testuser
  Database:  userdb
  PasswordAgeDays:  60
  PasswordLength:  8
  Strategy:  1
  Replicas:  0
  ArchiveMode:  false
  ArchiveTimeout:  60
  ServiceType:  ClusterIP
  Backrest:  false
  BackrestPort:  2022
  Autofail:  false
  AutofailReplaceReplica:  false
  LogStatement:  none
  LogMinDurationStatement:  60000
PrimaryStorage: rook
XlogStorage: rook
BackupStorage: rook
ReplicaStorage: rook
BackrestStorage: rook
Storage:
  hostpathstorage:
    AccessMode:  ReadWriteMany
    Size:  1G
    StorageType:  create
  replicastorage:
    AccessMode:  ReadWriteMany
    Size:  700M
    StorageType:  create
  nfsstorage:
    AccessMode:  ReadWriteMany
    Size:  1G
    StorageType:  create
    SupplementalGroups:  65534
  backreststorage:
    AccessMode:  ReadWriteMany
    Size:  600M
    StorageType:  create
    SupplementalGroups:  65534
  nfsstoragered:
    AccessMode:  ReadWriteMany
    Size:  1G
    MatchLabels: crunchyzone=red
    StorageType:  create
    SupplementalGroups:  65534
  xlogstorage:
    AccessMode:  ReadWriteMany
    Size:  800M
    StorageType:  create
  storageos:
    AccessMode:  ReadWriteOnce
    Size:  1Gi
    StorageType:  dynamic
    StorageClass:  fast
    Fsgroup:  26
  rook:
    AccessMode:  ReadWriteOnce
    Size:  1Gi
    StorageType:  dynamic
    StorageClass:  rook-ceph-block
    Fsgroup:  26
DefaultContainerResources: 
DefaultLoadResources:  
DefaultLspvcResources:  
DefaultRmdataResources:  
DefaultBackupResources:  
DefaultPgbouncerResources:  
DefaultPgpoolResources:   
ContainerResources:
  small:
    RequestsMemory:  512Mi
    RequestsCPU:  0.1
    LimitsMemory:  512Mi
    LimitsCPU:  0.1
  large:
    RequestsMemory:  2Gi
    RequestsCPU:  2.0
    LimitsMemory:  2Gi
    LimitsCPU:  4.0
Pgo:
  AutofailSleepSeconds:  9
  PreferredFailoverNode:  
  Audit:  false
  LSPVCTemplate:  /pgo-config/pgo.lspvc-template.json
  LoadTemplate:  /pgo-config/pgo.load-template.json
  COImagePrefix:  crunchydata
  COImageTag:  centos7-3.5.3
```
