### ISSUE TITLE
[Support] How to setup pgo client

### ISSUE THREAD

**Issue by jbmcfarlin31** [CrunchyData/postgres-operator#855]
** Which example are you working with? **
The default installation guide for bash located [here](https://access.crunchydata.com/documentation/postgres-operator/4.0.0/installation/operator-install/)

**What is the current behavior?**
I am trying to verify that my installation was successful. I can see by doing `kubectl -n pgo get pods` that all 3 containers for the operator are created and running. I created an ingress rule and placed it into the same namespace so that my `pgo version` command can be accessed from another client. This basically made the `postgres-operator` svc exposed to a fqdn `my.example.com` we will say.

I set the `PGO_APISERVER_URL` to be the `https://my.example.com` and I set the following `PGO_CA_CERT`, `PGO_CLIENT_CERT`, `PGO_CLIENT_KEY` to be the values that were created when I ran `make installrbac`, the `.../conf/postgres-operator/server.{crt,key}`.

When I run `pgo version` however, I get a status code of 502.

**What is the expected behavior?**
To see the PGO versions

**Other information** (e.g. detailed explanation, related issues,  etc)
I ran the following: `pgo version --debug`
Output:
```
...
DEBU[0000] setting up httpclient with TLS
DEBU[0000] version called
DEBU[0000] ShowVersion called
DEBU[0000] https://my.example.com/version
DEBU[0000] &{502 Bad Gateway 502 HTTP/1.1 1 1 map[Connection:[keep-alive] Strict-Transport-Security:[max-age=15724800; includeSubDomains] Server:[nginx/1.15.6] Date:[Wed, 03 Jul 2019 20:53:51 GMT] Content-Type:[text/html] Content-Length:[157]] 0xc000367500 157 [] false false map[] 0xc00017f600 0xc000318000}
DEBU[0000] http status code is 502
Error: Invalid Status Code: 502
```

**Please tell us about your environment:**
Running inside a k8s cluster running 1.13.5 and using the nginx ingress controller.

* Operating System: Ubuntu 16.04
* Where is this running ( Local , Cloud Provider): On prem cloud (azure stack)
* Storage being used (NFS, Hostpath, Gluster, etc): Rook storage class
* Container Image Tag:
* PostgreSQL Version:
* Platform (Docker, Kubernetes, OpenShift): Kubernetes via RKE
* Platform Version:

If possible please run the following on the kubernetes or Openshit (oc) commands and provide the result:
 kubectl describe yourPodName
 kubectl describe pvc
 kubectl get nodes
 kubectl log yourPodName

`APISERVER POD OUTPUT`:
`2019/07/03 20:53:51 http: TLS handshake error from 172.17.5.20:37918: tls: client didn't provide a certificate
`

**Comment by jmccormick2001** [comment]
can you share your Ingress resource yaml?

**Comment by jbmcfarlin31** [comment]
```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: pgo-ingress
  namespace: pgo
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  tls:
  - hosts:
    - my.example.com
  rules:
  - host: my.example.com
    http:
      paths:
      - path: /
        backend:
          serviceName: postgres-operator
          servicePort: 8443
```

**Comment by jbmcfarlin31** [comment]
@jmccormick2001 if I run the `pgo version` command with the above configuration, I get a `status code 502 error` and if I look at the log outputs I see the following: `http: TLS handshake error from 172.17.5.20:58388: tls: client didn't provide a certificate`.

If I change it the configuration to the be the following:
```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: pgo-ingress
  namespace: pgo
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: my.example.com
    http:
      paths:
      - path: /
        backend:
          serviceName: postgres-operator
          servicePort: 8443
```

I get the error: `Error: Invalid Status Code: 404`

Any suggestions?
