### ISSUE TITLE
Multiple primaries created from restore jobs

### ISSUE THREAD

**Issue by jippeholwerda** [CrunchyData/postgres-operator#999]
We have a database cluster with a single primary deployment. After successfully having performed multiple restores, the jobs listing shows the restore jobs that have been created for this.

The behaviour we see is that for each restore job, a new deployment is created resulting in the database cluster having multiple primaries. The creation of these deployments based on the restore jobs seems to be triggered periodically (every 10 minutes).

The resulting database cluster looks like this:
```
cluster : bpbro-is-db-cluster (crunchy-postgres:centos7-11.4-2.4.1)
	pod : bpbro-is-db-cluster-bjzu-5555fc46b5-4httm (Running) on worker-01 (3/3) (primary)
	pvc : bpbro-is-db-cluster-bjzu
	pod : bpbro-is-db-cluster-vfac-86d7757649-qrpdq (Running) on worker-14 (3/3) (primary)
	pvc : bpbro-is-db-cluster-vfac
	pod : bpbro-is-db-cluster-vgbu-79cb8fc96f-vtr9t (Running) on worker-16 (3/3) (primary)
	pvc : bpbro-is-db-cluster-vgbu
	resources : CPU Limit=0.1 Memory Limit=512Mi, CPU Request=0.1 Memory Request=512Mi
	storage : Primary=5G Replica=5G
	deployment : bpbro-is-db-cluster-backrest-shared-repo
	deployment : bpbro-is-db-cluster-bjzu
	deployment : bpbro-is-db-cluster-vfac
	deployment : bpbro-is-db-cluster-vgbu
	service : bpbro-is-db-cluster - ClusterIP (172.30.122.168)
	labels : crunchy_collect=true current-primary=bpbro-is-db-cluster-vgbu deployment-name=bpbro-is-db-cluster-vgbu pgo-backrest=true pgo-version=4.0.1 crunchy-pgbadger=true name=bpbro-is-db-cluster pg-cluster=bpbro-is-db-cluster workflowid=f09babbb-1417-473b-a387-fcd54ed07c86
```

Where each primary deployment has it's own version of the restored data (not consistent).

Additionally, when we remove a restore job manually, it also triggers the creation of a deployment which results in another primary being added to the cluster.

We have reproduced these results in our cluster in different namespaces with different database clusters (same operator).

We use the operator version 4.0.1.

Operator logging which shows the creation of deployments based on the restore jobs after being triggered:
```
time="2019-09-16T07:08:11Z" level=debug msg="PodController: onUpdate skipping pod that is not crunchydata /api/v1/namespaces/bzk-bpbro-tst/pods/bpbro-backend-78fabc0f-fdfcf99cd-28dnf"
time="2019-09-16T07:08:35Z" level=debug msg="[JobController] onUpdate ns=bzk-bpbro-tst /apis/batch/v1/namespaces/bzk-bpbro-tst/jobs/restore-bpbro-is-db-cluster-fsfl active=0 succeeded=1 conditions=[[{Complete True 2019-09-13 12:23:54 +0000 UTC 2019-09-13 12:23:54 +0000 UTC  }]]"
time="2019-09-16T07:08:35Z" level=debug msg="job controller backup label "
time="2019-09-16T07:08:35Z" level=debug msg="jobController onUpdate backrest restore job case"
time="2019-09-16T07:08:35Z" level=debug msg="got a backrest restore job status=1"
time="2019-09-16T07:08:35Z" level=debug msg="set status to restore job completed  for bpbro-is-db-cluster"
time="2019-09-16T07:08:35Z" level=debug msg="workflow to update is ba9cce8e-3e2a-4e8b-a85e-1536b36bb76b"
time="2019-09-16T07:08:35Z" level=debug msg="[{\"op\":\"replace\",\"path\":\"/spec/status\",\"value\":\"job completed\"}]"
time="2019-09-16T07:08:35Z" level=debug msg="[PodController] onUpdate ns=bzk-bpbro-tst /api/v1/namespaces/bzk-bpbro-tst/pods/restore-bpbro-is-db-cluster-fsfl-z6lt9"
time="2019-09-16T07:08:35Z" level=error msg="error in patching pgtask pgtasks.crunchydata.com \"restore-bpbro-is-db-cluster-fsfl\" not found"
time="2019-09-16T07:08:35Z" level=debug msg="restore workflow phase 2: taskName is bpbro-is-db-cluster-pgbackrestrestore"
time="2019-09-16T07:08:35Z" level=debug msg="job pod found [restore-bpbro-is-db-cluster-fsfl-z6lt9]"
time="2019-09-16T07:08:35Z" level=debug msg="[PodController] onDelete ns=bzk-bpbro-tst /api/v1/namespaces/bzk-bpbro-tst/pods/restore-bpbro-is-db-cluster-fsfl-z6lt9"
time="2019-09-16T07:08:35Z" level=debug msg="GetAffinity with nodeLabelKey=[] nodeLabelKey=[] and operator=[In]\n"
time="2019-09-16T07:08:35Z" level=debug msg="creating restored PG deployment with bouncer pass of []"
            "resources": {...},
time="2019-09-16T07:08:35Z" level=debug msg="configmaps \"pgo-custom-pg-config\" not found"
time="2019-09-16T07:08:35Z" level=debug msg="pgo-custom-pg-config configmap not found "
time="2019-09-16T07:08:35Z" level=debug msg="pgo-custom-pg-config was not found, , skipping global configMap"
time="2019-09-16T07:08:35Z" level=debug msg="crunchy_collect was found as a label on cluster create"
time="2019-09-16T07:08:35Z" level=info msg="namespace=bzk-bpbro-tst"
time="2019-09-16T07:08:35Z" level=info msg="secretName=bpbro-is-db-cluster-primaryuser-secret"
,{...deployment config}


time="2019-09-16T07:08:35Z" level=debug msg="crunchy_badger was found as a label on cluster create"
time="2019-09-16T07:08:35Z" level=debug msg="collectaddon value is [,{\n    \"name\": \"collect\",\n    \"image\": \"harbor/sp-beheer/crunchydata/crunchy-collect:centos7-11.4-2.4.1\",\n    \"ports\": [{\n        \"containerPort\": 9187,\n        \"protocol\": \"TCP\"\n    }],\n    \"env\": [{\n        \"name\": \"DATA_SOURCE_NAME\",\n        \"value\": \"postgresql://ccp_monitoring@127.0.0.1:5432/postgres?sslmode=disable\"\n    },\n    {\n    \t\"name\": \"JOB_NAME\",\n    \t\"value\": \"bpbro-is-db-cluster\"\n    }\n    ]\n}\n]"
                            ,{...}
time="2019-09-16T07:08:35Z" level=error msg="error creating Deployment deployments.apps \"bpbro-is-db-cluster-bjzu\" already exists"
time="2019-09-16T07:08:35Z" level=debug msg="restore workflow phase  2: created restored primary was bpbro-is-db-cluster now bpbro-is-db-cluster-bjzu"
time="2019-09-16T07:08:35Z" level=debug msg="restore workflow: update workflow ba9cce8e-3e2a-4e8b-a85e-1536b36bb76b"
time="2019-09-16T07:08:35Z" level=debug msg="myselector is workflowid=ba9cce8e-3e2a-4e8b-a85e-1536b36bb76b"
time="2019-09-16T07:08:35Z" level=error msg="restore workflow error: workflow ba9cce8e-3e2a-4e8b-a85e-1536b36bb76b not found"
time="2019-09-16T07:08:35Z" level=debug msg="[JobController] onDelete ns=bzk-bpbro-tst /apis/batch/v1/namespaces/bzk-bpbro-tst/jobs/restore-bpbro-is-db-cluster-fsfl"
```

Is this normal behaviour? Are we missing a step after restore? Any help is very much appreciated.

**Comment by jippeholwerda** [comment]
Reading the source code I notice that the `JobController` checks jobs whether they have the `pgo-backrest-restore` label with value 'true'. This triggers the restoration of a new primary deployment.
However, this label is never removed or set to false. Also, the `JobController` doesn't seem to take into account whether the job has already been completed or not.

So a workaround could be to just manually remove the `pgo-backrest-restore` label after a successful restore. But is this intentional?

**Comment by cahoonpwork** [comment]
@jippeholwerda Can you provide the steps that you are running and your pgo configuration?  I see you have metrics and pgbadger turned on so I created a cluster with those and performed several backrest restores but didn't end up with multiple primaries.

**Comment by jippeholwerda** [comment]
Steps:

```
pgo create cluster bpbro-is-db-cluster -n bzk-bpbro-tst \
	--pgbadger \
	--metrics \
	--resources-config=small \
	--storage-config=storage1 \
	--replica-storage-config=storage1

pgo backup bpbro-is-db-cluster -n bzk-bpbro-tst

pgo restore bpbro-is-db-cluster --pitr-target="2019-09-13 12:02:00.333362+00" --backup-opts="--type=time --set=20190913-115120F_20190913-120110I" -n bzk-bpbro-tst
```

pgo.yaml:
```
Cluster:
  PrimaryNodeLabel:
  ReplicaNodeLabel:
  CCPImagePrefix:  harbor/sp-beheer/crunchydata
  CCPImageTag:  centos7-11.4-2.4.1
  Autofail:  false
  AutofailReplaceReplica:  false
  Backrest:  true
  BackrestPort:  2022
  BackrestS3Bucket: 
  BackrestS3Endpoint: 
  BackrestS3Region: 
  Metrics:  false
  Badger:  false
  Port:  5432
  User:  testuser
  Database:  userdb
  PasswordAgeDays:  60
  PasswordLength:  20
  Strategy:  1
  Replicas:  0
  ArchiveMode:  true
  ArchiveTimeout:  60
  ServiceType:  ClusterIP
  LogStatement: none
  LogMinDurationStatement:  60000
PrimaryStorage: storage2
BackupStorage: storage2
ReplicaStorage: storage2
BackrestStorage: storage2
Storage:
  storage1:
    AccessMode:  ReadWriteOnce
    Size:  5G
    StorageType:  dynamic
    StorageClass: standard
    SupplementalGroups: 
    Fsgroup: 26
  storage2:
    AccessMode:  ReadWriteOnce
    Size:  10G
    StorageType:  dynamic
    StorageClass: standard
    SupplementalGroups: 
    Fsgroup: 26
  storage3:
    AccessMode:  ReadWriteOnce
    Size:  20G
    StorageType:  dynamic
    StorageClass: standard
    SupplementalGroups: 
    Fsgroup: 26
DefaultContainerResource:
DefaultContainerResources: 
DefaultLoadResources:  
DefaultLspvcResources:  
DefaultRmdataResources:  
DefaultBackupResources:  
DefaultPgbouncerResources:  
DefaultPgpoolResources:
ContainerResources:
  small:
    RequestsMemory:  512Mi
    RequestsCPU:  0.1
    LimitsMemory:  512Mi
    LimitsCPU:  0.1
  large:
    RequestsMemory:  2Gi
    RequestsCPU:  2.0
    LimitsMemory:  2Gi
    LimitsCPU:  4.0
Pgo:
  AutofailSleepSeconds:  9 
  Audit:  false
  LSPVCTemplate:  /pgo-config/pgo.lspvc-template.json
  LoadTemplate:  /pgo-config/pgo.load-template.json
  PGOImagePrefix:  harbor/sp-beheer/crunchydata
  PGOImageTag:  centos7-4.0.1
```
